### PR TITLE
chore: clang-format

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Makes sure that all sources are properly formatted by clang-format.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by miniak** [comment]
@deepak1556 `native_mate` for example is not included in `lint:cpp` as there are some other issues that would need to be addressed.

**Comment by deepak1556** [comment]
cool, what about the changes in `atom/browser` ?

**Comment by miniak** [comment]
@deepak1556 all of those are `.mm` files, those might not be linted either.

**Comment by deepak1556** [comment]
> all of those are .mm files, those might not be linted either.

Thats weird, `clang-format` shouldn't have restrictions on these files, I remember the restriction with `cpplint`. This should be looked into.

**Comment by miniak** [comment]
@deepak1556 can you please merge?

**Pull request merged**
