### PR TITLE
feat: add new components to Display structure

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Resolves https://github.com/electron/electron/issues/16078.

In the years since we added the [`Display`](https://github.com/electron/electron/blob/master/docs/api/structures/display.md) API structure, Chromium has added several new fields (and accessors for the them) to it: `monochrome`, `accelerometerEnabled`, `internal`, and `depthPerComponent`. This PR thus adds these three new fields to our own Display structure.

cc @ckerr @MarshallOfSound @deepak1556 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added new `monochrome`, `internal`, `acceleratorEnabled`, `colorDepth` and `depthPerComponent` properties to the Display API Structure.

### CODE REVIEW

**Comment by miniak** [comment]
@codebytere does it make sense to expose `color_depth()` as well?

**Comment by miniak** [comment]
Also [`color_space()`](https://cs.chromium.org/chromium/src/ui/display/display.h?type=cs&sq=package:chromium&g=0&l=226) can be useful, to detect whether the display id HDR or wide gamut.

**Comment by codebytere** [comment]
@miniak updated: i'll expose color_space in a follow-up PR.

**Comment by nornagon** [comment]
a test would be great!

**Pull request merged**
