### PR TITLE
feat: make desktopCapturer main-process-only

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This makes `desktopCapturer.getSources` a main-process-only method.

This is a security precaution; it prohibits renderers from being able to
request images from the desktop without explicit permission from the main
process.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: `desktopCapturer.getSources` is now only available in the main process.

### CODE REVIEW

**Comment by nornagon** [comment]
draft until 16.x forks

**Comment by miniak** [comment]
@nornagon also remove `--enable-api-filtering-logging` from docs/api/command-line-switches.md

**Comment by miniak** [comment]
@nornagon 16-x-y was branched off, we can land this now in main

**Comment by zcbenz** [comment]
nornagon is off until next year, so we should either pick this up, or wait for some time.

**Comment by miniak** [comment]
@zcbenz taking it over. rebased and conflicts resolved

**Review by MarshallOfSound — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
