### PR TITLE
Add arm64 build support

### PR DESCRIPTION
**Pull request by HAMIDx9**
This PR has patches to build arm64 electron package successfully. 
I've also provided unofficial packages for download until official releases prepared for the community.
This build has been tested successfully on Odroid C2 (arm64). Unfortunately support for electron-packager is not provided here.
You may just copy your resources to the `electron-v1.7.5-linux-arm64.zip` and run `electron` there.

libcromiumcontent build instructions:

```bash
$ git clone https://chromium.googlesource.com/chromium/src.git
$ cd libcromiumcontent
$ ./script/bootstrap
$ ./script/update -t arm64
$ ./script/build -t arm64
$ ./script/create-dist -t arm64
$ mkdir -p linux/arm64/7a9d4a1c9c265468dd54005f6c1920b2cc2c8ec3 # HACK for using later for electron build process
$ mv libchromiumcontent* linux/arm64/7a9d4a1c9c265468dd54005f6c1920b2cc2c8ec3
```

electron + arm64 support build instruction:
```bash
$ git clone https://github.com/HAMIDx9/electron.git
$ cd electron
$ ./script/bootstrap.py -v --target_arch=arm64 -u file:///home/hamidx9/dev/electron/libchromiumcontent/
$ ./script/build.py -c R
$ ./script/create-dist.py
$ ls ./dist/electron-v1.7.5-linux-arm64.zip
```

**Unofficial Builds**:
[electron-v1.7.5-linux-arm64-symbols.zip](https://www.hamidx9.ir/dl/electron_arm64/electron-v1.7.5-linux-arm64-symbols.zip)
[electron-v1.7.5-linux-arm64.zip](https://www.hamidx9.ir/dl/electron_arm64/electron-v1.7.5-linux-arm64.zip)
[ffmpeg-v1.7.5-linux-arm64.zip](https://www.hamidx9.ir/dl/electron_arm64/ffmpeg-v1.7.5-linux-arm64.zip)
[libchromiumcontent/libchromiumcontent-static.zip](https://www.hamidx9.ir/dl/electron_arm64/libchromiumcontent/libchromiumcontent-static.zip)
[libchromiumcontent/libchromiumcontent.zip](https://www.hamidx9.ir/dl/electron_arm64/libchromiumcontent/libchromiumcontent.zip)

**sha256sum**:
```bash
2d3fe036b4fa1efdb99b8fa15e03f11b9829428529640fa9db4794c8cd2babf7  electron-v1.7.5-linux-arm64-symbols.zip
2df42153e59d40ca03bc281cc515db3331d4facd9d2cdc7fe66aa660b76d43a2  electron-v1.7.5-linux-arm64.zip
4528e28412e5d1074b35e6bcb6198e07f0e4b6ef3434565b4d294124f9e01dbd  ffmpeg-v1.7.5-linux-arm64.zip
b4e8d028d34ce5a9010d4900140466e1f55c835ad7e64c0c7403d82ea41c44bf  libchromiumcontent/libchromiumcontent-static.zip
afa2486256ce561fd3a815e08a0dfee4841a7cbe467f3e518a4712aae48e25fe  libchromiumcontent/libchromiumcontent.zip
```

### CODE REVIEW

**Comment by groundwater** [comment]
First off, this is fantastic!

I just picked up an ARM64 laptop, and have been trying to get Electron running on it. I had to disable crashpad however. It looks like your work in `vendor/third_party/lss/linux_syscall_support.h` is to get crashpad working.

Just a heads up, this looks right, but we are upgrading our CI, and arm64 is not part of the immediate plan. Once CI is running steady, we can look at adding an official release.

I'll try building this manually to verify.

**Comment by zcbenz** [comment]
I'm rebasing this branch on master to make the tests passing.

**Comment by zcbenz** [comment]
I'm very sorry that my force push has somehow closed the pull request and I can't find a way to reopen it, I have opened https://github.com/electron/electron/pull/10217 to continue this.

**Comment by zcbenz** [comment]
@HAMIDx9 Can you push your change on your local machine to your repo again? If so I would be able to reopen this pull request.

**Comment by HAMIDx9** [comment]
I just did @zcbenz. should i rebase on master?

**Comment by zcbenz** [comment]
> I just did @zcbenz. should i rebase on master?

Yeah please do a rebase so we can have tests passing. And do you mind creating a new pull request for it? I still can not reopen this one.

**Comment by HAMIDx9** [comment]
Please use new PR #10219.

**Pull request closed without merging**
