### PR TITLE
Add BrowserWindow.getDevToolsExtensions API

### LINKED ISSUE #5960: installedDevToolsExtensions() API
Libraries like `electron-debug` programatically add a devtools extension (https://github.com/sindresorhus/electron-debug/pull/36). This works fine but on subsequent loads it prints the following to console:

```
Attempted to load extension "devtron", but extension was already loaded!
```

No big problem but it clutters up the console. A suggested alternative would be to check if the devtool already exists before trying to install it. Here are two possible APIs which could work:

```js
BrowserWindow.installedDevToolsExtensions(); // -> ['devtron', 'React Developer Tools'];
// or
BrowserWindow.isDevToolExtensionInstalled('devtron'); // -> `true`
```

* Electron version: 1.2.2

### PR DESCRIPTION
**Pull request by kevinsawicki**
Adds `BrowserWindow.getDevToolsExtensions()` that returns an object like so:

```json
{
  "devtron": {
    "name": "devtron",
    "version": "1.0.0"
  }
}
```

Closes #5960

### CODE REVIEW

**Comment by zcbenz** [comment]
Adding an `getDevToolsExtensions` API that lists all installed extensions is probably generic, it does the job of `isDevToolsExtensionInstalled`, and allows more usages, like removing all extensions.

**Comment by davej** [comment]
Just a thought on `getDevToolsExtensions` API. It might be worth considering returning something like:

```js
[{ name: 'devtron' }, { name: 'React Developer Tools' }]
```

instead of:

```js
['devtron', 'React Developer Tools']
```

The first example would allow properties (like `version` or `path`) to be added in the future without making a breaking change. Just a thought, feel free to discard this. 😃

**Comment by kevinsawicki** [comment]
> Adding an getDevToolsExtensions API that lists all installed extensions is probably generic, it does the job of isDevToolsExtensionInstalled, and allows more usages, like removing all extensions.

👍

**Comment by kevinsawicki** [comment]
I've updated this pull request to add `BrowserWindow.getDevToolsExtension()` that returns an object with extension names as they keys and the value is an object with selected manifest value fields, currently `name` and `version`.

So you can check if an extension is installed with:

```js
BrowserWindow.getDevToolsExtesion().hasOwnProperty('devtron')
```

```json
{
  "devtron": {
    "name": "devtron",
    "version": "1.0.0"
  }
}
```

**Comment by zcbenz** [comment]
👍

**Pull request merged**
