### PR TITLE
docs: `menu-item.md` `click` function description error

### PR DESCRIPTION
**Pull request by Xheldon**
#### Release Notes

Notes: 

Fix docs `menu-item.md`: `click` function description error

### CODE REVIEW

**Comment by Xheldon** [comment]
@codebytere  Reason for closure?

**Comment by Xheldon** [comment]
The document has errors and is inconsistent with the actual behavior. May I ask why this PR needs to be closed?

**Comment by codebytere** [comment]
This PR added arbitrary unnecessary verbiage: `(for example: when open a file selector dialog).` and included no PR body nor other information required.

**Comment by Xheldon** [comment]
I added this sentence in order to allow developers to understand more clearly when this parameter will be undefined, because if you read the current documentation directly, it's impossible to know this.

I discovered this while implementing the Menu, so I hope to add this note to the documentation as a remark to inform more developers.

Additionally, if you can see more, the PR below has corrected the incorrect parameter description for menu.click.

I hope you will reconsider this PR, thank you. @codebytere

**Pull request closed without merging**
