### PR TITLE
docs: clean up the native modules documentation

### PR DESCRIPTION
**Pull request by malept**
#### Description of Change

Attempt to make the native modules documentation clearer, and mention Electron Forge where appropriate.

CC: @electron/wg-ecosystem 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Review by erickzhao — COMMENTED** [review]
We should probably also add mentions to the work done in https://github.com/electron/electron/issues/18397.

Also question: does all this still apply to rebuilding modules written with N-API?

**Comment by MarshallOfSound** [comment]
> Also question: does all this still apply to rebuilding modules written with N-API?

Yes

**Comment by malept** [comment]
> We should probably also add mentions to the work done in #18397.

Can this be done in a follow-up PR? That seems like a big chunk of work to adapt that issue summary into docs.

> **Semver Label Enforcement** *In progress — No semver/* label found*

@MarshallOfSound can this check be skipped for pure docs changes?

**Comment by erickzhao** [comment]
> Can this be done in a follow-up PR?

Sounds good to me.

**Comment by MarshallOfSound** [comment]
> @MarshallOfSound can this check be skipped for pure docs changes?

It's not skipped for _any_ changes, adding a `semver/patch` label isn't too tricky 😄

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
