### PR TITLE
chore: set wg-infra as CODEOWNER for GHA build configs

### PR DESCRIPTION
**Pull request by dsanders11**
#### Description of Change

Ensures the WG gets automatically tagged for review on these files.

#### Checklist

- [x] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by codebytere** [comment]
Should this be infra? I would lean to that instead personally

**Review by codebytere — COMMENTED** [review]
Should this be infra? I would lean to that instead personally.

**Comment by dsanders11** [comment]
Yea, I also kind of lean that way, but the AppVeyor update image PRs tag Releases WG. 🤔

Marking it as both WGs is also an option. Happy to hear from others as well.

**Comment by codebytere** [comment]
@dsanders11 I circled back with @electron/wg-infra and I think we'd like this be marked with just infra for now!

**Review by codebytere — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Review by MarshallOfSound — APPROVED** [review]

**Pull request merged**
