### PR TITLE
chore: cleanup tests creating crashpad handler in the test runner process

### PR DESCRIPTION
**Pull request by deepak1556**
Found while debugging CI failure in https://github.com/electron/electron/pull/40017#issuecomment-1833964676

Test `allows the submitURL option to be omitted when uploadToServer is false` was accidentally start the crashpad handler process and it impacted crashpad clients for processes that were created in tests unrelated later down the path.

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Comment by deepak1556** [comment]
Debugging showed that process termination status in the crash scenarios ended up after the test timeout, very likely a delay in https://source.chromium.org/chromium/chromium/src/+/main:base/process/kill_win.cc;l=26-63. Increasing timeout of tests didn't help all failing tests. Also given this does not repro locally, I am going to disable them for win32 ia32 flavor moving forward.

**Review by codebytere — APPROVED** [review]

**Pull request merged**
