### PR TITLE
docs: add missing isSameDocument property to will-frame-navigate event details

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
It got lost between #37085 and #34418

#### Release Notes
Notes: none

### CODE REVIEW

**Comment by miniak** [comment]
@itsananderson isn't the same the case for `will-navigate` as well, where it is documented?

**Comment by miniak** [comment]
@itsananderson in that case there are 2 options
- add it for `will-frame-navigate`, but update it for `will-navigate` as well saying that it's always false
- remove it from `will-navigate` as it's not useful

**Review by VerteDinde — APPROVED** [review]

**Comment by itsananderson** [comment]
Sorry, I neglected to follow up on this discussion. I'm fine with the first proposal, to document this property but to have both `will-frame-navigate` and `will-navigate` document that the property will always be false because those events only fire for non-in-page navigations.

**Comment by miniak** [comment]
@itsananderson can you please check again?

**Review by itsananderson — APPROVED** [review]
lgtm with the suggested fix

**Review by deepak1556 — APPROVED** [review]

**Pull request merged**
