### PR TITLE
refactor: const Module = require('module') as NodeJS.ModuleInternal;

### PR DESCRIPTION
**Pull request by miniak**
Improve type safety for `Module` from NodeJS

Notes: none

### CODE REVIEW

**Review by zcbenz — APPROVED** [review]

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
Lots of this code is changing in my ESM pr.  Requesting changes just to avoid it landing while ESM is green, I don't want conflicts on the ESM side

**Comment by miniak** [comment]
@MarshallOfSound when are you planning to land your PR?

**Comment by dsanders11** [comment]
@miniak, the ESM pr is #37535. Since this PR is a refactor for internal type safety, while the other is a big feature PR, I think it's reasonable to hold off on this one until the bigger one lands to avoid unnecessary merge conflict. The intended timeline of merging the ESM pr is "soon", pending final reviews.

**Comment by miniak** [comment]
@MarshallOfSound can you please unblock now?

**Review by ppontes — APPROVED** [review]

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
If this PR is fixing types it shouldn't be changing runtime values like it currently is.  Can we limit this to types-only changes?

**Comment by miniak** [comment]
@MarshallOfSound reverted functional changes

**Review by MarshallOfSound — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Pull request merged**
