### PR TITLE
refactor: prevent consistent early exception

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/24189.

This PR alters our `process.electronBinding` parameters to pass the process type alongside the binding name.

cc @MarshallOfSound @deepak1556 @nornagon 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: Fixed an issue with a consistent unwanted exception appearing during a debugging session with the VSCode debugger.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
We should probably just make all call sites pass in the process type.  E.g. process.electronBinding('app', 'browser')

**Comment by codebytere** [comment]
That also works - i'll rework this a bit

**Comment by deepak1556** [comment]
Can't we just refactor to use the full module name at the call site ?

`const { nativeImage, NativeImage } = process._linkedBinding('electron_common_native_image');`

I don't see an advantage with this `electronBindingSetup` helper.

**Comment by nornagon** [comment]
Flagging that some 3rd-party tools might break with this change. It's a private API so it seems OK to break it, but it's been that way for a while and it's used to do some things which aren't otherwise accomplishable (e.g. get/setHiddenValue).

**Comment by deepak1556** [comment]
In that case we can leave the original `process.electronBinding` definition as such for 3rd-party tools and just replace the internal call sites to `process._linkedBinding`

**Comment by codebytere** [comment]
Works for me - it's a bit clearer anyway.

**Comment by codebytere** [comment]
I'm missing one somewhere 🤔 just two tests failing

**Pull request merged**
