### PR TITLE
The checksum file needs to indicate that the files should be opened in binary mode

### PR DESCRIPTION
**Pull request by malept**
For context, please see https://github.com/electron/electron/pull/6676#discussion_r75332120.

### CODE REVIEW

**Comment by malept** [comment]
Also, it would be nice if the `SHASUM256.txt` files were re-uploaded with the correct format for versions 1.3.2 and 1.3.3.

**Comment by zcbenz** [comment]
I was trying to follow Node on this, do you know why Node uses space instead of `*` in their [checksum file](https://nodejs.org/dist/latest-v6.x/SHASUMS256.txt)?

**Comment by malept** [comment]
> do you know why Node uses space instead of `*`

It looks like it's because [they hash binary files in text mode](https://github.com/nodejs/build/blob/12db79f166656da301138539fa2c5dac73992eb8/setup/www/tools/promote/_resha.sh#L19).

> This is causing my checksum verifications to not work (because it's reading the zips in text mode, not binary mode).

I did some further tests and it turned out to be a bug in my test code - it looks like the same hash is created whether the zip is read in text or binary mode.

I still think this is a good change to have, because the file is being read in binary mode when the hash is calculated and should be indicated in the checksum file. However, I retract my statement about re-uploading the checksum files for previous versions.

**Comment by zcbenz** [comment]
Thanks for the explanation, I agree it is a good change. 👍

**Pull request merged**
