### PR TITLE
Add missing chai-as-promised dep

### PR DESCRIPTION
**Pull request by MarshallOfSound**
/cc @codebytere

### CODE REVIEW

**Comment by codebytere** [comment]
TWO SECONDS LATE

**Comment by codebytere** [comment]
bitter

**Comment by MarshallOfSound** [comment]
May the faster terminal win 😆 👍

**Comment by alexeykuzmin** [comment]
@MarshallOfSound Why do you need this in the top-level package.json?

**Comment by MarshallOfSound** [comment]
@alexeykuzmin That is a good question 🤔 It definitely broke CI and locally even after rebootstrapping several times (both @codebytere and I had the same issue where this module could not be found).

**Comment by alexeykuzmin** [comment]
> It definitely broke CI

That's weird, because all builds were green in the PR where `chai-as-promised` was added.
https://github.com/electron/electron/pull/12652

**Pull request merged**
