### PR TITLE
build: move Windows release builds to AppVeyor cloud

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change
This PR moves our Windows builds from our self hosted AppVeyor instance to AppVeyor's cloud hosted instance.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by zcbenz** [comment]
`3-1-x` needs manual backport.

**Comment by zcbenz** [comment]
This needs approval from @electron/wg-releases .

**Comment by jkleinsc** [comment]
@MarshallOfSound corresponding sudowoodo PR here: electron/sudowoodo#120.

I added a new env variable, `APPVEYOR_CLOUD_TOKEN` so that sudowoodo can run builds on both self hosted AppVeyor and cloud hosted AppVeyor.

**Pull request merged**
