### PR TITLE
fix: add support for ELECTRON_OZONE_PLATFORM_HINT environment variable

### LINKED ISSUE #30897: [Feature Request]: environment variable to enable wayland support and get rid of individual --enable-features=UseOzonePlatform --ozone-platform=wayland flags
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently Wayland support in Electron needs to be turned on on per-app basis with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags. 

This is very inconvenient: we have to repeat this chore for every single Electron app, we need to take care of CLI aliases, etc, etc.

Without these flags Electron apps look blurry and are almost unusable when fractional scaling is on.

### Proposed Solution

Electron should read these options from an environment variable, like `ELECTRON_OPTS`,  this way the user would be able to turn on Wayland support globally. 

### Alternatives Considered

Alternatively Electron may support environment variables like 

`ELECTRON_OZONE_PLATFORM`
`ELECTRON_ENABLE_FEATURES`

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by vially**
#### Description of Change

Add support for the `ELECTRON_OZONE_PLATFORM_HINT` environment variable in order to make it easier for users to enable Wayland support for **all** Electron apps without having to manually patch application `.desktop` files (or other similar workarounds #30897).

The accepted values are the same [as upstream](https://chromium-review.googlesource.com/c/chromium/src/+/3188974), with the special `auto` value being recommended for most users (especially for those switching between X11 and Wayland environments).

When *both* the `--ozone-platform-hint` command line flag and the `ELECTRON_OZONE_PLATFORM_HINT` environment variable are specified, the command line flag has higher priority.

Fixes #30897

#### Checklist

- [x] PR description included and stakeholders cc'd (@ckerr @deepak1556 @zcbenz)
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added support for `ELECTRON_OZONE_PLATFORM_HINT` environment variable on Linux.

### CODE REVIEW

**Comment by deepak1556** [comment]
Can we instead set `--ozone-platform-hint=auto` by default in Electron ? We seem to have a resonable fallback to use X11 when wayland server is not found/running https://github.com/electron/electron/blob/730d9181b3de8561c1d87d82ccb923b1859122ae/shell/browser/electron_browser_main_parts_linux.cc#L56-L110, also `--ozone-platform` takes precedence over `--ozone-platform-hint` which still gives applications control over the default behavior of Electron for any edge cases they encounter. Seems like a default of `--ozone-platform-hint=auto` in Electron would cover all use cases mentioned in the linked issue.

**Comment by vially** [comment]
> Can we instead set --ozone-platform-hint=auto by default in Electron?

I've created #35630 which does that (set `--ozone-platform-hint` to `auto` by default). I think either one of these two pull-request (#35614, #35630) will fix #35630, but I'm personally more in favor of #35630.

**Comment by ckerr** [comment]
I think I'd prefer #35630 over this PR and from https://github.com/electron/electron/pull/35614#issuecomment-1241384306 it sounds like @deepak1556 would lean in the same direction

**Comment by deepak1556** [comment]
Yup I prefer https://github.com/electron/electron/pull/35630 over the environment variable. Maybe we close this and revisit if https://github.com/electron/electron/pull/35630 is not viable.

**Comment by parcelcat** [comment]
Since #35630 looks premature until Chromium changes the default ozone value, could we please reopen this pull request?

@ckerr @deepak1556 @vially

**Comment by ZtereoHYPE** [comment]
This feels way overdue considering chromium seems nowhere close to enabling their default ozone platform hint.

**Pull request closed without merging**
