### PR TITLE
chore: return early on promise rejection in cookies.set

### PR DESCRIPTION
**Pull request by dsanders11**
#### Description of Change

Return after rejecting the promise otherwise code execution will continue on.

cc: @nornagon 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes

Notes: none

### CODE REVIEW

**Review by MarshallOfSound — APPROVED** [review]

**Review by deepak1556 — APPROVED** [review]

**Comment by deepak1556** [comment]
Can you add some release notes given it is a `fix`, thanks!

**Review by nornagon — CHANGES_REQUESTED** [review]
The description of this PR is lacking, I'd like to know what bug this fixes!

Also, perhaps a test?

**Comment by dsanders11** [comment]
@nornagon, it wasn't found via a bug, I was walking code and noticed it. Should I have prefixed it `chore`? I think it's objectively wrong to not return `handle` there, unless I'm missing something? Execution continues on and will reject the promise again before dumping out.

@deepak1556, I can try to add a note, but there's no real world usage bug that this fixes (AFAIK) other than not continuing on execution which isn't correct.

**Comment by deepak1556** [comment]
> Should I have prefixed it chore?

A release note is not required if you can change from `fix` to `chore`.

**Review by zcbenz — APPROVED** [review]

**Review by nornagon — APPROVED** [review]

**Pull request merged**
