### PR TITLE
fix: navigator.bluetooth.requestDevice

### PR DESCRIPTION
**Pull request by VerteDinde**
Backport of #27902

See that PR for details.

Notes: Fixed navigator.bluetooth.requestDevice.

### CODE REVIEW

**Review by CyberFlameGO — APPROVED** [review]
LGTM

**Review by codebytere — APPROVED** [review]

**Comment by zcbenz** [comment]
The build is failing.

**Comment by jkleinsc** [comment]
Merging as Windows failures are known flake unrelated to this PR.

**Comment by mlynch** [comment]
I've been follow this issue as I have a usecase that calls for BLE support in Electron. I just pulled down master and built and tested this against the sample provided in #27618 and I'm still seeing this crash on `requestDevices` on MacOS.

Going to try to debug the native crash this weekend but it's been a while since I've debugged C++

**Comment by mlynch** [comment]
Hmm, when I debug it locally in lldb it does not crash and I get the permission prompt. I must be doing something wrong when testing the binary standalone.

**Pull request merged**
