### PR TITLE
build: don't depend on //chrome/common

### PR DESCRIPTION
**Pull request by nornagon**
//chrome/common is much to broad of a dependency and we could end up accidentally including dependencies we don't want

Notes: no-notes

### CODE REVIEW

**Comment by deepak1556** [comment]
Is there a considerable difference in size with this approach, I really don't want to go down this route if there isn't an advantage. It makes the target harder to reason about, when I initially added the dep, being a static lib target I was under the assumption most of the unwanted stuff would be optimized away for release builds. Would be great if some size comparisons for release builds are shared in this PR, thanks!

**Comment by nornagon** [comment]
Hmm, if it's truly eliding all the things we don't need, then I suppose it's OK to depend on. I worry though about things other than the direct impact on code size:
1. We may end up inadvertently shipping non-code things that `//chrome/common` depends on, such as strings, images, and other resources which we never use. This is probably a relatively small impact though.
2. We may inadvertently inherit build configuration from `//chrome/common`.
3. Even if the bundle size doesn't increase with this PR, it may accidentally do so in a future PR that adds a real dependency, possibly transitively, on something in `//chrome/common`.
4. It adds to the build time, because we spend a bunch of time building things that we don't need and then more time removing them from the final libraries.

I'll try to get some actual numbers, though.

**Comment by nornagon** [comment]
```sh
# master
$ du -sh out/Release/Electron.app
126M	out/Release/Electron.app
# with this PR
$ du -sh out/Release/Electron.app
127M	out/Release/Electron.app
```
not sure why it would be bigger, but it certainly doesn't make it smaller!

**Comment by deepak1556** [comment]
> We may inadvertently inherit build configuration from `//chrome/common`

We could remove inheriting any configs from this target.

> It adds to the build time, because we spend a bunch of time building things that we don't need and then more time removing them from the final libraries.
> Even if the bundle size doesn't increase with this PR, it may accidentally do so in a future PR that adds a real dependency, possibly transitively, on something in //chrome/common.

Agreed! this might be a problem. I guess, I relied more on the linker efficiency and didn't care about build time.

Sounds good to build only stuff we depend 👍, it would also make sense to have `gn check` precommit step so that we depend on what we include.

**Comment by nornagon** [comment]
I'm going to close this for now, I think it's OK to depend on `//chrome/common` as long as we're careful not to pull in extra stuff. The unnecessary extra build time is probably a reasonable price to pay for reduced integration effort.

**Pull request closed without merging**
