### PR TITLE
Update libchromiumcontent with official_build turned on

### PR DESCRIPTION
**Pull request by zcbenz**

### CODE REVIEW

**Comment by zeke** [comment]
🎉 

Do we know what the effects of this change will be?

**Comment by alexeykuzmin** [comment]
@zeke
I believe it enables additional optimisations in the build time,
so it may increase time to build libcc but improve app performance.

**Comment by alexeykuzmin** [comment]
Do you guys want to make a release with this change? It could help to get some feedback before we get Chromium 61.

**Comment by hansenman61** [comment]
atom --clear-window-state

**Pull request merged**
