### PR TITLE
fix: allow unsandboxed renderers to request new privileges (5-0-x)

### PR DESCRIPTION
**Pull request by the-j0k3r**
#### Description of Change 

Backport of #19953

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] npm test passes
- [x] tests are changed or added
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic commit guidelines
- [x] PR release notes describe the change in a way relevant to app developers, and are capitalized, punctuated, and past tense.

#### Release Notes

If this fails test please help if you can.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
I dont think theres anything I can do to fix the errors, and if there is Ive no idea what =)

**Comment by nornagon** [comment]
The 5.x release line is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

**Comment by yacc143** [comment]
> The 5.x release line is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

So why does Atom, which is not exactly a trivial or irrelevant Electron app, still use 5.x?

I'm currently wondering if it's worth my time to code up a crude work around (think LD_PRELOAD, fiddling with prctl, thus potentially making my Atom a little bit less safe), or if the issue that make the Atom Terminal Tab a bit useless (all snap installed binaries are symlinks to /usr/bin/snap, a suid root binary, and Ubuntu is delivering more and more stuff via snaps nowadays).

E.g. on my laptop the aws "binary" is a link /usr/bin/snap. Does not work in my editor terminal tab. My working environment setup scripts using fabric internally call sudo, oops. And so on.

**Comment by the-j0k3r** [comment]
@yacc143 

See https://github.com/atom/atom/pull/20764#issuecomment-638148679

Eventually Atom will ship a version of electron thats supported, until then thats the official explanation

**Pull request closed without merging**
