### PR TITLE
fix: titlebar incorrectly displayed on frameless windows

### PR DESCRIPTION
**Pull request by brhenrique**
#### Description of Change

Fixes one of the bugs described [in this thread](https://github.com/electron/electron/issues/39959): deactivating a transparent frameless window will show a title bar unexpectedly.

*Bug demo*

https://github.com/electron/electron/assets/6992723/64315631-cf15-458c-8ec2-db4432145b2e

This PR deletes the `fix_activate_background_material_on_windows` patch added in #39708. Frameless windows should not call `DefWindowProc` as stated by [this comment in hwnd_message_handler.cc](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/win/hwnd_message_handler.cc;l=2238;drc=7d8936b083e0451578cb7d55fed6d9f543013299). 

It looks like even without this patch, the activation of frameless windows with material backgrounds work correctly:

https://github.com/electron/electron/assets/6992723/30e7b4e1-d0ce-4645-adf5-7baa58cb3301

One thing that was broken was the transparency of Mica windows because of a change from #39895, this has also been addresed here.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: fix incorrect title bar shown on frameless transparent windows

### CODE REVIEW

**Comment by brhenrique** [comment]
@clavin could you give some more info on what this patch was solving exactly? Is it that Material windows require that `WN_NCACTIVATE` message and `SetForegroundWindow` is not enough?

**Comment by PlayQuartz** [comment]
Hi, 
From what I can read, I see that it has been fixed. However, it's still not working for me. 
Is there anything I have to change ? 

Here is my code: 
`const { app, BrowserWindow } = require('electron');

let overlayWindow;

app.on('ready', () => {
  overlayWindow = new BrowserWindow({
    width: 1920, 
    height: 1080,
    frame: false, 
    transparent: true,
    titleBarStyle: "hidden",
    alwaysOnTop: true,
    webPreferences: {
      nodeIntegration: true
    },
  });

  overlayWindow.loadFile('HUD.html'); 

  overlayWindow.setIgnoreMouseEvents(true); 

});
`

**Comment by PlayQuartz** [comment]
Hi,
From what I can read, I see that it has been fixed. However, it's still not working for me.
Is there anything I have to change ?

Here is my code:
image

**Comment by KochiyaOcean** [comment]
> Hi, From what I can read, I see that it has been fixed. However, it's still not working for me. Is there anything I have to change ?
> 
> Here is my code: image

You can turn off `transparent: true` because it's not required for material style after this patch

**Comment by PlayQuartz** [comment]
> > Hi, From what I can read, I see that it has been fixed. However, it's still not working for me. Is there anything I have to change ?
> > Here is my code: image
> 
> You can turn off `transparent: true` because it's not required for material style after this patch

Hi, 
Thanks for helping.

I'm currently making a HUD that I want to place on top of my game. However, when I set the background to transparent which I need otherwise I don't see the gameplay, it displays that weird title bar. How can I remove that bar keeping the transparent background. I've been looking around and can't find anything that works, maybe its still not patch

Thanks,

**Comment by brhenrique** [comment]
@PlayQuartz this PR has not been merged yet. You can build it yourself by checking out the branch and following the Electron build steps to test it or wait until it gets released

**Review by clavin — CHANGES_REQUESTED** [review]
Hiya! Sorry on getting back to you so late, my notifications have been a bit of a sinkhole recently.

**About the patch**: I was resolving an issue where Mica/Acrylic frameless windows on Windows were not rendering the background material effect. I tracked it down to the code in the patch. As I understand it, a frameless window with Mica/Acrylic *does* require being painted as active/inactive in order for the Mica/Acrylic effect to work properly. Unfortunately, this seems to also control rendering some other effects like title bars. To get around this, I also told the DWM to hide the title bar.

Unfortunately, this means your second video (`testing-mica-activation.mp4`) shows broken behavior: the background material effect never renders since the window effect never "activates" with the patch missing. 😕 This is what got me stuck on the original issue for a long time and why I had to add this patch.

Here's what it looks like with the patch:

Screenshot 2023-11-13 115652

Notice the faint yellow glow (based on my wallpaper) starting from the upper-left of the window.

This is what it looks like without the patch:

Screenshot 2023-11-13 115950

The Mica effect is missing and the window looks plain.

**Comment by brhenrique** [comment]
thanks for claryfing @clavin, I'll look into alternatives to fix this titlebar issue without breaking Mica backgrounds

**Comment by yuzh0816** [comment]
> thanks for claryfing @clavin, I'll look into alternatives to fix this titlebar issue without breaking Mica backgrounds

Have you get any progress? Looking forward to see the perfect solution!

**Comment by michalzaq12** [comment]
Maybe we should take #40370 into account again

**Comment by meta-panic** [comment]
Hi!

[brhenrique](https://github.com/brhenrique), is any updates here?

**Comment by KochiyaOcean** [comment]
> Maybe we should take #40370 into account again

I still thinks it's a better solution. If we want to fix the arcylic style earlier it would be better to pick the change in `shell/browser/ui/win/electron_desktop_window_tree_host_win.cc`

**Comment by brhenrique** [comment]
@zcbenz @clavin could you take a look at the latest changes please 🙏🏼 ?

What seems to have fixed the titlebar issue was passing `-1` to the lParam of `WM_NCACTIVATE`:

From https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-ncactivate:

> When a visual style is not active for this window, this parameter is a handle to an optional update region for the nonclient area of the window. If this parameter is set to -1, [DefWindowProc](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-defwindowproca) does not repaint the nonclient area to reflect the state change

From what I can tell, neither Chromium nor Electron are using the `ComCtl` visual styles, which might explain why this works.



|            | Transparent: False | Transparent: True, Frame: False | Transparent: True, Frame: True, Mica | Transparent: True, Frame: False, No Mica |
|------------|:------------------:|:--------------------------------:|:-------------------------------------:|:------------------------------------------:|
| **Mica Before** |       ❌       |              ❌              |                ✅                 |                      -                     |
| **Mica After**  |       ✅        |              ❌              |                ✅                 |                      -                     |
| **Title Bar Before** |          -         |              ❌              |                ✅                 |                 ❌                     |
| **Title Bar After**  |          -         |              ✅              |                ✅                 |                 ✅                     |

**Comment by brhenrique** [comment]
closed this by accident, following up on https://github.com/electron/electron/pull/40749

**Pull request closed without merging**
