### PR TITLE
Screen Lock / Unlock events

### LINKED ISSUE #12706: Detecting 'Put display to sleep' on MacOS
Both hot corners and 'CTRL + SHIFT + EJECT' can put the display to sleep without actually suspending the device. This means the `powerMonitor.on('suspend'` event is not emitted, which makes sense, but we still require a way of detecting this use case in electron.

Is there any known way to detect this situation? And if not, would it be possible to add this functionality to electron's powerMonitor? Ideally something like a `'screen-lock'` or `'display-sleep'` event emitted from `powerMonitor`. This would likely apply to other OS as well.

Ideally we would like to be able to detect:
- Screen-lock
image
- Putting display to sleep via hot corner
image
- Putting display to sleep via 'CTRL + SHIFT + EJECT'

Not necessarily with the same powerMonitor events.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Closes #12706

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I though about tests for a while, locking / unlocking a machine during CI runs seems like a good way to break CI so this is probably untestable

**Comment by alexeykuzmin** [comment]
Can you use anything from Chromium's [//ui/base/idle/](https://chromium.googlesource.com/chromium/src.git/+/master/ui/base/idle/)?

**Comment by MarshallOfSound** [comment]
@alexeykuzmin  Unfortunately not, the idle logic in Chromium does do similar stuff (checking for screen lock) but doesn't emit events / monitor when it changes.

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 

To implement [`chrome.idle.onStateChanged`](https://developer.chrome.com/apps/idle#event-onStateChanged) event, Chromium uses stuff from `//ui/base/idle` and polling, check the [`extensions/browser/api/idle/idle_manager.cc`](https://chromium.googlesource.com/chromium/src.git/+/master/extensions/browser/api/idle/idle_manager.cc).

Can we do something similar? I'm not a big fun of reimplementing of something that Chromium already has, especially platform-specific.

**Comment by MarshallOfSound** [comment]
@alexeykuzmin Hooking into events is gonna be way more performant than polling the idle state API.  And although the macOS implementation of this contains some similar code to `idle` the windows implementation is completely new as `idle` on windows doesn't have a concept of `locked` afaics. It's not too much code for a pretty performant event implementation

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 

> the windows implementation is completely new as `idle` on windows doesn't have a concept of `locked` afaics

It does. https://chromium.googlesource.com/chromium/src.git/+/master/ui/base/idle/idle_win.cc#53
```cpp
bool CheckIdleStateIsLocked() {
  return ui::IsWorkstationLocked() || IsScreensaverRunning();
}
```

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 
By "performance" here you mean a delay between a system event and an Electron event?
Polling once a second the typical delay will be about 0.5 seconds, for what use case it not acceptable?
Not using an already existing code you just increase a cost of project maintenance.

I don't really care about this piece of code, it doesn't matter.
But what I care about is the approach we use, and the priorities we have.

To live in a long run it has to be maintainable, it has to be able to survive constant changes.
Trading maintainability for performance should be a tough decision with a good reasoning.
If you cannot measure a performance gain your changes make, why even bother making them?
No matter how performant and bug-free a certain piece of code is now, at some point in time it _will have_ to be changed, and if it is too complex and doesn't have a good test suite, it will gradually loose its speed and get bugs, and eventually will be throw away.

I'm not talking about the code in this PR btw =)
But I think we have to have reasons to write new code better than because it's easy and you like writing code.

**Comment by alexeykuzmin** [comment]
I don't really care about this piece of code, it doesn't matter.
But what I care about is the approach we use, and the priorities we have.

To live in a long run a project has to be maintainable, it has to be able to survive constant changes.
Trading maintainability for performance should be a tough decision with a good reasoning.
Like if you cannot measure a performance gain your changes make, why even bother making them?
No matter how performant and bug-free a certain piece of code is now, at some point in time it will have to be changed, and if it is too complex and doesn't have a good test suite, it will gradually loose its speed and get bugs, and eventually will be throw away.

I'm not talking about the code in this PR btw =)
But I think we have to have reasons to write new code better than because it's easy and you like writing code.

**Comment by MarshallOfSound** [comment]
@alexeykuzmin 

> Polling once a second the typical delay will be about 0.5 seconds, for what use case it not acceptable?

In most cases, that's totally OK, but when the machine is locked on macOS process's can and will get slept, you need to do your stuff as fast as possible.

Happy to take this offline to discuss but in general I agree, premature optimization is a bad thing but in this case timing was key and using event based native logic seemed the only way to go.  (Initially I did try polling native idle API's using the `node-idle-time` module (or something like that))

**Comment by avner-hoffmann** [comment]
@MarshallOfSound - Is this PR supplies events for only catching lock/unlock screen?
What about the case when the monitor is put to sleep but the screen isn't yet locked? 
e.g. on macOS when you press on the  button and then "Sleep", the monitor is put to sleep but doesn't gets locked immediately. Will those events fire in that case, or only after the computer gets locked?

**Pull request merged**
