### PR TITLE
test: exercise fuller `globalShortcut` matrix

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Refs https://github.com/electron/electron/pull/44341.

Test fuller matrix of accelerator combinations to prevent regressions like the above.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by codebytere** [comment]
Interestingly looks like this is causing failures in this test:

> not ok 1279 session module DownloadItem webContents.downloadURL when a save path is specified and the URL is unavailable does not display a save dialog and reports the done state as interrupted

**Review by ckerr — APPROVED** [review]
Hell yeah

**Review by deepak1556 — APPROVED** [review]
Nice!

**Comment by deepak1556** [comment]
Just to clarify, https://github.com/electron/electron/pull/44341 will be triggered only when the accelerators are used in menu entries and the menu attempted to generate shortcut text on activating it. Yet another path we need to capture.

**Pull request merged**
