### PR TITLE
fix: documentation spelling errors

### PR DESCRIPTION
**Pull request by Sajjon**
#### Description of Change
Fix typos only

#### Checklist

Typos only.

I was unable to run tests, since [Build Tools has Xcode issues](https://github.com/electron/build-tools/issues/514#issuecomment-2298204226)

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by Kilian** [comment]
Can you split this up? I think we're glad to accept the typo fixes in the docs, but the ones in code comments and function names probably should be their own. 

I'm not sure we'd want to change the code just to not have typos, but I'll leave that for other maintainers to decide.

**Review by ckerr — CHANGES_REQUESTED** [review]
I love this patch. @Sajjon, thank you for submitting it!

- I agree with @Kilian that the `docs/` fixes could be accepted as-is
- I'm also OK with some of the non-docs changes, e.g. typos in patch descriptions and in source code comments in our own code (e.g. `shell/` or `lib/` or `spec/`)
- But we shouldn't change upstream code. For example, the spelling of  `ConvertableToTraceFormat` comes from [upstream V8](https://v8.github.io/api/head/classv8_1_1ConvertableToTraceFormat.html), so changing it to `Convertible` here will increase our maintenance burden.  Those changes should be removed from this PR and submitted separately to the upstream projects :smile_cat: 

Also, how did you find all these? Is this something that we could automate to watch for new spelling errors in future code?

**Comment by Sajjon** [comment]
> I love this patch. @Sajjon, thank you for submitting it!
> 
> * I agree with @Kilian that the `docs/` fixes could be accepted as-is

Great, I will let this PR (with this source branch) be the `docs/` fixes PR.

> * I'm also OK with some of the non-docs changes, e.g. typos in patch descriptions and in source code comments in our own code (e.g. `shell/` or `lib/` or `spec/`)

Splitting out those fixes from the commit, and will force push so that this PR has a single - `docs/` - commit, and will create **one** new PR for the rest, or do you want one PR per folder?

> * But we shouldn't change upstream code. For example, the spelling of  `ConvertableToTraceFormat` comes from [upstream V8](https://v8.github.io/api/head/classv8_1_1ConvertableToTraceFormat.html), so changing it to `Convertible` here will increase our maintenance burden.  Those changes should be removed from this PR and submitted separately to the upstream projects 😸

Absolutely, I'm reverting, I missed that it was a dependency.


> Also, how did you find all these? Is this something that we could automate to watch for new spelling errors in future code?

I'm using the excellent [`typos` cli tool](https://github.com/crate-ci/typos/tree/master) which can be heavily configures using a `_typos.toml` file. `typos` is crazy fast. You can probably get the same state - i.e. no new change (after the changes I found have been merged) after some hours of config. But most definitely worth it!

Here is a "scaffolding" config you can start with:

```toml
[default]
extend-ignore-re = [
    "\\bBig Sur\\b",
]
check-filename = false

[default.extend-identifiers]
ede3 = "ede3"

[default.extend-words]
invokable = "invokable"
```

See [this page for some more configs](https://github.com/crate-ci/typos/blob/master/docs/reference.md)

I use `typos` + [`pre-commit` tool](https://pre-commit.com) in all my projects, [see e.g. Sargon](https://github.com/radixdlt/sargon/blob/main/.pre-commit-config.yaml#L3-L7), which comprise a nice DevX!

**Review by ckerr — APPROVED** [review]

**Review by erickzhao — APPROVED** [review]
docs: LGTM

**Review by jkleinsc — APPROVED** [review]

**Comment by jkleinsc** [comment]
@Sajjon we require PR commits to be signed in order to merge the PR. Can you sign your commit?

**Comment by Sajjon** [comment]
@jkleinsc I will re-commit with sign commits in this and the other PRs during the day

**Comment by Sajjon** [comment]
@jkleinsc ok now I've signed the commit, thanks for pushing for that, I've been wanting to setup commit signing for a long time!

**Pull request merged**
