### PR TITLE
fix: disallow loading extensions in temp sessions (#22090)

### PR DESCRIPTION
**Pull request by samuelmaddock**
#### Description of Change
Backport of #22090

I removed the docs additions since I assume those don't matter for backports. Extensions docs don't exist in 9-x-y either.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by sentialx** [comment]
Does it mean I won't be able to load extensions into incognito sessions? In Chrome it's possible by checking the `Allow in incognito` switch.

**Comment by samuelmaddock** [comment]
> 
> 
> Does it mean I won't be able to load extensions into incognito sessions? In Chrome it's possible by checking the `Allow in incognito` switch.

I believe the current issue is mostly the potential instability of doing so in Electron. As @nornagon mentioned, a `DCHECK()` statement was hit which usually indicates something isn't quite right. I think if someone were to resolve these issues, maintainers might be receptive to supporting extensions in temporary/incognito sessions.

**Comment by sentialx** [comment]
@samuelmaddock Where does the DCHECK trigger?

**Comment by samuelmaddock** [comment]
> 
> 
> @samuelmaddock Where does the DCHECK trigger?

@sentialx I don't know off hand. If you checkout `master` and remove the changes made in #22090, you should be able to reproduce it.

**Comment by nornagon** [comment]
We don't currently support the "allow in incognito" behavior that's present in Chromium, unfortunately. There's some fairly significant machinery required for it.

**Pull request merged**
