### PR TITLE
fix: don't emit `did-fail-load` for MediaDocuments

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/37804.

Fixes an issue where successfully loaded media documents emit `did-fail-load`. We already throw out cancelled navigations [in certain places](https://github.com/electron/electron/blob/df9c7799c2507ef09d310872b25bcbb890fa03cc/shell/browser/api/electron_api_web_contents.cc#L2096) - we want to address the case where it's incorrectly emitted for media documents.

Per [spec](https://html.spec.whatwg.org/C/browsing-the-web.html#read-media): when we navigate to a media resource: the original request for the media resource—which resulted in a committed navigation—is simply discarded, while the media element created inside the MediaDocument then makes *another new* request for the same media resource.

We fix the issue by determining if the ostensible load failure originated from a media document and discard it if it is.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where successfully loaded media documents emitted `did-fail-load`.

### CODE REVIEW

**Review by deepak1556 — APPROVED** [review]
Possible to have a test ?

**Comment by codebytere** [comment]
@deepak1556 i thought about it and am not sure - the issue at hand is that the webContents never emits `did-finish-load` either. So we'd ultimately be checking for an event _not_ being emitted, which isn't really possible to do because there's then nothing to hook on. We could, I suppose, hook onto `did-stop-loading`? Ideally, we should figure out how to emit `did-finish-load` correctly but at the moment i'm not quite sure how.

**Review by zcbenz — APPROVED** [review]

**Comment by deepak1556** [comment]
What about listening for `media-started-playing` instead ?

**Review by deepak1556 — APPROVED** [review]
Thanks!

**Pull request merged**
