### PR TITLE
update electron-docs-linter and electron-typescript-definitions

### PR DESCRIPTION
**Pull request by zeke**
This PR bumps `electron-docs-linter` and `electron-typescript-definitions` to latest versions.

cc @marshallofsound @felixrieseberg

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Did you mean to add a package lockfile? Otherwise, obvious ✅

**Comment by zeke** [comment]
> Did you mean to add a package lockfile? 

Yeah because [np](http://ghub.io/np) got mad about it being ignored.

**Comment by felixrieseberg** [comment]
I think we should have a bigger conversation around package lockfiles, I'm not sure that we really want to lock down dependencies on a development branch (master). Once we release, sure.

**Comment by zeke** [comment]
Took out the `package-lock.json`. This should be good to go now.

**Pull request merged**
