### PR TITLE
chore: cleanup unusued variables + enable linting

### PR DESCRIPTION
**Pull request by miniak**
Fix errors reported by `@typescript-eslint/no-unused-vars` or suppress in-place

Notes: none

### CODE REVIEW

**Review by deepak1556 — APPROVED** [review]
LGTM on the `spec` folder changes, someone from release should sign on the `script` changes.

**Review by ppontes — APPROVED** [review]

**Review by codebytere — APPROVED** [review]

**Comment by MarshallOfSound** [comment]
@miniak If you're going to keep raising these small "enable one eslint rule at a time" PRs can you instead open them in larger chunks, the number of PRs changing files that impact our cache hashes is causing significant CI churn and obliterating some of our caches and costing us large amounts of CI time.

**Comment by miniak** [comment]
@MarshallOfSound sorry about that, having each as a separate PR makes it easier to review. Did you mean just creating a large PRs with multiple changes combined?

**Comment by MarshallOfSound** [comment]
> Did you mean just creating a large PRs with multiple changes combined?

Yes, lot's of these PRs typically conflict with each other anyway as a result of `eslint` config changes and even if they don't they can easily be stacked into a single PR with separate commits for each change (and the review can be done per-commit).

Otherwise we're gonna burn out entire months CI budget in 2 days of style changes... 🙃

**Comment by miniak** [comment]
@MarshallOfSound I can combine the other PRs related to https://github.com/sindresorhus/eslint-plugin-unicorn, but let's keep this one separate

**Comment by deepak1556** [comment]
Merging based on https://github.com/electron/electron/pull/38898#issuecomment-1603974913

**Pull request merged**
