### PR TITLE
chore: remove patch: fix_breakpad_symbol_generation_on_linux_arm

### PR DESCRIPTION
**Pull request by nornagon**
The patch description doesn't say what the error was, so let's try removing it to find out!

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
@jkleinsc we might need release builds on this one

**Comment by codebytere** [comment]
@nornagon it was a release build error - we'll need to run release builds on this

i'll do it monday!

**Comment by jkleinsc** [comment]
@nornagon @codebytere I kicked off release builds on this one.

**Comment by nornagon** [comment]
Looks to me like the linux arm release build succeeded, but I'm not sure what the "Build Error" build is.

**Comment by jkleinsc** [comment]
`Build Error` is from an incorrectly kicked off release build.  It can safely be ignored.

**Comment by jkleinsc** [comment]
Merging as CI failures are unrelated to PR change.

**Pull request merged**
