### PR TITLE
Bump .node-version file

### LINKED ISSUE #5987: node version
What's the purpose of the .node-version [file](https://github.com/electron/electron/blob/master/.node-version)

It's indicating a version that is inconsistent from the changelog.

### PR DESCRIPTION
**Pull request by danhp**
Close #5987

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Personally I'd like to keep this file, I use https://github.com/nodenv/nodenv to manage node installations and so it is helpful to have this file in Electron so `npm run` scripts use a specific version of node.

**Comment by danhp** [comment]
Should I go ahead and just update it then?

**Comment by kevinsawicki** [comment]
> Should I go ahead and just update it then?

Yeah, that sounds good 👍

**Comment by danhp** [comment]
Updated 😄

**Comment by kevinsawicki** [comment]
Thanks 👍

**Pull request merged**
