### PR TITLE
Use gn chrome54

### LINKED ISSUE #6571: screen.scaleFactor always returns 1 for 125% DPI
- Electron version: 1.2.8
- Operating system: Windows

I have a hidpi screen on my laptop and a normal main monitor that has some scaling applied through windows' display properties. In both cases the following code returns 1 even though I would expect something larger:

```
require('electron').screen.getPrimaryDisplay().scaleFactor
```

### LINKED ISSUE #7814: vm.runInNewContext() & console.log causes devtools to disconnect
* Electron version: 1.4.3
* Operating system: Windows 10 x64

I am building an app which runs user scripts in a sandboxed environment, so I want to use the Node vm module. Here is the code I use to load the user scripts:

```TypeScript
function runInSandbox(visPath: string): IVisualization {
    let context = {
        require: (moduleName) => {
            // I implement a custom "safe" require method here
        },
        console: console,
        module: {}
    };
    let data = fs.readFileSync(path.join(visPath, 'index.js'));
    let result = vm.runInNewContext(data, context, { visPath });
    return result;
}
```

```JavaScript
// userscript/index.js
console.log('test');
```

Now, when I run the app without devtools open, the user scripts execute as expected. However, when I am running with the devtools open, as soon as one of the user scripts does a `console.log`, the devtools crashes with:

```
DevTools was disconnected from the page.
Once the page is reloaded, DevTools will automatically reconnect.
```
electron-crash

However, if I define the `console` object in the context thus:
```TypeScript
console: {
  log: (...args) => console.log(...args),
 },
```

then the script works fine and DevTools does not disconnect, which seems strange, since I have seen many examples online where the `console` object is defined as in the first example.

### LINKED ISSUE #8062: Windows 10 blurry, with desktop scaling on 150%
* Electron version: 1.4.8
* Operating system: Windows 10 Anniversary Edition (build 1607)

### Expected behavior

When dragging a window to hidpi desktop, e.g. 150% scaling, it should scale it correctly. 

### Actual behavior

It does not scale, the window remains blurry.

Google Chrome stable version (54.0.2840.99 m (64-bit)) works correctly, if I drag window (any window e.g. even the developer tools window) it changes the scaling correctly as soon as it gets to the desktop with different scaling factor.

### LINKED ISSUE #8366: net::ERR_INSECURE_RESPONSE error 1.4.13 mac-only
* Electron version: 1.4.13
* Operating system: MACOS

### Expected behavior

No network error

### Actual behavior

We are getting net::ERR_INSECURE_RESPONSE errors on a https css file used within a local html file. The error does not happen on windows, but does happen on multiple different mac machines. This is a recent thing and rolling back electron versions does not help. I suspect that means it is related to the 10 week certificate issue I found noted in other issues.

The bug does not happen in safari or chrome on mac or chrome or electron on windows

### LINKED ISSUE #8405: OpenType CALT feature related with `*` character does not work.
Tested with Iosevka and Fira Code: `*`-related ligatures are not enabled.

### PR DESCRIPTION
**Pull request by alespergl**
Complements [libchromiumcontent #254](https://github.com/electron/libchromiumcontent/pull/254)

Fixes #6571
Fixes #7814 
Fixes #8062
Fixes #8366
Fixes #8405

### CODE REVIEW

**Comment by zcbenz** [comment]
I have rebased this branch on master, ready to merge now.

**Comment by kevinsawicki** [comment]
Rebased this on top of latest master to pull in #8348

**Comment by poiru** [comment]
Fixed compiling Node on Windows (patch [upstreamed](https://github.com/nodejs/node/pull/10893)) and rebased on top of latest master.

**Comment by poiru** [comment]
@kevinsawicki Some specs were failing due to mismatching `NODE_MODULE_VERSION`:

```
not ok 543 third-party module runas can be required in renderer
  Error: The module '/Users/jenkins/Home/workspace/electron-mas-x64/spec/node_modules/runas/build/Release/runas.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 50. This version of Node.js requires
  NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or`npm install`).
```

The modules in question are compiled using the headers downloaded from `https://atom.io/download/electron`. Since they are published when releasing Electron, we have a bit of a chicken and egg problem.

I'm not sure how this has been worked around in the past, but I decided to fix this permanently by generating the header tarballs during bootstrap and then pointing npm/node-gyp at the local tarball.

**Comment by kevinsawicki** [comment]
Thanks @alespergl and @poiru 🚢 🚢 🚢 

Going to release this as a beta 1.5.0 to npm now.

**Comment by herrmannplatz** [comment]
Great job. Looking forward to give it a try.

**Comment by gregor** [comment]
@kevinsawicki What is the eta for the beta?

**Comment by kevinsawicki** [comment]
> What is the eta for the beta?

We hit a linker error on macOS when building the release builds, we are working on upgrading Xcode versions on CI to resolve this.

Assuming the builds/tests are successful after the upgrade, we will release the beta on Monday or Tuesday.

**Comment by kevinsawicki** [comment]
1.5.0 is now published as a prerelease to `npm` under the `beta` tag.

You can install it via `npm install electron@1.5.0` or `electron@beta`, please open new issues for any regressions found.

**Pull request merged**
