### PR TITLE
docs: process.getProcessMemoryInfo() returns a Promise

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Fix `process.getProcessMemoryInfo()` return type, which is `Promise<ProcessMemoryInfo>`, not just `ProcessMemoryInfo`.

/cc @nitsakh

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed `process.getProcessMemoryInfo()` return type to `Promise<ProcessMemoryInfo` in `electron.d.ts`.

### CODE REVIEW

**Comment by miniak** [comment]
The artifact comparison is broken after 
https://github.com/electron/electron/pull/16416

**Comment by miniak** [comment]
There is an issue with the generator. It's producing `getProcessMemoryInfo(): Electron.Promise;` @MarshallOfSound can you please help?

**Comment by miniak** [comment]
@zcbenz it's still not working properly, now it's generating `getProcessMemoryInfo(): Promise<ProcessMemoryInfo>;` instead of `getProcessMemoryInfo(): Promise<Electron.ProcessMemoryInfo>;`

**Comment by alexeykuzmin** [comment]
@miniak Since #16591 is merged, I added the "target/4-0-x" label to this PR to ensure it's backported.
cc @nitsakh

**Comment by alexeykuzmin** [comment]
@miniak Can you please fix conflicts here?

**Comment by miniak** [comment]
@alexeykuzmin rebased. It's still not generated properly.

**Comment by codebytere** [comment]
@miniak
> index.d.ts(10015,37): error TS2304: Cannot find name 'ProcessMemoryInfo'

is likely why it's not generating properly.

**Comment by MarshallOfSound** [comment]
@codebytere This is a bug in the typescript generator not prefixing the innerType correctly in this case, can hack it in tonight

**Comment by miniak** [comment]
@MarshallOfSound did you have time to check the code generator?

**Comment by miniak** [comment]
@MarshallOfSound ping on the typescript generator

**Comment by MarshallOfSound** [comment]
@miniak https://github.com/electron/typescript-definitions/pull/136 will fix this 👍

**Comment by MarshallOfSound** [comment]
@miniak Bumping `electron-typescript-definitions` in this PR should get everything working again 👍

**Pull request merged**
