### PR TITLE
fix: potential crash caused by dlopen different gtk libraries

### PR DESCRIPTION
**Pull request by miniak**
Backport of #33650
Backport of #34141

See that PR for details.

Notes: fix crash when opening gtk file dialogs due to mismatched versions

### CODE REVIEW

**Comment by miniak** [comment]
@deepak1556 can you please check? The change from E18 is slightly different than our internal backport

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
@miniak gn check failed:

```
#!/bin/bash -eo pipefail
cd src
gn gen out/Default --args="import(\"$GN_CONFIG\") import(\"$GN_GOMA_FILE\") $GN_EXTRA_ARGS $GN_BUILDFLAG_ARGS"

ERROR Unresolved dependencies.
//electron:electron_gtk_stubs(//build/toolchain/linux:clang_arm64)
  needs //ui/gtk:gtk_config(//build/toolchain/linux:clang_arm64)


Exited with code exit status 1
CircleCI received exit code 1
```

**Review by deepak1556 — APPROVED** [review]

**Comment by deepak1556** [comment]
@codebytere the gn check is a weird failure, the dependency on `//ui/gtk:gtk_config` was replaced in commit https://github.com/electron/electron/commit/3c0ea37a4adae75794bebe28e27412292945f8c9 with `//build/config/linux/gtk`. The failing step in the gn check run is actually before the actual check in `Default GN gen` which passes on other runs for the same commit.

**Comment by jviotti** [comment]
An interesting Linux one you might be curious about @robertgzr

**Review by VerteDinde — APPROVED** [review]

**Pull request merged**
