### PR TITLE
Migrate base::Bind to base::BindOnce and base::BindRepeating

### PR DESCRIPTION
**Pull request by codebytere**
Resolves https://github.com/electron/electron/issues/12639.

This PR migrates instances of `base::Bind` to `base::BindOnce` and `base::BindRepeating`.

To-Do:
- [x] add new converters for  `base::OnceCallback` and `base::RepeatingCallback`
- [ ] convert all callbacks exposed as event parameters or methods to js land as `base::BindRepeating`
- [ ] convert `base::Bind` to `base::BindOnce` for callbacks passed between threads

/cc @MarshallOfSound @alexeykuzmin @deepak1556

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
It is very difficult to review with so many formatting changes.
Can you please make them in a separate PR?

**Comment by deepak1556** [comment]
Agreed on splitting the PR, also FWIW we can use https://cs.chromium.org/chromium/src/tools/clang/base_bind_rewriters/ clang plugin to lessen the work and fix edge cases manually.

**Comment by deepak1556** [comment]
> It is very difficult to review with so many formatting changes.

Can we do this separately before attempting the migration, it would keep the scope of future PR's to what its actually supposed to do. /cc @alexeykuzmin @codebytere

**Comment by codebytere** [comment]
@deepak1556 yeah, unfortunately the `clang-format` atom package doesn't have an option to only format changes so it ended up formatting the whole files

**Comment by codebytere** [comment]
Closing this and cherry-picking it into a series of smaller PRs.

**Pull request closed without merging**
