### PR TITLE
docs: reword sentence for better understanding

### PR DESCRIPTION
**Pull request by aryanshridhar**
"The main process' primary purpose" -> "The primary purpose of the main process"

#### Description of Change
As suggested in comments, reworded the [sentence](https://www.electronjs.org/docs/latest/tutorial/process-model#window-management) for a better understanding.

#### Checklist

- [x] relevant documentation is changed or added

#### Release Notes

Notes: none

### CODE REVIEW

**Review by dsanders11 — CHANGES_REQUESTED** [review]
Hi @aryanshridhar! Thanks for the PR.

Unfortunately I believe the current wording it correct. The sentence is saying "The main process's primary purpose", [and "'s" for words ending with "s" is usually written as just the single apostrophe](https://www.thepunctuationguide.com/apostrophe.html).

The sentence could be reworded to avoid the apostrophe there (such as, "The primary purpose of the main process"). I'll leave this PR open for the moment so you can rework it if you'd like. We do want the docs to be accessible, so it might be a good idea to avoid punctuation like that which can be confusing.

**Comment by aryanshridhar** [comment]
@dsanders11 Ohh! I wasn't aware of it, My bad! Yup, rewording the sentence sounds like a good idea. Reflected the same in the pr :)

**Comment by dsanders11** [comment]
@aryanshridhar, thanks for the changes!

You'll also need to edit the description of this PR to add back in "Notes: none" so that the release notes check is happy. 🙂 Then I think we'll be ready to merge!

**Comment by aryanshridhar** [comment]
Cool, Done :)

**Review by VerteDinde — APPROVED** [review]

**Comment by VerteDinde** [comment]
Appveyor failures are unrelated

**Pull request merged**
