### PR TITLE
ci: run tests on VSTS in a separate job

### PR DESCRIPTION
**Pull request by alexeykuzmin**
##### Description of Change

Split current monolithic job into two: one to build Electron,
and the other to run its JavaScript tests.

Optionally a "**Custom.UseArtifacts.BuildId**" variable
can be used to run tests using binaries built in a different job.
Useful to rerun test jobs failed because of flaky tests.

This job runs only tests for Electron built in job [14300](https://github.visualstudio.com/electron/_build/results?buildId=14300&view=results):
https://github.visualstudio.com/electron/_build/results?buildId=14327&view=logs

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

/cc @jkleinsc 

##### Release Notes

Notes: no notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@jkleinsc I agree, running `verify-ffmpeg` in a separate job is difficult, and doesn't worth it.

But at least we can run tests in a separate job to allow faster reruns.
That second job now takes about 9 minutes.

**Comment by jkleinsc** [comment]
> But at least we can run tests in a separate job to allow faster reruns.
@alexeykuzmin VSTS currently doesn't allow us to rerun just the test job.  They are working on the feature but I don't think it works right now.  However, we should still do this if we can get the tests running on VSTS VMS.  

You can run the tests on VSTS VMS by using the following parameter:
``` 
queue:
    name: Hosted macOS
```
Eg
```
jobs:
- job: build
  displayName: Build
 ....
- job: run_tests
  displayName: Run Tests
  dependsOn: build
  queue:
    name: Hosted macOS
```

**Comment by alexeykuzmin** [comment]
@jkleinsc 

> VSTS currently doesn't allow us to rerun just the test job.

It is not possible via their UI, but we can archive the same using manually triggered builds.
Check [this build](https://github.visualstudio.com/electron/_build/results?buildId=14327&view=logs), the build step was skipped because we used artefacts from a different build.

**Comment by jkleinsc** [comment]
@alexeykuzmin that is awesome! 👊

**Comment by alexeykuzmin** [comment]
> Optionally a "**Custom.UseArtifacts.BuildId**" variable
can be used to run tests using binaries built in a different job.
Useful to rerun test jobs failed because of flaky tests.

Works only for reruns.
An attempt to run tests for a binary built from a different revision will fail:
https://github.visualstudio.com/electron/_build/results?buildId=14353&view=logs

**Comment by alexeykuzmin** [comment]
> we could probably run tests on VSTS hosted mac VMs

Done.

**Comment by alexeykuzmin** [comment]
@jkleinsc I can't run tests on Microsoft-hosted machines because of a failing test https://github.com/electron/electron/issues/15041
The commit is still there, but the change is commented out.

**Pull request merged**
