### PR TITLE
Introduce Chrome extensions management APIs independent of Dev Tools Extensions

### PR DESCRIPTION
**Pull request by alexstrat**
With the objective to load some Chrome extensions in an Electron app, I introduce here an API to add/remove/get extensions. It's the same mechanism than the one used in `addDevToolsExtension` except the loaded [extensions are not persisted](https://github.com/electron/electron/blob/master/lib/browser/chrome-extension.js#L331).

- [x] documentation
- [x] tests

_Related: #1498_

### CODE REVIEW

**Comment by alexstrat** [comment]
Not sure the build on Travis is failing for legit reasons 🤔

**Comment by kevinsawicki** [comment]
The implementation looks good to me but I'm wondering if it would be better to just augment the 
 existing `addDevToolsExtension` and `removeDevToolsExtension` API with a second options parameter where you could set something like `{persist: false}` to not persist the change.

And we could then add a `persisted` property to the objects returned from `getDevToolsExtensions` to be able to differentiate the two.

What do you think about that @alexstrat?

**Comment by kevinsawicki** [comment]
> Not sure the build on Travis is failing for legit reasons 🤔

Yeah, I'd say don't worry about any flaky travis specs that are non-devtools related

**Comment by alexstrat** [comment]
@kevinsawicki Further than making optional the persistence behind `addDevToolsExtension`, a motivation behind the proposal is to have an API that officializes the support for Chrome extensions already living behind the implementation of `addDevToolsExtension`.

I know electron maintainers [are apparently not willing to support Chrome extensions](https://github.com/electron/electron/issues/1498#issuecomment-96995155), so it'd make sense to chose a path that gets around officializing the support for Chrome extensions.
On one hand, I'd find it too bad because the already-existing implementation is a correct support of parts of Chrome extensions, but on the other hand, an official support is a commitment.

Happy to contribute towards a path to an official support of Chrome extensions — or towards simply tweaking the `addDevToolsExtension` with an option like you suggested. Your call! :)

**Comment by kevinsawicki** [comment]
> Further than making optional the persistence behind addDevToolsExtension, a motivation behind the proposal is to have an API that officializes the support for Chrome extensions already living behind the implementation of addDevToolsExtension.

Thanks for clarifying this, please ignore my previous suggestion then 👍

**Comment by TimNZ** [comment]
@alexstrat Awesome.  Please tell me you are going to implement the full chrome extension api! :)

**Comment by bil88** [comment]
alexstrat  One question, is it valid for any extension?
I am trying but after BrowserWindow.addExtension is already installed or must be installed?
On the other hand you have to pack as such the extension in the app or you can do a get from the store?

**Pull request merged**
