### PR TITLE
fix: Drop support for OS X Mavericks (version 10.9)

### LINKED ISSUE #13125: Set Mac deployment target to 10.10 for Chromium 66+
Chromium doesn't support Mac OS 10.9 from the version 66, see https://support.google.com/chrome/answer/95346?vid=0-44659795628-1527793827712#sysreq_mac

Also verify that there's no OS version checks in code that are no longer required.

/cc @miniak

### PR DESCRIPTION
**Pull request by miniak**
It's not supported anymore by Chromium 66

Fixes #13125

### CODE REVIEW

**Comment by nornagon** [comment]
I'm not sure it's true that chrome 66 doesn't support 10.9? https://chromium.googlesource.com/chromium/src/+/66.0.3359.203/build/config/mac/mac_sdk.gni#12 seems to suggest that chrome 66 is still targeting 10.9 as a deployment target, and it's using functions that are deprecated in 10.10, eg [`launch_data_malloc`](https://chromium.googlesource.com/chromium/src/+/66.0.3359.203/base/mac/launchd.cc#20). Setting `mac_deployment_target` to 10.10.0 in the GN build causes `-Wdeprecated-declarations` errors in `base`.

Perhaps I'm missing something—where did you learn that 10.9 was no longer supported?

**Comment by miniak** [comment]
Beginning with Chrome M66, Chrome requires Mac OSX 10.10 or later. Mac OSX 10.9 users will receive no further updates to Chrome after Chrome M65.

**Comment by MarshallOfSound** [comment]
> The deployment target not being set to 10.10 in Chromium seems like a bug

This was the case with 10.8 for a while, although they didn't "support" it, they didn't go out of their way to break it

**Comment by miniak** [comment]
I’ve seen some commits actually removing some code with 10.9 support. I can dig them up. Anyway, we should probably make sure that we have great 10.14 support instead of caring too much about past. Supporting 5 versions is (10.10-10.14) is already generous.

**Comment by MarshallOfSound** [comment]
@miniak I agree, we'll drop support as soon as Chromium doesn't build targetting 10.9 (which if I'm reading this correctly would be M68) 👍

**Comment by miniak** [comment]
@MarshallOfSound, this commit needs to be reverted as well https://github.com/electron/electron/commit/efa0ec0263481ae188f206625bec6f4a4e5d3ecf

**Comment by nornagon** [comment]
Current `master` chromium is still using functions that are deprecated in 10.10: https://chromium.googlesource.com/chromium/src/+/master/base/mac/launchd.cc#20 and still setting deployment target to 10.9: https://chromium.googlesource.com/chromium/src/+/master/build/config/mac/mac_sdk.gni#17

I think "support" as reported on macrumors != deployment target. We should keep our deployment target the same as chromium's.

FWIW in master chromium there seems to be an additional variable called [`mac_min_system_version`](https://chromium.googlesource.com/chromium/src/+/master/build/config/mac/mac_sdk.gni#25) that's set to 10.10 at time of writing, but this is only used to fill the Info.plist. At some point presumably the `mac_deployment_target` will advance to 10.10, and that time will be the appropriate time for these changes, but it isn't 68.

**Pull request merged**
