### PR TITLE
[WIP] Upgrade to Chromium 60

### PR DESCRIPTION
**Pull request by alexeykuzmin**
**TODO**: Change target branch to *master*.

### CODE REVIEW

**Comment by setpixel** [comment]
Question: is the plan to upgrade to 60 for 1.8 release, skipping 59?

**Comment by alexeykuzmin** [comment]
> is the plan to upgrade to 60 for 1.8 release, skipping 59?

Nope. Chromium 59 upgrade is kind of ready to merge into the master.
It would take too much time to wait for code to be fixed with Chromium 60 changes.

**Comment by alexeykuzmin** [comment]
We are going to skip Chromium 60 and upgrade to 61 instead.
See #10213. Closed.

**Comment by YurySolovyov** [comment]
Why so?

**Comment by alexeykuzmin** [comment]
@YurySolovyov 
We are not delaying the upgrade, it has already been started.
It won't make a huge difference in terms of time and effort required, but when it's done we will end up with the latest Chromium under the hood instead of the latest-minus-one.

**Pull request closed without merging**
