### PR TITLE
fix: Introduce LocationProxy for BrowserWindowProxy

### LINKED ISSUE #15017: BrowserWindowProxy.location.href is undefined
* Output of `node_modules/.bin/electron --version`: since atleast 1.7.11 and all newer versions up to master
* Operating System (Platform and Version): All

**Expected Behavior**
Calling `location.href` of child window if `nativeWindowOpen = false` returns string with current URL.

**Actual behavior**
Calling `location.href` of child window if `nativeWindowOpen = false` returns undefined

**To Reproduce**
```
const w = window.open('https://google.com')
w.location.href = 'https://electronjs.org' // fail
```

In `/lib/renderer/window-setup.js`, `window.location` is defined like this, instead of  emulating `Location` object properly 
```javascript
function BrowserWindowProxy (ipcRenderer, guestId) {
  ...
  defineProperty(this, 'location', {
    get: function () {
      return ipcRenderer.sendSync('ELECTRON_GUEST_WINDOW_MANAGER_WEB_CONTENTS_METHOD_SYNC', guestId, 'getURL')
    },
    set: function (url) {
      url = resolveURL(url)
      return ipcRenderer.sendSync('ELECTRON_GUEST_WINDOW_MANAGER_WEB_CONTENTS_METHOD_SYNC', guestId, 'loadURL', url)
    }
  })
...
```

### PR DESCRIPTION
**Pull request by Anrock**
Fixes #15017

##### Description of Change
Implements proxy Location object for BrowserWindowProxy

##### Checklist
- [ ] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes
Notes: Implement proper Location object for BrowserWindowProxy

### CODE REVIEW

**Comment by Anrock** [comment]
@codebytere no, i didn't - once again `git pull` rendered master unbuildable for me. Therefore marked as WIP.

However i'm interested in top-level review if this approach is viable and if it's a welcomed change in regards of electron architecture..

**Comment by Anrock** [comment]
@codebytere ping

**Comment by alexeykuzmin** [comment]
@Anrock 

https://circleci.com/gh/electron/electron/82004
Among all failed tests only these two look like real failures:
 - "chromium feature window.open defines a window.location getter"
 - "BrowserWindow module contextIsolation option with and without sandbox option doesn't break ipc serialization"

Can you please fix them?

**Comment by Anrock** [comment]
@alexeykuzmin i'll take a look at it as soon as i can. Don't have much free time for it, unfortunately.

**Pull request merged**
