### PR TITLE
fix: throw when using globalShortcut before ready

### LINKED ISSUE #26986: CHECK when globalShortcut.register called before app.on('ready')
I have something like this:

```
const { app, BrowserWindow, BrowserView, globalShortcut} = require('electron');
...
globalShortcut.register("F5", () => {
    alert();
});
```

Adding this `globalShortcut.register` makes Electron crash on startup.

What's the best way to do an action when F5 is pressed, globally (even if there are other browserviews in the main window)?

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #26986.

We should throw in JS instead of CHECK()ing.

No release notes because this module was already not usable before
app.on('ready'), it just changes a CHECK to an exception.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
In order to be API consistent shouldn't this just `return false`.  I don't really like introducing exceptions into methods that didn't throw before

**Comment by codebytere** [comment]
@MarshallOfSound i see the concern but i think from a user perspective it's a lot less friendly to fail without giving the user a clear notice as to why. Our docs say this, yes, but that's not always intuitive to the user and to that end i think introducing exceptions to clarify _extant_ behavior is a net positive.

**Comment by MarshallOfSound** [comment]
> Our docs say this, yes, but that's not always intuitive to the user and to that end i think introducing exceptions to clarify extant behavior is a net positive.

Yes, but... Breaking change.  If something that never threw, now throws that's a breaking change IMO.  The "hitting the CHECK" is new.  So if we specifically only backport this to branches that hit the CHECK then we're OK.  If we backport beyond that, then we need to not throw an error on those older branches.

**Comment by nornagon** [comment]
@MarshallOfSound this will only throw in cases which previously `CHECK`ed.

The return value from these functions (`false`) is ignored, as an exception is thrown.

**Comment by nornagon** [comment]
The `CHECK` was added in 2013.

**Comment by MarshallOfSound** [comment]
> To double check, I confirmed that all currently supported versions of electron currently CHECK when using globalShortcut prior to app.on('ready').

Sounds good to me then 👍  Would have crashed, now errors, so it's Better ™️ 😆

**Comment by nornagon** [comment]
@MarshallOfSound switch your ❌  to a ✅  then?

**Review by MarshallOfSound — APPROVED** [review]

**Review by miniak — APPROVED** [review]

**Pull request merged**
