### PR TITLE
refactor: only create webContents after 'will-attach-webview'

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Merge `createGuest` and `attachGuest` handlers. Remove `WebContentsPreferences::Merge`.
Depends on #24344 and #30280.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: WebContents for `<webview>` are now only created after the `'will-attach-webview'` event is emitted and `preventDefault` is not called.

### CODE REVIEW

**Review by nornagon — APPROVED** [review]
looks like a nice refactor! as a sanity check, as i'm not sure we have any tests for it, do things still work if you detach a webview from the dom, modify its parameters, and reattach it?

**Review by ckerr — APPROVED** [review]
:heavy_plus_sign: on the test question; but otherwise, this looks like a good patch

**Comment by miniak** [comment]
@nornagon I does work

**Comment by miniak** [comment]
@zcbenz and @deepak1556 can you please review?

**Review by deepak1556 — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Review by nornagon — APPROVED** [review]
nice cleanup.

**Pull request merged**
