### PR TITLE
build: update libcxx filenames

### PR DESCRIPTION
**Pull request by VerteDinde**
#### Description of Change

This PR updates the needed libcxx filenames in filenames.libcxx.gn after a recent Chromium bump.

Fixes main `publish-linux` job for nightly.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by VerteDinde** [comment]
publish-linux job here is passing where it was previously failing - here it’s failing on upload, (which is expected, this isn’t a real release)

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
Linux failure is:
> `upload.py: error: unrecognized arguments: --UPLOAD_TO_STORAGE`

which is not something i think is directly caused by this PR?

**Review by codebytere — COMMENTED** [review]
Linux failure is:

> `upload.py: error: unrecognized arguments: --UPLOAD_TO_STORAGE`

which is not something i think is directly caused by this PR? that's here: https://github.com/electron/electron/blob/97b353a30a0e92a169fb0557ddff641fa0332d7c/.circleci/config/base.yml#L638

however, i'm not sure why `--UPLOAD_TO_STORAGE` is all caps? other usage is lowecase and the file itself indicates that as well: https://github.com/electron/electron/blob/ff804e3a748c72f4812af8ccf3b1d7442a468f4a/script/release/uploaders/upload.py#L175

I believe it's case-sensitive so maybe we should try changing that @VerteDinde 🤔

**Comment by VerteDinde** [comment]
@codebytere Good call! You're right, I don't know why that's listed in uppercase here 🤔 I'll try pushing a fix here and seeing if it makes a difference

**Pull request merged**
