### PR TITLE
Simplify customButtonsOnHover implementation

### PR DESCRIPTION
**Pull request by poiru**

### CODE REVIEW

**Comment by poiru** [comment]
FWIW, I have more fixes that I will PR later when I have some more time.

**Comment by poiru** [comment]
I have more fixes that I will PR later on.

I think we should also change the API to something like this for greater flexibility:

```js
customWindowButtons: {
  x: 0,
  y: 0,
  showOnHover: true,
}
```

`titleBarStyle: 'hidden' | 'hidden-inset'` would then be deprecated and mapped to `customTitleBar` for backwards compatibility.

@mst128256 @tonyganch Thoughts?

**Comment by kevinsawicki** [comment]
> titleBarStyle: 'hidden' | 'hidden-inset' would then be deprecated and mapped to customWindowButtons for backwards compatibility.

Yeah, I think this approach going forward sounds good 👍 

Thanks for cleaning this up, I'm going to merge this and we can discuss the option changes/deprecations in another PR :shipit:

**Comment by MarshallOfSound** [comment]
@poiru The original PR message included this

> This also includes a fix to make the window round instead of being rectangular.

I've actually been looking for a way to get a rectangular window on macOS (without rounded corners).  Is that what was just removed and if so can we add it back under an option 😄 If you just point out the code that made the rounded corners I can put it behind an option 👍

**Comment by poiru** [comment]
@MarshallOfSound The rectangular window is caused by: https://github.com/electron/electron/blob/7a3a092c720c66090898df8d1547fc89017d0d5b/atom/browser/native_window_mac.mm#L843-L847

I was going to remove it in this PR, but it made the window buttons always visible. I'm planning to get rid of that and change our custom button implementation to no longer rely on it in a future PR. Maybe we should have a separate option to use `NSFullSizeContentViewWindowMask`.

**Pull request merged**
