### PR TITLE
Use dynamic CRT in the release build

### PR DESCRIPTION
**Pull request by alespergl**
This addresses #9443 
Depends on [libchromiumcontent#312](https://github.com/electron/libchromiumcontent/pull/312)

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Just to call this out: I'm pretty happy about this change. We're already including the CRT anyway, so I feel like developers just gain flexibility here.

**Comment by computerquip-streamlabs** [comment]
Is there any need for atom/node/* and things that rely on that?

**Comment by alespergl** [comment]
Not anymore after this is merged. We'll take care of that in a separate PR.

**Comment by zcbenz** [comment]
I'm 👍 on this. It should probably be part of next minor update.

**Pull request merged**
