### PR TITLE
fix: add missing translation string for ax tree

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes https://sentry.io/share/issue/be7de46ea41d4628ac692dadc5a8248d/

Notes: Fixed potential crash while generating accessibility trees for certain images

### CODE REVIEW

**Review by miniak — APPROVED** [review]

**Review by VerteDinde — APPROVED** [review]

**Comment by VerteDinde** [comment]
Opting to merge this PR in now in the interest of getting a backport queued up and green for 18-x-y and 19-x-y before tomorrow morning - build-linux is failing one test, which is a known flake.

**Comment by andersk** [comment]
This fix didn’t seem to work, at least in 18.0.3 which includes the backport:

- #33693

**Comment by MRayermannMSFT** [comment]
@MarshallOfSound @VerteDinde

**Comment by MRayermannMSFT** [comment]
Ok, I'm just a slow-poke here. I think I understand now. The fix did not take, and another fix was made in 18.1.0. I'm all good.

**Comment by MarshallOfSound** [comment]
@MRayermannMSFT Please don't randomly tag maintainers, I have mention notifications enabled for important issues, not a comment consistent of just two @ mentions.

**Pull request merged**
