### PR TITLE
feat: session.resolveHost

### PR DESCRIPTION
**Pull request by indutny**
Backport of #37690.

See that PR for details.

Notes: Introduced `session.resolveHost` for resolving hostnames with Chromium's DNS resolver

### CODE REVIEW

**Comment by indutny** [comment]
cc @nornagon ?

**Comment by VerteDinde** [comment]
@indutny Thanks for the backport! We have a Releases WG meeting this afternoon we review/approve backport requests, will get this reviewed for you 🙇‍♀️

**Comment by nornagon** [comment]
@indutny please copy over the release notes 🙇🏻

**Comment by indutny** [comment]
Really appreciate it. Thanks!

**Comment by indutny** [comment]
> please copy over the release notes 🙇🏻

done, sorry! I wasn't sure what the template for the backport PR should look like so I copied it from https://github.com/electron/electron/pull/37846 :joy:

**Comment by dsanders11** [comment]
@indutny, if you use [`electron/build-tools`](https://github.com/electron/build-tools), you can do the backport PR with the helpers there, which should do everything for you. 🙂 

```sh
$ e backport 37690
// Fix conflicts, `git cherry-pick --continue`
$ git push fork
$ e pr --backport 37690
```

**Comment by indutny** [comment]
@dsanders11 😮

**Review by VerteDinde — APPROVED** [review]
Backport approved on behalf of @electron/wg-releases

**Pull request merged**
