### PR TITLE
feat: support mixed-sandbox mode on linux

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This adds a patch to Chromium to allow mixing `--no-zygote` renderers with regular zygote-launched renderers.

This currently only works when launching the app with `--enable-mixed-sandbox` on the command line—when using the `app.enableMixedSandbox` API, the zygote process is launched before the JS initialization code is run, and thus fails to pick up the mixed-sandbox flag and launches with `--no-sandbox`, resulting in a weird mix of zygote-launched and non-zygote-launched renderers all of which are without sandbox. My preferred fix for that problem is to remove the `--enable-mixed-sandbox` flag and have it be the default (overridden by `--no-sandbox` or `--enable-sandbox`).

I'm not exactly sure how this will interact with site-per-process and navigation. In particular, will this behave correctly if you load `a.com` in a sandboxed renderer and then navigate to `b.com` with site-per-process enabled? (Further, what's the status of site-per-process? cc @ppontes)

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: mixed-sandbox mode works on Linux

### CODE REVIEW

**Comment by ppontes** [comment]
@nornagon, site-per-process is also WIP: [15821](https://github.com/electron/electron/pull/15821). We're addressing one last issue before we can attempt to merge it.

**Comment by miniak** [comment]
@nornagon would it make sense to keep two zygotes? one sandboxed and one non-sandboxed?

**Comment by nornagon** [comment]
possibly, but it would be a rather more involved change and it's not clear to me that the zygote is providing substantial value other than optimizing sandbox setup (see e.g. [rsesek's comment here](https://chromium-review.googlesource.com/c/chromium/src/+/1316356/1#message-5dec694040cec1ff1e06188a0558883af176612e)). It may indeed be a worthwhile improvement, but without data to back it up I don't think it's worth going through the effort of supporting a 2nd zygote.

**Comment by nornagon** [comment]
ping @zcbenz @deepak1556, this is ready for review :)

**Comment by deepak1556** [comment]
Can we have a tracking issue for https://github.com/electron/electron/pull/15870#issuecomment-443896793 ? Could lead to a potential enhancement.

**Comment by nornagon** [comment]
I don't think it makes sense to have a tracking issue at this time, given we haven't even evaluated whether it would be an improvement or not.

**Comment by deepak1556** [comment]
>  given we haven't even evaluated whether it would be an improvement or not.

The tracking issue in my mind was for this specifically, don't want it to get lost in PR comments :)

**Comment by nornagon** [comment]
> don't want it to get lost in PR comments

want it to get lost in the issue tracker instead? :D

**Comment by nornagon** [comment]
Merging even though I still have some concerns about the way this might interact with site-per-process, we can revert / fix forward if we discover issues.

**Pull request merged**
