### PR TITLE
[WIP] Upgrade to Chromium 59

### PR DESCRIPTION
**Pull request by alexeykuzmin**
Related to #9679.  
Here are mostly fixes of trivial compilation errors. There are still plenty of errors left, I'm working on it.  
Keep it mind that a [PR](https://github.com/electron/libchromiumcontent/pull/313) with changes to libcc hasn't been merged yet.

/cc @tonyganch @kevinsawicki @zcbenz @setpixel @dezmathio

Almost all commits have a corresponding CL title as a first line of their commit message.
Link(s) to the CL(s) can be also found in the commit message.

Incomplete list of the compilation errors left:
- [x] **atom/browser/bridge_task_runner.cc**:16:28: error: call to implicitly-deleted copy constructor of 'base::OnceClosure'
  Related CLs: [chromium/2637843002](https://codereview.chromium.org/2637843002), [chromium/2726523002](https://codereview.chromium.org/2726523002), [chromium/2797133002](https://codereview.chromium.org/2797133002).
- [x] **atom/browser/api/frame_subscriber.cc**:87:10: error: no member named 'copyPixelsTo' in 'SkBitmap'
  Related issue: [Remove SkBitmap::copyPixelsTo](https://bugs.chromium.org/p/skia/issues/detail?id=6465)
- [x] **atom/browser/net/atom_url_request_job_factory.h**:58:44: error: only virtual member functions can be marked 'override'
  Related CL: https://codereview.chromium.org/2783343002
- [ ] _(OSR disabled)_ **atom/browser/osr/osr_web_contents_view.cc**:104:14: error: allocating an object of abstract class type 'atom::OffScreenRenderWidgetHostView'
- [ ] _(OSR disabled)_ **atom/browser/osr/osr_render_widget_host_view.cc**:562:40: error: use of undeclared identifier 'GetBackgroundOpaque'
- [ ]  _(OSR disabled)_ **atom/browser/osr/osr_render_widget_host_view.cc**:581:37: error: out-of-line definition of 'OnSwapCompositorFrame' does not match any declaration in 'atom::OffScreenRenderWidgetHostView'
- [ ]  _(OSR disabled)_ **atom/browser/osr/osr_render_widget_host_view.cc**:602:32: error: no member named 'SwapDelegatedFrame' in 'content::DelegatedFrameHost'
- [ ]  _(OSR disabled)_ **atom/browser/osr/osr_render_widget_host_view_mac.mm**:44:51: error: only virtual member functions can be marked 'override'
- [ ]  _(OSR disabled)_ **atom/browser/osr/osr_render_widget_host_view_mac.mm**:45:43: error: unknown type name 'ViewMsg_ReclaimCompositorResources'
- [x] **atom/common/native_mate_converters/blink_converter.cc**:250:28: error: no member named 'x' in 'blink::WebMouseEvent'
  Related CL: https://codereview.chromium.org/2782893002
- [x] **atom/renderer/api/atom_api_spell_check_client.h**:39:64: error: only virtual member functions can be marked 'override'
  Related issue: [OOPIF: SpellCheckProvider is a RenderViewObserver](https://crbug.com/638361) and [design doc](https://goo.gl/VfCENk).
- [x] **atom/renderer/atom_autofill_agent.h**:38:45: error: only virtual member functions can be marked 'override'
  Related CL: https://codereview.chromium.org/2766053002
- [x] **vendor/native_mate/native_mate/converter.h**:298:24: error: no member named 'ToV8' in 'mate::Converter<content::ServiceWorkerCapability, void>'
  Related CL: https://codereview.chromium.org/2751343002

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
Would it make sense to create a feature branch in the electron/electron repo, push all the changes there and re-create a pr?

**Comment by zcbenz** [comment]
> Would it make sense to create a feature branch in the electron/electron repo, push all the changes there and re-create a pr?

It is not needed on Electron's side, the third party CI workers can work fine.

A thing to notice is that the CI servers normally only build Debug versions, so it is necessary to manually test the Release build. I usually test by running `./script/bump-version.py` and then push the changes to a temporary brach, it would trigger CI servers to build Release versions.

**Comment by tonyganch** [comment]
PR currently should be in a state with OSR disabled, compilation passing on mac and 18 tests failing.
We're working on win build and looking into tests.

**Comment by alexeykuzmin** [comment]
@kevinsawicki @zcbenz 
Is there anyone who can look at OSR related compilation errors?
I have disabled OSR for now, at least compilation-wise, but is has to be fixed before a new Electron version can be released.

**Comment by brenca** [comment]
I might be able to take a look at the OSR code on Windows this week.

**Comment by alexeykuzmin** [comment]
I'm going to tidy things up a little bit here and make a force push.
If someone is working on the tests or anything else right now please let me now or simply just push all what you have. I expect to finish everything on June 30th at 9pm UTC.

/cc @tonyganch @kevinsawicki

**Comment by kevinsawicki** [comment]
> I'm going to tidy things up a little bit here and make a force push.

Sounds good, I pushed up a commit to fix the failing devtools specs.

**Comment by alexeykuzmin** [comment]
On my Windows machine Electron builds successfully but crashes when started.
Can anyone look into it please?
exception

/cc @zcbenz @kevinsawicki @tonyganch

**Comment by kevinsawicki** [comment]
> Can anyone look into it please?

Yup, taking a look now.

**Comment by kevinsawicki** [comment]
> On my Windows machine Electron builds successfully but crashes when started.

I added a default layout provider to fix the crash which was introduced in https://chromium.googlesource.com/chromium/src/+/4e8cac4101f13be9f86b455f06ec7b46fc707e93

Now it launches for me without crashing but the menus don't appear when clicked, investigating further.

**Comment by kevinsawicki** [comment]
> Now it launches for me without crashing but the menus don't appear when clicked, investigating further

Fixed this issue, menus now appear on Windows.

Looks like the async menu support was removed in Chrome 59 https://chromium.googlesource.com/chromium/src/+/b31c887a2d14761b078f329629f1d3469106b891%5E%21/ so the stack-allocated `MenuDelegate` was getting deleted too soon since `RunMenu` no returns immediately.

**Comment by alexeykuzmin** [comment]
> I might be able to take a look at the OSR code on Windows this week.

@brenca Is there a chance you would have time to do that anytime soon?

**Comment by brenca** [comment]
@alexeykumin Sorry, I sadly can't. Maybe @gerhardberger could.

**Comment by gerhardberger** [comment]
@alexeykuzmin @brenca I will try and fix the OSR errors during the week, but I can only test on macOS though.

**Comment by alper-teke** [comment]
What is the plan for this PR? When ready, will it be merged to 1.7.x? 
Or will you soon "release" 1.7.x and then this is a candidate for 1.8?

**Comment by brenca** [comment]
AFAIK minor versions are bumped with Chromium and node version bumps, so it would be 1.8.x

**Comment by kevinsawicki** [comment]
@alexeykuzmin can you re-open this pull request from a branch within this repository (instead of your fork) so we can get the CI builds going? They only trigger for branches inside this repository.

**Comment by alexeykuzmin** [comment]
> @alexeykuzmin can you re-open this pull request from a branch within this repository (instead of your fork) so we can get the CI builds going? They only trigger for branches inside this repository.

@kevinsawicki, sure. The only reason why I left the branch in my fork was [this reply](https://github.com/electron/electron/pull/9766#issuecomment-309657400) by @zcbenz:
> > Would it make sense to create a feature branch in the electron/electron repo, push all the changes there and re-create a pr? 

 > It is not needed on Electron's side, the third party CI workers can work fine.

**Comment by alexeykuzmin** [comment]
> @alexeykuzmin can you re-open this pull request from a branch within this repository

@kevinsawicki #9946

**Pull request closed without merging**
