### PR TITLE
chore: generate API definitions in the project root

### PR DESCRIPTION
**Pull request by alexeykuzmin**
'out' folder doesn't exist in a freshly cloned repo,
and there are not reasons to use it anyway.

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: no notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@MarshallOfSound I can't find a single script which would use `out/electron-api.json` or `out/electron.d.ts`

**Comment by nornagon** [comment]
wow, the lint check passed! 😮

**Comment by MarshallOfSound** [comment]
@alexeykuzmin Both files are referenced in [`upload.py`](https://github.com/electron/electron/blob/master/script/upload.py#L68-L69)

**Comment by MarshallOfSound** [comment]
@alexeykuzmin @ckerr This is my bad I should have requested changes but can we ensure we have a follow up PR for the path changes in `upload.py` as commented above

**Comment by alexeykuzmin** [comment]
> @alexeykuzmin Both files are referenced in [`upload.py`](https://github.com/electron/electron/blob/master/script/upload.py#L68-L69)

@MarshallOfSound 
Paths in that file are `//dist/electron-api.json` and `//dist/electron.d.ts`.
What kind of a change you want to be done there?

**Pull request merged**
