### PR TITLE
test: move dialog spec to main process

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Moves the dialog spec to the main process. Also re-enable the tests that actually create dialogs, as they're no longer synchronous.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
hmm, looks like some funkiness on windows when destroying a window with an open dialog...

**Comment by zcbenz** [comment]
It seems that the simplest way too fix the crash is to add `ScopedAllowBaseSyncPrimitives` in `~TopLevelWindow`

```
[5820:0712/193002.180:FATAL:thread_restrictions.cc(175)] Check failed: !g_base_sync_primitives_disallowed.Get().Get(). Waiting on a //base sync primitive is not allowed on this thread to prevent jank and deadlock. If waiting on a //base sync primitive is unavoidable, do it within the scope of a ScopedAllowBaseSyncPrimitives. If in a test, use ScopedAllowBaseSyncPrimitivesForTesting.
22068g_base_sync_primitives_disallowed currently set to true by 
22069Backtrace:
22070	base::debug::CollectStackTrace [0x036B81D3+19] (o:\base\debug\stack_trace_win.cc:284)
22071	base::debug::StackTrace::StackTrace [0x036B2481+17] (o:\base\debug\stack_trace.cc:203)
22072	base::`anonymous namespace'::ThreadLocalBooleanWithStacks::Set [0x0376E6DA+58] (o:\base\threading\thread_restrictions.cc:36)
22073	base::ScopedAllowBaseSyncPrimitivesOutsideBlockingScope::~ScopedAllowBaseSyncPrimitivesOutsideBlockingScope [0x03744B35+117] (o:\base\threading\thread_restrictions.cc:138)
22074	viz::HostFrameSinkManager::InvalidateFrameSinkId [0x03DB1162+274] (o:\components\viz\host\host_frame_sink_manager.cc:119)
22075	ui::Compositor::~Compositor [0x03C979D7+567] (o:\ui\compositor\compositor.cc:273)
22076	ui::Compositor::~Compositor [0x03CA3BEB+11] (o:\ui\compositor\compositor.cc:243)
22077	aura::WindowTreeHost::DestroyCompositor [0x03C92B2D+41] (o:\ui\aura\window_tree_host.cc:366)
22078	views::HWNDMessageHandler::OnDestroy [0x051E375F+59] (o:\ui\views\win\hwnd_message_handler.cc:1631)
22079	views::HWNDMessageHandler::_ProcessWindowMessage [0x051E0C38+1264] (o:\ui\views\win\hwnd_message_handler.h:418)
22080	views::HWNDMessageHandler::OnWndProc [0x051E0659+121] (o:\ui\views\win\hwnd_message_handler.cc:991)
22081	gfx::WindowImpl::WndProc [0x039EB32F+173] (o:\ui\gfx\win\window_impl.cc:299)
22082	base::win::WrappedWindowProc<&gfx::WindowImpl::WndProc> [0x039EB180+80] (o:\base\win\wrapped_window_proc.h:78)
22083	CallNextHookEx [0x74FF8E71+177]
22084	CallNextHookEx [0x74FF90D1+785]
22085	CallNextHookEx [0x74FF932C+1388]
22086	CallNextHookEx [0x74FF9529+1897]
22087	KiUserCallbackDispatcher [0x77580666+54]
22088	views::Widget::CloseNow [0x051D7038+158] (o:\ui\views\widget\widget.cc:620)
22089	electron::api::TopLevelWindow::~TopLevelWindow [0x059AB03B+61] (o:\electron\shell\browser\api\atom_api_top_level_window.cc:121)
22090
````

**Comment by nornagon** [comment]
Hmm, that doesn't seem like a great approach; it seems like something deeper in Chromium should be responsible for allowing sync primitives in this situation. Perhaps we're doing something weird in the teardown sequence.

There's also this error message which seems like it could be related:
> [5536:0712/192643.847:ERROR:surface_manager.cc(439)] Old/orphaned temporary reference to SurfaceId(FrameSinkId[](32, 3), LocalSurfaceId(3, 1, 5114...))

**Comment by nornagon** [comment]
remaining windows failure is a flake.

**Pull request merged**
