### PR TITLE
feat: add `²` AZERTY keyboard shortcut support

### PR DESCRIPTION
**Pull request by Axelcouty**
#### Description of Change

Adds support for `²` key to electron's accelerator, see the [feature request](https://github.com/electron/electron/issues/39333).  

@mlaurencin would you be able to tell me if I can convert this Draft to a Pull Request or If I should make some changes beforehand ? :pleading_face: 

I don't know how to write tests for this

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Added support for AZERTY `²` keyboard shorcut to accelerator.

### CODE REVIEW

**Review by codebytere — COMMENTED** [review]
In addition to the above, it doesn't make a lot of sense in my opinion to add a single superscript number without adding the rest, especially when it's not clear this couldn't be accomplished by mapping to another comparable key.

**Comment by Axelcouty** [comment]
@codebytere Your point makes sense to me I'll try to see how it's done to handle them

**Comment by ogdabou** [comment]
Thanks or your comments,

> @mlaurencin 
>  have you tried testing to see if ² maps to another key on the QWERTY keyboard?

I tried locally to type `²` with a qwerty (US) layout and got `` ` ``

> @codebytere 
> superscript number without adding the rest

What do you mean exactly by "the rest" ?

For example I see that the belgian AZERTY has both `²` and `³` at this location, so that would mean I should add them ?

Just to be sure I understand,
@mlaurencin suggests that such findings should be resported in the documentation while @codebytere you suggest that I try to map them all, right (or some) ?

Thanks for your time :)

**Comment by mlaurencin** [comment]
@Axelcouty Speaking to my own suggestion, it seems that you can accomplish what you want to do by using ` as your accelerator. Is that correct? If so, rather than adding new accelerators, my suggestion would be to update the documentation to note that the accelerators are based on the QWERTY keyboard layout. Thus when adding accelerators to your Electron project on other layouts, one must note what character is used on the QWERTY keyboard for the key they want to map to.

**Comment by zcbenz** [comment]
I'm closing this PR since there has been no update for a long time, and technically the feature this PR wanted to implemented does not seem to be possible.

**Pull request closed without merging**
