### PR TITLE
docs: NSPrincipalClass should be ElectronApplication

### PR DESCRIPTION
**Pull request by nornagon**
This was renamed, just updating the docs.

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
maybe we should revert the rename instead...?

**Comment by MarshallOfSound** [comment]
> maybe we should revert the rename instead...?

Sounds like it's the safest option 👍

**Comment by nornagon** [comment]
I have no idea what this thing does; what would be the expected behavior of this being broken?

**Comment by MarshallOfSound** [comment]
@nornagon Deep links would stop working, i.e. `my-app://`

**Pull request closed without merging**
