### PR TITLE
fix: prevent Menu.buildFromTemplate with empty array

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/23282.

Prevent issues with menu creation and subsequent pane focus from menu bar by preventing menus from being created from an empty array. I can't conceive a valid use case for this, since if one wants to remove a menu they should be be passing `null` to `win.setMenu()` or calling `win.removeMenu()`. This issue is also specific to top-level menus, and not submenus, so the new check and exception is scoped to top-level menus.

cc @zcbenz @jkleinsc @MarshallOfSound 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed a potential crash when menu is created from an empty template.

### CODE REVIEW

**Comment by zcbenz** [comment]
Would the crash in original issue still happen when calling `win.setMenu(new Menu)`?

**Comment by dezsiszabi** [comment]
Just to give a usecase.

We have a wrapper package around electron window creation/menu creation. It exposes a WindowBuilder, TrayBuilder, MenuBuilder etc (using a fluent API/builder pattern to compose the electron application).

In this wrapper code we called a code similar to

```
window.setMenu(Menu.buildFromTemplate(this.menuBuilder.map(mb => mb.build())));
```

Of course the issue should be prevented in our code by adding defensive checks and not call `setMenu` when there are no menu builders.

That said, I'd still prefer an early failure which doesn't result in a crash.

Either:

1. Fail early by throwing an exception if `Menu.buildFromTemplate` is called with an empty array
OR
2. `Menu.buildFromTemplate` should return `null` if called with an empty array.

In both cases the documentation should mention the behavior in case `Menu.buildFromTemplate` is called with an empty array.

**Comment by codebytere** [comment]
@zcbenz it shouldn't from my read of [this function](https://github.com/electron/electron/blob/6159066c261a286a2e7ac4bb3cff3800c0a6d2b3/shell/browser/api/electron_api_top_level_window.cc#L685-L700)

**Comment by codebytere** [comment]
New information came to light about how this may break existing codepaths - i'm going to open a new PR that avoids this breakage and backport that.

**Pull request merged**
