### PR TITLE
fix: Properly cleanup in `removeAsDefaultProtocolClient`

### PR DESCRIPTION
**Pull request by felixrieseberg**
As it turns out, when I first built `removeAsDefaultProtocolClient`, I didn't _really_ cleanup after ourselves. This PR fixes that, ensuring that calling those two commands doesn't leave garbage in the registry:

:one: `setAsDefaultProtocolClient('foo')`
:two: `removeAsDefaultProtocolClient('foo')`

Thanks to @juturu for noticing.

Closes https://github.com/electron/electron/issues/9944

### CODE REVIEW

**Comment by ckerr** [comment]
@felixrieseberg, would it be difficult to add tests for this cleanup?

**Comment by felixrieseberg** [comment]
@ckerr It's possible, but only if we add a new generic "read the registry" module so that we can verify that the registry is clean after running `removeAsDefaultProtocolClient('foo')`. We could also shell out to powershell to confirm that it actually worked.

Thoughts? Happy to write one!

**Comment by ckerr** [comment]
Yes, sounds good to me.

**Comment by felixrieseberg** [comment]
@ckerr Detailed tests added!

**Pull request merged**
