### PR TITLE
chore: use relative links in docs

### PR DESCRIPTION
**Pull request by dsanders11**
#### Description of Change

Needs #26359 to land first, as one of the links includes a fragment which the relative links linter wasn't handling properly.

#### Checklist

- [x] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
(approved pending https://github.com/electron/electron/pull/26359)

**Review by MarshallOfSound — APPROVED** [review]

**Comment by codebytere** [comment]
@dsanders11 the precursor just landed - this can be rebased now :)

**Comment by dsanders11** [comment]
@codebytere, thanks, rebased.

**Comment by zcbenz** [comment]
@dsanders11 Can you rebase again? The lint is failing for some other files.

**Comment by dsanders11** [comment]
@zcbenz, rebased, looks like the lint runs clean now.

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
