### PR TITLE
build: remove dead symlink from MAS build

### LINKED ISSUE #23828: Electron 9.0.0: Mac App Store rejection - ITMS-90332: Invalid Symbolic Link
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0
* **Operating System:** MacOS
* **Last Known Working Electron version:** Electron 8

Release to Mac App Store failed with below error:

ITMS-90332: Invalid Symbolic Link - The symbolic link 'com.my.app.pkg/Payload/MyApp.app/Contents/Frameworks/Electron Framework.framework/Helpers' resolves to an invalid location. Make sure that the symbolic link does not resolve to itself, and that the location exists and is contained within the app bundle.

I've checked `electron-v9.0.0-mas-x64.zip` file from `~/Library/Caches/electron`, open the package content of `Electron.app` and I found it contains an invalid alias at `Electron.app/Contents/Frameworks/Electron Framework.framework/Helpers`. I am not sure if this file is added on purpose - it is not in electron 8 release.

### Expected Behavior

App should be able to release to App Store

### Actual Behavior
Apple rejected the build

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #23828

This fixes the stray symbolic link and adds a script to ensure it doesn't happen again

Notes: Fixed mac app store rejection notice for invalid symbolic link in bundle.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@jkleinsc It's the same symlink, my fix didn't hold.

**Comment by thomasdao** [comment]
Hi @MarshallOfSound would it be possible to look at this PR again? Electron 9 has many important features for us but Mac App Store keeps rejecting it. Thank you :)

**Comment by wnajar** [comment]
Hi @MarshallOfSound @zcbenz @codebytere, I'm a product manager at Facebook working on Messenger for MacOS and Windows. We use Electron and recently upgraded to 9.0.0.

Apple rejected our latest submission to the Mac App Store with 9.0.0 and specifically mentioned https://github.com/electron/electron/issues/23828 as the problem, which this PR resolves. It looks like all clients distributing via the Mac App Store are blocked by this issue now. Would you be willing to take another look at this PR so we can resolve the issue ASAP? We'd like to upgrade to 9.0.0 which resolves several other issues but are dead in the water there until this fix lands. Thank you so much.

**Comment by MarshallOfSound** [comment]
@zcbenz I don't believe those comments are the correct fix.  We're depending on headers incorrectly.  I'm going to back this out and land with the headers behind ifdefs for the MAS build flag.

i e. The gn check was failing correctly, we need to fix our includes.  I've got a WIP locally for this

**Pull request merged**
