### PR TITLE
Fix address of Korea Community

### PR DESCRIPTION
**Pull request by ssu2030**
Korean community existed in Slack, So fix it.

### CODE REVIEW

**Comment by ragingwind** [comment]
ssu2030 Would you change the url with https://electron-kr.github.io/electron-kr instead of Slack ? Slack is one of the place we(Electron Korea) using. Thanks

FYI We need to update this also https://github.com/electron/electron.atom.io/blob/5239cf3e8719987f4ff2b399de7b7541914d9c5a/data/meetups.json#L14

**Comment by ssu2030** [comment]
@ragingwind okay i will change that
Thank for your recommand 😀

**Comment by ssu2030** [comment]
@ragingwind I check your request.  
I'll also fix things you checked soon. I really appreciate your advice.

**Comment by ckerr** [comment]
This is the same intent as #11079 which was merged.

**Pull request closed without merging**
