### PR TITLE
chore: remove unneeded SetBackgroundOpaque hack

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This removes some code that doesn't seem to be necessary any more for getting
transparent windows. I think the transparency code has changed quite a bit since
then and manual testing seems to indicate this is no longer necessary, I think?

At least, I can create a transparent window without this now!

cc @zcbenz who originated this code: https://github.com/electron/electron/commit/6650a063393104531b271bc7326debf068d85481

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)

#### Release Notes

Notes: none

### CODE REVIEW

**Review by ckerr — APPROVED** [review]
+1 on the `no-backport` label

**Comment by Eldeloro1** [comment]
@codebytere

**Comment by Eldeloro1** [comment]
Yes

**Comment by Eldeloro1** [comment]
Awww yeahhh

**Comment by Eldeloro1** [comment]
Vert shinin

**Pull request merged**
