### PR TITLE
fix: third time screen sharing on macOS

### PR DESCRIPTION
**Pull request by indutny-signal**
Because we used decrementing negative source ids for fake video id when instantating a native macOS screen share picker, we eventually hit the `DesktopMediaID::kFakeId = -3` in Chromium source code which displayed a test green screen.

In this change we reserve our own fake id of `-4` and decrement the window id integer for uniqueness instead.

image

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

cc @VerteDinde 

#### Release Notes

Notes: Third time isn't always a charm. Fixed the native macOS Screen Share picker invocation triggering a test Chromium green screen

### CODE REVIEW

**Comment by indutny-signal** [comment]
cc @MarshallOfSound perhaps as well

**Comment by indutny-signal** [comment]
This is still very relevant to us and I'd appreciate a review 🤗

**Review by MarshallOfSound — APPROVED** [review]

**Comment by VerteDinde** [comment]
Just testing this locally to make sure it doesn't break multiple streams, but the code changes look good to me (please hold merging until I make sure multiple streams work!)

**Review by VerteDinde — APPROVED** [review]
Works great, thanks to @indutny for the fix! 🙇‍♀️ Will get this backported to 33-x-y and 32-x-y

**Comment by indutny-signal** [comment]
This is so awesome. Thank you @VerteDinde !

**Review by Theghost256 — COMMENTED** [review]
Thanks

**Pull request merged**
