### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by gclotault**
#### Description of Change
Added contexIsolation: false to BrowserWindow options (see https://github.com/electron/electron/issues/18139#issuecomment-790087307)

### CODE REVIEW

**Review by zcbenz — COMMENTED** [review]
Can you also update the line numbers in the "What is going on above?" section?

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
We should update the example to function with the secure defaults, our docs should never explicitly or implicitly recommend insecure options

**Review by ckerr — CHANGES_REQUESTED** [review]
:+1: on @MarshallOfSound's comment; this is why electron-quick-start [added a preload script](https://github.com/electron/electron-quick-start/pull/279)

**Comment by ckerr** [comment]
However, I think @gclotault is right that the instructions in `docs/tutorial/quick-start.md` won't work as-is due to the contextIsolation change. We should update this file to use a preload script and to explain why that's preferred. Also we might want to include links to [Electron Fiddle](https://github.com/electron/fiddle) and [electron-quick-start](https://github.com/electron-quick-start).

**Comment by erickzhao** [comment]
I personally think this is okay for a band-aid fix before rewriting the tutorials to use sensible defaults at some later point.

Right now, our tutorial just doesn't work, and that's a very confusing experience for newbies.

**Comment by jkleinsc** [comment]
Thanks for the PR @gclotault!  While this solution technically works, the preferred way to handle this is with a preload script.  Since #28223 makes that change, I am going to close this PR in favor of #28223.

**Pull request closed without merging**
