### PR TITLE
:memo: Translation of CONTRIBUTING.md to pt-br [ci skip]

### PR DESCRIPTION
**Pull request by fplucas**

### CODE REVIEW

**Comment by zcbenz** [comment]
This pull request has conflicts with https://github.com/electron/electron/pull/7444, and I merged the latter because it was sent earlier. Do you mind solving the conflicts in your branch? I don't understand Portuguese so I can not do it myself.

**Comment by fplucas** [comment]
@zcbenz It's all right, I solved the conflicts.

**Comment by fplucas** [comment]
I just have a doubt, I need to create another pull request or this one already works?

**Comment by kevinsawicki** [comment]
> I just have a doubt, I need to create another pull request or this one already works?

This one should work as long as the diff shown on https://github.com/electron/electron/pull/7437/files looks good to you.

**Comment by fplucas** [comment]
@kevinsawicki Thanks man!

**Comment by kevinsawicki** [comment]
Thanks for updating 🚢

**Pull request merged**
