### PR TITLE
spec: isolate sw file scheme spec storage with temp partition

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/electron/electron/issues/12173

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@deepak1556 We should probably merge it to the master too )

**Comment by MarshallOfSound** [comment]
> We should probably merge it into the master too

This PR should target `master` and add a label for `target/2-0-x`

**Comment by deepak1556** [comment]
Done, thanks!

**Pull request merged**
