### PR TITLE
test: move module tests to main process

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Moves module tests to the main process.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
@jkleinsc something's weird about that test run. It looks like `ELECTRON_SKIP_NATIVE_MODULE_TESTS` is set somehow? but i don't see that anywhere in `azure-pipelines-woa.yml`.

**Comment by jkleinsc** [comment]
@nornagon it could be set on the job definition on Azure Pipelines

**Comment by nornagon** [comment]
@jkleinsc if that's the case can you move it to the yml file? it's v. confusing and hard to track down configuration that's not in the repo.

**Comment by nornagon** [comment]
win-x64-testing has flaked 3 times in a row, so i'm giving up on it now. woa is fixed though :)

**Comment by nornagon** [comment]
merging as @jkleinsc's concern was addressed.

**Pull request merged**
