### PR TITLE
protocol: register about scheme handler

### LINKED ISSUE #7883: handle about scheme
* Electron version: 1.4.5
* Operating system: win10

### Expected behavior

Use about:blank without error

### Actual behavior

Devtools console will show an error message: **`GET about:blank net::ERR_UNKNOWN_URL_SCHEME`** if use `about:blank` url.

### How to reproduce

`<iframe src="about:blank">`

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #7883

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@deepak1556 what is the best way to manually see the error from #7883, I tried the following page on master but didn't see that error in the dev tools:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <iframe src="about:blank">
  </body>
</html>
```

**Comment by deepak1556** [comment]
The best way is to look at the net-log trace.

```
app.commandLine.appendSwitch('log-net-log', <path-to-dump-net-trace-json>)
```

Import the file into `chrome://net-internals` and you should see the error for the request `about:blank`.

**Comment by kevinsawicki** [comment]
@deepak1556 awesome tip, thanks so much 👍 

screen shot 2016-11-09 at 4 01 11 pm

**Comment by kevinsawicki** [comment]
Looks great, thanks 👍 

screen shot 2016-11-09 at 4 13 02 pm

**Comment by zeke** [comment]
Is this tip worth adding to `/docs/tutorial` somewhere?

**Pull request merged**
