### PR TITLE
only emit `download-item done` event once

### PR DESCRIPTION
**Pull request by liusy182**
#8625

### CODE REVIEW

**Comment by YurySolovyov** [comment]
I wonder if it is possible to somehow unbind/remove the handler instead of using a flag.

**Comment by liusy182** [comment]
@YurySolovyov Thanks for the suggestion. We can detach `DownloadItem` from an observer after `done` event is emitted. But I am not sure if `DownloadItem` is still interested in event `OnDownloadDestroyed` by that time.

**Comment by YurySolovyov** [comment]
Yeah, might be worthwhile to add a test

**Comment by YurySolovyov** [comment]
I'm not sure if they're still in development, but there are [OnceCallback<> And RepeatingCallback<>](https://chromium.googlesource.com/chromium/src/+/master/docs/callback.md#OnceCallback_And-RepeatingCallback)

**Comment by deepak1556** [comment]
You could just avoid calling `DownloadItem::Remove` when triggering the cancel api. We eventually remove it when `DownloadItem` is destroyed.

**Comment by liusy182** [comment]
Thanks @deepak1556 I have updated.

@YurySolovyov In terms of test, I couldn't think of a way of without using setTimeout, Do you have a better idea?

**Comment by kevinsawicki** [comment]
Thanks for this @liusy182 👍

**Pull request merged**
