### PR TITLE
fix: nws13n: make ses.setUserAgent work 

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This fixes `session.setUserAgent` in the post-network-service world. Ref https://chromium-review.googlesource.com/c/chromium/src/+/1585083. Ref #19602.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
Looks like the Chromium roll in #19609 included this, so i'm removing the needs-manual-bp label.

**Comment by bughit** [comment]
@nornagon 

Session#setUserAgent takes a second acceptLanguages param, which was not restored in this PR

https://github.com/electron/electron/blob/4-2-x/atom/browser/api/atom_api_session.cc#L612
https://www.electronjs.org/docs/api/session#sessetuseragentuseragent-acceptlanguages

**Comment by nornagon** [comment]
@bughit that's true; if you're experiencing an issue with that it would be great if you can open a new issue w/ a quick repro!

**Comment by bughit** [comment]
#23211

**Pull request merged**
