### PR TITLE
[wip] feat: custom titlebar on Windows

### PR DESCRIPTION
**Pull request by brenca**
#### Description of Change

A lot of electron apps on `Windows` use a frameless window with a custom painted title bar, which is a nice and endlessly customizable way to have a fancy custom titlebar, but it has the drawback of it essentially being part of the page itself, which needs time to load. 
Instead of that, I propose a title bar that's fairly customizable, drawn with `views::View`s, just like `chrome`'s title bar is drawn, providing a close to native, but customizable experience.

titlebar1

Goals:
- [x] should behave as close to the native titlebar as possible, allowing the user to recreate the native titlebar as closely as desired
- [x] should provide a way to replace the default window menu (right click on a window's titlebar, clicking on the icon or pressing `Alt+Space` should bring up that menu instead of the default one)
- [ ] should work well with existing titlebar customization API (for mac)
- [ ] should allow custom buttons to be added (painted from JS with a `NativeImage`)
- [ ] should allow color customization

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added the ability to set a custom titlebar for windows on Windows.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
_plz send screenshots of this magic_

**Comment by brenca** [comment]
@MarshallOfSound I added a gif to the description

**Comment by miniak** [comment]
@brenca what about this? https://docs.microsoft.com/en-us/windows/win32/dwm/customframe
just allowing to use the native window control buttons (similar to what we do on macOS)

**Comment by ckerr** [comment]
I'm closing this PR as part of a bulk-closing of stale PRs that appear to no longer be applicable.

If anyone thinks this PR is still valid and thinks it should be reconsidered, please rebase / update the patch to `master` and open a new PR. Thank you!

**Pull request closed without merging**
