### PR TITLE
session: api to provide security style for the webcontents.

### LINKED ISSUE #5022: Dev Tools in Electron 0.37.3 Does Not Show SSL Cert Info in Security Tab
* Electron version: 0.37.3
* Operating system: OSX 10.11.4

So in Chrome, When you click on the green lock (github.com used as an example) and click the details link you are directed to the Security Tab in ChromeDevTools: 

1. Details Link: 

secureconnectiondetailslinkinchrome
2. Security Tab in ChromeDevTools: Security Tab in ChromeDevTools

Here's what happens when you view the Dev Tools Security Tab using Electron:

1. Note that using Electron there is no visibility into the Security Status of the Site's Cert. There is no visibility into the Secure TLS Connection and that the Site is using a 'strong protocol version and cipher suite' like Chrome displays. Nor is there any visibility in Dev Tools to Verify that Secure Resources 'are all served securely'.

### PR DESCRIPTION
**Pull request by deepak1556**
Instead of electron describing the security style of the webcontents, we allow users to decide custom security style when requested by devtools security panel.

Depends on https://github.com/electron/brightray/pull/206

Fixes #5022

### CODE REVIEW

**Comment by zcbenz** [comment]
Do we need a API for it? I don't know if anyone would have a use case for it.

**Comment by deepak1556** [comment]
I wasnt really sure here, whether electron should decide the security style or not. If we are deciding the style should we port the same criteria from chrome ?

**Comment by deepak1556** [comment]
Not sure if anyone besides browsers built on electron would care about security overview tab and if we are providing the details then internalization has to be taken care of. Seemed too much for a small feature.

**Comment by deepak1556** [comment]
have the alternate version based on chrome security style [here](https://github.com/deepak1556/atom-shell/commit/c53716e448001c385cf418ebb03bee0fd2b6b65a) . I am not sure what is the right solution, so will PR once decided.

**Comment by zcbenz** [comment]
> have the alternate version based on chrome security style here . I am not sure what is the right solution, so will PR once decided.

The alternative version looks good to me.

**Comment by deepak1556** [comment]
closing in favor of https://github.com/electron/electron/pull/5117

**Pull request closed without merging**
