### PR TITLE
fix: disable more private macOS APIs in MAS build (6-1-x)

### PR DESCRIPTION
**Pull request by zcbenz**
Backport of #20965.

Notes: Fix Electron apps getting rejected to Mac App Store.

### CODE REVIEW

**Comment by gaodeng** [comment]
electron 6.1.7 rejected by apple
here is the otool -ov  output
[d.txt](https://github.com/electron/electron/files/3971504/d.txt)

```
Guideline 2.5.1 - Performance - Software Requirements


Your app includes a version of an SDK from Electron that violates the App Store Review Guidelines. The version of the Electron SDK you are using in your app attempts to hide the use of private APIs. This is a violation Section 2.5.1 of the App Store Review Guidelines.

Guideline 2.5.1: Apps may only use public APIs.

Next Steps

To resolve this issue, please either remove the Electron SDK entirely from your app, or revise your app to utilize a corrected version of the Electron SDK.

```

**Comment by MarshallOfSound** [comment]
@gaodeng Do they tell you which apis?  If not challenge it and tell them you are using a corrected version of the SDK.

**Comment by gaodeng** [comment]
@MarshallOfSound  Above is all the information they gave me. I have asked them for more information in the Resolution Center and hope they will reply to me with specific information instead of giving a review Guideline

**Comment by gaodeng** [comment]
New Message from App Store Review

> Hello,
> 
> Thank you for your reply. Your app’s review will require additional time as we take this new information into account. We do not require any further information about your app at this time.
> 
> Once we have thoroughly reviewed your app, we will either contact you in Resolution Center to communicate any issues found, or your app will be approved.
> 
> Best regards,
> 
> App Store Review

**Comment by gaodeng** [comment]
6.1.7 just approved by apple 10 minutes ago

**Pull request merged**
