### PR TITLE
fix: restore rounded window corners for vibrant windows on Mac

### PR DESCRIPTION
**Pull request by natew**
#### Description of Change

I opened this issue a few years ago and finally got around to looking at it again:

https://github.com/electron/electron/issues/10886

I saw a potential solution here:

https://github.com/electron/electron/pull/8354

And so ported this to the current codebase, and tested it successfully on master.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are no change, fixed visual bug

#### Release Notes

Notes: Fixed vibrant windows not properly having rounded corners on Mac.

#### Example

Here's before:

before

And after:

Screen Shot 2019-09-05 at 4 20 18 PM

### CODE REVIEW

**Comment by codebytere** [comment]
@natew doesn't look like this is building successfully:
```
../../electron/shell/browser/ui/cocoa/atom_ns_window.mm:27:13: error: property implementation must have its declaration in interface 'AtomNSWindow' or one of its extensions
@synthesize cornerMask;
            ^
../../electron/shell/browser/ui/cocoa/atom_ns_window.mm:144:16: error: instance method '-cornerMask' not found (return type defaults to 'id'); did you mean '-_cornerMask'? [-Werror,-Wobjc-method-access]
  return [self cornerMask];
               ^~~~~~~~~~
               _cornerMask
../../electron/shell/browser/ui/cocoa/atom_ns_window.h:30:12: note: receiver is instance of class declared here
@interface AtomNSWindow : NativeWidgetMacNSWindow {
           ^
2 errors generated.
[1 processes, 17731/19070 @ 25.3/s : 701.250s] OBJCXX obj/electron/electron_lib/atom_api_app_mas.o
ninja: build stopped: subcommand failed.
Exited with code 1
```

**Comment by natew** [comment]
I had a weird issue where if I built for Release I had to do `@synthesize _cornerMask;` but for Debug `@synthesize _cornerMask;`, so I pushed a patch changing it and hadn't tried Debug again. Any idea? I'm pretty unexperienced in objc, is there some IDE? Also I found the `electron-gn` sub-dir a bit confusing, I was making edits directly there but I assume one of the build commands in the docs handles copying it over.

**Comment by natew** [comment]
@codebytere turns out that was because I forgot to paste back some stuff from the `electron-gn` folder to main src. Still not sure if there's some automated way to do that. This shoudl work now.

**Comment by codebytere** [comment]
Looks like some macOS tests have died here: https://circleci.com/gh/electron/electron/329285

**Comment by natew** [comment]
If I'm understanding correctly, I see:

```
# tests 544
# pass 544
# fail 0
```

And then some sort of bug in the test suite runner itself, as well as
various errors in compilation of dependencies.

I haven't touched any of this stuff, and I don't see any errors relating to
what I've touched which is just a couple files in the window area. Correct
me if I'm wrong.

**Comment by codebytere** [comment]
@natew there are two spec runners, one for main process tests and one for renderer process tests. This is the crash, about halfway down the log:

<details>

```
node:1589) electron: NSVisualEffectMaterialUltraDark has been deprecated and will be removed in a future version of macOS.
Received signal 11 SEGV_MAPERR 000000000020
0   Electron Framework                  0x000000011dd56649 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x000000011dc013f3 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000011dd564e1 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 2385
3   libsystem_platform.dylib            0x00007fff7f544f5a _sigtramp + 26
4   ???                                 0x0000000000000000 0x0 + 0
5   libobjc.A.dylib                     0x00007fff7e6cb47a _object_remove_assocations + 394
6   libobjc.A.dylib                     0x00007fff7e6cb2be objc_destructInstance + 105
7   libobjc.A.dylib                     0x00007fff7e6cb244 object_dispose + 22
8   AppKit                              0x00007fff54ed60ab -[NSResponder dealloc] + 143
9   AppKit                              0x00007fff54ed4a80 -[NSView dealloc] + 194
10  AppKit                              0x00007fff551311a0 -[NSVisualEffectView dealloc] + 791
11  libobjc.A.dylib                     0x00007fff7e6cc042 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 812
12  CoreFoundation                      0x00007fff578ca676 _CFAutoreleasePoolPop + 22
13  Foundation                          0x00007fff599ea4f5 -[NSAutoreleasePool drain] + 144
14  Electron Framework                  0x000000011dd8b7b3 base::MessagePumpCFRunLoopBase::RunWork() + 163
15  Electron Framework                  0x000000011dbf644a base::mac::CallWithEHFrame(void () block_pointer) + 10
16  Electron Framework                  0x000000011dd8af2f base::MessagePumpCFRunLoopBase::RunWorkSource(void*) + 63
17  CoreFoundation                      0x00007fff57927a21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
18  CoreFoundation                      0x00007fff579df26c __CFRunLoopDoSource0 + 108
19  CoreFoundation                      0x00007fff5790aab0 __CFRunLoopDoSources0 + 208
20  CoreFoundation                      0x00007fff57909f2d __CFRunLoopRun + 1293
21  CoreFoundation                      0x00007fff57909787 CFRunLoopRunSpecific + 487
22  HIToolbox                           0x00007fff56c16e26 RunCurrentEventLoopInMode + 286
23  HIToolbox                           0x00007fff56c16b96 ReceiveNextEventCommon + 613
24  HIToolbox                           0x00007fff56c16914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
25  AppKit                              0x00007fff54ee1f5f _DPSNextEvent + 2085
26  AppKit                              0x00007fff55677b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
27  AppKit                              0x00007fff54ed6d6d -[NSApplication run] + 764
28  Electron Framework                  0x000000011dd8c7ec base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) + 348
29  Electron Framework                  0x000000011dd8a898 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) + 136
30  Electron Framework                  0x000000011dcd2ad2 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 242
31  Electron Framework                  0x000000011dc7d2f6 base::RunLoop::Run() + 726
32  Electron Framework                  0x000000011c85cd7d content::BrowserMainLoop::RunMainMessageLoopParts() + 173
33  Electron Framework                  0x000000011c85e956 content::BrowserMainRunnerImpl::Run() + 102
34  Electron Framework                  0x000000011c8595af content::BrowserMain(content::MainFunctionParams const&) + 287
35  Electron Framework                  0x000000011c68ce85 content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) + 949
36  Electron Framework                  0x000000011c68caaa content::ContentMainRunnerImpl::Run(bool) + 442
37  Electron Framework                  0x00000001200e0ed3 service_manager::Main(service_manager::MainParams const&) + 3139
38  Electron Framework                  0x000000011a984734 content::ContentMain(content::ContentMainParams const&) + 68
39  Electron Framework                  0x00000001194e9194 AtomMain + 84
40  Electron                            0x000000010e828c90 main + 240
41  libdyld.dylib                       0x00007fff7f2c3115 start + 1
42  ???                                 0x0000000000000006 0x0 + 6
[end of stack trace]
```
</details>

**Comment by natew** [comment]
@codebytere thanks for the helpful explanation, that makes sense. The error there seems unrelated to this PR does it not? I don't believe I've touched the material stuff at all.

**Comment by natew** [comment]
I realized all my confusion was due to the really strange way I ended up setting up the repo, so I redid it from scratch this morning and re-opened a new PR #20360

**Pull request closed without merging**
