### PR TITLE
Fixes #5969

### LINKED ISSUE #5969: Use non random ID for trayIcon
* Electron version: All
* Operating system: Ubuntu 16.04

Looking at the source code, https://github.com/electron/electron/blob/e05804848f98959d63337aacd9047cd579c5b23f/atom/browser/ui/tray_icon_gtk.cc#L30 it seems that for the AppIndicator tray icon uses a randomly generated ID for the tray icon. This number changes everytime the app starts. This creates problems, because the ID is used in Ubuntu for changing order of tray icons, which is impossible if the ID changes everytime the app starts. 

Is there a reason why a Random number is used as AppIndictor ID? Is it possible to change that to let's say the app name, or at least to something that is not random?

### PR DESCRIPTION
**Pull request by wa4557**
Simple fix that generate tray icons with name corresponding to the app name

### CODE REVIEW

**Comment by zcbenz** [comment]
This makes all tray icons share the same ID, they should use names like `app_name_1`, `app_name_2`, depending on their sequence of being created.

**Comment by wa4557** [comment]
well, one could argue that this makes more sense. After all an ID is an identification which means that each electron app should have its own ID, regardless of how often it is opened. 

But yeah I guess making it `app_name_1` etc. also makes sense. Any idea how I could implement that?

**Comment by zcbenz** [comment]
You can reference how Chromium implemented it:
https://cs.chromium.org/chromium/src/chrome/browser/ui/libgtk2ui/gtk2_ui.cc?sq=package:chromium&dr=Ss&rcl=1465773398&l=687

**Comment by wa4557** [comment]
Just to be clear what you envision:

- I make an app named `test` (that's the name my patch would give right now)
- The ID should be sth like `test_1`
- If I open the app again the ID should be something like `test_2`

Is this correct?

**Comment by zcbenz** [comment]
No, the first tray icon in your app has `test_1` as ID, and the second tray icon will have `test_2` as ID. If you restart the app the ID will still start from `test_1`.

This way tray icon IDs are unique between apps, and can have permanent names in one app.

**Comment by zcbenz** [comment]
Closed in favor of #6145.

**Pull request closed without merging**
