### PR TITLE
fix: crash when exiting app with active nodejs worker_threads

### PR DESCRIPTION
**Pull request by indutny**
#### Description of Change

Refs https://github.com/electron/electron/pull/28468 for details

Fixes: https://github.com/electron/electron/issues/23315

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix crash when exiting app with active nodejs worker_threads

### CODE REVIEW

**Comment by deepak1556** [comment]
Also needs to backport https://github.com/nodejs/node/commit/d7bc5816a5d88e18d7ede081042d87f48a2bc54b, steps https://github.com/electron/electron/blob/master/docs/development/patches.md#usage

**Comment by indutny-signal** [comment]
@deepak1556 oh, true. Although, I must admit that it fixes the issue with worker_threads already! I'll update the PR soon!

**Review by deepak1556 — APPROVED** [review]
Great, thanks!

**Comment by indutny** [comment]
I don't know the state of CI too well, but the logs for `build-linux` seem to be unrelated to the files that this Pull Request changes.

**Review by codebytere — APPROVED** [review]

**Comment by indutny** [comment]
So what's going to happen next with this PR? (Sorry, I don't really know how the process works for electron)

**Comment by indutny** [comment]
Before merging we might want to consider https://github.com/electron/electron/pull/28468#issuecomment-811995684

**Comment by deepak1556** [comment]
Failing tests are unrelated, merging.

**Comment by indutny-signal** [comment]
Yay! Thank you.

@deepak1556 will it be released this week?

**Comment by deepak1556** [comment]
We will cut a new 11-x-y release tomorrow, but if the ci is flaky release might be pushed but you can definitely expect a new version early next week

**Comment by indutny-signal** [comment]
Thank you, and sorry for using different accounts (work vs personal)!

**Pull request merged**
