### PR TITLE
Translate indonesian

### PR DESCRIPTION
**Pull request by suryast**

### CODE REVIEW

**Comment by suryast** [comment]
:memo: starting Indonesian documentation translation

**Comment by kevinsawicki** [comment]
> starting Indonesian documentation translation

@suryast thanks for translating these, are you planning on pushing more changes to this pull request or is this ready to be merged?

**Comment by suryast** [comment]
@kevinsawicki I do plan to translate all of them. Sorry - I'm also new to contributing to opensource. Should I merge once I have them all ready or should I do pull request bit by bit that I could get done?

**Comment by kevinsawicki** [comment]
> Should I merge once I have them all ready or should I do pull request bit by bit that I could get done?

Either works, let's start by merging this one since it translates the README which is valuable to get in there, then you can open new pull requests as you translate more files, thanks again for your contributions 👍

**Comment by zeke** [comment]
Thanks, @suryast 🇮🇩

**Pull request merged**
