### PR TITLE
Set appropriate defaults for webview options

### PR DESCRIPTION
**Pull request by ckerr**
Ensure that the webview options object has appropriate default values.

Details at https://www.electronjs.org/blog/webview-fix

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Requires #12289

**Comment by pakastin** [comment]
Why did you release this as a patch? It broke our 3rd party content 😓

**Comment by ckerr** [comment]
@parastin, sorry to hear that! We try to not make incompatible changes in point releases. This time it was necessary as a mitigation for https://electronjs.org/blog/webview-fix

**Comment by MarshallOfSound** [comment]
@pakastin Can you clarify or provide an example of how this broke existing code.  I still clarify this PR as a fix as it simply ensures that the behavior we have in our docs actually happens in all cases.  If you could provide an example of what broke it would help a lot 👍

**Comment by pakastin** [comment]
I wouldn't want to disclose the details here, but I'll send you an email 🙂

**Comment by pakastin** [comment]
Email sent 😉

**Comment by pakastin** [comment]
We updated the players already so no worries, I'm just kindly hoping these kind of changes would be at least with minor semver push in the future.. 🙂

**Pull request merged**
