### PR TITLE
[WIP] getLastCrashReport does not return latest crash report

### LINKED ISSUE #11749: CrashReporter.getLastCrashReport() does not return latest
Electron: 1.7.11
Platform: Windows

```JSON.stringify(require('electron').remote.crashReporter.getLastCrashReport())```
Returns:
```json
{
  "date":"2018-01-27T10:48:47.000Z",
  "id":"a1f8a8c4-e6d3-4729-a126-aadcef61d9da"
}
```
```JSON.stringify(require('electron').remote.crashReporter.getUploadedReports())```
Returns:
```json
[
  {
    "date": "2018-01-27T10:48:47.000Z",
    "id": "a1f8a8c4-e6d3-4729-a126-aadcef61d9da"
  },
  {
    "date": "2018-01-27T11:11:54.000Z",
    "id": "3d8d2e06-d186-4cc9-b9b3-396673d68902"
  },
  {
    "date": "2018-01-27T11:12:28.000Z",
    "id": "24668c94-44e0-4b58-901c-32a6ec950d1b"
  },
  {
    "date": "2018-01-27T11:38:17.000Z",
    "id": "1d99e1cc-9a54-4dff-bbae-9c37a5566592"
  },
  {
    "date": "2018-01-27T11:50:30.000Z",
    "id": "9b222337-806c-4b53-bab1-aa9e84cbfe37"
  }
]
```

The last error report by timestamp is clearly `9b222337-806c-4b53-bab1-aa9e84cbfe37`

Looking at the code, [its expecting the first crash](https://github.com/electron/electron/blob/63c91e7dd3764499d846f7e0b384d82d1da2bbc5/lib/common/api/crash-reporter.js#L61) to be the latest.

### PR DESCRIPTION
**Pull request by timfish**
Fixes #11749

### CODE REVIEW

**Comment by timfish** [comment]
It looks like [here](https://github.com/electron/electron/blob/6bc7c8cc496a2bd899b2511de39f8fa1b0d7147c/atom/common/crash_reporter/crash_reporter.cc#L56) its just pulling the list from `uploads.log` which is just appended so has them in chronalogical order.

```
1517050127,a1f8a8c4-e6d3-4729-a126-aadcef61d9da
1517051514,3d8d2e06-d186-4cc9-b9b3-396673d68902
1517051548,24668c94-44e0-4b58-901c-32a6ec950d1b
1517053097,1d99e1cc-9a54-4dff-bbae-9c37a5566592
1517053830,9b222337-806c-4b53-bab1-aa9e84cbfe37
1517054216,9fcd1316-dfad-4631-b4e1-32d27e63203d
```

**Comment by timfish** [comment]
Ah, the tests probably need fixing too as it looks like they're looking at `reports[0]`.

**Comment by timfish** [comment]
It looks like [the getLastCrashReport test](https://github.com/electron/electron/blob/b9c0bab8f1e8c40427db3d48da3d51481f6603c2/spec/api-crash-reporter-spec.js#L259) doesn't even call `getLastCrashReport` which may be why this hasn't been picked up.

**Comment by MarshallOfSound** [comment]
@timfish Would you be down to extend that test with some logic that actually checks the one is returned is the latest report.  Loop through the reports and check dates or something, just so we catch this kind of thing in the future

**Comment by timfish** [comment]
Yeah, I'll have a look. Any test with `getLastCrashReport` will obviously only make sense if there is more than one crash!

**Comment by alexeykuzmin** [comment]
@timfish no tests == broken stuff in the future.

**Comment by timfish** [comment]
Don't worry, I do intend to finish this I just ran out of time before. 😄 

I already found that the crash directory isn't being cleared between tests and it was harder that I first thought it would be to get at least two crashes in a single test which is what this needs.

@alexeykuzmin why are some tests skipped on AppVeyor and Mac?
```
// TODO(alexeykuzmin): Skip the test instead of marking it as passed.
if (process.env.APPVEYOR === 'True') return done()

if (process.platform !== 'darwin') {
  // FIXME(alexeykuzmin): Skip the test.
  // this.skip()
  return
}
```

**Comment by alexeykuzmin** [comment]
@timfish 

Some APIs are platform specific and their tests are skipped on other platforms.

Skipping tests on AppVeyor or any any other CI platform is a temporary solution for some weird failures or timeouts. All of them should be removed some day.

**Comment by timfish** [comment]
I've been trying to get some sensible tests working here for a couple of hours not helped by the fact that I'd never looked at any of the Electron tests before.

A few observations:
- `getCrashesDirectory` test fails on my Windows machine before I made any changes

```[ERR_ASSERTION]: 'C:\\Users\\tim\\AppData\\Local\\Temp\\electronCrashReporterSpec-11818-10756-xgvi2h.idtg\\Electron Test Crashes' == 'C:\\Users\\tim\\AppData\\Local\\Temp\\electronCrashReporterSpec-11818-10756-xgvi2h.idtg/Zombies Crashes'```
- Proper segregation of the tests does not seem possible. To do any serious testing of the list of uploaded reports, the crash directory should be cleaned between tests. This is not possible because the operation log is locked until the main process closes.
- I can write a test which works well in isolation but fails when all the tests from all of `api-crash-reporter-spec.js` run. For some reason `getUploadedReports` returns an empty array.

**Comment by codebytere** [comment]
@timfish i think i was one of the last to look at crash report tests so i'll take a look if that'll help

**Comment by timfish** [comment]
@codebytere that would be great. Unfortunately I forgot to commit the test I added before leaving for a long weekend. It basically started the server, crashed, reloaded the window to crash again and then checked the reported errors and latest and checked the dates. 

One idea I had was to replace all of the crash tests with Spectron tests which could fully start and year down the Electron process.

**Comment by ckerr** [comment]
@codebytere, @timfish, any news?

**Comment by timfish** [comment]
When run in isolation, the test passes:
image

When all the tests in `api-crash-reporter-spec.js` are run, `getLastCrashReport()` returns `null`.

**Comment by timfish** [comment]
I recently helped write Spectron tests that test native crash reporting for [sentry-electron](https://github.com/getsentry/sentry-electron/blob/ede18f60bdbbd04480b793f72a522bfeae79baa2/test/e2e/index.test.ts). These are successfully running on all three platforms in CI.

I propose replacing all the crashing tests in Electron with something similar as it gets round many of the shortcomings of the existing tests. As well as there currently being no isolation, there are no tests that crash the main process!

**Comment by codebytere** [comment]
@timfish i would absolutely be +1 for this, and also down to pair on it if you'd be interested; have you joined the [maintainers group](electronjs.org/maintainers/join)? some things might be easier to coordinate if you are :)

**Comment by timfish** [comment]
@codebytere Just filled the maintainers join form. 

Spectron might not necessarily be required and certainly caused [some issues](https://github.com/getsentry/sentry-electron/blob/ede18f60bdbbd04480b793f72a522bfeae79baa2/test/e2e/context.ts#L24). Simply starting individual app instances might be enough.

**Comment by timfish** [comment]
Sorry, been too busy to finish this!

**Pull request closed without merging**
