### PR TITLE
refactor: add prefer-const to .eslintrc + fix errors

### PR DESCRIPTION
**Pull request by miniak**
##### Description of Change
According to https://eslint.org/docs/rules/prefer-const:
> If a variable is never reassigned, using the const declaration is better.
>
> const declaration tells readers, “this variable is never reassigned,” reducing cognitive load and improving maintainability.

##### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@miniak Looks good! Please fix the conflict )

**Comment by MarshallOfSound** [comment]
@miniak Some `let` have landed on master since this branch, can you bring it 100% up to date then we can merge 👍

**Comment by alexeykuzmin** [comment]
@miniak, do you want to update `//spec/**/*.js` as well?

**Comment by miniak** [comment]
@alexeykuzmin I did update the specs? Did I miss something?

**Comment by miniak** [comment]
@MarshallOfSound it should be up to date

**Comment by alexeykuzmin** [comment]
> @alexeykuzmin I did update the specs? Did I miss something?

Sorry, my bad. Everything's fine.

**Pull request merged**
