### PR TITLE
chore: add tests for the spellchecker

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Let's make sure we don't break this again, just some simple E2E spellchecker tests

Notes: no-notes

### CODE REVIEW

**Comment by codebytere** [comment]
Windows looks to actually be failing:

```
not ok 1356 spellchecker should detect correctly spelled words as correct
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\src\electron\spec-main\spellchecker-spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
  
not ok 1357 spellchecker should detect incorrectly spelled words as incorrect
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\src\electron\spec-main\spellchecker-spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

**Comment by MarshallOfSound** [comment]
Interesting, I'll look into the windows failures on Monday 🤔

**Comment by ckerr** [comment]
Interesting that it's only on Windows. Maybe there's something platform-specific, e.g. the mouse coordinates need to be changed or something...?

**Comment by MarshallOfSound** [comment]
`sendInputEvent` doesn't seem to trigger context menus on Windows 🤷‍♂ Using a different technique on windows now

**Pull request merged**
