### PR TITLE
Polish lang docs init

### PR DESCRIPTION
**Pull request by PanHerbaciarz**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@PanHerbaciarz thanks for translating these 👍 Please comment when it is ready for review and feel free to break it up across multiple pull requests.

**Comment by zeke** [comment]
Hey @PanHerbaciarz thanks for your contribution. We can definitely merge this PR, but I wanted to let you know that we're working on a new system for translating Electron's docs.

See the readme at https://github.com/electron/electron-i18n#readme for info on how to get started.

If you're able to give it a try, your feedback would be much appreciated!

**Comment by zeke** [comment]
Hey @PanHerbaciarz I just enabled Polish as a target language on our Crowdin project. See https://crowdin.com/project/electron/pl

**Comment by zeke** [comment]
@PanHerbaciarz did you get a chance to check out Crowdin? Let me know if you have any problem getting set up. Also, what do you want to do with this PR? Is it ready to be merged?

**Comment by zeke** [comment]
@PanHerbaciarz I'm going to close this due to inactivity. Feel free to comment here if you want it re-opened.

**Pull request closed without merging**
