### PR TITLE
Add German translation for README and Contributor Covenant

### PR DESCRIPTION
**Pull request by calmandniceperson**
This PR contains German translations for README and the Contributor Covenant (copied from [here](http://contributor-covenant.org/version/1/4/de/code_of_conduct.md)).

Even though I'm not sure translations for the code of conduct are even supposed to exist for each language (since the other languages seemingly don't contain it), but there are translations of it freely available and I figured that it only made sense to allow *everyone* to understand how they are expected to behave when working on Electron.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Thanks for translating these @calmandniceperson 👍 📝 🇩🇪

**Comment by calmandniceperson** [comment]
@kevinsawicki Glad I can help. I'm already seeing about translating other documents as well. Sorry I didn't include them all in this pull request.

**Comment by kevinsawicki** [comment]
>  I'm already seeing about translating other documents as well. Sorry I didn't include them all in this pull request.

We are in the process of switching to Crowdin to handle translations.

See the readme at https://github.com/electron/electron-i18n#readme for info on how to get started.

**Comment by kevinsawicki** [comment]
The current state of those translations can be found in https://crowdin.com/project/electron/de

**Comment by calmandniceperson** [comment]
@kevinsawicki Thanks! I'll check it out

**Comment by zeke** [comment]
Thanks for the PR, @calmandniceperson. Great handle, too :)

The electron-i18n repo doesn't currently include the top-level README or the code of conduct, but maybe it should?

The Contributor Covenant already has translations so we should probably just prominently link to http://contributor-covenant.org/i18n/ rather than duplicating the effort.

**Comment by calmandniceperson** [comment]
@zeke I think it should contain the top-level README as well. Currently, two (or more) different READMEs can be found in the translations (e.g. the [Indonesian](https://github.com/electron/electron/blob/master/docs-translations/id/README.md) (?) and the [Italian](https://github.com/electron/electron/tree/master/docs-translations/it-IT) translation contain different READMEs.) Personally, I believe unifying the READMEs would make more sense, considering that there already translations for some languages available and the new translation projects in Crowdin would make it a lot more manageable anyway, but I can see why they're separated right now. As far as I can see, the top-level README contains general information, whereas the other one contains mostly links containing further information.

As for the Contributor Covenant, I think linking to the homepage is a great idea. Why copy text when there's already a website available that contains all available translations?

**Pull request merged**
