### PR TITLE
chore: wrap process restart flag in renderer process reuse check

### PR DESCRIPTION
**Pull request by MarshallOfSound**
This is in preparation for the removal of our process hacks.  Make it clearer what logic is required / runs under the two states of this flag.

Refs: #18397

Notes: no-notes

### CODE REVIEW

**Comment by deepak1556** [comment]
Should also add a switch around loading our custom `navigation-controller` https://github.com/electron/electron/blob/master/lib/browser/navigation-controller.js which is not required in the process reuse code path , either in this PR or https://github.com/electron/electron/pull/22335 

Also add a switch around `RendererClient::ShouldFork` and follow what chromium does there.

**Comment by MarshallOfSound** [comment]
@deepak1556 I think `RendererClient::ShouldFork` is tricky as without it we don't get `will-navigate`

**Comment by MarshallOfSound** [comment]
Also yeah, I'm planning on going through the navigation controller, there is some code we'll still need there though like the `loadURL` being a promise

**Comment by deepak1556** [comment]
> I think RendererClient::ShouldFork is tricky as without it we don't get will-navigate

Hmm yeah, we can leave it for cleanup post electron 11.

**Pull request merged**
