### PR TITLE
fix: clear HANDLE_FLAG_INHERIT flag from console handles

### PR DESCRIPTION
**Pull request by the-ress**
#### Description of Change
[`base::RouteStdioToConsole`](https://github.com/chromium/chromium/blob/708bbea4cedfa0346cb9b16466ae20b8c66bd31f/base/process/launch_win.cc#L127) opens four new handles to console. These handles are created with HANDLE_FLAG_INHERIT flag which causes them to be inherited by child processes. This causes the console window to remain open when all attached processes terminate.

[`uv_disable_stdio_inheritance`](https://github.com/libuv/libuv/blob/4101d1dfed05bae4b543d1769adcb11067e8dcdb/src/win/process-stdio.c#L72) tries to clear this flag, but only from handles it gets from `GetStdHandle` function.

This change clears the flag from the four handles created in `base::RouteStdioToConsole`.
Fixes Microsoft/vscode#66750

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Console handles are not being inherited by child processes on Windows.

### CODE REVIEW

**Comment by miniak** [comment]
@the-ress can you please rebase on the latest master? some CI flakes have been fixed. Also are you planning to get this PR out of Draft state?

**Comment by the-ress** [comment]
@miniak I've rebased on the latest master. I haven't been able to [run the tests locally](https://electronjs.org/docs/development/pull-requests#step-7-test) so I'm going to wait for the CI tests to pass before moving it out of Draft state (if that's OK).

**Comment by codebytere** [comment]
@the-ress would you still like to move this forward?

**Comment by codebytere** [comment]
Closing due to inactivity and lack of response, but can and will open this PR again if there are still plans to work on it!

**Comment by jpelton-stroud** [comment]
@the-ress, @miniak, @codebytere, et. al:  Is this issue still on anyone's radar?  As minor as it may seem, not being able to close the parent console is quite annoying, particularly when you *do* close it by accident.

Thank you all for the work you do,
- A Simple Grunt

**Comment by the-ress** [comment]
@jpelton-stroud The PR seems to break CI build tests and I haven’t been able to run the tests locally to investigate it. I’d like to try it again someday when I have time. If anyone wants to help, they’re very welcome.

**Pull request closed without merging**
