### PR TITLE
test: re-enable `test-child-process-stdio-overlapped`

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Re-enable disabled `parallel/test-child-process-stdio-overlapped` spec. This was previously disabled owing to the fact that it relied on a small test executable being build in `node.gyp`, which we didn't build. Fixed this by building the executable as a component of the node tests in CI.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by nornagon — APPROVED** [review]

**Comment by nornagon** [comment]
@codebytere conceptually lgtm but apparently the test is borken

**Comment by codebytere** [comment]
ah, looks like

> /bin/bash: line 1: ninja: command not foun

hmm

**Review by MarshallOfSound — APPROVED** [review]

**Review by MarshallOfSound — COMMENTED** [review]
GitHub mobile sucks, I was trying to comment on this.  You'll need to build this in the build step and persist it in the workspace like the `dist`

**Review by MarshallOfSound — APPROVED** [review]

**Comment by codebytere** [comment]
https://app.circleci.com/jobs/github/electron/electron/1173526?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link is not running as the UI seems to indicate - it's green. Merging.

**Pull request merged**
