### PR TITLE
Chrome 54 update

### LINKED ISSUE #6571: screen.scaleFactor always returns 1 for 125% DPI
- Electron version: 1.2.8
- Operating system: Windows

I have a hidpi screen on my laptop and a normal main monitor that has some scaling applied through windows' display properties. In both cases the following code returns 1 even though I would expect something larger:

```
require('electron').screen.getPrimaryDisplay().scaleFactor
```

### LINKED ISSUE #7814: vm.runInNewContext() & console.log causes devtools to disconnect
* Electron version: 1.4.3
* Operating system: Windows 10 x64

I am building an app which runs user scripts in a sandboxed environment, so I want to use the Node vm module. Here is the code I use to load the user scripts:

```TypeScript
function runInSandbox(visPath: string): IVisualization {
    let context = {
        require: (moduleName) => {
            // I implement a custom "safe" require method here
        },
        console: console,
        module: {}
    };
    let data = fs.readFileSync(path.join(visPath, 'index.js'));
    let result = vm.runInNewContext(data, context, { visPath });
    return result;
}
```

```JavaScript
// userscript/index.js
console.log('test');
```

Now, when I run the app without devtools open, the user scripts execute as expected. However, when I am running with the devtools open, as soon as one of the user scripts does a `console.log`, the devtools crashes with:

```
DevTools was disconnected from the page.
Once the page is reloaded, DevTools will automatically reconnect.
```
electron-crash

However, if I define the `console` object in the context thus:
```TypeScript
console: {
  log: (...args) => console.log(...args),
 },
```

then the script works fine and DevTools does not disconnect, which seems strange, since I have seen many examples online where the `console` object is defined as in the first example.

### LINKED ISSUE #8062: Windows 10 blurry, with desktop scaling on 150%
* Electron version: 1.4.8
* Operating system: Windows 10 Anniversary Edition (build 1607)

### Expected behavior

When dragging a window to hidpi desktop, e.g. 150% scaling, it should scale it correctly. 

### Actual behavior

It does not scale, the window remains blurry.

Google Chrome stable version (54.0.2840.99 m (64-bit)) works correctly, if I drag window (any window e.g. even the developer tools window) it changes the scaling correctly as soon as it gets to the desktop with different scaling factor.

### LINKED ISSUE #8366: net::ERR_INSECURE_RESPONSE error 1.4.13 mac-only
* Electron version: 1.4.13
* Operating system: MACOS

### Expected behavior

No network error

### Actual behavior

We are getting net::ERR_INSECURE_RESPONSE errors on a https css file used within a local html file. The error does not happen on windows, but does happen on multiple different mac machines. This is a recent thing and rolling back electron versions does not help. I suspect that means it is related to the 10 week certificate issue I found noted in other issues.

The bug does not happen in safari or chrome on mac or chrome or electron on windows

### PR DESCRIPTION
**Pull request by groundwater**
Debug build compiles on:
- [x] OS X
- [x] Linux
- [x] Windows

Release build compiles on:
- [x] OS X
- [x] Linux
- [x] Windows

Tests passing on:
- [x] OS X
- [x] Linux
- [x] Windows

Fix features:
- [x] `insertCSS`
- [x] `inspectElement`
- [x] offscreen rendering
- [x] POST navigations
- [x] `navigator.requestMIDIAccess`

Merge:
- [ ] https://github.com/electron/libchromiumcontent/pull/239
- [ ] https://github.com/electron/brightray/pull/260

Fixes #6571
Fixes #7814 
Fixes #8062
Fixes #8366

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Boom failed! Please fix this before anything else.

**Comment by poiru** [comment]
@groundwater You may be already aware of this, but your commit is changing the line-endings fron LF to CRLF.

**Comment by groundwater** [comment]
Hey @poiru thanks for the tip! I thought git for windows would fix that, but I'll see if I can adjust Atom editor to use the correct line endings.

Hi @WarenGonzaga, I would like to keep this discussion reserved for people working on the chrome54 fix. I appreciate your enthusiasm, but this is a very early work, and there is much to be done. Thanks!

**Comment by paulcbetts** [comment]
If y'all upload libchromiumcontent for Windows I can pitch in on that front

**Comment by zcbenz** [comment]
This is closed in favor of https://github.com/electron/electron/pull/8406.

**Pull request closed without merging**
