### PR TITLE
fix: remote.protocol.{register|intercept}StreamProtocol can work now under certain conditions

### PR DESCRIPTION
**Pull request by ianho**
#### Description of Change
For issue #17059
`remote.protocol.{register|intercept}StreamProtocol` not work.
This commit wont fix all the case because the `remote ipc` is sync but `stream` is async.
At least `remote.{register|intercept}StreamProtocol` can work under certain conditions now.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed remote stream protocol now working

### CODE REVIEW

**Comment by vincentdchan** [comment]
How long it can be merged! Can't wait to use it!

**Comment by ianho** [comment]
How can I retrigger the CI pipline?
I found that win-ia32 build succeeded but win-x64 build failed.
I think my changes wont cause this problem.

**Comment by ianho** [comment]
I think “reading all the data into memory takes very long time” is very convincing for me.
But this issue block my work in our project. I must use api `remote.protocol.{register|intercept}StreamProtocol` because of some complicated reasons which I cant control.
Api `remote.protocl.{register|intercept}BufferProtocol` cant return with headers, so it wont work too.
Otherwise, if api `remote.protocol.{register|intercept}StreamProtocol` cant work, maybe we can tell people that in doc. Or we can tell people using this api with remote will take very long time?

**Comment by ianho** [comment]
> I agree with @zcbenz it makes no sense to use a `stream` protocol then load the entire stream into memory. This is terrible for performance and is terribly misleading for folks using a stream protocol.
> 
> Because of the way streams work making them work over remote is basically impossible. If this is what you want to achieve you should use a buffer protocol not a stream protocol.

I said I agree with the opinion. But I think if we dont want to support stream protocl with remote way, maybe we should tell people that instead of provide a api with bug.
And about buffer protocol, it cant response with headers. Maybe we should support response headers via buffer protocol ?

**Comment by zcbenz** [comment]
I'm closing this PR as so far no maintainer thinks we should solve the problem in this direction.

**Pull request closed without merging**
