### PR TITLE
refactor: let mate converters do their job, don't call GetHandle manually

### PR DESCRIPTION
**Pull request by MarshallOfSound**
We have mate converters for `util::Promise`, there is no need to convert to `v8::Local<T>` manually, in fact this will allow us to more easily change how `util::Promise` works in the future.

Notes: no-notes

### CODE REVIEW

**Comment by deepak1556** [comment]
I am down with having this merged once the sequence checker macro has been added to `util::Promise`.

**Comment by zcbenz** [comment]
The `promise` has been `std::move`d before being returned, so the code is actually returning an empty handle. That's why the tests are failing with crashes.

I'm actually surprised that the compiler did not complain about this, since this belongs to use-after-move errors.

**Comment by codebytere** [comment]
@MarshallOfSound should we close this one out given the above comments??

**Comment by MarshallOfSound** [comment]
Closing out as per above comments

**Pull request closed without merging**
