### PR TITLE
revert: only allow bundled preload scripts

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Revert #17308. There are issues with `electron-mocha`.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Reverted change to only allow preload scripts to be loaded from application root due to issues with `electron-mocha`.

/cc @electron/wg-security

### CODE REVIEW

**Comment by miniak** [comment]
The actual issue was #18092

**Comment by zcbenz** [comment]
Would like to hear more voices from @electron/wg-security before merging.

**Comment by miniak** [comment]
@zcbenz I would like to re-land this change later after I resolve all the issues.

**Comment by alitaheri** [comment]
Will this be backported to 6.x-beta?

Also @miniak please keep in mind that in the development stage this is a real pain. Allow disabling this behavior somehow, like an environment variable or a function on the `app` module.

I understand that this is an important security feature. but it's not needed during development. Since you're using `realpath` even symbolic links can't be used as a workaround. please allow some safe way of disabling this, at least during development. thanks 🙏

**Comment by MarshallOfSound** [comment]
@alitaheri What is your development use case for loading a preload script outside of your app path?  In development the app path should be the directory containing your apps `package.json`.  If that doesn't include your preload script I'm not sure what your set up is?

**Comment by alitaheri** [comment]
@MarshallOfSound Our app is pretty complex, we use typescript and have many outputs. but a single preload to be used for all the processes. for production we copy everything under the same folder, but in development the main processes are in different folders than the preload itself. it was all working fine. but this change broke it. right now we copy the preload output to the mainProcess folders too but would like to be able to disable this during development.

**Comment by alitaheri** [comment]
I have worked around this by always copying preload after bundling to where the main processes are. this isn't ideal but gets the job done. though I would still prefer an option to disable this check. thank you

**Comment by miniak** [comment]
@alitaheri in the new version, I will probably only apply this for bundled apps, which is basically production only. Would that work for you?

**Comment by alitaheri** [comment]
@miniak Yes absolutely, thank you 👍

**Pull request merged**
