### PR TITLE
Update menu.md

### PR DESCRIPTION
**Pull request by fab1an**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Looks like many classes use `##`, is there a reason only this one is changed?

Also, this is the preferred format according to the `docs/styleguide.md`:

>  API classes or classes that are part of modules must be listed under a `## Class: TheClassName` chapter.

**Comment by MarshallOfSound** [comment]
This change would break the docs parser, as @kevinsawicki the styleguide requires the double `##`

**Comment by zeke** [comment]
The change in this PR does indeed conflict with the styleguide, but @fab1an is on to something: It's the first heading in the file so it seems like it should be an `<h1>`.

The reason it's an `<h2>` is historical: Classes used to be documented within the context of other API docs, so they were nested. Now they're not, and [every API has its own markdown file](https://github.com/electron/electron/pull/7969).

There's no practical reason to keep using `<h2>` instead of `<h1>`; it's just going to require a bit of extra work if we want to change them all. At a minimum, this would have to happen:

- [ ] Decrement heading levels in the markdown doc of every Class.
- [ ] Update the styleguide to reflect the new rules.
- [ ] Update [electron-docs-linter](https://github.com/electron/electron-docs-linter/blob/3c0128cafa3efecdaecefd094a11c830c096acb4/lib/api.js#L43-L50) to account for changes.

@fab1an if you want to take a shot at those first two items,  I'd be willing to do the work of updating the linter.

**Comment by fab1an** [comment]
There is a docs parser? The reason I added this PR is because I also wrote a parser to automatically generate kotlin bindings.

**Comment by enlight** [comment]
@fab1an Yes, the parser is in https://github.com/electron/electron-docs-linter

**Comment by MarshallOfSound** [comment]
@fab1an And we also publish the output of the parser with each release.

For instance:
https://github.com/electron/electron/releases/download/v1.6.0/electron-api.json

**Comment by zeke** [comment]
And we auto-publish an npm module with every release: https://github.com/electron/electron-api-docs#readme

Intro blog post: http://electron.atom.io/blog/2016/09/27/api-docs-json-schema

**Comment by fab1an** [comment]
Ok, I use XML which then looks like this: https://github.com/fab1an/kotlin-electron-api/blob/master/build/api_docbook/browser-window.source.normalized.xml

Is information whether parameters are optional included as well in the json-schema?

**Comment by MarshallOfSound** [comment]
@fab1an Not currently, although we have an open issue for it somewhere I think

You can see how I determine if something is optional in `electron-definitelytyped` however

https://github.com/electron/electron-definitelytyped/blob/master/lib/utils.js#L88

**Comment by fab1an** [comment]
Ok. Feel free to use my xml-definition, if it suits you.

**Comment by zeke** [comment]
Gonna close this out due to inactivity.

If @fab1an or anyone else wants to pick it back up, the necessary steps are outlined in this comment: https://github.com/electron/electron/pull/8630#issuecomment-279124739

**Pull request closed without merging**
