### PR TITLE
chore: Update husky v6.0.0

### PR DESCRIPTION
**Pull request by Maeda-Naoki**
#### Description of Change
Update to [husky](https://github.com/typicode/husky) [v6.0.0](https://github.com/typicode/husky/releases/tag/v6.0.0)  

modify list
- package.json
    - scripts
    -  husky
- yarn.lock 
- .husky

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Update husky v6.0.0

### CODE REVIEW

**Review by codebytere — APPROVED** [review]
hey thanks!

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
For security reasons we don't normally allow third party contributors to bump dependencies.  This appears valid but we'll have to double check the lockfile changes

**Review by MarshallOfSound — APPROVED** [review]
Fixed the `pre-push` script and did the `yarn.lock` changes on my machine, should be all set here

**Comment by codebytere** [comment]
Failure not relevant.

**Pull request merged**
