### PR TITLE
fix: loading dedicated/shared worker scripts over custom protocol

### PR DESCRIPTION
**Pull request by miniak**
Backport of #20625

See that PR for details.

Notes:
* fix loading shared worker scripts over custom protocol
* fix crash when loading worker scripts with nodeIntegration enabled

### CODE REVIEW

**Comment by codebytere** [comment]
@miniak 
```
obj/electron/electron_lib/electron_browser_client.o
../../electron/shell/browser/electron_browser_client.cc:990:7: error: use of undeclared identifier 'ProtocolRegistry'
      ProtocolRegistry::FromBrowserContext(browser_context);
      ^
1 error generated.
```

**Comment by codebytere** [comment]
@miniak this is still failing

**Comment by miniak** [comment]
@deepak1556 we might need your help here as I am not familiar with this change

**Comment by miniak** [comment]
@codebytere fixed

**Review by codebytere — APPROVED** [review]

**Review by deepak1556 — APPROVED** [review]

**Comment by deepak1556** [comment]
Failing test is unrelated, merging.

**Pull request merged**
