### PR TITLE
docs: mention alternative tooling

### PR DESCRIPTION
**Pull request by erickzhao**
#### Description of Change

Supersedes #38685.

After discussion with @electron/docs, we wanted to give visibility to these tools without providing a whole other page and avoid duplicating "Boilerplates and CLIs".

I think we should revisit the structure of that page, though!

cc @mikehearn

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by georgexu99 — APPROVED** [review]

**Review by mlaurencin — APPROVED** [review]

**Review by dsanders11 — CHANGES_REQUESTED** [review]
This has a couple of problems rendering on the website:
* `**Alternative tooling**` is rendered as is (same in preview here on GitHub) - not sure you can use Markdown inside of the `<summary>` tag and have it render correctly
* The sidebar on the right side picks up the headings, which is confusing, especially since links to those headers don't expand the collapsed section

Screenshot 2023-08-02 at 5 10 04 PM

**Comment by malept** [comment]
> not sure you can use Markdown inside of the `<summary>` tag and have it render correctly

It'd be worth testing if you can just use straight HTML instead.

**Comment by mikehearn** [comment]
LGTM! Thanks!

**Comment by erickzhao** [comment]
@dsanders11 Good catch. I'll make this a style change in the website CSS rather than incorporated into the markdown.

**Comment by dsanders11** [comment]
@erickzhao, let's follow the advice here and use `<h2>` to fix the headings from showing up in the table of contents for the page: https://docusaurus.io/docs/markdown-features/toc#customizing-table-of-contents-generation

**Review by ckerr — APPROVED** [review]
:+1: on the text.

**Review by VerteDinde — APPROVED** [review]

**Comment by mikehearn** [comment]
Looks like this just needs an ack from @dsanders11 now?

**Review by dsanders11 — APPROVED** [review]
Whoops, hadn't seen the change in f35a8bdfeddf33f5f10f658f5827132260da0680, thanks @malept.

@mikehearn, thanks for the ping, approving. 👍

**Comment by mikehearn** [comment]
@dsanders11 Super, thanks. There are now 5 approvals, CI seems to be fully green. Should be OK to merge?

**Pull request merged**
