### PR TITLE
feat: support `use selection for find` on macOS

### LINKED ISSUE #29635: Encourage apps to support "Use Selection for Find"
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

A very commonly-available feature across macOS apps is "Use Selection for Find," a menu item with Command-E as the standard keyboard shortcut. Its behavior is that it takes the currently-selected text, and enters it into the application's text search target (field, or whatever). Command-G can then be quickly used to find the next instance of that text.

But more importantly, a well-behaved macOS app also pastes that text to the `NSPasteboard` with name `NSPasteboardNameFind`. In Swift, you'd get it like this: `let findPBoard = NSPasteboard(name: .find)`. Apps should also grab any text on that pasteboard when activating, and enter them into their text search targets.

Given how many third-party developer-focused apps I use are Electron apps, I think there'd be a big benefit to helping those app developers include this functionality in their apps.

I don't know if non-macOS platforms have similar functionality, but it's very handy.

### Proposed Solution

Use the `NSPasteboard` with name `NSPasteboardNameFind`. In Swift, you'd get it like this: `let findPBoard = NSPasteboard(name: .find)`. Apps should also grab any text on that pasteboard when activating, and enter them into their text search targets.

### Alternatives Considered

The alternative is copy and paste, which requires several extra steps. The problem is that the feature is so ubiquitous across macOS apps, one often forgets that it doesn't work in a particular Electron app. Leading to a moment of confusion and cognitive disconnect when it doesn't work.

### Additional Information

n/a

### PR DESCRIPTION
**Pull request by anyerqi**
#### Description of Change
Chromium has supported `Use Selection for Find` on macOS, which is commonly-available feature across macOS apps
The changes are:
  - add a menu role  `useSelectionForFind` with Command-E as the standard keyboard shortcut 
  - add a default Edit > Use Selection for Find menu on macOS
  - `useSelectionForFind` maps to `copyToFindPboard` action

Fixes #29635

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

notes: Added a menu role  on macOS: `useSelectionForFind`

### CODE REVIEW

**Review by codebytere — CHANGES_REQUESTED** [review]
Can you talk a little about what use cases you're hoping to enable here? I understand Chromium makes use of it, but on Chromium for example it is part of a greater set of find-related menu items, none of which we support as bespoke menu item roles:

Screenshot 2023-08-24 at 10 40 56 AM

Given we've [previously merged](https://github.com/electron/electron/pull/32024) some Chromium-specific menu roles, I think we're open to this, but would we want to support any other commands in that menu?

**Comment by anyerqi** [comment]
`Use Selection for Find` is a common function in apps on MacOS, such as Mail, Safari. In addition, Electron-based VSCode also implements this function by itself. So we can speculate that there must be many other apps that also need this feature. This function is not only effective within the app, it will be passed across apps, you can use it in A app, and then use `Find Next` in B app.  Although there is already an API that allows developers to implement similar function themselves, I think it is more convenient to provide it directly.

For the other commands about Finding, I found that implementing these features in chromium would require a lot of extra work and possibly UI components, but pre-defining the UI in ELectron is not appropriate. In addition, as to which content can be searched and selected, different apps may be different, and there are no uniform rules for Finding

**Comment by itsananderson** [comment]
The `clipboard` module already has APIs to [read](https://www.electronjs.org/docs/latest/api/clipboard#clipboardreadfindtext-macos) and [write](https://www.electronjs.org/docs/latest/api/clipboard#clipboardwritefindtexttext-macos) to the Find Pasteboard, so I think individual apps could use those APIs to implement their own version of this behavior.

In Chrome, the `Use Selection for Find` menu item actually opens UI widget to begin a search, whereas I think what you have here would *only* copy the current selection to the Find Pasteboard, which makes the `Use Selection for Find` menu name seem misleading. Please correct me if I'm misinterpreting what this new menu item does.

If we were to add any new API surface here, perhaps we could add an API on `webContents` to make it easier to fetch the current text selection. Otherwise I *think* currently one would need to run something like the following to fetch the selection, when running from the Main process.

```javascript
const selectionText = await window.webContents.executeJavaScript('window.getSelection().toString()')
clipboard.writeFindText(selectionText)
```

**Comment by anyerqi** [comment]
OK, I understand, I will close this PR

**Pull request closed without merging**
