### PR TITLE
feat: add support for unsafe origin switch

### LINKED ISSUE #15448: Support Chromium's command-line switch --unsafely-treat-insecure-origin-as-secure
**Is your feature request related to a problem? Please describe.**
Notifications, Geolocation, Device motion/orientation, EME, getUserMedia, AppCache require a secure origin to work in Chromium. HTTP URLs are not considered secure.
That's why Chromium provides the command-line switch
`--unsafely-treat-insecure-origin-as-secure="$url"` to circumvent this problem.
Unfortunately it's not working in Electron.

**Describe the solution you'd like**
Please make it work. In the renderer. I'd suggest simply like 
```
new BrowserWindow({
  webPreferences: {
    additionalArguments: {
    '--unsafely-treat-insecure-origin-as-secure', 'http://insecure-origin'
    }
}
```
Or a new option `considerSecure: String[]` to `BrowserWindow.webPreferences`.
I guess it should be not too hard to implement since Chromium already supports it and it seems to get lost only in the process of Electron integration.

**Describe alternatives you've considered**
- `app.commandLine.appendSwitch('unsafely-treat-insecure-origin-as-secure', $url)` in the main thread
- Invisible [BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) with secure origin + IPC
- `<iframe>` on a secure origin
- localhost-Proxy
- Using Data URLs in [loadURL](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winloadurlurl-options): `data:text/html,<script>new Notification("hi")</script>`
- webFrame.registerURLSchemeAsPrivileged

**Additional context**
'Deprecating Powerful Features on Insecure Origins' https://goo.gl/rStTGz
When the flag is set in Chromium a message appears under the address bar, saying that
'You are using an unsupported command-line flag'.
image
Nonetheless the features are then working on the origin treated securely.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #15448

Notes: Add support for the `--unsafely-treat-insecure-origin-as-secure` switch

### CODE REVIEW

**Comment by nornagon** [comment]
Also, needs a test.

**Comment by MarshallOfSound** [comment]
@nornagon I'm not 100% sure what that particular line is used for elsewhere in chromium, this patch makes `navigator.serviceWorker` work for instance on an insecure domain (I used `http://example.com` as my test).

That line appears to require the switch to be set quite early in the initialization.  I can add that logic if you want, just not sure what it's purpose is 😆

**Comment by deepak1556** [comment]
@MarshallOfSound the registration on content client is for the browser process side, a scheme needs to be registered for a particular privilege both on the browser process as well as renderer process. There are checks on the browser process that will fail when not registered.

**Comment by zcbenz** [comment]
@MarshallOfSound Do you still want to work on this?

**Comment by zcbenz** [comment]
Closing as all activities on this PR seem to be dead.

**Comment by cachius** [comment]
Hey, I'd like to revive this PR.
The reason is, to say it with Neil Armstrong,
That's one small step for a dev, one giant leap for Electron.

With access to the mighty API via nodeIntegration
Chromium's classification of 'Insecure Origins' doesn't hold for Electron.

I can access any file I want and request across the whole internet,
but have to evoke intricatest trickery to display a humble notification.

Let's get this right and let Electron shine!

**Pull request closed without merging**
