### PR TITLE
fix: center window properly after BrowserWindow::center is called

### PR DESCRIPTION
**Pull request by CezaryKulakowski**
This pr fixes https://github.com/electron/electron/issues/26362.

Call to BrowserWindow::center puts window somewhat above center vertically.
It's because Electron uses NSWindow::center:
https://developer.apple.com/documentation/appkit/nswindow/1419090-center
and according to documentation it doesn't center the window vertically
so we must do calculation and placement manually.
#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed call to BrowserWindow::center on mac.

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
A case could be made here that this is expected behavior, and if you want to center the window _exactly_ then you can do exactly what this code does using the `screen` and `setPosition` API

**Comment by codebytere** [comment]
@MarshallOfSound this is intended to https://github.com/electron/electron/issues/26362 it looks like. @CezaryKulakowski it's important when opening pull requests to indicate clearly which problem a change is intending to solve in detail and also to link to the relevant issue - without that it is hard for us to effectively review.

**Comment by CezaryKulakowski** [comment]
@codebytere Is there a way to link issue with pr? Or I just should add link to issue in the pr's description?

**Comment by jkleinsc** [comment]
@CezaryKulakowski add a link to the issue in the PR's description.  Something like fixes #26362.

**Comment by CezaryKulakowski** [comment]
Closing this pr as according to electron current behaviour is expected. I'm going to keep the fix on our side as I don't agree with it (center means center to me and not somewhat above center vertically).

**Pull request closed without merging**
