### PR TITLE
Adds --chromium_dir argument to script/create-dist.py

### LINKED ISSUE #11353: script/create-dist.py doesn't allow custom libchromiumcontent directory
* Electron version: 1.8.2 beta 3
* Operating system: Fedora 27

### Expected behavior

I'd expect the `script/create-dist.py` to accept an argument (like `--chromium_dir <path>`) in order to specify a custom libcc dist folder

### Actual behavior

There is no such option

### How to reproduce

Just compile libchromiumcontent in a different folder than electron's `vendor/libchromiumcontent` and after bootstrap, update and build, run the `create-dist.py` script.

Note: I'm going to create a pull request for this

### PR DESCRIPTION
**Pull request by elegos**
Fixes #11353 

This patch adds `--chromium_dir` to specify a custom libchromiumcontent dist folder (i.e. `./script/create-dist.py --chromium_dir /my/libchromiumcontent/dist/static_library`)

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Is this different from the existing `--libcc_static_library_path` argument?

https://github.com/electron/electron/blob/f8adaed7633d39b95e38998d748978bc5ef059d1/script/bootstrap.py#L103

**Comment by elegos** [comment]
@MarshallOfSound it is, as the bootstrap's argument is not taken in consideration. I'm not a python expert, so I haven't invastigated more than the `create-dist.py` script (which has the chromium content dir hardened into the code).

Maybe the create-dist script may take in consideration the bootstrap's variables, but I'm not sure how the bootstrap passes the variables.

**Comment by codebytere** [comment]
@elegos builds are failing on lint, please `npm run lint` and commit associated changes!

**Comment by elegos** [comment]
@codebytere thanks for the reply :)

Honestly I'm confused about the docs lint fail, as I modified no readme or doc, but only the python script, which I fixed the CS problem already. I'll try sync'ing the project again and see if it will fix itself.

**Pull request merged**
