### PR TITLE
fix: --inspect-brk hang when loading internal scripts

### PR DESCRIPTION
**Pull request by deepak1556**
#### Description of Change

Refs https://github.com/microsoft/vscode/issues/230495
Upstream PR https://github.com/nodejs/node/pull/54219

#### Release Notes

Notes: fix `--inspect-brk` hang when debugging with esm

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Has this landed upstream, can you link the PR for reference?

**Comment by deepak1556** [comment]
Yup, the patch has additional context and is a backport from upstream change. It will be available from `v20.18.0`

**Comment by deepak1556** [comment]
Main is now on `v20.18.0`, retargeting.

**Comment by deepak1556** [comment]
We have `v20.18.0` rolls [ongoing](https://github.com/electron/electron/pulls/app%2Felectron-roller), closing this in favor of them.

/cc @jkleinsc

**Pull request closed without merging**
