### PR TITLE
fix: session.getBlobData never resolves with blob sizes > 65536

### LINKED ISSUE #34398: [Bug]: session.getBlobData never resolves with blob sizes > 65536
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1 (21E258)

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When running `session.getBlobData` on a blob UUID from an `onBeforeRequest` handler, I expect the resulting promise to resolve successfully to a buffer when the blob size is <<< RAM size. According to https://source.chromium.org/chromium/chromium/src/+/main:storage/browser/blob/blob_memory_controller.cc?q=CalculateBlobStorageLimitsImpl&ss=chromium, a blob of size 65537 should be handled correctly.

### Actual Behavior

When calling `session.getBlobData` on a blob with size > 65536, the resulting promise never resolves.

### Testcase Gist URL

https://gist.github.com/b3b9955084b145c77987e4dbc6c81078

### Additional Information

This issue appears to be a possible duplicate of https://github.com/electron/electron/issues/33081, though the other issue includes very little additional information, so I have filed a separate issue to be safe.

I did a bit of digging through the Electron glue source, and I found the following:

https://github.com/electron/electron/blob/61374019c03ab1af8584550277318ba7c2adb0ca/shell/browser/api/electron_api_session.cc#L725-L735
https://github.com/electron/electron/blob/c4ea33d1bf6faf8ca685e67e63b197d89efa9870/shell/browser/api/electron_api_data_pipe_holder.h#L33-L35

I suspect that this is related.

### PR DESCRIPTION
**Pull request by frank-pian**
#### Description of Change
Fixes #34398
When the blob data is greater than 65536 in length, remaining_size_ != 0. 
My understanding of the Electron code is superficial, but it is feasible after testing.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix session.getBlobData never resolves with blob sizes > 65536

### CODE REVIEW

**Comment by frank-pian** [comment]
@VerteDinde  It seems to work

**Review by codebytere — CHANGES_REQUESTED** [review]
@frank-pian please fill out the PR body and describe your changes in enough detail for them to be appropriately reviewed. Release notes are also required. Can this be tested? If yes, we should add a test to prevent regressions.

**Comment by frank-pian** [comment]
> @frank-pian please fill out the PR body and describe your changes in enough detail for them to be appropriately reviewed. Release notes are also required. Can this be tested? If yes, we should add a test to prevent regressions.

OK, I'll try to complete the information.
This PR submission process is confusing to me. I hope you can help me complete the test. I just want to fix this bug. 
Thanks!

**Review by zcbenz — APPROVED** [review]
I'm good with this change since it is a trivial one and matches the behavior of Chromium's code:
https://source.chromium.org/chromium/chromium/src/+/main:services/network/data_pipe_element_reader.cc;drc=aeedf4cd0d323c89781ecbe6662c899cdfa8aa81;l=112?q=OnHandleReadable&ss=chromium

But a test is still preferred since there is already a test case written in https://gist.github.com/quantatic/b3b9955084b145c77987e4dbc6c81078.

**Comment by frank-pian** [comment]
@zcbenz 
Yes, I have verified the code using this case and it works.

**Review by jkleinsc — CHANGES_REQUESTED** [review]
@frank-pian can you add a test here https://github.com/electron/electron/blob/main/spec-main/api-session-spec.ts#L485 using the gist https://gist.github.com/quantatic/b3b9955084b145c77987e4dbc6c81078?  You can copy what was done for the existing `session.getBlobData` test and just modify to test this fix.

**Comment by microwugui** [comment]
> @frank-pian can you add a test here https://github.com/electron/electron/blob/main/spec-main/api-session-spec.ts#L485 using the gist https://gist.github.com/quantatic/b3b9955084b145c77987e4dbc6c81078? You can copy what was done for the existing `session.getBlobData` test and just modify to test this fix.

I think it's not frank's business
Why not create a new PR by yourself to fix this issue and provide the test cases you supposed?

**Comment by frank-pian** [comment]
@jkleinsc ok, i have added test case.

**Review by zcbenz — COMMENTED** [review]
Can you rebase to fix the merge conflict?

**Comment by frank-pian** [comment]
> Can you rebase to fix the merge conflict?

I merged main branch. Are there any other mistakes?

**Review by codebytere — APPROVED** [review]

**Comment by RangerMauve** [comment]
This would be very useful to have, running into some issues with uploading files to protocol handlers. 😅

**Review by jkleinsc — APPROVED** [review]

**Pull request merged**
