### PR TITLE
chore: auto-label new issues based on template

### PR DESCRIPTION
**Pull request by dsanders11**
#### Description of Change

Auto-label issues based on the template used for creating it.

#### Checklist

- [x] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by 05527223971** [comment]
Uueii3

**Review by MarshallOfSound — COMMENTED** [review]
This is tricky, because in reality there is a solid quantity of issues that get raised with these templates that _aren't_ bugs or enhancement requests.  Until GitHub has strict template validation, I don't think we should be generous with auto-labels 😢

**Comment by zcbenz** [comment]
When triaging issues, I think it is more helpful that new issues have no labels, otherwise it would be hard to tell if an issue has been triaged.

**Comment by dsanders11** [comment]
> This is tricky, because in reality there is a solid quantity of issues that get raised with these templates that aren't bugs or enhancement requests.

That's a fair point.

> When triaging issues, I think it is more helpful that new issues have no labels, otherwise it would be hard to tell if an issue has been triaged.

That thought did occur to me, but it's also easy enough to add a label indicating it needs to be triaged, which would be removed on triage.

~10-12% of currently open issues are unlabeled, with an unknown percentage (hard to query) that only end up with a version label or the likes.

I think it might result in more issues being fully labeled if they were auto-labeled first, and the person triaging simply removed the auto-label if it wasn't applicable.

**Comment by dsanders11** [comment]
Closing this PR since it's just outdated and hanging around, and looks like the newest version of the templates auto-label.

**Pull request closed without merging**
