### PR TITLE
refactor: remove InspectableWebContentsViewMac in favor of the Views version

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change

I just deleted the Mac version and things seem to work okay? A bit surprising.
Probably I missed something?

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
Looks like this regresses https://github.com/electron/electron/issues/37301, which was fixed by https://github.com/electron/electron/pull/37386.

**Comment by nornagon** [comment]
Spent a day tracking down why the frame subscriber tests were failing. It looks like there's logic to skip rendering when the window is hidden unless headless mode is enabled: https://source.chromium.org/chromium/chromium/src/+/main:ui/views/cocoa/native_widget_mac_ns_window_host.mm;l=634-635;drc=3eb9fd518875bee685ad2e8c2b699822a8dfd5d9
```objcpp
  if (is_visible_ || is_headless_mode_window_)
    compositor_->Unsuspend();
```
i.e., if the window is hidden, the compositor won't unsuspend unless the headless bit is set.

The effects of setting the headless bit appear (currently) to be only this and one other thing: the frame size won't be constrained to a screen (https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/app_shim/native_widget_mac_nswindow.mm;l=322-326;drc=2245eaf45d235260c18959d54844d6acc9fb4556). So I added some extra logic to unset the headless bit if we're visible in that function.

**Review by zcbenz — APPROVED** [review]
This puts Electron's WebContents in a `views::WebView`, which I think might cause some behavior changes, but this refactoring surely worths the little risk.

**Comment by nornagon** [comment]
Let's find out :D

**Pull request merged**
