### PR TITLE
Fix Korean grammatic mistakes

### PR DESCRIPTION
**Pull request by ssu2030**
Mostly spacing errors. Haven't look at full Korean translation, but will do.

Signed-off-by: Dongho Lee <ssu2030@naver.com>

### CODE REVIEW

**Comment by codebytere** [comment]
since this PR and https://github.com/electron/electron/pull/11019 are extremely related and similar, if you could please aggregate them and close one of them that would be great.

**Comment by Toinane** [comment]
I think it would be cool to use Crowdin now for this :)! [https://crowdin.com/project/electron](https://crowdin.com/project/electron)

**Comment by ssu2030** [comment]
@Toinane Thanks, So I was translating in `https://crowdin.com/project/electron`
I am sorry for the mistakes made because I could not recognize the process correctly.

**Comment by ssu2030** [comment]
@codebytere I am sorry for the mistakes made because I could not recognize the PR process correctly.
From now on,  I will translate there. and really grateful for your interest in small things.

**Comment by Toinane** [comment]
ahah no worries :) any help is always useful!

**Comment by ssu2030** [comment]
Thank you for your advice :-)
I will do my best to make an important contribution to Electron with interest in issues. 
-----Original Message-----

**Comment by ckerr** [comment]
Thank you for your translation!

We've recently [moved](https://github.com/electron/electron/blob/master/docs-translations/README.md)  our translations to [Crowdin](https://crowdin.com/projects/electron) to make it easier for contributors to make changes. Please feel encouraged to make the correction there.

I'm going to close this pull request, though, because as a result of the change this patched file is no longer kept in the electron/electron repo.

**Pull request closed without merging**
