### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by m1guelpf**
TO DO:

- [x] Wait to the next year (100% done, depends on timezone)
- [ ] Merge!

:octocat:

### CODE REVIEW

**Comment by lee-dohm** [comment]
@MarshallOfSound we set it up this way based on advice from one of our awesome legal folks that know a lot more about licensing than I ever will :grinning: I believe technically we should wait until there is a code change before updating the year, we shouldn't just update the year because the year changed.

**Comment by MarshallOfSound** [comment]
@lee-dohm Gotcha, makes sense 👍 Will just leave this one hanging until the first 2018 commit goes in then 😄

**Comment by sdbedi** [comment]
@lee-dohm Might be safe to run that point by an attorney to be sure - I don't see how the two are linked. 

I know that Facebook uses -Present format for their open source projects. I trust their lawyers ;p

**Comment by sdbedi** [comment]
@lee-dohm My apologies, on further research, I see you may be right.

**Comment by lee-dohm** [comment]
Looks like there's been a code change. Thanks for the help!

**Comment by mickaelandrieu** [comment]
@sdbedi can you provide a link about it? I've never seen a proof of an advantage of date range instead of the initial date of creation :)

**Comment by phillip-haydon** [comment]
@mickaelandrieu seems like it doesn't really matter based on this:

https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year

It seems like wasted effort to me, but I'm no copyright expert so that's just an opinion :)

**Comment by sdbedi** [comment]
@mickaelandrieu 

Strictly speaking, copyright notice is not required under U.S. law: 
https://en.wikipedia.org/wiki/Copyright_notice

However, a couple of sources suggest that a date range is the best practice for _continuously updated_ source materials, ie. source code:
http://epiphany.law/articles/copyright/copyright-dates-single-year-or-range
http://smallbusiness.chron.com/year-copyright-statement-mean-62027.html
https://www.copyrightlaws.com/copyright-notice-year/

DISCLAIMER: The above is not intended as legal advice. You should consult your own attorney if you require legal advice personalized to your situation.

**Comment by lee-dohm** [comment]
I think we should avoid legal speculation in the discussions here. As @sdbedi pointed out, anyone interested should consult their own attorney for legal advice.

I appreciate that you state that you're an attorney in your profile @sdbedi but I would feel more comfortable if discussions of legal matters occurred in a more formal setting than in a random issue conversation :grinning: Because of this, I'm going to lock this for further comments.

Thanks everyone for your feedback.

**Pull request merged**
