### PR TITLE
build: better error handling for release builds

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Mild improvement in release build error handling.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by VerteDinde — APPROVED** [review]
Thanks! 🙇‍♀️

**Review by ckerr — APPROVED** [review]
LGTM

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
This will silently absorb the errors here and make sudowoodo think the script succeeded right?

**Comment by codebytere** [comment]
@MarshallOfSound the errors were already being caught if you look at the old code - the thing i'm fixing is that the lines after assume success

**Comment by MarshallOfSound** [comment]
@codebytere I might be missing something but in the case where `makeRequest` throws an error the `console.log` for the success state wouldn't run.  So this would only catch errors in the actual console.log call which I don't understand how they would happen

**Review by clavin — APPROVED** [review]
The original code is a little deceptive in that the `.catch()` on the promises mean that the `await` will never throw:

```js
await Promise.reject(new Error('oops')); // throws here
console.log('after'); // NOT printed
```

```js
await Promise.reject(new Error('oops')).catch(err => console.log('caught', err));
console.log('after'); // always printed
```

The original code is structured as `await`ing some promise returned from `.catch()` and then doing something with the returned value (which is `undefined` when that promise is rejected and caught by `.catch()`):

```js
// this `await` never throws in the way you would expect from `await`:
const something = await makeRequest(...).catch(err => {
    console.log('oops', err);
});

// which means this code will always run, sometimes with `something = undefined`:
const buildUrl = `https://example.ci/${something}`; // uh oh
console.log(`Example release build request for ${job} successful.  Check build status at ${buildUrl}`);
```

The new code removes the `.catch()` calls to make the code more clear and actually sequence correctly when the `makeRequest` promise is rejected.

**Comment by jkleinsc** [comment]
@codebytere @MarshallOfSound iirc, sudowoodo looks for the message `AppVeyor release build request for ${job} successful.`  to determine if a job call was successful so I think this change is ok.

**Review by MarshallOfSound — APPROVED** [review]

**Pull request merged**
