### PR TITLE
Update electron-download to version 4.1.0

### PR DESCRIPTION
**Pull request by Siilwyn**
Respects the OS cache location and be able to set he cache location by setting the environment variable `ELECTRON_CACHE`.

### CODE REVIEW

**Comment by jkleinsc** [comment]
I'm trying to figure out why CI isn't running for this PR, so I am going to close it and then reopen.

**Comment by jkleinsc** [comment]
Still tracking down CI... closing and reopening.

**Comment by Siilwyn** [comment]
@jkleinsc looks like it's running now. 👀 
:)

**Comment by Siilwyn** [comment]
@jkleinsc cheers! Thanks for the quick reply and merge.

**Comment by malept** [comment]
Please note that this will drop support for Node < 4. In the past there were concerns from the core team about preventing people from installing Electron, even with unsupported Node versions.

**Comment by MarshallOfSound** [comment]
The discussion there is this bump should go out in a major version, perhaps we roll this back till 2.0

**Comment by Siilwyn** [comment]
Perhaps I am missing the point as I am not up to speed with Electron's release cycle but why not bump to 2.0 if this update needs it?

I think this is a case of what Germans would call Hauptversionsnummernerhöhungsangst. The fear of a major bump. As Stephan Bönnemann (who is arguing hard for semver and did talks on the subject), loosely quoted:
> Version numbers should be used to avoid dependency hell... There's no reason for keeping the version number low, expect for marketing or maybe emotional attachment to versions. There's this concept in our mind that the version number has something to say about the project or the process or the stability and all of this is wrong... People believe something incredible existing is happening when a major/breaking version is released... Leave your emotions out of this.

**Comment by MarshallOfSound** [comment]
@Siilwyn We are currently working on a new versioning scheme and I personally don't think we should be doing our first major bump in a very long time for a simple dependency breaking change.  When we adopt our new versioning scheme major bumps can come more frequently but until then I don't want us to jump to 2.0 for what is effectively just dropping node version support.

I'm all for this change, but after that versioning scheme has come in and we can slot it in with a major bump (potentially chromium 61)

**Comment by ckerr** [comment]
@MarshallOfSound just to make sure I'm reading your last comment correctly, when you say "I'm all for this change, but after that versioning scheme has come in..." do you think we should roll this back for now and re-add it in a future release alongside another major bump e.g. chromium 61?

We're thinking about doing a beta2 in the next day or two, so I'd like to resolve this before that happens

**Comment by MarshallOfSound** [comment]
> do you think we should roll this back for now and re-add it in a future release alongside another major bump e.g. chromium 61

Yes

**Pull request merged**
