### PR TITLE
refactor: move GetCursorBlinkInterval() to a helper function

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Follow up to #20020

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by deepak1556** [comment]
@miniak whats the motivation behind this change ?

**Comment by miniak** [comment]
@deepak1556 it makes it more readable IMO, but I don’t feel to strongly about this PR.

**Comment by codebytere** [comment]
I'm not opposed to this PR on principle, but given the small amount of code here and that this wasn't mentioned in original code review, we may want to consider that this will increase code drift between this branch and others for a small comparative benefit 🤔

**Comment by codebytere** [comment]
@miniak are you ok with closing this?

**Comment by miniak** [comment]
@nornagon, @MarshallOfSound what do you think?

**Pull request merged**
