### PR TITLE
chore: add debug build profile

### PR DESCRIPTION
**Pull request by BlackHole1**
#### Description of Change

add debug build profile

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by BlackHole1** [comment]
cc: @codebytere @zcbenz @nornagon @deepak1556

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
This was removed a while ago because it was a massive burden to maintain support for (as a result of how we did some things with Chromium) and no one really used it.

All these flags can be set yourself if you want to when running `gn gen`.  If we add this to main, folks will try to use it, and then we'll be stuck supporting it again 🤔

**Comment by MarshallOfSound** [comment]
Refs: https://github.com/electron/electron/pull/21016

**Comment by BlackHole1** [comment]
Thanks for the reply, now I understand the whole context. The reason I raised this PR is that I sometimes need to debug electron source code, and electron doesn't explain how to breakpoint debugging, causing me to spend a lot of time trying.

I have a suggestion though, we should tell people in the documentation how to do breakpoint debugging of electron source code. The current documentation uses `testing.gn` which only allows the developer to package a working electron, but not to breakpoint debug it.(I would be happy to resubmit a PR for this if I could)

**Comment by deepak1556** [comment]
I am good with PR that improves debugging documentation, as @MarshallOfSound mentioned we can't check in a build configuration into the tree that won't get run on CI.

**Comment by BlackHole1** [comment]
> I am good with PR that improves debugging documentation, as @MarshallOfSound mentioned we can't check in a build configuration into the tree that won't get run on CI.

okey. do you mean that you will improve the debugging documentation?

**Comment by deepak1556** [comment]
PR is welcome :)

**Comment by BlackHole1** [comment]
okey~😄

**Pull request closed without merging**
