### PR TITLE
Fixed field type in Dialog doc

### PR DESCRIPTION
**Pull request by Dhanielk**
Fix properties type. Previously showed as 'String', now 'String[]'

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Looks like there are several other cases of this in the `docs` folder.

It seems to render fine on http://electron.atom.io/docs/api/dialog/#dialogshowopendialogbrowserwindow-options-callback but not on https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback

/cc @zeke any thoughts on this one?

One thing could be to link built-in types to pages like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String so this could just be `[String[]](string)` with a footer link to  `[string]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String`

**Comment by zeke** [comment]
Yeah this popped up before as an issue with GitHub's markdown parser misinterpreting the `[] (`. As a workaround, I think @MarshallOfSound changed all instances of:

```
Foo[] (optional) - the description
```

to this:

```
Foo[] - (optional) the description
```

...but it seems there are some instances of the old style left over.

> One thing could be to link built-in types to pages

☝️  I like this idea. I also think placing the `(optional)` string before the ` - ` delimiter makes more sense anway, and is easier to read.

**Comment by kevinsawicki** [comment]
> .but it seems there are some instances of the old style left over.

I think I reverted these in #8309 for consistency, sorry, didn't know they were intentional.

**Comment by zeke** [comment]
>  sorry, didn't know they were intentional.

No problem. I think the way you changed them is better, and the linter should probably warn when this stuff is wrong.

@Dhanielk what do think of @kevinsawicki's `[String[]](string)` proposal above?

**Comment by MarshallOfSound** [comment]
> One thing could be to link built-in types to pages

I'm like 99% convinced that that kind of sugar should be done in the `electron.atom.io` generation logic and not really in our repository.  The sheer quantity of these types throughout the docs would result in a ridiculous amount of duplication and a lot of potential for mistakes.  Although these links could be useful for some people I don't think it's worth the debt of having literally hundreds / thousands of these links scattered around the codebase ready for typos and such. 

Tbh I would love to see our docs site be generated from our JSON file so that this is more possible but that's a massive goal.

**Comment by kevinsawicki** [comment]
> I'm like 99% convinced that that kind of sugar should be done in the electron.atom.io generation logic and not really in our repository

That would work there but it would be nice if the docs on github.com rendered well too since people still view them there and the translated versions are only rendered there.

 > The sheer quantity of these types throughout the docs would result in a ridiculous amount of duplication and a lot of potential for mistakes.

Linking to types could be used for internal types as well. For example, right now [`BrowserWindow.fromWebContents`](http://electron.atom.io/docs/api/browser-window/#browserwindowfromwebcontentswebcontents) doesn't link the return type to the `webContents` doc making it harder to navigate around.

Although there would be potential for mistake, we could start by adding footers to every doc page for all the types that exist. Then people would just need to wrap types in `[]` when adding new docs and the page having a footer link of `[webContents]: ../web-contents.md` would get them to the right place.

**Comment by zeke** [comment]
Good points, @MarshallOfSound. Do you have other ideas about how to work around the markdown parsing issue at hand, aside from moving the `(default)` to the other side of the description delimiter?

> Tbh I would love to see our docs site be generated from our JSON file so that this is more possible but that's a massive goal.

Me too! This would give us great flexibility in how we present the docs on the website. I think the main blocker for this is that there is "prose" in the markdown docs that doesn't make it's way into the parsed JSON file.

**Comment by MarshallOfSound** [comment]
> aside from moving the (default) to the other side of the description delimiter?

Not off the top of my head, I think we did it that way last time so that we wouldn't have to toucher the docs parser.

**Comment by kevinsawicki** [comment]
> Not off the top of my head, I think we did it that way last time so that we wouldn't have to toucher the docs parser.

How about wrapping the type in backticks? That seems to render fine on github.com and the site, and we already do that for types in certain doc pages like http://electron.atom.io/docs/api/screen where `Display` is wrapped in backticks in the raw doc file.

```
* `properties` `String[]` (optional) - a description
```

**Comment by MarshallOfSound** [comment]
@kevinsawicki That would require changes to the parser I believe as we accept a `<code>` block around return types but not param or object types.  I think the reason we haven't put backticks around them before is that we then have two things with backticks right next to each other E.g.

`properties` `String[]` and then you lose the "these things mean different things" context.

I'm OK with the change just need to be sure that losing the distinction is OK

**Comment by zeke** [comment]
What about simply not putting parens around `optional`?

**Comment by zeke** [comment]
(Not sure I like that. Just thinking out loud here)

**Comment by Dhanielk** [comment]
I will be rather for `type` then [] (which seems more like workaround).

**Comment by Dhanielk** [comment]
So maybe like??
```
* **properties** `String[]` (Optional) - Description
```

* **properties** `String[]` (Optional) - Description

**Comment by kevinsawicki** [comment]
I'm going to close this out since the discussion here has us wanting to go in a different direction for addressing this.

@Dhanielk thanks for raising this issue up 👍 If you are still interested in fixing this please open a pull request against the latest docs on master.

**Pull request closed without merging**
