### PR TITLE
fix: crash when generating shortcut text for super accelerator (32-x-y)

### PR DESCRIPTION
**Pull request by mabaasit**
Manually backport https://github.com/electron/electron/pull/44341 to 32-x-y. See that for more details.

Notes: fix crash when rendering super menu accelerator on linux.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

### CODE REVIEW

**Comment by jkleinsc** [comment]
@mabaasit use `e sync --3` to do a 3 way merge on the patch.  If that succeeds without a problem then run `e patches chromium` to export the updated patch.  If `e sync --3` fails with a conflict, you can manually fix the conflicts by doing the following:
1. Edit the conflicted files and resolve the conflicts
2. Run `git add` on the conflicted files
3. Run `git am --continue`
4. Run `e patches chromium`

Hope that helps!

**Comment by mabaasit** [comment]
@jkleinsc i tried to do that and am getting following error:

```
Applying: Add missing shortcut text for VKEY_COMMAND on linux
error: invalid object 100644 32a3fc0843656eaa87b85dd63ac1ade6d83b6e5b for 'ui/base/accelerators/accelerator.cc'
error: Repository lacks necessary blobs to fall back on 3-way merge.
Patch failed at 0141 Add missing shortcut text for VKEY_COMMAND on linux
```

it seems that its not able to find that in chromium (`ui`). What would be the right approach to resolve this?

**Review by jkleinsc — APPROVED** [review]

**Comment by jkleinsc** [comment]
Merging as CI failure unrelated to PR change.

**Comment by daiyam** [comment]
@mabaasit Thanks you!

**Pull request merged**
