### PR TITLE
[docs] switch footnote links to regular links syntax

### PR DESCRIPTION
**Pull request by sofianguy**
quick fix for https://github.com/electron/electron/issues/12085

There are other docs that need the same fix, but this is a start.

### CODE REVIEW

**Comment by sofianguy** [comment]
lol jk. Upon further inspection 🕵️‍♀️ , looks like it's just the boilerplate doc that had broken links. Haven't found any other pages with broken links. Weird

**Comment by codebytere** [comment]
@sofianguy is this ready for merge?

**Comment by sofianguy** [comment]
@codebytere it is!

**Comment by codebytere** [comment]
failure's a flake; merging anyway!

**Pull request merged**
