### PR TITLE
test: tsify more web contents specs

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Move a handful of tests from renderer to main runner.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by zcbenz** [comment]
> I'm mystified why the shell.openExternal tests would have started failing on Windows because of this PR. Any ideas?

Windows has weird rules on which process can give focus to which window.

**Comment by nornagon** [comment]
@zcbenz I didn't change that file at all though. I don't know how my changes in this PR could have affected it. I've changed the strategy by which the test detects success, though, and now it's failing on mac instead :D

**Comment by nornagon** [comment]
Aaaand this is why it doesn't work on mac. sigh.

Distiller’s_Mac

**Comment by ckerr** [comment]
This PR not just ts'ifys the spec, it also makes the tests a little more robust and fills in some gaps in the documentation. Thanks @nornagon

**Pull request merged**
