### PR TITLE
Fix Korean grammatic mistakes

### PR DESCRIPTION
**Pull request by sdj01044**
I fixed wrong words & wrong translations.

### CODE REVIEW

**Comment by sdj01044** [comment]
I want to know about a check.
(ci/circleci: electron-linux-x64)

**Comment by Toinane** [comment]
@sdj01044 Hey! Thanks for your PR, I recommend you to use Crowdin for this [https://crowdin.com/project/electron](https://crowdin.com/project/electron)
because this translation folder will be deprecated soon and it easier for translators 👍

**Comment by zeke** [comment]
Thanks for your contribution, @sdj01044. Like @Toinane said, all future translation efforts should happen on Crowdin instead of this repository. See https://github.com/electron/electron-i18n#readme for more info.

**Comment by sdj01044** [comment]
Thanks for your kindness, @Toinane  & @zeke.
Your detail information is very helpful to me and other contributors! 👍👍👍
(I am so glad that my first PR has been approved!)

**Pull request merged**
