### PR TITLE
build: remove native mksnapshot for arm/arm64

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change
Starting with Chromium 74, we can no longer build native mksnapshot binaries for arm and arm64.  The decision was made by the @electron/wg-upgrades Working Group to deprecate these binaries for 5-0-x with the intention of removing them completely for 6-0-x.

This PR removes those binaries from our build and from the release.  Also to make sure snapshots still work on arm/arm64, CI has been updated to create arm/arm64 snapshots using the x64 binary that are then tested on arm/arm64 hardware.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Removed native mksnapshot binaries for arm/arm64 as they no longer work.

### CODE REVIEW

**Comment by nornagon** [comment]
Can we remove the patches also?

**Comment by jkleinsc** [comment]
Thanks for the reminder @nornagon.  I was planning on removing them but forgot to do so.  They are now removed as part of this PR.

**Comment by nornagon** [comment]
Looks like the linux build is failing though?

**Comment by jkleinsc** [comment]
@nornagon I had started work on this in another branch and must have missed a commit.  The latest commit should fix the linux build.

**Comment by nornagon** [comment]
Aha, I thought there ought to be more red lines! Thanks :)

**Comment by jkleinsc** [comment]
Merging as mac failure was flake and it reran successfully here: https://circleci.com/gh/electron/electron/165267

**Pull request merged**
