### PR TITLE
Reverting per monitor dpi aware causing issues with different dpis

### LINKED ISSUE #9688: In windows multiple monitor setup with different DPIs, electron app starts out of bounds
* Electron version: 1.6.8 or 1.7.1
* Operating system: Windows

### Expected behavior
In windows multiple monitor setup with different DPIs, electron app starts out of bounds

### Actual behavior
Should start at the same place where app was last opened

### How to reproduce
1. Have two monitors with 200% and 100% DPI
2. Start electron app and move the app to monitor with 100% DPI (non maximized)
3. Quit and Restart the app

App starts out of the bounds in the 100% DPI monitor.

This is a regression after #8786 . I reverted this change and this issue no longer repros.

### PR DESCRIPTION
**Pull request by juturu**
Fixes #9688 #9560 #9691 

Reverts #8786

### CODE REVIEW

**Comment by alespergl** [comment]
I don't think this is a good way to go about solving the mentioned issues and view it as a step backwards. I would much rather see an _actual_ fix to the mentioned problems instead of reverting per-monitor DPI awareness. IMO the user experience without per-monitor DPI awareness is worse than a window placement bug.

**Comment by juturu** [comment]
This is a blocking issue and want to resolve quickly for folks to move forward. I think there are other issues with the actual fix of per-monitor dpi aware and needs more investigation. If we don't want to revert and continue investigation on higher priority, i'm good with it. If we can't get a fix out by next release, we should consider reverting the change to unblock people to move to latest electron. @kevinsawicki your thoughts?

**Comment by alespergl** [comment]
> This is a blocking issue and want to resolve quickly for folks to move forward.

I dare to doubt the graveness of the bug as something that would "block" a way "forward" for people. Can you be more specific? Note that per-monitor DPI awareness has been turned on for a couple of releases now.

**Comment by alexdevero** [comment]
Is there any update or progress on this issue?

**Comment by alespergl** [comment]
I think we should close it. This does not provide a fix to the aforementioned issues.

**Comment by alexdevero** [comment]
@alespergl So, what are other solutions? I would love to see this fixed as I'm currently experiencing this scaling issue (Win 10, 125%).

**Comment by groundwater** [comment]
This was put up for review in one of our standups. We would normally discuss this in out monday meeting, but most of us are in Tokyo next week, so perhaps an in-person conversation can be had there, if not we can make a final decision at the next standup.

**Comment by bpasero** [comment]
VS Code is badly broken on Windows due to all the window position issues. Would like to see this merged eventually 👍

**Comment by alespergl** [comment]
@bpasero This PR is _not_ a fix for your problems, it's a workaround. VS Code can have this workaround applied internally - pm me if you need help with that.
We need to close this PR and replace it with a real fix without regressing high DPI funcionality.

**Comment by bpasero** [comment]
@alespergl yes, thanks for clarifying. I would prefer the real fix too if possible :-).

**Comment by zcbenz** [comment]
This pull request has been hanging for too long, and apparently we don't have an agreement here. I'm closing this pull request and let's continue the discussion at #10862.

**Pull request closed without merging**
