### PR TITLE
feat: add new ElectronSquirrelPreventDowngrades flag

### PR DESCRIPTION
**Pull request by MarshallOfSound**
This adds a new `ElectronSquirrelPreventDowngrades` flag which you put in your apps Info.plist to prevent Squirrel.Mac from ever _downgrading_ your app via the auto updater.  Because some folks may want this behaviour and it adds new limitations on the version strings you can use for your app we don't enable this by default.  In the future it may end up as a recommendation in a packaging guide or something.

Specifically this flag means if the auto updater receives even a Valid And Signed payload for `1.0.0` while your app is on `2.0.0` it will _refuse_ to install that update payload.

Some key things to note:
* If your app version string is not valid according to apples spec (`Major.Minor.Patch`) this flag will make your app un-updateable
* If your update payload version string is not valid according to apples spec this flag will reject the update
* If you issue an update to a lower version this flag will reject the update
* The version string for this feature specifically is read from the apps bundle **not** taken from the update server info payload like the rest of Squirrel.Mac.  i.e. lying about your payload version in the JSON response will not bypass this feature

Left undocumented deliberately so that we can do internal testing / validation of the sensitive autoUpdater component before unleashing this feature into the world.

If any reviewers can come up with any more edge cases for the `should compare version numbers correctly` testcase please comment them in 👍 

This PR also adds a spare auto updater test I had laying around where it tests stacking two updates on top of each other and ensuring only the final one is applied by ShipIt.

Notes: no-notes

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
This needs to be documented somewhere in the docs/

**Comment by MarshallOfSound** [comment]
@jkleinsc See the PR body, specifically:

> Left undocumented deliberately so that we can do internal testing / validation of the sensitive autoUpdater component before unleashing this feature into the world.

**Review by jkleinsc — APPROVED** [review]

**Comment by jkleinsc** [comment]
> @jkleinsc See the PR body, specifically:
> 
> > Left undocumented deliberately so that we can do internal testing / validation of the sensitive autoUpdater component before unleashing this feature into the world.

@MarshallOfSound sorry I missed that.

**Review by jkleinsc — COMMENTED** [review]
API LGTM

**Review by erickzhao — COMMENTED** [review]
API LGTM

**Review by VerteDinde — APPROVED** [review]

**Pull request merged**
