### PR TITLE
:white_check_mark: Add test to check for relative links in docs

### PR DESCRIPTION
**Pull request by joeydlee95**
#11368 

Checks all relative links from every .md file in to see if it points to an existing file or existing file and header location. Prints the file name of where the links are broken and the tabbed output are the broken links within that file.

Does not check for valid remote links.

### CODE REVIEW

**Comment by codebytere** [comment]
Can you run `npm run lint` and commit associated style changes?

**Comment by zeke** [comment]
For the curious, here's what the output currently looks like:

```
$ ./script/check-relative-doc-links.py  
File Location: /Users/z/git/electron/electron/docs/README.md
	Broken links: development/upgrading-chrome.md
File Location: /Users/z/git/electron/electron/docs/api/client-request.md
	Broken links: #requestfollowRedirect
	Broken links: #requestfollowRedirect
File Location: /Users/z/git/electron/electron/docs/api/web-contents.md
	Broken links: #contentssetignoremenushortcuts
	Broken links: web-view-tag.md#disableguestresize
File Location: /Users/z/git/electron/electron/docs/api/webview-tag.md
	Broken links: webview-tag.md#webviewtagfindinpage
	Broken links: web-contents.md#webcontentssendchannel-args
	Broken links: web-contents.md#webcontentssendinputeventevent
	Broken links: webview-tag.md#webviewtagfindinpage
File Location: /Users/z/git/electron/electron/docs/development/upgrading-node.md
	Broken links: upgrading-chrome.md
File Location: /Users/z/git/electron/electron/docs/tutorial/keyboard-shortcuts.md
	Broken links: web-contents.md#event-before-input-event
Parsed through 140 files.
Found 11 broken relative links.
```

**Comment by ckerr** [comment]
Looks great.

+1 on integrating this into the lint tests

**Comment by joeydlee95** [comment]
Committed the additional requests. (should I rebase and squash my commits?)
I'm struggling to actually run the `npm run lint` I believe it is because of my environment is there a doc for properly running and testing?

**Comment by ckerr** [comment]
https://electronjs.org/docs/development/build-system-overview has a lot of information on doing a local build.

**Comment by zeke** [comment]
> I'm struggling to actually run the npm run lint

If you can get `npm run lint-docs` working, that should be a good enough test locally. We can let CI determine whether the full test suite is passing.

**Comment by joeydlee95** [comment]
Hi, I noticed that I am failing 3 test, looking at the stack trace from ci/circleci: electron-linux-x64 and logs from jenkins/pr-head, the errors comes from the script `./script/test.py --ci --rebuild_native_modules` on the x64 machines. Any advice? Wondering how this relates to the test I created, if it relates at all.

**Comment by codebytere** [comment]
@joeydlee95 i don't think these failures are related to your changes, i've kicked some of the builds again and it looks like most are passing now

**Comment by joeydlee95** [comment]
@zeke Hi! Noticed this is still pending! Any other changes needed here?

**Comment by zeke** [comment]
Thanks for making this happen, @joeydlee95! 👍

**Pull request merged**
