### PR TITLE
chore: bump chromium to 74.0.3729.27 (master)

### PR DESCRIPTION
**Pull request by nornagon**
Updating Chromium to 74.0.3729.27.

See [all changes in 74.0.3724.8..74.0.3729.27](https://chromium.googlesource.com/chromium/src/+/74.0.3724.8..74.0.3729.27)

Notes: Updated Chromium to 74.0.3729.27.

### CODE REVIEW

**Comment by nornagon** [comment]
Resolved conflicts in:
- accelerator.patch
- disable_color_correct_rendering.patch

Patches deleted due to inclusion in upstream:
- enable_osr_components.patch
- fix_build_on_arm.patch

Supersedes #17332

**Comment by deepak1556** [comment]
Jumbo build failure on windows should be fixed by cherry-picking https://chromium-review.googlesource.com/c/chromium/src/+/1510658 but lets avoid that because we will again have a patch application clash in the next patch upgrade. Lets wait for that release and update it here manually.

**Comment by jkleinsc** [comment]
I updated our CircleCI config on this PR to use XCode 9.4.1 (which includes 10.13 sdk) and CI now passes: https://circleci.com/workflow-run/61a1bc40-352e-43ad-9670-2f6666659a21?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by deepak1556** [comment]
Changes since the last roll:

* [`36f7c14`](https://chromium.googlesource.com/chromium/src/+/36f7c149d372cba7cd5b830ca2baea6f41384a45^!) Publish DEPS for 74.0.3729.10
* [`df786ba`](https://chromium.googlesource.com/chromium/src/+/df786ba5cfefda596770531880b8de62b04e690d^!) Incrementing VERSION to 74.0.3729.10
* [`809cf1b`](https://chromium.googlesource.com/chromium/src/+/809cf1b1368077e04b961854c18dd617e856856e^!) Fix segfault in ThrottlingURLLoader
* [`af4ab8b`](https://chromium.googlesource.com/chromium/src/+/af4ab8bc8276d591dbde9799280b5d7982e8664e^!) Revert "Move tab_list_ui/ code into its own DFM"
* [`4bc7b1c`](https://chromium.googlesource.com/chromium/src/+/4bc7b1c772ff85fbf77de0f8ff8dc636df2443ee^!) Revert "Use ObserverList for OverviewModeBehavior"
* [`3d0a2d1`](https://chromium.googlesource.com/chromium/src/+/3d0a2d10ca1a72aa09bb8a02f3a4b5a8d8a7d01c^!) [m74] Adding 2 extensions to the allowlist.
* [`911bfc3`](https://chromium.googlesource.com/chromium/src/+/911bfc30e2a8756ceabf0034dfa187d20aa55f71^!) [AndroidSms] Fix issue with background notifications after migration.
* [`1606ed6`](https://chromium.googlesource.com/chromium/src/+/1606ed6810c9feb215713cebd4767d6abea53f36^!) Incrementing VERSION to 74.0.3729.9
* [`91619b9`](https://chromium.googlesource.com/chromium/src/+/91619b9fd1ceacc9eb9d3a573da1babcdb48cdaa^!) Reland "Prevent sending client area for custom-frame widgets"
* [`cd9c25b`](https://chromium.googlesource.com/chromium/src/+/cd9c25b331c492953acefb98967400564e2fb644^!) Revert "Prevent sending client area for custom-frame widgets"
* [`c6ae198`](https://chromium.googlesource.com/chromium/src/+/c6ae19808cc2a71c3b12b4b4027cf888e95b33a7^!) Incrementing VERSION to 74.0.3729.8
* [`7dcbfa1`](https://chromium.googlesource.com/chromium/src/+/7dcbfa110d9ebeec8eaa2a4f4f5838915410f791^!) Use ObserverList for OverviewModeBehavior
* [`c0b9245`](https://chromium.googlesource.com/chromium/src/+/c0b924568870f749c8d969292639321879a70464^!) Move tab_list_ui/ code into its own DFM
* [`603ef46`](https://chromium.googlesource.com/chromium/src/+/603ef46adb973dd10d5886fc866144ada33cc068^!) AsyncInitializationActivity#checkOrientation() should check orientation not rotation
* [`add6db5`](https://chromium.googlesource.com/chromium/src/+/add6db52ad66558cb559ad92f9474b8d6d5d54eb^!) Hook up TabModelFilter framework with TabGroupUi component
* [`9f758c2`](https://chromium.googlesource.com/chromium/src/+/9f758c25ec9be30906bfd67ccc8a770f8ff191d1^!) Apply fonts to all elements instead of relying on inheritance.
* [`8054a56`](https://chromium.googlesource.com/chromium/src/+/8054a567bcb3ef0b3b6acbc4679614796fd36d0f^!) [IntersectionObserver] Optimize occlusion checking
* [`46ff441`](https://chromium.googlesource.com/chromium/src/+/46ff441f3937977374bb8f95410cecf38e41fd04^!) [M74] crashfix: Checked IsSupported() before calling GetSafetyNetId()
* [`49b815f`](https://chromium.googlesource.com/chromium/src/+/49b815f8297dd6776cbb72059fb3c9510d358e67^!) Android: Fix Favicon NPE in accessibility mode
* [`84c6117`](https://chromium.googlesource.com/chromium/src/+/84c6117c01c4cd03a8530b9e32a28f69d1f7b2a9^!) [IntersectionObserver] Fix tracking bookkeeping
* [`3b6cf30`](https://chromium.googlesource.com/chromium/src/+/3b6cf3097ae61df24ff7e70be1abd2b5c86db61f^!) Get rid of redundant intersection computation
* [`b760288`](https://chromium.googlesource.com/chromium/src/+/b7602886107660dbfe79563ac765a24a00cf0ea0^!) Do not access web state while the CRWWebController is being destroyed.
* [`419f5d5`](https://chromium.googlesource.com/chromium/src/+/419f5d52e62c3b994afaea4dff2e53aa2fd397a7^!) Don't use custom load original logic for LitePageRedirect
* [`8df72e3`](https://chromium.googlesource.com/chromium/src/+/8df72e32fdc519232a4fbd3bb0c8fb97794f351b^!) Incrementing VERSION to 74.0.3729.7
* [`c3d24de`](https://chromium.googlesource.com/chromium/src/+/c3d24de14ba3b4e0d8a646a7ba61c73b22b9653c^!) [M74]: Check enabled_ before getting a SafeBrowsingApiHandler instance
* [`842fb88`](https://chromium.googlesource.com/chromium/src/+/842fb88e7b60e8aa565d60958bbd0eaa05e74194^!) [M74][Extensions] Gracefully handle unknown ids in ExtensionHost::OnEventAck
* [`97bfcb1`](https://chromium.googlesource.com/chromium/src/+/97bfcb13f24487cd6a7a003ce47b02f1510b5642^!) ActiveScriptWrappableBase: Ignore objects in construction
* [`e1d8189`](https://chromium.googlesource.com/chromium/src/+/e1d81894f9cfe94ce2df120844390834f1a459b1^!) [ElementTiming] Expose cross origin elements that do not pass TAO
* [`019163b`](https://chromium.googlesource.com/chromium/src/+/019163b7d2bde541b40ec57f73101e8d8d6191b4^!) Add a flag for dispatching touch events to "SyntheticGestureController"
* [`3ffbc18`](https://chromium.googlesource.com/chromium/src/+/3ffbc185c65e767963942d3e53ab55fc955bb657^!) Merge "Prevent enterprise startup dialog crash during closing"
* [`3bd37c2`](https://chromium.googlesource.com/chromium/src/+/3bd37c248cf549acadac8402a5edd60235674a92^!) [Translate] Clear recent target language in TranslatePrefs::ResetToDefaults
* [`a1d098e`](https://chromium.googlesource.com/chromium/src/+/a1d098e34eaf2c6a4f6e3ddd685f0c3b51c8d9c8^!) [Tab Capture] Ensure CAPTURE_UPDATE_RECT aligns with I420 subsample boundaries
* [`e0907f0`](https://chromium.googlesource.com/chromium/src/+/e0907f01c3df9ba1d9a15d3ed88df09ba46f6804^!) [Sync::USS] Fix bookmarks handling of server-illegal titles
* [`8d55430`](https://chromium.googlesource.com/chromium/src/+/8d554308f4f2220ad17576f66da2c3c69c6f904d^!) Fix an NTP texture issue
* [`4e67f3a`](https://chromium.googlesource.com/chromium/src/+/4e67f3a414d0b601cbf373414c55cc232852f5c5^!) Force Picture-in-Picture play/pause button image update
* [`dde23d3`](https://chromium.googlesource.com/chromium/src/+/dde23d3b82a68186e4893edeb5bc193a6d205e07^!) Fix Picture-in-Picture window track controls size
* [`fc6ef3e`](https://chromium.googlesource.com/chromium/src/+/fc6ef3ebf5fc465d0a7fe19fd04ce86a6ea7fb74^!) Fix one pixel black line in Picture-in-Picture window
* [`9a3bdc8`](https://chromium.googlesource.com/chromium/src/+/9a3bdc8b1ee8aa6ca0d6d225d319624ead79bcbb^!) [Unity][Android] Add metrics for advanced sign-in flow
* [`ae30287`](https://chromium.googlesource.com/chromium/src/+/ae3028747b1d89b21261aceaa295c39422f37e81^!) Update FlagExpectations for disable-features=NetworkService
* [`2ae33c9`](https://chromium.googlesource.com/chromium/src/+/2ae33c97fab6b805bb03465a05d7ef8d5490b326^!) Revert "Reland: OOR-CORS: Introduce ResourceRequest::cors_exempt_headers"
* [`2979410`](https://chromium.googlesource.com/chromium/src/+/2979410eb3a798d3c0bf1aa9554f13a91b1a5351^!) Reland "Reland "OOR-CORS: Make kOutOfBlinkCors depends on kNetworkService""
* [`5fae232`](https://chromium.googlesource.com/chromium/src/+/5fae232be8229a0f23c9f95b3f4b04b66796d54b^!) Don't set bounds directly if the bounds change should be animated.
* [`40bfdb1`](https://chromium.googlesource.com/chromium/src/+/40bfdb1f85b227025e9c05e97a682ebc51afc844^!) Mark child windows as having content for SingleProcessMash.
* [`ad65833`](https://chromium.googlesource.com/chromium/src/+/ad65833e73af9f0f6731cd768c08a2475396ba41^!) Collect PIP position metric.
* [`c7aed8f`](https://chromium.googlesource.com/chromium/src/+/c7aed8f7586acef6c0ad422c602f20350817ad0a^!) Remove check that the component is running before installing.
* [`255758e`](https://chromium.googlesource.com/chromium/src/+/255758eccf3d244491b8a1317aa76e1ce10d57e9^!) Incrementing VERSION to 74.0.3729.6
* [`ea01c7c`](https://chromium.googlesource.com/chromium/src/+/ea01c7cddd02e48a4b8711768105e663efd5384f^!) expose ext float blend implicitly
* [`6bcf64b`](https://chromium.googlesource.com/chromium/src/+/6bcf64b73172d0f2f0ca354928c20f6117c3dc58^!) Fixed issue with a settings dropdown being disabled
* [`d5212ec`](https://chromium.googlesource.com/chromium/src/+/d5212ec29e65e06431fbc00bec4ff23c14ab87f5^!) WebUI Dark Mode: re-enable dark mode for User Manager
* [`929a1a8`](https://chromium.googlesource.com/chromium/src/+/929a1a8903be2fa89e6d29bf35d30fab61ff9241^!) Updating XTBs based on .GRDs from branch 3729
* [`233c6e1`](https://chromium.googlesource.com/chromium/src/+/233c6e17ea4aee8c6bee47ea43d2bcd6714c2504^!) WebUI Dark Mode: fix scrollable top/bottom border colors
* [`374c3be`](https://chromium.googlesource.com/chromium/src/+/374c3be6d17376e81dc9cbbbb1d32df5cca1db2b^!) CrOS Shelf: Hide the shelf a short time out after mouse leaves
* [`326a105`](https://chromium.googlesource.com/chromium/src/+/326a1052ae23f445ad539a6225afe42eb30eea6d^!) Reland "Reland "Fix black screen when navigating to somewhere after js alert dialog""
* [`0d3a49a`](https://chromium.googlesource.com/chromium/src/+/0d3a49a846d523fbb63bbdac32c8e0a13349b535^!) Add support for SetShape in Mash
* [`31d0cc4`](https://chromium.googlesource.com/chromium/src/+/31d0cc4110c24abd35118d4076faf61288c18d39^!) Replacing downloads backend with DownloadOfflineContentProvider
* [`cc61394`](https://chromium.googlesource.com/chromium/src/+/cc61394c1561758bd14fcb0839f1a3131d7b1670^!) [BGPT] Don't trigger a render surface for kDstIn blend modes with one layer
* [`626580e`](https://chromium.googlesource.com/chromium/src/+/626580e9087e7f40cda5b9069dbeb7b204e7122a^!) [iOS] Remove omnibox popup animations
* [`ee53471`](https://chromium.googlesource.com/chromium/src/+/ee53471afa5a0e3bc2a819a1ccd947c44065708f^!) [getUserMedia] Do not read experimental flag to determine system EC on source.
* [`6b6ba0a`](https://chromium.googlesource.com/chromium/src/+/6b6ba0ae14b588269df2cb4bdf3dcc4195637254^!) Merge to M74: Start adding dynamic isolated origins after password entry.
* [`23d65f1`](https://chromium.googlesource.com/chromium/src/+/23d65f19eb7f05464e2e28575a92a55765f571eb^!) Incrementing VERSION to 74.0.3729.5
* [`c3886b1`](https://chromium.googlesource.com/chromium/src/+/c3886b12d7c0abbf3571ed87055ce855477ce4fb^!) [Merge to M74] cros: Splash screen should be removed only after active session starts
* [`3493256`](https://chromium.googlesource.com/chromium/src/+/3493256a676db9d3bcf92f595b79a72970203067^!) Fix onCrostiniChanged Entry conversion
* [`b1759f3`](https://chromium.googlesource.com/chromium/src/+/b1759f3b20fec035c527d7037ca54619fa387e3b^!) [Merge] Add DataSaver Milestone Promo IPH
* [`233295b`](https://chromium.googlesource.com/chromium/src/+/233295b7a8dfed018f6ab5246ea4b393e4d47cc5^!) media/android: Ensure correct synchronization of video buffers.
* [`6c8a43f`](https://chromium.googlesource.com/chromium/src/+/6c8a43f3e486a17b2305724bcda98581a2c94340^!) Incrementing VERSION to 74.0.3729.4
* [`6b92167`](https://chromium.googlesource.com/chromium/src/+/6b921671634267b61401ccfec88529d4e669594e^!) [M74 merge] app_list: Show web ui in embedded Assistant view
* [`0facb2c`](https://chromium.googlesource.com/chromium/src/+/0facb2c6b68c5f2e7fec946bb169a51913d65b34^!) [M74 merge] app_list: Handle stylus in embedded Assistant Ui
* [`4df9c29`](https://chromium.googlesource.com/chromium/src/+/4df9c2978ca67a62137fb504d2542aa2f33c4bca^!) Update and fix GetRandomAvatarIconIndex()
* [`3d083e6`](https://chromium.googlesource.com/chromium/src/+/3d083e6391f2c2581fb1abbedd577525ecd44cc9^!) Incrementing VERSION to 74.0.3729.3
* [`4a4b5a7`](https://chromium.googlesource.com/chromium/src/+/4a4b5a74b597036d4227041e257f4b8aac545da5^!) Incrementing VERSION to 74.0.3729.2
* [`d0acfdb`](https://chromium.googlesource.com/chromium/src/+/d0acfdb1c16a7b7982bb89eaf4644091dd903e85^!) Updating XTBs based on .GRDs from branch 3729
* [`484993e`](https://chromium.googlesource.com/chromium/src/+/484993eac5c4fe7ed8f69a6ab76a0a2ea2b734e5^!) Update 3729 DEPS for M74 branching
* [`cb49154`](https://chromium.googlesource.com/chromium/src/+/cb491544d326079793afe22f3cb42b72fb57247a^!) Incrementing VERSION to 74.0.3729.1
* [`05469e6`](https://chromium.googlesource.com/chromium/src/+/05469e6a43c408e2577d840bc00e314748ba575d^!) Update DEPS for 3729 branching
* [`d4a8972`](https://chromium.googlesource.com/chromium/src/+/d4a8972e30b604f090aeda5dfff68386ae656267^!) [build] specify lower symbol level for x86/x64 simple chrome
* [`b46cb22`](https://chromium.googlesource.com/chromium/src/+/b46cb22b64b6ce00648834a342187c8474ab7a09^!) Detect ComputedStyle::IsRunningXXXAnimationOnCompositor changes
* [`c0b84f7`](https://chromium.googlesource.com/chromium/src/+/c0b84f74da8f49a56a45a642333ae359c008d36d^!) Reland "Use key bundle name instead of key handle for HKDF "info" parameter"
* [`2f7bf66`](https://chromium.googlesource.com/chromium/src/+/2f7bf668875154e25451ddd085c6b320962b07e4^!) Import wpt@8a14626934f5748a4ea6210847a02c0d8bbc8560
* [`2fd04ce`](https://chromium.googlesource.com/chromium/src/+/2fd04ce621b872f28018c2615c716baadc824c47^!) Update bounds if it is exiting minimized state.
* [`8a7976e`](https://chromium.googlesource.com/chromium/src/+/8a7976e8cc5ae72d6d2a2bf5f44e805b5245cb35^!) Move DCHECK for HTTPS Previews Reload Type
* [`2d53b4e`](https://chromium.googlesource.com/chromium/src/+/2d53b4e9f6df6f66f83adbf7a05a074dcf74f105^!) Implement UIA accessibility tree formatter
* [`11e6683`](https://chromium.googlesource.com/chromium/src/+/11e66833d7901fd298834204e40ed43380112724^!) [Files app] Fix MyFiles to auto expand only once
* [`32112ef`](https://chromium.googlesource.com/chromium/src/+/32112ef8f3a959567cca56c47ff81a8fb4fec778^!) Add histogram for UIA GetPropertyValue
* [`3ce8191`](https://chromium.googlesource.com/chromium/src/+/3ce81911d0713e52f6fc1b222ce0165b8c5dbacc^!) [LayoutNG] Stop NGPaintFragment to inherit from ImageResourceObserver
* [`a70a5bd`](https://chromium.googlesource.com/chromium/src/+/a70a5bd2be13bdda5333c3291339acb4eef42efa^!) Roll Fuchsia SDK from 9216f29f7750 to d09ea1353373
* [`5103458`](https://chromium.googlesource.com/chromium/src/+/51034587a7bc62ebf7baddc25c269889036dfc98^!) Crostini multi-profile fix for shelf spinners
* [`86a0357`](https://chromium.googlesource.com/chromium/src/+/86a03575cbaaaeab45764b679e69ef32d2817eb1^!) Change UpdateHoverReason to be an enum class.
* [`e7001e7`](https://chromium.googlesource.com/chromium/src/+/e7001e77a1b3488cf80b01e03568cefb970f5ffe^!) Revert "[Animation Worklet] Remove unnecessary force composition"
* [`3fd51ca`](https://chromium.googlesource.com/chromium/src/+/3fd51ca8e3f4fbe1bba7858c02ce4962cca25453^!) [LayoutNG] Remove NGPaintFragment::{Next,Last}
* [`860047a`](https://chromium.googlesource.com/chromium/src/+/860047ad6754da240046f4e4ede56154962df7c0^!) Roll src/third_party/chromite 0db96d1aa896..28dfd94b57ae (2 commits)
* [`dd68861`](https://chromium.googlesource.com/chromium/src/+/dd68861bbd3aabf721ea4f57e6372f9d104da6fd^!) [layoutng] Avoid copying vectors when passing arguments
* [`2f40eac`](https://chromium.googlesource.com/chromium/src/+/2f40eac36b0b35834442243c9b63ea70b571a0d9^!) [iOS][Translate] Fixes translate infobar's options menu misalignment bug
* [`0400f3a`](https://chromium.googlesource.com/chromium/src/+/0400f3abcb28bdce97ae34213c96f943918acdea^!) Shut down PowerManagerClient in a few tests.
* [`e6da851`](https://chromium.googlesource.com/chromium/src/+/e6da851a9edeaacf6d794521ea45c5a0dc8b6dde^!) fixup! BlinkMemoryMgt: Annotate Blink's platform/scheduler with the macros of Allocator
* [`31f5170`](https://chromium.googlesource.com/chromium/src/+/31f5170fe1813113c5bfe4bc67c3c83bf1c713fe^!) Hook the TabStrip UI to the BottomControls component
* [`9bbe1d8`](https://chromium.googlesource.com/chromium/src/+/9bbe1d88412b70a2f6b0e23073e32d4522cfad65^!) Support keyboard users in reopen tab in-product help
* [`96e4f4c`](https://chromium.googlesource.com/chromium/src/+/96e4f4c7a07d1007e61700b93b0d664eb2a5af05^!) GWP-ASan: Correct free-invalid-address handling
* [`ddeccbd`](https://chromium.googlesource.com/chromium/src/+/ddeccbdb8361201a7755c66d35832c4ca10608b8^!) Add default_site_instance_ to BrowsingInstance.
* [`ad07622`](https://chromium.googlesource.com/chromium/src/+/ad07622787124b5dda719acae811c332a3723578^!) splitview: Fix animation parameters for the drag indicator labels.
* [`e5c31e4`](https://chromium.googlesource.com/chromium/src/+/e5c31e4d0b83cdef4a4eadb2e60291c3fa4037d0^!) Implement CompositorAnimationHandlerTest (migration to CompositorAnimator, part 5)

_Originally posted by @roller-bot in https://github.com/electron/electron/pull/17368#issuecomment-472411927_

**Comment by nornagon** [comment]
```
In file included from gen/content/browser/browser_jumbo_1.cc:34:
.\../../content/browser/accessibility/accessibility_tree_formatter_win.cc(40,8): error: redefinition of 'HwndWithProcId'
struct HwndWithProcId {
       ^
.\../../content/browser/accessibility/accessibility_tree_formatter_uia_win.cc(38,8): note: previous definition is here
struct HwndWithProcId {
       ^
In file included from gen/content/browser/browser_jumbo_1.cc:34:
.\../../content/browser/accessibility/accessibility_tree_formatter_win.cc(46,15): error: redefinition of 'EnumWindowsProcPid'
BOOL CALLBACK EnumWindowsProcPid(HWND hwnd, LPARAM lParam) {
              ^
.\../../content/browser/accessibility/accessibility_tree_formatter_uia_win.cc(44,15): note: previous definition is here
BOOL CALLBACK EnumWindowsProcPid(HWND hwnd, LPARAM lParam) {
              ^
In file included from gen/content/browser/browser_jumbo_1.cc:34:
.\../../content/browser/accessibility/accessibility_tree_formatter_win.cc(57,6): error: redefinition of 'GetHwndForProcess'
HWND GetHwndForProcess(base::ProcessId pid) {
     ^
.\../../content/browser/accessibility/accessibility_tree_formatter_uia_win.cc(55,6): note: previous definition is here
HWND GetHwndForProcess(base::ProcessId pid) {
     ^
3 errors generated.
```

**Comment by deepak1556** [comment]
I missed to check the release when the fix was available https://bugs.chromium.org/p/chromium/issues/detail?id=939668. Looks like it only got into 75.0.3732.0. We should backport it, then again 74 builds are boken shouldn't upstream backport the fix to that line as well ?

**Comment by deepak1556** [comment]
The commit that fixes the jumbo build failure made it in this release, should be good to merge once the builds are done.

[`f6669b3`](https://chromium.googlesource.com/chromium/src/+/f6669b3f17ae8e9f9b12217baafe8bf216b45285^!) [M74] Backported fix for jumbo compilation in new accessibility code (again)

**Pull request merged**
