### PR TITLE
Refactor remote.js / rpc-server.js implementation

### PR DESCRIPTION
**Pull request by miniak**
- move all the logic to `remote.js` / `rpc-server.js`
- use `KeyWeakMap` to report objects being GCed
- remove `setRemoteCallbackFreer` / `setRemoteObjectFreer`
- send `ELECTRON_BROWSER_DEREFERENCE` / `ELECTRON_RENDERER_RELEASE_CALLBACK` from JavaScript

### CODE REVIEW

**Comment by codebytere** [comment]
@miniak can you rebase this on latest `master` to fix Ci errors?

**Comment by zcbenz** [comment]
@miniak V8 does not support calling JavaScript code from a weak callback, V8 does not explicitly forbid it (abort or DCHECK), but doing that will crash randomly.

We were actually doing similar things with this PR years ago, until we encountered crashes from V8 (https://github.com/electron/electron/issues/5239) and had to move to use native code (https://github.com/electron/electron/pull/5293).

So while this is a very good refactoring, we can not merge it.

**Comment by miniak** [comment]
@zcbenz good to know. Wasn’t the issue previously that the callback was being invoked directly from the GC callback? I am dispatching an async call on the main thread to do it later, which could actually make it safe.

**Comment by zcbenz** [comment]
@miniak We have to send the message immediately when the GC happens, otherwise we would have race conditions. Discussions can be found at https://github.com/electron/electron/commit/06cf0406fe8ddcef3a500a689952c77fdfb9c9a8#comments, https://github.com/electron/electron/issues/4733#issuecomment-198197090, https://github.com/electron/electron/pull/4869.

I don't have a simple way to reproduce the crash, it happened in a rather non-deterministic way. But since V8 explicitly documents we should not use V8 API in GC callback, and we have to send the message immediately in the GC callback, I think there is no way for us to simplify the implementation with JavaScript.

**Pull request closed without merging**
