### PR TITLE
app: api to import client certificate

### PR DESCRIPTION
**Pull request by deepak1556**
Ref #1956 

```
app.importClientCertificate(options, function(result) {
  // app logic
})

* options
  * clientCertificate - pkcs12 file
  * password
```
A few thoughts with implementation
* Currently the trust bits for the CA certs are set by the api internally otherwise certificate verification will fail for untrusted. Should this be exposed as another api and let users set the trust bits ?

* Does the current options object serve all purposes for client certificate import ? Or is there any other format users would like to provide ?

* The api is implemented only for linux, for other platforms chromium invokes the platform certificate manager whose implementation can be found in [settings_utils::ShowManageSSLCertificates](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/webui/settings_utils.h&l=24). I dont have access to other platforms to test and implement, so would like some help in this area.

\cc @kjlaw89

### CODE REVIEW

**Comment by kjlaw89** [comment]
Looks good to me. I'm not sure by looking at the code though - does it store the certificate in the system's certificate store, or just import it for use during the current lifecycle of the application?

I'm all for the latter if that's possible, but I understand if it's only possible to do the former. If you could do both though it would be pretty cool to have a flag to control it.

Thanks again for looking into this!

**Comment by deepak1556** [comment]
> does it store the certificate in the system's certificate store, or just import it for use during the current lifecycle of the application?

it imports to the platform certificate store, currently its not possible to do the latter.

**Comment by kjlaw89** [comment]
That's fine with me then. Will it handle duplicate certificates okay, or will there need to be checks in place to prevent duplicates?

**Comment by deepak1556** [comment]
> Will it handle duplicate certificates okay, or will there need to be checks in place to prevent duplicates?

the platform certificate manager will handle it

**Comment by zcbenz** [comment]
It seems that the API doesn't only work for client certificate, should we rename it to `app.importCertificate`? Other parts look perfect to me.

**Comment by deepak1556** [comment]
yeah `importCertificate` sounds better, fixed thanks! regarding the trust bits, the api only sets the SSL bits to trusted. Should the api handle it automatically or let the users do it with another api ?

**Comment by zcbenz** [comment]
I think it is fine to set the trust bits automatically.

**Pull request merged**
