### PR TITLE
build: [gn] widevine cdm support behind flag

### PR DESCRIPTION
**Pull request by deepak1556**
##### Description of Change

Fixes https://github.com/electron/electron/issues/14227
Depends on https://github.com/electron/libchromiumcontent/pull/671

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: fix widevine cdm not loading content

### CODE REVIEW

**Comment by codebytere** [comment]
\trop backport-to 3-0-x

**Comment by deepak1556** [comment]
@codebytere this can't be backported because of GN related changes, I will create a separate PR for 3.x with minimal changes that fixes the issue.

**Comment by nornagon** [comment]
Love removing chromium_src files 😍

**Pull request merged**
