### PR TITLE
docs: update Ubuntu version used for Linux prebuilt binaries

### PR DESCRIPTION
**Pull request by dsanders11**
#### Description of Change

These are now being built on 20.04, and 18.04 is going EOL in April.

#### Checklist

- [x] PR description included and stakeholders cc'd
#### Release Notes

Notes: none

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Comment by Aameen5** [comment]
[](url)https://www.absher.sa/portal/landing.html

**Comment by cobalt2727** [comment]
> These are now being built on 20.04, and 18.04 is going EOL in April.

This appears to be a mistake - Ubuntu 18.04's EoL hits in April **2023**, not this year. Please revert it at your earliest convenience.

**Comment by dsanders11** [comment]
@cobalt2727, you're right that was a mistake. However, this PR was still functionally correct, the prebuilt binaries are built on Ubuntu 20.04.

**Comment by cobalt2727** [comment]
Is there an ETA as to when packages prebuilt on 18.04 will be available again?

**Comment by dsanders11** [comment]
@cobalt2727, I think there's some confusion, the packages are prebuilt on 20.04 (and this will remain true going forward), but are verified to work on 14.04 and other Linux distros.

Are you seeing an issue you're trying to resolve?

**Comment by dsanders11** [comment]
@cobalt2727, I see. Let's keep discussion on that issue. This PR was just a docs update and is long since merged.

**Pull request merged**
