### PR TITLE
chore: synchronously destroy WebContents on event prevented

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Trying this out to see if CI breaks. From my reading of the Chromium code it should be ok.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by zcbenz** [comment]
This was introduced by https://github.com/electron/electron/pull/9113, since the tests passed it would be fine. /cc @deepak1556

**Review by deepak1556 — APPROVED** [review]
I originally wanted to keep all top level webContent destruction async and this was added along side. Sounds good to have this sync when the webContents is not exposed to the user.

**Comment by nornagon** [comment]
I think it's important for this to be sync because it prevents `window.open` from returning a window that's then destroyed (instead it'll return `null`).

**Review by zcbenz — APPROVED** [review]

**Comment by mlaurencin** [comment]
@nornagon [This issue](https://github.com/electron/electron/issues/26133) was fixed when I applied this commit locally to 10, so I think this would be good to backport to 9, 10, and 11 as well.

**Pull request merged**
