### PR TITLE
fix: silent print settings

### PR DESCRIPTION
**Pull request by codebytere**
Backport of #31489.

See that PR for details.

Notes: Fixed an issue which caused print settings to not work properly when printing silently.

### CODE REVIEW

**Comment by Hedwig188** [comment]
I tested the fix in v16.0.0-beta.6. It looks like the header is not being respected, but the rest of the settings are.
It always print the header with the window's title.

Is there any way to workaround this?

Test code:
```
(async () => {
  const {app, BrowserWindow} = require("electron");

  await app.whenReady()

  const window = new BrowserWindow();
  await window.loadURL("https://www.electronjs.org/")
  window.webContents.print(
    {
      header: "I am header",
      footer: "I am footer",
      deviceName: "Microsoft Print to PDF",
      landscape: true,
      silent: true,
    });
})();
```

**Comment by Hedwig188** [comment]
Looks like setting the document.title using the js before printing would be the workaround.
`await window.webContents.executeJavaScript("document.title = 'I am header'")`

**Comment by sunchanglong** [comment]
pageSize not work in all electron version. I have test electron version [8.x - 16.0.0-beta.6]
 #31705

**Comment by sunchanglong** [comment]
@codebytere , could you confirm if #31705 is a bug first?

**Pull request merged**
