### PR TITLE
test: clean up some stale code in renderer spec runner

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Just stuff that wasn't used any more.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by zcbenz** [comment]
I think the crash is caused by the removal of `protocol.registerSchemesAsPrivileged` call.

**Comment by nornagon** [comment]
Hm... I'm not sure I understand why removing that call would cause a crash in `legacy_cache_storage_manager.cc`. Can you explain your reasoning? Restoring the call doesn't seem like the right fix if that's the case.

**Comment by zcbenz** [comment]
Certain code in Chromium used to assert whether the origin of URL has privileges, and if we did not call `protocol.registerSchemesAsPrivileged` for the custom protocols, some operations would crash Chromium. That is why the `protocol.registerSchemesAsPrivileged` call was added.

The crash in Windows CI looks very similar to what we saw:
```
[6088:1210/193848.572:FATAL:legacy_cache_storage_manager.cc(170)] Check failed: !origin.GetURL().is_empty(). 
```

But it might be unrelated though.

**Comment by nornagon** [comment]
The renderer specs no longer use any custom schemes, though.

**Comment by nornagon** [comment]
Did some more investigation, it looks like the crash happens when reading info from the service worker cache. On my machine, the crash happens after reading this file:

```
/Users/nornagon/Library/Application Support/Electron Test/Service Worker/CacheStorage/33300f42568342e80d69cb8f0f8781d2c70179ad/index.txt
```

which contains a protobuf, and the string `app://fake-host/`. That URL is used in many of our other tests, so probably one of those tests is creating this index file and filling it with data that the renderer tests crash on.

Clearing out the user-data directory for the test app fixes the issue.

**Pull request merged**
