### PR TITLE
move window z-order top with out focus

### PR DESCRIPTION
**Pull request by MadfishDT**
Tested Window7 ,  10
os: window7,10 , Mac
API: BrowserWindow.moveTop()
Desc: move window to top position without focus
Usage: notification and show message

### CODE REVIEW

**Comment by ckerr** [comment]
@alexeykuzmin :+1:

**Comment by MadfishDT** [comment]
thanks for comments. I will add document and I will make code for linux

**Comment by MadfishDT** [comment]
somebody help, i do not know how to fix this error

crashReporter module with sandbox should send minidump when renderer crashes - should send minidump when renderer crashes
/home/builduser/project/spec/api-crash-reporter-spec.js

**Comment by MadfishDT** [comment]
close this pull request,
move this request to master branch

**Pull request closed without merging**
