### PR TITLE
fix: bad assertion in crypto functions that use BN_bn2bin_padded

### PR DESCRIPTION
**Pull request by nornagon**
in particular, this picks up electron/node#70a78f07b, which fixes an issue with incorrect usage of the BN_bn2bin_padded API in boringssl. This also adds tests to make sure those functions are fixed.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an assertion when calling `ECDH.getPrivateKey()`, `diffieHellman.generateKeys()` or `diffieHellman.get*()`.

### CODE REVIEW

**Comment by nornagon** [comment]
This will need a manual backport to 4 and 5.

**Comment by codebytere** [comment]
arm error seems to be:
> `type.toLowerCase`
🤔

**Comment by deepak1556** [comment]
@nornagon any reason this needs backport to 4.x ? AFAIK the changes on electron/node only made it to electron 5.x branch.

**Comment by nornagon** [comment]
ack, you're right, no need for 4.

**Pull request merged**
