### PR TITLE
feat: enable sandbox by default

### LINKED ISSUE #28466: [Feature Request]: Enable `sandbox: true` by default for `BrowserWindow`
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Since Electron v5 the default behavior of `BrowserWindow` is to create it with `nodeIntegration: false`. In v12 `contextIsolation` was turned on as well (see #23506). Another default that Electron should have is `sandbox: true`.

### Proposed Solution

I'd like the defaults of creating a new `BrowserWindow` to be equivalent to the following:

```js
const mainWindow = new BrowserWindow({
  webPreferences: {
    nodeIntegration: false,
    contextIsolation: true,
    sandbox: true
  }
);
```

### Alternatives Considered

No alternatives considered. As @MarshallOfSound said in #23506:

> We're making this change to improve the **default** security of Electron apps so that your app is only insecure if you have deliberately opted in to the insecure behaviour.

### Additional Information

Happy to dig and try to find any data needed to make a decission.

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Closes #28466.

This enables `sandbox: true` by default unless `nodeIntegration: true` is
specified. This is a non-breaking change because without `nodeIntegration:
true`, there's no documented way to perform any action that would cause
different behavior depending on whether the sandbox is enabled or not.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Renderer processes without node integration enabled are now sandboxed by default.

### CODE REVIEW

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
This is most definitely a breaking change, `nodeIntegration: false` still has NodeJS in preload scripts.  Defaulting to `sandbox: true` will break preload script that utilize node.js

**Comment by nornagon** [comment]
@MarshallOfSound do you have thoughts about how we can approach making this the default?

perhaps a phased deprecation:

1. If `preload` is empty and `nodeIntegration` is false or unspecified, enable sandbox by default.
2. If `preload` is non-null and `nodeIntegration` is false or unspecified, and `sandbox` is unspecified, warn that the default will be changing.
3. Enable sandbox by default when `nodeIntegration` is false or unspecified (i.e. this PR)

**Comment by MarshallOfSound** [comment]
> If preload is empty and nodeIntegration is false or unspecified, enable sandbox by default.

I think you also have to care about `nodeIntegrationInSubFrames` and `nodeIntegrationInWorkers` too, in general I think those three steps if sufficiently documented are a viable path to enabling sandbox by default.

**Comment by nornagon** [comment]
Is it the case that `nodeIntegrationIn(SubFrames|Workers): true` w/o `nodeIntegration: true` has an effect? that seems odd, that you'd be able to enable node integration in subframes/workers without it being enabled in the main frame, but uh, if so, then sure.

**Comment by nornagon** [comment]
Closing in favor of #30197

**Pull request closed without merging**
