### PR TITLE
docs: missing instructions for installing electron in first-app.md

### PR DESCRIPTION
**Pull request by ericchase**
#### Description of Change
The 'Electron Development in a Nutshell' section seems to require 
`electron` to be installed globally. I have added instructions to do 
so in the 'Installing Electron' section.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by malept** [comment]
Hi @ericchase, in this tutorial, all you should need is to install Electron within the Node.js project that the docs describe. 

It would be greatly appreciated if you could help us understand the process you went through that led you to installing Electron globally, so that we can pinpoint the parts of this doc that could be clarified for future users.

**Comment by ericchase** [comment]
I've only added some documentation, so this seems to be an external build issue.

**Comment by ericchase** [comment]
> 
> 
> Hi @ericchase, in this tutorial, all you should need is to install Electron within the Node.js project that the docs describe.
> 
> It would be greatly appreciated if you could help us understand the process you went through that led you to installing Electron globally, so that we can pinpoint the parts of this doc that could be clarified for future users.

Oh, it seems I confused the sections. The 'Writing Your First Electron App' section describes the process of turning a Node application into an Electron application. Therefore, the issue is not with 'Electron Development in a Nutshell' as I have written. That was a mistake.

**Comment by ericchase** [comment]
Let me submit a new PR with the corrected details.

**Pull request closed without merging**
