### PR TITLE
Functions returned from the backend to the frontend now get reference…

### PR DESCRIPTION
**Pull request by karvapallo**
…d correctly when passed back

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@karvapallo Can you please explain what this does / what it fixes.  It is not obvious what this is intended to fix by the commit message or the change itself. ❓

**Comment by karvapallo** [comment]
Sure thing. 

If a function on the backend returns a another function, and we want to call or pass said function from the frontend back to the backend, this would not work without this fix. 

The backend is correctly assigns an 'atomId' to the returned function, but the frontend part in question, would ignore it, and instead assume that we are passing back a function created on the frontend (say a callback), which would then no longer have the correct reference to the backend function (it was not interpreted as a 'remote-object', even though it was).

**Comment by MarshallOfSound** [comment]
@karvapallo Is it possible to add a spec demonstrating this scenario, I think I understand what you mean.  It would be good to add a spec to ensure this isn't modifed / broken at some point 👍

**Comment by karvapallo** [comment]
@MarshallOfSound I'll take a look at making one for you tomorrow when I'm back at work. I'm guessing I can find examples of how you are testing the remote module somewhere in the repo?

**Comment by paulcbetts** [comment]
> If a function on the backend returns a another function, and we want to call or pass said function from the frontend back to the backend, this would not work without this fix.

When you say "Backend" you mean, "Main process" and when you say "Frontend", you mean "Window process" right?

**Comment by karvapallo** [comment]
@paulcbetts yes that is correct.

So when a main process method, that returns a function, is passed via remote to the renderer (window) process and called there, the returned function loses it's reference on the main process without this fix. 

The system currently thinks that it's a callback function passed from the renderer process.

**Comment by karvapallo** [comment]
I'm having issues trying to get the tests running on my work comp. And I really don't want to screw up my dev env by installing other versions of electron, node and python.

Is there any way one of you guys could try and do a test on this? If you have a working setup where you can run the tests, it should be fairly easy. 

Here's an example on how to reproduce the issue.

Main process:

someFunc.js
```javascript
let someFunc = function someFunc() {
    this.retFunc = function retFunc() {
        return function myTestFunction() {
            return 'foobar';
        }
    };
    this.passMeTheRetFunc = function passMeTheRetFunc(passedFunc) {
        console.log('calling passed func: ', passedFunc());
    };
};

module.exports = new someFunc();
```
On the window (renderer) process:

```javascript
let someFunc = remote.require('./backend/someFunc.js');
let returnedFunc = someFunc.retFunc();
someFunc.passMeTheRetFunc(returnedFunc);
```

Without this fix, the main process will print out 'undefined' if you add this fix, it will find the correct reference to myTestFunction and print out 'foobar'.

Thanks!

**Comment by zcbenz** [comment]
I'm closing this since no one is picking up the remaining work.

**Comment by karvapallo** [comment]
@zcbenz what would I need to do to have someone take another look at this.

I provided a solutions, I provided a test case, what else do you need?

Our whole main process lib is based on returning other functions from function calls, and the lib is basically a singleton, and must be shared among all the renderer processes. Without this fix the `remote` module is not very useful to us.

**Pull request closed without merging**
