### PR TITLE
Document what APIs will break in Electron 2.0

### PR DESCRIPTION
**Pull request by kevinsawicki**
Even though 1.0 was recently released and 2.0 probably won't be for awhile, I've started a document for the things we've already renamed (but kept around the old names) since 1.0 and marked for 2.0 removal.

The goal of the `API.md` document is to explicitly list the planned breakage so you don't have to grep the code base or `TODO` comments for what is going away in 2.0.

It also explicitly commits to at least a 90-day deprecation window before 2.0 so people will see logged warnings similar to the lead up to the 1.0 release.

/cc @electron/maintainers

### CODE REVIEW

**Comment by zeke** [comment]
What about a table?

Old | New
--- | ---
`clipboard.readRtf()` | `clipboard.readRTF()`

**Comment by kevinsawicki** [comment]
> What about a table?

Yeah, I like that but you can't do syntax highlighted blocks in tables (as far as I know) and longer examples would wrap.

**Comment by kevinsawicki** [comment]
> What about a table?

And we couldn't have multiple line examples

**Comment by zeke** [comment]
Got it. Is there a particular reason not to put this file in `/docs` and give it a more explanatory name?

**Comment by kevinsawicki** [comment]
> Got it. Is there a particular reason not to put this file in /docs and give it a more explanatory name?

Great point, putting it in under `tutorial/` so it ends up under the Guides section on the site 👍

**Pull request merged**
