### PR TITLE
chore(extensions): remove old renderer code

### PR DESCRIPTION
**Pull request by samuelmaddock**
#### Description of Change

Remove old renderer code used for JavaScript-based Chrome extensions.

The affected files were removed from the bundle in #23340, but never deleted.

Ref #19447

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by zcbenz — APPROVED** [review]

**Comment by nornagon** [comment]
@miniak Why backport this? it's just a cleanup, I don't think it's doing any harm in older branches.

**Comment by miniak** [comment]
@nornagon I ran into those dangling files when back-porting the IPC change.

**Pull request merged**
