### PR TITLE
Fix Korean grammatic mistakes

### PR DESCRIPTION
**Pull request by ssu2030**
1. Fix Mistranslation

- There was a mistranslation in the Core Philosophy part
  Philosophy has many meanings in Korea. It was used korea in the sense
   of like 'the philosophy of jung' = '철학'

- It seems to be right to modify the meaning of 'Ideology' = '이념'
  The '핵심' rather than the '중심' is more appropriate in Korean.

- '지원하지 않습니다.' more appropriate than '빠집니다'

2. Sentence Spacing

-  '그후에' should be changed to '그 후에'. It is a Korean grammar error

Signed-off-by: Dongho Lee <ssu2030@naver.com>

### CODE REVIEW

**Comment by ssu2030** [comment]
Why was my request rejected?

**Comment by codebytere** [comment]
Nobody rejected it? Please see https://github.com/electron/electron/pull/11023#issuecomment-342182621

**Comment by ssu2030** [comment]
@codebytere
I'm sorry if it sounded rude.
Thank you for your advice.

**Comment by ckerr** [comment]
Thank you for your translation!

We've recently [moved](https://github.com/electron/electron/blob/master/docs-translations/README.md)  our translations to [Crowdin](https://crowdin.com/projects/electron) to make it easier for contributors to make changes. Please feel encouraged to make the correction there!

I'm going to close this pull request, though, because as a result of the change there is no longer a `docs-translations/ko-KR/tutorial/about.md` to patch.

**Pull request closed without merging**
