### PR TITLE
fix: `desktopCapturer` and `screen` source ids should match screen ids

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/42747.

Fixes an issue where sources returned by the `desktopCapturer` API and by `screen.getAllDisplays()` no longer match on Windows. This happened initially as a result of https://chromium-review.googlesource.com/c/chromium/src/+/5362362, which removed the static helper we were previously using and required that the id be derived from `HMONITOREX`. The ids are specifically intended and expected to match, so this created a problem for developers needing this information to be kept consistent. To fix this, we need to do a bit more work unfortunately and get that `HMONITOREX` information ourselves in order to derive the correct id.

Confirmed to produce expected results via https://gist.github.com/bukharin/7e4c4d61c9569e57de2183076d2808f9

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where sources returned by the `desktopCapturer` API and `screen.getAllDisplays()` no longer matched on Windows.

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
Is this something we can test for? Assert that each ID is findable in the other apis array?

**Review by jkleinsc — CHANGES_REQUESTED** [review]
Newly added test fails on Windows.

**Comment by codebytere** [comment]
@jkleinsc it seems like the reason we didn't have tests for this in the first place - we can't guarantee sources in CI it doesn't seem :( I think we just need to proceed without the test unfortunately.

**Review by jkleinsc — APPROVED** [review]

**Review by VerteDinde — APPROVED** [review]

**Comment by VerteDinde** [comment]
Stuck on old CircleCI lint check, overriding to merge

**Comment by clavin** [comment]
Beware: Win32 `EnumDisplayMonitors` is a bit of a double-edged sword. If the user changes their displays (adds/removes) in the middle of its execution, we might end up with incomplete data. (I recently fixed an [issue in Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/5353255) based on that discovery.)

**Pull request merged**
