### PR TITLE
Update korean docs, according to most recent changes and other missing.

### PR DESCRIPTION
**Pull request by tinydew4**

### CODE REVIEW

**Comment by zeke** [comment]
@tinydew4 we are using [`standard`](http://standardjs.com/) style JavaScript everywhere in the codebase now, including markdown js snippets. If you'd be willing to standardize these code snippets, it would be appreciated. To help in that process, try running this:

```sh
cd electron/electron
npm install
./node_modules/.bin/standard-markdown docs-translations/ko-KR 
```

There's a PR in the works that will introduce a `--fix` flag to help automate some style fixes. See https://github.com/zeke/standard-markdown/pull/5 for progress on that.

**Comment by tinydew4** [comment]
Thanks kind help @zeke .
Fixed all syntax errors.

**Comment by tinydew4** [comment]
I apply recent changes.

**Comment by kevinsawicki** [comment]
Thanks 👍

**Pull request merged**
