### PR TITLE
Fix remote.getGlobal return type description

### PR DESCRIPTION
**Pull request by tong**
There exists no type of `any`, should be object.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
It doesn't always return an object though?  I personally went with "any" as it fits with the return type (literally anything, could be a function, number, Etc.).  And it's what other syntax use to describe unknown variable types (such as Typescript)

**Comment by tong** [comment]
I am working on auto generation of type descriptions for haxe and this creates an unnecessary [patch](https://github.com/tong/hxelectron/blob/generate-externs/Run.hx#L216) and [type](https://github.com/tong/hxelectron/blob/generate-externs/src/electron/Any.hx). Also it's the only occurrence in all docs where a non existing type is used.

**Comment by MarshallOfSound** [comment]
I am unfamiliar with have but if we change it to object it will technically be incorrect.

Also changing will result in a manually patch for other syntax's (typescript).

I still feel "any" is the best description of a return type that literally could be anything.  Does haxe have an equivalent type for "anything"?

**Comment by tong** [comment]
It's mapped to haxe 'Dynamic' therefore working as no type checks are made, still not correct since it's the only place where a fictional type description (which doesn't exists in js either) is used.

**Comment by MarshallOfSound** [comment]
We somehow need to indicate it's return value is "anything".  `Object` is just incorrect and you have to somehow map it to `Dynamic` anyway in your haxe definition.

I'm reasonably convinced this should stay as is
/cc @zeke

**Comment by zeke** [comment]
> I still feel "any" is the best description of a return type that literally could be anything.

I agree with this ☝️ 

@tong I think your best option is to rename instances of `any` to whatever works best for your purposes.

**Comment by tong** [comment]
Cannot agree but ok, we can easily workaround this. Thanks.

**Pull request closed without merging**
