### PR TITLE
Support nativeWindowOpen from <webview> tags

### LINKED ISSUE #9556: Crash using nativeWindowOpen from <webview>
* Electron version: 1.7.1
* Operating system: macOS

### Expected behavior

`window.open` works from a `<webview>` tag with `nativeWindowOpen` enabled.

### Actual behavior

Crashes with the following:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 000000010f78c000-000000010f78d000 [    4K] r-x/rwx SM=COW  /Users/USER/*/Electron.app/Contents/MacOS/Electron

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libcontent.dylib              	0x0000000115cd8327 content::WebContentsImpl::CreateNewWindow(content::SiteInstance*, int, int, int, content::mojom::CreateNewWindowParams const&, content::SessionStorageNamespace*) + 759
1   libcontent.dylib              	0x0000000115a55bce content::RenderFrameHostImpl::OnCreateNewWindow(int, int, int, content::mojom::CreateNewWindowParams const&, content::SessionStorageNamespace*) + 206
2   libcontent.dylib              	0x0000000115be6102 0x11559f000 + 6582530
3   libcontent.dylib              	0x0000000115be6537 0x11559f000 + 6583607
4   libbase.dylib                 	0x0000000112aae140 base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 288

```

### How to reproduce

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
      webview {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
      }
    </style>
  </head>
  <body>
    <webview src="./wv.html" allowpopups webpreferences="nativeWindowOpen=yes" nodeintegration></webview>
  </body>
</html>
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    test
    <script>
      window.open()
    </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by kevinsawicki**
Support setting `webpreferences="nativeWindowOpen=1"` on `<webview>` tags.

- [x] Don't crash when using `nativeWindowOpen` on a `<webview>` tag
- [x] Return `null` from native `window.open` when called from a `<webview>` tag that does not have `allowpopups` set
- [x] Add more specs

Refs #8963 
Fixes #9556

### CODE REVIEW

**Comment by snene** [comment]
@kevinsawicki Thanks, I noticed that this change is merged and is available as part of Electron beta 1.7.2. I am currently trying it out, but not working for me as expected.

I just wanted to understand the exact steps that are needed if I want to call native window.open and window.document.write from the pages loaded in webview. Here is what I understand:

1. Create the BrowserWindow with nativeWindowOpen set to true as follows:
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nativeWindowOpen: true
    }
})
2. The BrowserWindow will load a html page with a webview with nativeWindowOpen set to true as follows:
<webview id="webview" webpreferences="nodeIntegration=no, nativeWindowOpen=true" allowpopups></webview>

My questions are:
1. Is it still needed to handle new-window event in the BrowserWindow and return the newly created  window as event.newGuest?
2. When the guest page calls window.open, does it still get BrowserWindowProxy as return object? I am assuming not, because I want to call window.open and then window.document.write on that window.

Please refer to my issue #9515  for the sample code of what I want to do. Thanks a lot for your continued support!

**Comment by kevinsawicki** [comment]
> Is it still needed to handle new-window event in the BrowserWindow and return the newly created window as event.newGuest?

You are not required to override the `newGuest` from the `new-window` event unless you want to customize the created window.

> When the guest page calls window.open, does it still get BrowserWindowProxy as return object? 

It returns a regular `Window` object similar to Chrome

**Comment by snene** [comment]
Thanks for the quick reply @kevinsawicki ! So it's ok if I don't handle new-window event and create a new window? It should just work! But I need "allowpopups" to be set on the webview, correct?

I am asking these questions because I am trying it out and still not working for me.

**Comment by kevinsawicki** [comment]
>  So it's ok if I don't handle new-window event and create a new window?

Yes, it should be fine, the docs show it just as an example for creating a truly modal window.

>  But I need "allowpopups" to be set on the webview, correct?

Yes, `window.open` will return `null` unless `allowpopups` is set.

> I am asking these questions because I am trying it out and still not working for me.

Can you post some example code that isn't working for you? Thanks.

**Comment by snene** [comment]
Thanks! Actually, my original example code is in issue #9515

**Comment by kevinsawicki** [comment]
> Thanks! Actually, my original example code is in issue #9515

Could you post your current code that is still failing for you on 1.7.2?

**Comment by snene** [comment]
Sample code is as follows:
Main app:

```
const {app, BrowserWindow, ipcMain} = require("electron")

let win = null

app.on('ready', () => {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nativeWindowOpen: true
    }
  });
 win.loadURL('./MyWindow.html');
  win.on("closed", () => {
    win = null
});

```
MyWindow.html:

```
<html>
  <body>
        <div class="mainView">
            <webview id="webview" style="height:100%" src="about:blank"  webpreferences="nodeIntegration=no, nativeWindowOpen=true" allowpopups></webview>
        </div>
    </div>
    <script src="../src/js/ClientShell.js"></script>
  </body>
</html>
```

ClientShell.js

```
const BrowserWindowR = require('electron').remote.BrowserWindow;

 webview.addEventListener('dom-ready', () => {
    webview.loadURL('Print.html');
});
```


Print.html has code which open a window like following:

```
var printWin = window.open("", "_blank");
printWin.document.open();
printWin.document.write(<some html text>);
printWin.document.close();
```

I see that the printWin.document.open still fails with the error "TypeError: Cannot read property 'open' of undefined". This is happening because window.open is still returning BrowserWindowProxy and so printWin is set to type BrowserWindowProxy which does not have "document" defined on it.

@kevinsawicki can you please look into it?

**Comment by kevinsawicki** [comment]
>  <webview id="webview" style="height:100%" src="about:blank"  webpreferences="nodeIntegration=no, nativeWindowOpen=true" allowpopups></webview>


`nativeWindowOpen` needs to be `yes` or `1` to be enabled. Can you try:

```html
 <webview id="webview" style="height:100%" src="about:blank"  webpreferences="nodeIntegration=no, nativeWindowOpen=yes" allowpopups></webview>
```

**Comment by snene** [comment]
Yesssss, that worked! This is awesome. It just solved one of our biggest issue. Thanks a lot @kevinsawicki for all the help and support you provided! Do you know when will this be available in the official release of Electron?

**Comment by kevinsawicki** [comment]
> Yesssss, that worked! 

Glad to hear it 👍 

> Do you know when will this be available in the official release of Electron?

I don't have a firm timeline at this point, I would think if all goes well with people testing the beta release it could hit stable in a week or so.

**Comment by snene** [comment]
@kevinsawicki I understand that using "nativeWindowOpen=yes" for a webview needs "allowpopups" to be set on the webview. But is it still possible to override the functionality by using 'new-window' handler and calling preventDefault. I added the following code to the BrowserWindow:

```
  webview.addEventListener('new-window', (evt) => {
    if (<check for some condition>) {
         evt.preventDefault();
     }
  });
```

But still a new popup window is created even if evt.preventDefault(); is called.

Is it possible to stop popup window in certain cases? If yes, how? Thanks a million!

**Comment by kevinsawicki** [comment]
> Is it possible to stop popup window in certain cases? If yes, how? Thanks a million!

You need to listen to this event from the main process, `webview.addEventListener` does not support preventing the default for events since they are dispatched through the main process. You can listen to `<webview>` events from a renderer process but modifying the event parameters or preventing the default is not possible.

Can you try this instead from the main process:

```
app.on('web-contents-created', (event, contents) => {
  if (contents.getType() === 'webview') {
    contents.on('new-window', (event) => {
      console.log('blocking!')
      event.preventDefault()
    })
  }
})
```

**Comment by snene** [comment]
Thanks a lot @kevinsawicki Will try and let you know!

**Comment by snene** [comment]
Thanks a lot @kevinsawicki I tried and it works! Thanks again!

**Comment by elite28** [comment]
@kevinsawicki setting `webpreferences="nativeWindowOpen=1"` on `<webview>` tag, it can open a new window for me, but when the new window excute js after body onload, like get data from opener, the opener is null..

**Comment by mkazlauskas** [comment]
The 'new-window' event seems to only be firing with 'nativeWindowOpen=true', and not '1' or 'yes'. Using Electron 1.7.6

**Pull request merged**
