### PR TITLE
Add app.setDisplayNotifications method

### PR DESCRIPTION
**Pull request by gerhardberger**
This PR adds a `setDisplayNotifications` method to the `app` object.

This allows to add a quick option for Electron apps to disable and enable displaying notifications, sort of like a more fine grained Do not disturb mode.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I feel as though this should be something users should do in a preload script (`window.Notification = NoopNotification`), either that or it should be a `webPreferences` property similar to how notifications are muted based on `webContents.setMuted()`.  Maybe I'm just missing the use case for disabling notifications that users create at an app level.

Also if this method goes ahead you need to add this check into the `atom_api_notification.cc` file before showing notifications there 👍

**Comment by gerhardberger** [comment]
@MarshallOfSound my use case was to provide an easy way to toggle the showing of notifications of an app. This would let a user mute certain apps (e.g. a chat client) and still receive notifications from others as opposed to something like a Do Not Disturb mode. On macOS this can be done in notification preferences, but it is a lot of work to set it and this method would allow to do a one or two click option to apps.

The problem with overriding it in a preload script or disabling it in webpreferences is that would be a one time option, so I couldn't toggle it at runtime.

**Comment by zcbenz** [comment]
A runtime switch can be simply implemented as:

```js
const NativeNotification = window.Notification
window.Notification = (args...) => {
  if (notificationEnabled)
    new NativeNotification(args...)
}
```

I'm against adding an API that simply turn on/off a feature, which can be simply achieved on users' side. This is a principle of API design, as an example, none of the native notification APIs provides an API to switch on/off the notifications.

**Comment by gerhardberger** [comment]
@zcbenz I will try this solution and if it works for my app, I'm totally okay with it, as I also wasn't too sure about adding this sort of functionality as an API.

**Comment by jkleinsc** [comment]
@gerhardberger does the solution @zcbenz work for you?  If so, can you close this PR?

**Comment by gerhardberger** [comment]
@jkleinsc @zcbenz's solution didn't work for me, after overriding `Notification`, I didn't receive any notification anymore. But I managed to find another solution so this PR is not necessary.

**Pull request closed without merging**
