### PR TITLE
ci: build ffmpeg and verify it in a separate jobs

### PR DESCRIPTION
**Pull request by alexeykuzmin**
- it is an independent task and should be done separately
 - we can use smaller machines for that

An example workflow https://circleci.com/workflow-run/379ca922-fcea-42bc-b370-803a916fd4b6

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: no notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
An btw, do we really want to run this check to every PR?
Maybe it would be enough to have it a part of the nightly builds only?

**Comment by jkleinsc** [comment]
@alexeykuzmin in theory someone could add a patch in a PR that modifies ffmpeg, so wouldn't we want it on every build?  Also, it is possible that a change someone makes to Electron somehow breaks us using a non-proprietary ffmpeg.

**Comment by deepak1556** [comment]
It would be best to run this in every PR if possible, we are building ffmpeg as a component in release build, which is different from chrome. So best to make sure any build time changes we make for electron doesn't affect it. Running it on nightly isn't bad, but would make it a little difficult to identify which change caused the regression.

**Comment by alexeykuzmin** [comment]
@jkleinsc @deepak1556 
Running it for every PR doesn't affect a workflow's time to complete, so it should be ok.
It only takes some additional machine time, but we run them on `medium` sized boxes, shouldn't be that expensive =)

Can someone please merge it then? )

**Pull request merged**
