### PR TITLE
Fix crash in ReadImageSkiaFromICO when CreateSkBitmapFromHICON fails

### PR DESCRIPTION
**Pull request by miniak**
Fixes https://github.com/electron/electron/issues/6253

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Would you mind adding a spec to cover a `.ico` that does not exist?

Perhaps after this line?

https://github.com/electron/electron/blob/a47e30dd82a91347f27c8958d6be04f6a32bfb2f/spec/api-native-image-spec.js#L11

**Comment by kevinsawicki** [comment]
Thanks for this, merged via #6278

**Comment by miniak** [comment]
@kevinsawicki sorry for not adding the test, I was busy doing something important at work. I only got to check Electron my PRs. I see that you added it yourself already.

**Comment by kevinsawicki** [comment]
> sorry for not adding the test, I was busy doing something important at work. I only got to check Electron my PRs today. I see that you added it yourself already.

No worries at all, thanks again for this important fix 👍

**Pull request closed without merging**
