### PR TITLE
test: add more tests for BrowserView.setAutoResize

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This is to check existing behavior ahead of an upcoming refactor and
deprecation.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by ckerr** [comment]
CI failure seems on-topic for the PR, might not be a flake?

https://app.circleci.com/pipelines/github/electron/electron/57951/workflows/aa71cb67-9b7a-48d6-be6c-f2366f88e427/jobs/1316144

> BrowserView module BrowserView.setAutoResize() resizes proportionally
resizes proportionally
/home/builduser/project/src/electron/spec/api-browser-view-spec.ts

```
AssertionError: expected { x: +0, y: +0, width: 600, height: 100 } to deeply equal { x: +0, y: +0, width: 400, height: 100 }
    at Context.<anonymous> (electron/spec/api-browser-view-spec.ts:202:40)
    at processImmediate (node:internal/timers:466:21)
```

**Review by jkleinsc — CHANGES_REQUESTED** [review]
newly added test fails

**Comment by jkleinsc** [comment]
@nornagon looks like the test still fails.

**Comment by nornagon** [comment]
I'm going to close this out and leave it to #35658 to land these tests. That PR normalizes the behavior across all platforms (the behavior on macOS will change to match Windows and Linux). This is a fairly breaky change, but I think that's okay because (1) the API is marked "experimental", and (2) anyone who's using setAutoResize on both Windows and Mac either doesn't care about the differences in behavior (perhaps they're just using it to make the view fill the window, which works the same on any platform), or they have specific code to do something differently on Mac vs Windows, in which case they can just delete their Mac-specific code and do the same thing everywhere now.

**Pull request closed without merging**
