### PR TITLE
build: fixup autoninja

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change

https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4869108 fixed our use of autoninja, but it introduced an error verifying goma, so this PR will fix that issue.

- Main will get this change via #39774
- 26-x-y will get this change via #39887
#### Checklist

- [X] PR description included and stakeholders cc'd
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
My change landed upstream in depot_tools, no need to apply this patch anymore

**Comment by jkleinsc** [comment]
[90c1f6e](https://github.com/electron/electron/pull/39896/commits/90c1f6e1cb8d22d94dd01791dc4b9c3e0a7e86fc) is still needed.

**Review by MarshallOfSound — APPROVED** [review]

**Comment by MarshallOfSound** [comment]
Can we target this at main and then backport it everywhere? Don't want other CI to be blocked on chrome rolls landing

**Review by codebytere — APPROVED** [review]

**Comment by jkleinsc** [comment]
- 26-x-y got this fix via https://github.com/electron/electron/pull/39887

**Pull request merged**
