### PR TITLE
[WIP] Publish the public API as a JSON object

### PR DESCRIPTION
**Pull request by zeke**
🚧  Work In Progress 🚧 

This is an effort to parse the markdown files in `docs/api` into a JSON object that describes all the APIs in meticulous detail. This includes things like:

- name
- description
- processes the API is available in
- methods
- instance methods
- events
- instance events

This is a first pass, and there are undoubtedly some areas where the parsing needs to be tweaked. Please have a look at `docs/api.json`, and report anything that looks inconsistent with the documentation. Feel free to report your findings on this PR or file issues directly on the [electron-docs-linter](https://github.com/zeke/electron-docs-linter/issues) repository.

To lint the docs and write the JSON file, I ran this:

```sh
npm run lint-docs -- 1.2.7
```

... where 1.2.7 is the version of electron that is *about to be released*.

@zcbenz you said your release process is this:

> usually I push a commit with message “Bump vx.x.x”, wait for CI machines to build and upload the binaries, and finally run `./script/upload.py -p` to update checksum files and publish the release.

I don't wish to add any more manual steps to that process. Maybe we can make a release script that takes a single `version` argument, lints the docs, commits with the bump message, etc.

### CODE REVIEW

**Comment by zcbenz** [comment]
Should we just upload the file to S3? If so this step would be the same with uploading `index.json` and checksum files. I don't think this file should be put in the repo, it would encourage people to download it through GitHub, which is very bad.

**Comment by mnquintana** [comment]
❓ – What would y'all think about moving the Markdown API docs to inline comments in the source so they can be parsed by a docs tool like [ESDoc](https://esdoc.org/) or [JSDoc](http://usejsdoc.org/)? (Non-API guides would be left alone, of course.)

**Comment by felixrieseberg** [comment]
@mnquintana: I'm in theory totally with you, but there's one serious downside: A huge portion the available API comes straight out of Brightray or Chromium (meaning that there wouldn't be IDE-parsed code to attach the documentation to).

However, if we find a nice way to add interface-style documentation Brightray-injected objects, I'd also favor in-code documentation.

**Comment by miniak** [comment]
Wouldn't it work better if a .d.ts file was the master and the docs would be generated from that?

**Comment by miniak** [comment]
Also, if I can help with this effort in any way, let me know. It would be great if I don't have to update the DefinitelyTyped electron typings manually every time there is a new release :)

**Comment by zeke** [comment]
>  I don't think this file should be put in the repo

@zcbenz that's fine with me. What about including it as a standalone file in the GitHub Release, [the way atom does](https://github.com/atom/atom/releases/tag/v1.7.3)? That seems more publicly discoverable to me than S3.

Once we get the docs object rolled into the release process, my hope is to set up a self-publishing npm package (like `electron-prebuilt`) that exports the JSON doc in a `require`able dependency-free way.

> A huge portion the available API comes straight out of Brightray or Chromium

Yep, code introspection won't really work because of this. That's why we chose to use the documentation as our source of truth for now.

> Wouldn't it work better if a .d.ts file was the master and the docs would be generated from that?

Maybe so, but that's not where we're at today. The docs are what we have. I was unfamiliar with [DefinitelyTyped](http://definitelytyped.org/), but it looks pretty useful. Perhaps we could use this new JSON object as a starting point for generating an up-to-date TypeScript type definition?

**Comment by zcbenz** [comment]
> @zcbenz that's fine with me. What about including it as a standalone file in the GitHub Release, the way atom does? That seems more publicly discoverable to me than S3.

👍

**Comment by zeke** [comment]
I just added a few updates that move some of the linting song and dance out of the repo and into the linter's new CLI. This has the nice side effect of leaving all the scripts pristinely pythonic. 🐍 

The CLI can be used in a few ways. You can use it to only verify that the docs are well-formatted:

```
electron-docs-linter docs/api

Docs are good to go! 👍
```

Or if you specify a version and a pipe, the generated JSON schema will be output:

```
electron-docs-linter docs/api --version=1.2.8 > docs/api.json
```

If the docs are not ship-shape, you'll see errors and the process exits with code of `1`:

```
❯ node cli.js ../../electron/electron/docs/api

🙊  uh-oh! bad docs 🙈

-----------------------
file: app.md
type: argument subproperties
pattern: /<code>(\w+)<\/code>\s*(?:<a href.*>)?([a-zA-Z0-9\[\]]+)(?:<\/a>)?(?: - )?(.*)/
html: <code>%APPDATA%</code> on Windows
markdown (approximate): `%APPDATA%` on Windows
-----------------------
... etc
```

This gives us some flexibility. We can choose to use the linter in `electron/electron` purely as a linter, only to tell us that docs are good to go, OR we could use it to lint and generate the JSON schema to be included as a GitHub Release artifact.

In either case, this still needs some work as there are currently 100+ formatting errors remaining to fix.

@zcbenz would you prefer to adapt the `upload.py` script to zip and upload the generated JSON, or would you prefer to just lint, and leave the schema generation to a separate project outside of `electron/electron`?

**Comment by zcbenz** [comment]
> @zcbenz would you prefer to adapt the upload.py script to zip and upload the generated JSON, or would you prefer to just lint, and leave the schema generation to a separate project outside of electron/electron?

I think we can have both, make docs lint as part of CI, and upload api.json in `upload.py`. We probably do not need to zip the JSON file.

**Comment by zeke** [comment]
Sorry for leaving this PR open for so long. Bad hygiene!

I'm going to close it for now and re-open it when the [MVP milestone](https://github.com/zeke/electron-docs-linter/milestone/1) for `electron-docs-linter` is complete.

**Comment by mmc41** [comment]
@zeke What happened to the typescript stuff mentioned ? Would be extremely nice with an official up-2-date typescript file for both documentation and code-completion.

**Pull request closed without merging**
