### PR TITLE
feat: add multi BrowserView support to BrowserWindow

### PR DESCRIPTION
**Pull request by summeroff**
#### Description of Change
new feature: multi browser views support for BrowserWindow 

Add functions addBrowserView, removeBroserView, getBrowserViews to BrowserWindow class. 

Existing API setBrowserView and getBrowserView changed to use new API inside.

This functionality was mentioned in the initial BrowserView feature PR https://github.com/electron/electron/pull/9166 . And asked few times since then. Recently in a discussion https://github.com/electron/electron/issues/10622 .

It is a resubmit of PR #16064 as changes moved to master branch instead of 2-0-x branch. 
/cc @zcbenz 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: multi browser views support for BrowserWindow

### CODE REVIEW

**Comment by codebytere** [comment]
```
not ok 1026 chromium feature focus handling "before each" hook for "moves focus to the next focusable item"
  ReferenceError: emittedOnce is not defined
      at Context.beforeEach (/home/builduser/project/src/electron/spec/chromium-spec.js:1422:28)
      at processImmediate (timers.js:632:19)
```
is failing across several platforms, and is thus i believe consequential of this PR.

**Comment by summeroff** [comment]
Failed test is trying to use `emittedOnce` without including it. 
Something like `const { emittedOnce } = require('./events-helpers')` probably can help. But I am not sure it should be fixed in this feature PR and not small fix PR that will be merged in master a lot faster.

Change what added test with `emittedOnce` was merged into master just 18 hours ago. So my PR can be one of the first that catches it.

**Comment by zcbenz** [comment]
The CI is broken on master branch, I also see the failed test in other unrelated PRs.

**Comment by summeroff** [comment]
For failed tests on 'ci/circleci: mas-testing-tests' run. They not look related to changed code and there is no fails on 'ci/circleci: osx-testing-tests' run. Or am I missed something? What I should do next?

**Comment by adel-sbeh** [comment]
When I try to create a new browser view, the old one disappears.

**Comment by vmars316** [comment]
Hello & Thanks ,
Can someone aim me at an Electron browserview simple example  Browser ? 
Thanks for your Help...

**Comment by rumkin** [comment]
BrowserView couldn't be detached from BrowserWindow and added to another BrowserWindow. The old window still has a reference to the view in its `TopLevelWindow::browser_views_` map. Filed it as a separate issue #26975.

**Pull request merged**
