### PR TITLE
chore: cherry-pick 0f481c9ddf2a from v8

### PR DESCRIPTION
**Pull request by ppontes**
Merged: [wasm][turbofan] Load 32-bit values more efficiently

When loading a 32-bit value from the stack, just load 32 bit and
zero-extend them into the target register, instead of loading the full
64 bits.

As there are things to fix (see https://crbug.com/1356461), we only
enable this optimization for Wasm for now.

Also include the related fix https://crrev.com/c/4096985.

R=mslekova@chromium.org

(cherry picked from commit 2ee52447c878721c89a55a780eb689ecba6817d3)
(cherry picked from commit a38209949fcbf045231c316e2d790b8b70ccb7ef)

Bug: chromium:1395604
Change-Id: I54a2182ada6fadbfcf5565f0dc8d4f477ecff393
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4110897
Reviewed-by: Maya Lekova <mslekova@chromium.org>
Commit-Queue: Clemens Backes <clemensb@chromium.org>
Cr-Commit-Position: refs/branch-heads/10.8@{#46}
Cr-Branched-From: f1bc03fd6b4c201abd9f0fd9d51fb989150f97b9-refs/heads/10.8.168@{#1}
Cr-Branched-From: 237de893e1c0a0628a57d0f5797483d3add7f005-refs/heads/main@{#83672}

Notes: Security: backported fix for 1395604.

### CODE REVIEW

**Comment by zcbenz** [comment]
The bot removed the content of the patch :(

**Comment by ppontes** [comment]
> The bot removed the content of the patch :(

Pushed again.

**Comment by codebytere** [comment]
Same thing 🤔

**Comment by codebytere** [comment]
Closing as this patch already exists in 22-x-y Chromium (that's why the bot removed it)

**Pull request closed without merging**
