### PR TITLE
docs: es6ify 'Breaking Changes' and 'File' API pages

### PR DESCRIPTION
**Pull request by ntocampos**
#### Description of Change

This pull-request "es6ifies" code snippets in the `Breaking Changes` and `File` object documentation pages, as suggested on #14842.
cc @ckerr 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes:  no-notes

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@ntocampos Can you group all your ES6'ify PR's into one PR please? It'll make it easier to review in one go and will cause less CI jobs to run 👍

**Comment by ntocampos** [comment]
> @ntocampos Can you group all your ES6'ify PR's into one PR please? It'll make it easier to review in one go and will cause less CI jobs to run 👍

Sure. I'm gonna do this now 😄

**Comment by ntocampos** [comment]
Done. I've closed the other PR.

**Comment by jatin33** [comment]
Can I work on this issue?

**Pull request merged**
