### PR TITLE
Disable flaky specs on Travis

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull request comments out some specs that are timing out pretty regularly on Travis but still will run on Jenkins builds.

### CODE REVIEW

**Comment by zeke** [comment]
@kevinsawicki you can use mocha's `this.skip()` instead of `done()` so as not to fake the passing of those tests. Note that this would require changing from an arrow function to an old-school function to scope `this` to the context of the test.

**Comment by kevinsawicki** [comment]
> this.skip()

This was causing issues previously since `beforeEach/afterEach` blocks aren't run for skipped tests so I removed it in #8096

**Comment by zeke** [comment]
😞

**Comment by MarshallOfSound** [comment]
@kevinsawicki What about `it.skip()`, that should stop the before blocks running as well

**Comment by kevinsawicki** [comment]
> What about it.skip(), that should stop the before blocks running as well

We want the before/after blocks to run though to make sure windows are properly destroyed.

Also, we want this to run everywhere but Travis so using `it.skip` would be kind of tricky since we would need to wrap the function call in the Travis check.

**Pull request merged**
