### PR TITLE
Deprecate /docs-translations

### PR DESCRIPTION
**Pull request by zeke**
The `/docs-translations` directory was a home-grown effort to translate Electron's docs. It has undoubtedly helped many folks learn Electron, but we never had a real process for keeping the translations up to date and consistent across locales. Until now!

The [new Electron website](https://github.com/electron/electron.atom.io/pull/758) is internationalized, and it consumes translated (and source) content from electron/electron-i18n, a repo that syncs with Crowdin, our new localization service.

This PR:

- removes all existing content in the `/docs-translations` directory
- keeps the directory around, and adds an explanatory README with info about the new translation process
- documents steps for getting good-ol-days raw, offline, localized, Markdown docs.

@electron/i18n  @electron/docs @sethlu

### CODE REVIEW

**Comment by vanessayuenn** [comment]
@zeke do you think it will be possible/worth the effort to programmatically salvage some of the existing doc translations and import them into the new crowdin system? Just tossing them seems like such a waste of old translation effort.

**Comment by zeke** [comment]
> do you think it will be possible/worth the effort to programmatically salvage some of the existing doc translations

@alebourne and I discussed this with the Crowdin team and the consensus seemed to be that it would be too hard. That said, I would not be opposed to giving it a try.

**Comment by Toinane** [comment]
I would add that the translations (e.g. french translations) are no longer up to date for most files or I already copy them into Crowdin when I can. But it can be useful for others languages who have recent translations.

**Comment by natebwangsut** [comment]
Agreed. @Toinane

A lot of the translation are no longer up to date. Personally I do think by using the whole new interface from Crowdin makes the recent translation much more consistent as we have access to the language guideline and commonly agreed terms.

Beside that, some of the vocab that reflect the context more expressively could be retrieved from the old docs and use it in the new one. However, it would be programmatically hard to do so.

**Comment by alebourne** [comment]
Hi @zeke and team members,
Recently,I reached out to Crowdin AGAIN about trying to salvage translations done outside the system. They have told me this is now possible. Here is the information I got from them:
My question was: 

> We have several existing translation repositories that already exist. The community members had translated these documents by cloning a repo and then translate them. We want to move them to Crowdin. Is there any way to reuse the translations that have already been completed? 

The Crowdin answer was:

> Regarding the existing translations, the suggested workflow might be the following:
1. please download the translations from each repository on your computer and place them in the ZIP archive;
2. after that, please upload ZIP archive as the existing translations to your project (https://support.crowdin.com/uploading-translations/)
3. finally, it is necessary to invite the owners of the repositories as the translators. As a result, they will be able to continue working on the translations directly in Crowdin

Also, I have a glossary that we have completed with GtHub terms that we should consider to start translation for that might be beneficial for Electron. I'm thinking we should create a separate issue to discuss.

**Comment by sethlu** [comment]
@alebourne glad to hear about the news!

@zeke I'll put the copy & paste migration on block until further notice.

**Comment by TiagoDanin** [comment]
@zeke  Missing edit the README.md in:
- [Line 8](https://github.com/electron/electron/blame/5e0fe575c9cf1b82ab7213809f7ce4d96f8e60ca/README.md#L8)
- [Lines 83-96](https://github.com/electron/electron/blame/5e0fe575c9cf1b82ab7213809f7ce4d96f8e60ca/README.md#L85)

**Comment by zeke** [comment]
> Missing edit the README.md

Thanks, @TiagoDanin. Fixed 👍

**Pull request merged**
