### PR TITLE
fix: window with customButtonsOnHover should have rounded corner

### PR DESCRIPTION
**Pull request by zcbenz**
#### Description of Change

Close https://github.com/electron/electron/issues/10424.

The `customButtonsOnHover` option relied on the `NSWindowStyleMaskFullSizeContentView` style to hide window title and buttons, which is actually a weird code path and unnecessary.

This PR makes it use the normal window styles like the other `titleBarStyle` options, which fixes the problem that the window has no rounded corner.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix window with `customButtonsOnHover` option not having rounded corner on macOS.

### CODE REVIEW

**Review by xdumsidedx — APPROVED** [review]

**Review by xdumsidedx — APPROVED** [review]

**Review by xdumsidedx — APPROVED** [review]

**Review by xdumsidedx — APPROVED** [review]

**Review by xdumsidedx — APPROVED** [review]

**Review by xdumsidedx — APPROVED** [review]

**Comment by xdumsidedx** [comment]
💙💚💜🖤

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
Failure is:

> reporting api sends a report for a deprecation

And is known.

**Comment by nornagon** [comment]
Is it still possible to get a frameless window _without_ rounded corners on macOS after this PR?

**Comment by zcbenz** [comment]
> Is it still possible to get a frameless window _without_ rounded corners on macOS after this PR?

No, but we can add a new API to turn off rounded corner if there is request, we only need to apply the `NSWindowStyleMaskFullSizeContentView` style.

**Comment by zcbenz** [comment]
I think we should hold on backporting it to 10/11, there are some users relying on this option to create a frameless window without rounded corner.

**Pull request merged**
