### PR TITLE
added accelerator.md to api folders and translated

### PR DESCRIPTION
**Pull request by arifcakiroglu**
* Added all files to /tr-TR folder for broken links
* File-object.md and accelerator.md translated

### CODE REVIEW

**Comment by zeke** [comment]
Thanks @arifcakiroglu! I can see why you copied over all the existing docs (to keep relative links working) but it seems like this introduces a lot of redundant content that will quickly be out of date.

How else could we work around the relative links issue?

**Comment by arifcakiroglu** [comment]
You're right @zeke, these files should be up to date. But i would like you to know that I love Electron.
I'll be translatlng all the api, and other files as fast as I can, tracking the updates and applying to their Turkish versions.

Another solution would be to provide references to their original Electron urls, therefore preventing them to lose their up-to-date state.This way, we would also provide access, to anyone that wants to read the originals

I'm trying to teach Electron in Turkey, and people need some Turkish materials. So I figured that the best solution would be to translate the api.

If you have some other solutions in mind, I would love to hear about it.

**Comment by zcbenz** [comment]
@arifcakiroglu If you want to make links work, I suggest just letting users navigate documents in your forked repo instead, in future we will fix this on [the website side](https://github.com/electron/electron.atom.io).

We can not just copy all documentation files untouched, otherwise it would be very difficult to maintain the documents.

**Comment by arifcakiroglu** [comment]
Thanks for your suggestion @zcbenz. I fixed all documentation file.

**Comment by zcbenz** [comment]
Thanks!

**Pull request merged**
