### PR TITLE
test: deflake ses.setProxy test

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Example flake: https://app.circleci.com/pipelines/github/electron/electron/31724/workflows/ad370a6d-7c65-44dc-bf8b-e3978e263fe5/jobs/699105

Ref #26166

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: none

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Review by ckerr — COMMENTED** [review]
+1 if this is only something that shows up in CI situations -- but is that the case here? Is this something that could hit users in production as well?

**Comment by nornagon** [comment]
@ckerr see referenced issue

**Comment by deepak1556** [comment]
Maybe use `session.forceReloadProxyConfig` from https://github.com/electron/electron/pull/24937 instead of a delay

**Comment by nornagon** [comment]
@deepak1556 I think the real fix is to have `ses.setProxy` return a promise that actually waits until the config has been applied, instead of what it does now which just a simple next-tick promise that doesn't wait for anything. this is a stopgap measure

**Comment by deepak1556** [comment]
Sounds good

**Comment by LuoJinghua** [comment]
The TEST_F(NetworkContextTest, StaticProxyConfig) from services/network/network_service_unittest.cc says:
``` c++
  // Kick the ConfiguredProxyResolutionService into action, as it doesn't start
  // updating its config until it's first used.
  proxy_resolution_service->ForceReloadProxyConfig();
```

**Comment by nornagon** [comment]
@LuoJinghua good info. I'd still like to look into making the promise that `setProxy` returns more useful.

**Comment by nornagon** [comment]
Also, hm, that comment seems inaccurate in our situation. Based on my experimentation in #26166, a `setTimeout` is sufficient to allow the change to propagate, no usage is required.

**Pull request merged**
