### PR TITLE
feat: add path to FileSystemFileHandle & FileSystemDirectoryHandle

### PR DESCRIPTION
**Pull request by jtbandes**
#### Description of Change
Adds a `path` property to `FileSystemFileHandle` & `FileSystemDirectoryHandle`, similar to the `path` property on `File` added by [`blink_file_path.patch`](https://github.com/electron/electron/blob/main/patches/chromium/blink_file_path.patch).

Fixes https://github.com/electron/electron/issues/33647.

cc @zcbenz as the author of `blink_file_path.patch` — any other relevant stakeholders I should add?

Known limitations: this still doesn't provide a path for file handles serialized in IndexedDB — I wasn't sure how to make that work (see comment below). It also doesn't update the path when a file is moved. Any advice appreciated!

https://user-images.githubusercontent.com/14237/189011460-c40d926c-fdc7-4bd7-a57d-4c4014a71765.mov

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added `path` property to `FileSystemFileHandle` and `FileSystemDirectoryHandle`.

### CODE REVIEW

**Review by codebytere — CHANGES_REQUESTED** [review]
At the moment, this patch is rather large and not something we're prepared to accept without a plan for removal or input from upstream per our [patch policy](https://github.com/electron/electron/blob/43dbd1bdf8a48d798f4e392f921bde81a3430f4b/docs/development/patches.md#L9-L11). Is this something that's on the `File System Access API` roadmap? if not, have it been raised? The issue notes that:

> Furthermore, a File returned by [FileSystemFileHandle.getFile](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/getFile) has an empty path.

this should, imo, be proposed upstream and discussed prior to being opened here.

**Comment by Cirras** [comment]
> Is this something that's on the `File System Access API` roadmap?

No.

> if not, have it been raised?

Yes, and seemingly rejected.
In fairness, it doesn't really make sense to expose full filesystem paths in a browser context.

Relevant issues:
- https://github.com/WICG/file-system-access/issues/145
- https://github.com/WICG/file-system-access/issues/178
- https://github.com/WICG/file-system-access/issues/36

**Comment by MarshallOfSound** [comment]
> In fairness, it doesn't really make sense to expose full filesystem paths in a browser context.

We have an item in our backlog to actually _remove_ this path patch as it is non-standard, non-secure and is counter to some of Electrons goals.  It hasn't happened yet because we still want to support the usecase it allows.  I don't think _expanding_ the surface area we would have to remove is a good idea

**Comment by jtbandes** [comment]
For an application that wants to use [setRepresentedFilename](https://www.electronjs.org/docs/latest/tutorial/represented-file) on macOS, a full file path is required. How would it be possible to use setRepresentedFilename with dragged files (or files from `showOpenFilePicker`) if `path` support is removed? Are there any ideas for alternative ways to access absolute file paths? Seems like a contradiction for it to be both counter to Electron's goals and also necessary for using a standard feature...

**Comment by jtbandes** [comment]
Thanks, I did read that. I am merely asking if any ideas have been proposed that would still allow this usecase while solving the security issues. Sorry if my comment came off as anything beyond that.

It sounds like this PR as proposed is going further in a direction that the team is planning to eventually move away from. I am hoping a solution can be found that would also support FileSystemHandles and address the security concerns at the same time.

**Comment by MarshallOfSound** [comment]
@jtbandes A renderer-side Electron API that allows passing in a `File` handle and receiving its path is probably reasonable.

E.g. 

```js
// Preload
const { contextBridge, files } from 'electron';

contextBridge.exposeInMainWorld('myApp', {
  getPathToFile: (file) => files.getPathToFile(file),
});
```

```js
// Main World
window.myApp.getPathToFile(input.files[0]);
```

I don't believe that exposes an unreasonable surface area and could probably be extended to support the other file handles you reference but I'm not 100% sure on that.  I know that `blink::File` definitely has a `GetPath` method --> https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/fileapi/file.h;l=206?q=blink%20File%20blob&ss=chromium which is trapped behind the `private_` member of `WebBlob` (which is the public blink API for files / blobs).

So not super easy, will probably still need a small patch but that would be the desired endstate for sure IMO

**Review by nornagon — CHANGES_REQUESTED** [review]
I don't think we should merge this, and further, I think we should delete `blink_file_path.patch`.

**Comment by nornagon** [comment]
Ah, sorry, @MarshallOfSound already said the same thing :)

**Comment by jtbandes** [comment]
I've been experimenting with creating a `files.getPath()` function as described. When I pass in a File, I am able to use `blink::ToScriptWrappable()` to get the underlying File from the `v8::Object`. However, when I pass a FileSystemFileHandle into the function, the same does not work (and `blink::V8DOMWrapper::IsWrapper` returns false). Any ideas for how to access the underlying FileSystemFileHandle object?

**Comment by nornagon** [comment]
Marking this as `wip` to drop it out of the API review queue for now.

**Comment by jtbandes** [comment]
Is there anyone who would be able to help advise on how to get the path from a FileSystemFileHandle object? I've also tried posting my question to the chromium storage-dev mailing list but got no response yet: https://groups.google.com/a/chromium.org/g/storage-dev/c/02zAZmC814A

**Review by nornagon — COMMENTED** [review]
From the APIs you're calling here, it looks like actually the renderer doesn't have access to the file path directly, but has to call `ResolveTransferToken` in the main process in order to get the path. This isn't something we'd want to be exposing unconditionally—it would allow a compromised renderer to resolve any transfer token, which is the same security problem we already have with the patch, which we'd like to get rid of.

If the renderer doesn't have the file path anywhere in this situation, and must ask the main process, then we must allow the main process to choose when it will or won't resolve file paths. For instance, we could make the transfer tokens (or the file handles themselves) serializable over IPC via `ipcRenderer.postMessage`, say, and give the main process JS a way to resolve those into file paths. But as written this approach would get a :-1: from me even if the V8 APIs worked as you expect—I'm not sure why they aren't, I haven't dug into it yet.

**Comment by jtbandes** [comment]
> give the main process JS a way to resolve those into file paths

Is your point that you’d like the resolving API to be a main-only API, not a renderer API, and just allow application developers to postMessage files/handles to main themselves and decide in main whether or not to resolve them? That concept makes sense, but I am still curious how the main process would be able to know whether the renderer was compromised or not in this scenario? I suppose it wouldn’t know, but could still choose whether or not to respond to the request?

Anyway, I could probably use help figuring out how to structure the code to properly implement that suggestion, since even putting together what I have so far (which I think is close to working, but not quite) was quite a struggle 😅

**Comment by samuelmaddock** [comment]
>I’m just not totally sure what the threat model is that we’re concerned with and would be curious to learn more.

I just came across this article in the Chromium docs which gives a nice introduction: https://chromium.googlesource.com/chromium/src/+/master/docs/security/compromised-renderers.md

The excerpt here is what I believe @nornagon is getting at
> A compromised renderer can forge malicious IPC messages, impersonate a Chrome Extension content script, or use other techniques to trick more privileged parts of the browser.

With the implementation of `ResolveFileSystemAccessTransferToken(token)`, a compromised renderer would potentially be able to resolve file paths of any file handles it can access within the process. It would be up to the main process to perform necessary validation to ensure the renderer should be able to request access to the file path.

In some cases, validation can be application-specific such as in [permissions requests](https://www.electronjs.org/docs/latest/tutorial/security#5-handle-session-permission-requests-from-remote-content), [opening new windows](https://www.electronjs.org/docs/latest/tutorial/security#14-disable-or-limit-creation-of-new-windows), and [validation of IPC messages](https://www.electronjs.org/docs/latest/tutorial/security#17-validate-the-sender-of-all-ipc-messages).

The question then becomes whether we want to add a new API for validating these requests, or make use of an existing API. @nornagon had mentioned:

> we could make the transfer tokens (or the file handles themselves) serializable over IPC via ipcRenderer.postMessage, say, and give the main process JS a way to resolve those into file paths.

In practice this might look something like this:
```ts
// preload.js
function getFilePath(fileHandle) {
  // Note that file handles aren't currently serializable over IPC. An implementation
  // of this will be needed to work.
  ipcRenderer.postMessage('resolve-file-path', fileHandle);
}

// main.js
ipcMain.on('resolve-file-path', (e, fileHandle) => {
  // Validate request sent from our app to mitigate potentially compromised renderer
  if (e.frame.url === 'http://example.app') {
    return nativeMethodToResolveFilePath(fileHandle);
  }
});
```

I'm not personally familiar with our IPC serialization code, but I believe some of the code for handling serialization of v8 values over `ipcRenderer` is available here: https://github.com/electron/electron/blob/2f2c43e5e513e65a0aabac62622d51a1dfe49357/shell/common/v8_value_serializer.cc

**Pull request closed without merging**
