### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by ZReC**
Notes: none

### CODE REVIEW

**Comment by RaisinTen** [comment]
Here is another repetition of the typo:
https://github.com/electron/electron/blob/fa2db00e55a9c285491ae9b91ad13b57ed950adf/docs/fiddles/features/macos-dark-mode/main.js#L25
I think we should fix both of them in this PR itself. :)

**Comment by ez5393ez** [comment]
> _No description provided._

Outing

**Comment by ZReC** [comment]
> > _No description provided._
> 
> Outing

Sorry, I thought the commit was self explanatory

**Comment by ZReC** [comment]
> Here is another repetition of the typo:
> https://github.com/electron/electron/blob/fa2db00e55a9c285491ae9b91ad13b57ed950adf/docs/fiddles/features/macos-dark-mode/main.js#L25
> 
> 
> I think we should fix both of them in this PR itself. :)

Done, thanks!

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
