### PR TITLE
fix: disable swapping BrowsingInstance triggered by COOP in <webview>

### LINKED ISSUE #25421: Twitter does not load inside Webview
### Issue Details

Twitter does not load inside Webview anymore.

It's broken in 9+ versions

image
image

Even though if I load twitter directly into BrowserWindow it works:
image

* **Electron Version:**
  9.0.0 +

### Expected Behavior
Twitter should load inside the webview

### Actual Behavior
Twitter does not load in webview. There is no error, neither in root renderer nor in Twitter devtools.

### To Reproduce
Just this:
<webview src="https://www.twitter.com/"></webview>

### LINKED ISSUE #25469: Segfault in content::RenderFrameHostManager::SetRWHViewForInnerContents when navigating webview
Version: 9.3.0, 10.1.1, 11.0.0-beta.4, master
Last working version: 8.5.0

To repro: load this gist and hit run. It will crash within a few seconds. https://gist.github.com/19fa4b45478032494306a7388e0804a2
Sometimes it will take a few navigations before it crashes; it's not 100% reliable.

Crash trace excerpt:

```
4   ???                                 0x0000000000000000 0x0 + 0
5   Electron Framework                  0x000000010885a576 content::RenderFrameHostManager::SetRWHViewForInnerContents(content::RenderWidgetHostView*) + 118
6   Electron Framework                  0x0000000108d2ffa5 content::WebContentsImpl::ReattachToOuterWebContentsFrame() + 133
7   Electron Framework                  0x0000000108d484cd content::WebContentsImpl::NotifyViewSwapped(content::RenderViewHost*, content::RenderViewHost*) + 909
8   Electron Framework                  0x0000000108d518c8 content::WebContentsImpl::NotifySwappedFromRenderManager(content::RenderFrameHost*, content::RenderFrameHost*, bool) + 312
9   Electron Framework                  0x0000000108852904 content::RenderFrameHostManager::CommitPending(std::__1::unique_ptr<content::RenderFrameHostImpl, std::__1::default_delete<content::RenderFrameHostImpl> >, std::__1::unique_ptr<content::BackForwardCacheImpl::Entry, std::__1::default_delete<content::BackForwardCacheImpl::Entry> >, bool) + 1940
10  Electron Framework                  0x0000000108851fcf content::RenderFrameHostManager::CommitPendingIfNecessary(content::RenderFrameHostImpl*, bool, bool, bool) + 399
11  Electron Framework                  0x0000000108851e17 content::RenderFrameHostManager::DidNavigateFrame(content::RenderFrameHostImpl*, bool, bool, bool, blink::FramePolicy const&) + 23
[...]
```

<details>
<summary>Full stack trace</summary>

```
Received signal 11 SEGV_MAPERR 000000000050
0   Electron Framework                  0x0000000109cf8d79 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x0000000109bf33f3 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x0000000109cf8c41 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 2385
3   libsystem_platform.dylib            0x00007fff73e0d42d _sigtramp + 29
4   ???                                 0x0000000000000000 0x0 + 0
5   Electron Framework                  0x000000010885a576 content::RenderFrameHostManager::SetRWHViewForInnerContents(content::RenderWidgetHostView*) + 118
6   Electron Framework                  0x0000000108d2ffa5 content::WebContentsImpl::ReattachToOuterWebContentsFrame() + 133
7   Electron Framework                  0x0000000108d484cd content::WebContentsImpl::NotifyViewSwapped(content::RenderViewHost*, content::RenderViewHost*) + 909
8   Electron Framework                  0x0000000108d518c8 content::WebContentsImpl::NotifySwappedFromRenderManager(content::RenderFrameHost*, content::RenderFrameHost*, bool) + 312
9   Electron Framework                  0x0000000108852904 content::RenderFrameHostManager::CommitPending(std::__1::unique_ptr<content::RenderFrameHostImpl, std::__1::default_delete<content::RenderFrameHostImpl> >, std::__1::unique_ptr<content::BackForwardCacheImpl::Entry, std::__1::default_delete<content::BackForwardCacheImpl::Entry> >, bool) + 1940
10  Electron Framework                  0x0000000108851fcf content::RenderFrameHostManager::CommitPendingIfNecessary(content::RenderFrameHostImpl*, bool, bool, bool) + 399
11  Electron Framework                  0x0000000108851e17 content::RenderFrameHostManager::DidNavigateFrame(content::RenderFrameHostImpl*, bool, bool, bool, blink::FramePolicy const&) + 23
12  Electron Framework                  0x0000000108809d6f content::Navigator::DidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, bool) + 495
13  Electron Framework                  0x0000000108820974 content::RenderFrameHostImpl::DidCommitNavigationInternal(std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, bool) + 2820
14  Electron Framework                  0x000000010881fa9d content::RenderFrameHostImpl::DidCommitNavigation(std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) + 1085
15  Electron Framework                  0x00000001088212e5 content::RenderFrameHostImpl::DidCommitPerNavigationMojoInterfaceNavigation(content::NavigationRequest*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) + 341
16  Electron Framework                  0x000000010884fdf2 base::internal::Invoker<base::internal::BindState<void (content::RenderFrameHostImpl::*)(content::NavigationRequest*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>), base::internal::UnretainedWrapper<content::RenderFrameHostImpl>, content::NavigationRequest*>, void (std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::RunOnce(base::internal::BindStateBase*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >&&, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>&&) + 82
17  Electron Framework                  0x0000000105d82f0e content::mojom::NavigationClient_CommitNavigation_ForwardToCallback::Accept(mojo::Message*) + 478
18  Electron Framework                  0x000000010a197ff6 mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) + 1462
19  Electron Framework                  0x000000010a19bbdb mojo::MessageDispatcher::Accept(mojo::Message*) + 251
20  Electron Framework                  0x000000010a199361 mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) + 97
21  Electron Framework                  0x000000010a1f9df6 IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread(mojo::Message) + 630
22  Electron Framework                  0x000000010a1f6e9c base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, mojo::Message>, void ()>::RunOnce(base::internal::BindStateBase*) + 140
23  Electron Framework                  0x0000000109c88dbb base::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 411
24  Electron Framework                  0x0000000109ca7da7 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*) + 519
25  Electron Framework                  0x0000000109ca7a18 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 168
26  Electron Framework                  0x0000000109d19511 base::MessagePumpCFRunLoopBase::RunWork() + 65
27  Electron Framework                  0x0000000109d0e5a2 base::mac::CallWithEHFrame(void () block_pointer) + 10
28  Electron Framework                  0x0000000109d18edf base::MessagePumpCFRunLoopBase::RunWorkSource(void*) + 63
29  CoreFoundation                      0x00007fff3c570b21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
30  CoreFoundation                      0x00007fff3c570ac0 __CFRunLoopDoSource0 + 103
31  CoreFoundation                      0x00007fff3c5708d4 __CFRunLoopDoSources0 + 209
32  CoreFoundation                      0x00007fff3c56f740 __CFRunLoopRun + 1272
33  CoreFoundation                      0x00007fff3c56ebd3 CFRunLoopRunSpecific + 499
34  HIToolbox                           0x00007fff3b0c465d RunCurrentEventLoopInMode + 292
35  HIToolbox                           0x00007fff3b0c439d ReceiveNextEventCommon + 600
36  HIToolbox                           0x00007fff3b0c4127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
37  AppKit                              0x00007fff39734ba4 _DPSNextEvent + 990
38  AppKit                              0x00007fff39733380 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
39  AppKit                              0x00007fff3972509e -[NSApplication run] + 658
40  Electron Framework                  0x0000000109d1a4cc base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) + 348
41  Electron Framework                  0x0000000109d189e2 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) + 130
42  Electron Framework                  0x0000000109ca85dd base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 349
43  Electron Framework                  0x0000000109c5bf2c base::RunLoop::Run() + 956
44  Electron Framework                  0x00000001085bfe4b content::BrowserMainLoop::RunMainMessageLoopParts() + 203
45  Electron Framework                  0x00000001085c2212 content::BrowserMainRunnerImpl::Run() + 82
46  Electron Framework                  0x00000001085bc96b content::BrowserMain(content::MainFunctionParams const&) + 267
47  Electron Framework                  0x00000001083d282e content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) + 1406
48  Electron Framework                  0x00000001083d2283 content::ContentMainRunnerImpl::Run(bool) + 467
49  Electron Framework                  0x000000010c42c11e service_manager::Main(service_manager::MainParams const&) + 3310
50  Electron Framework                  0x00000001063095c8 content::ContentMain(content::ContentMainParams const&) + 120
51  Electron Framework                  0x00000001043fadc6 ElectronMain + 134
52  Electron                            0x0000000103835551 main + 289
53  libdyld.dylib                       0x00007fff73c147fd start + 1
54  ???                                 0x0000000000000002 0x0 + 2
```

</details>

### PR DESCRIPTION
**Pull request by sentialx**
#### Description of Change
Since Electron is using `SiteInstance::CreateForURL` instead of `SiteInstance::CreateForGuest`, Chromium tries to swap the browsing instance when COOP is triggered, but that's not supported in `<webview>`. So I made a patch disabling COOP only for guest WebContents.

Could this be backported to 9-x-y?

Fixes #25469, #25421

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed loading twitter.com and other websites enforcing Cross-Origin-Opener-Policy in `<webview>`.

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
Is this a thing that should be upstreamed to Chromium?

**Comment by sentialx** [comment]
Maybe, I don't know.

**Comment by deepak1556** [comment]
Why can't we use `CreateForGuest` instead ? I believe `CreateForURL` was used following upstream and we didn't make the transition when upstream change was made in https://chromium-review.googlesource.com/c/chromium/src/+/1959337

**Comment by sentialx** [comment]
@deepak1556 Because then, WebUI pages would not load in a `<webview>`. Chromium is using the `is_guest` property to also disallow loading WebUI pages, see here: https://source.chromium.org/chromium/chromium/src/+/master:content/browser/renderer_host/render_frame_host_impl.cc;l=6881;drc=f8a50cecbdeec78553325d9996dc14ab31e21b20

I also feel that the unsupported BrowsingInstance swapping mechanism may be somehow related to setDevToolsWebContents not working for webviews, but I don't know.

That's the reason why Twitter is working in webview with CreateForGuest...
https://source.chromium.org/chromium/chromium/src/+/master:content/browser/renderer_host/render_frame_host_manager.cc;l=1536

**Comment by deepak1556** [comment]
> WebUI pages would not load in a <webview>. Chromium is using the is_guest property to also disallow loading WebUI pages, see here:

I don't think this should be an issue, we never explicitly supported loading webui pages in `<webview>`. Also aligning with chromium security policy is a good move.


> That's the reason why Twitter is working in webview with CreateForGuest...

We only force process restart for browser side navigations when renderprocessreuse option is not set https://github.com/electron/electron/blob/master/patches/chromium/frame_host_manager.patch but we always force a process restart for renderer side navigations https://github.com/electron/electron/blob/master/patches/chromium/revert_remove_contentrendererclient_shouldfork.patch irrespective of renderprocessreuse. 

The answer for twitter.com issue lies whether it is performing a render side navigation or browser side navigation in your test case.


I would suggest two changes to this PR,

1) Guard ElectronRenderClient::ShouldFork implementation based on renderprocessreuse option
2) Convert webview site instance to be based on CreatForGuest

**Comment by sentialx** [comment]
> I don't think this should be an issue, we never explicitly supported loading webui pages in <webview>. Also aligning with chromium security policy is a good move.

Many projects rely on loading `chrome-extension` scheme and other WebUIs into `<webview>` including mine.

**Comment by deepak1556** [comment]
Hmm I am not sure how long we can support that, at some point we would flip the switch to align process policies with chromium. What needs to done is provide a GuestView that can load webUi pages for your use case and not rely on webview.

For now we can ignore the CreatForGuest change and fix the implementation in ElectronRenderClient::ShouldFork for renderprocessreuse.

**Comment by sentialx** [comment]
@deepak1556 How can I patch ShouldFork?

**Comment by miniak** [comment]
@sentialx are you still planning to land this PR?

**Comment by codebytere** [comment]
Closing as abandoned.

**Pull request closed without merging**
