### PR TITLE
fix: crash when loading wasm in mac arm64

### PR DESCRIPTION
**Pull request by deepak1556**
#### Description of Change

Instead of defaulting to always write protect, prefer v8 fix that does write and executable protection hop using background thread https://chromium-review.googlesource.com/c/v8/v8/+/2378307 .

Test: https://gist.github.com/deepak1556/c85a324822bf64ffeef450f3d1f33119
Refs https://github.com/microsoft/vscode/issues/106770#issuecomment-719877989

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: fix crash when loading wasm in mac arm64

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
@deepak1556 in my work of getting CI testing working on a DTK, I found that this patch is not needed at all: https://github.com/electron/electron/pull/24832/

**Comment by deepak1556** [comment]
@jkleinsc that would be ideal, is there a timeline for when the native compiled arm64 releases will be available ? The current cross compiled build is a no-go for vscode because of this wasm crash. Also while testing this fix realized that v8 made most of its fixes using `V8_HOST_ARCH_ARM64` so this change won't get picked up, really need native compiled bits.

**Comment by jkleinsc** [comment]
@deepak1556 native arm64 releases are currently available for 11-x-y betas as well as on our nightly builds.

**Comment by deepak1556** [comment]
Isn't it cross-compiled https://github.com/electron/electron/blob/master/.circleci/config.yml#L141 ?

**Comment by jkleinsc** [comment]
@deepak1556 ah --I missed the cross-compiled bit of your comment.  Yes we cross-compile the arm64 binary on x64.  We won't have a native compiled arm64 release until our CircleCI provides arm64 macs and as of right now I don't have a date for that.

**Comment by deepak1556** [comment]
@MarshallOfSound @jkleinsc can we remove the following patches from 11-x-y branch ? chrome arm64 beta (87.0.4280.67) is available without these, so I don't think we need them either ?

https://github.com/electron/electron/blob/11-x-y/patches/v8/chore_add_v8_apple_silicon_patches.patch
https://github.com/electron/electron/blob/11-x-y/patches/v8/fix_use_proper_page_size_for_mac_arm64.patch

**Comment by jkleinsc** [comment]
@deepak1556 yes -- I'll put up a PR for that. #24832 is waiting until I have enough macs to run arm64 CI, but we can just address 11-x-y for now.

**Comment by jkleinsc** [comment]
@deepak1556 PR is up here: #26650

**Pull request closed without merging**
