### PR TITLE
refactor: ginify Notification

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Also, add some tests.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
#### Release Notes

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
cc @sethlu

**Comment by nornagon** [comment]
@zcbenz hmm, that seems like it might be the intended behavior on Windows in the underlying API?

If an app crashes, it won't be able to call any OS functions to remove notifications.

**Comment by zcbenz** [comment]
It think this is similar to Tray icons, it is fine to leave a ghost icon there if the process crashed, but it should clear the icon if it exited normally.

But anyway I tried to find out the original issue about this but didn't succeed, let's just do this way.

**Comment by zcbenz** [comment]
Also I think this should be marked as `feat` and documented for the same reason with https://github.com/electron/electron/pull/22822#issuecomment-604153428.

**Comment by nornagon** [comment]
Blocking on #22822 for solutions to the same problems described above.

**Comment by nornagon** [comment]
NB this removes the `.destroy` method from `Notification`, because it's not documented and not tested.

**Pull request merged**
