### PR TITLE
feat: GPU shared texture offscreen rendering (33-x-y)

### PR DESCRIPTION
**Pull request by reitowo**
Backport of https://github.com/electron/electron/pull/42953

See that PR for details.

Notes: Added GPU accelerated shared texture offscreen rendering.

### CODE REVIEW

**Comment by reitowo** [comment]
Verified to work locally.

**Comment by ckerr** [comment]
@reitowo the Releases Working Group meets on Wednesdays and that is usually when big backports like this one are considered. That is probably the next step for this PR

**Comment by reitowo** [comment]
OK, Let's wait.

**Comment by ckerr** [comment]
In the interim, there's a linting error in this PR:

> /__w/electron/electron/src/electron/spec/api-browser-window-spec.ts
>  20:1  error  There should be at least one empty line between import groups    import/order
>  21:1  error  `electron` import should occur before import of `electron/main`  import/order

If this is a verbatim backport, I'm not sure why this is showing up in 33 but not 34 :thinking:

**Comment by reitowo** [comment]
This file had a merge conflict, and I merged manually. Probably I'm the one to be blamed. 🫣

**Comment by reitowo** [comment]
Thanks!

**Review by jkleinsc — APPROVED** [review]

**Comment by reitowo** [comment]
Just to ask, when will the next 33 release happen including this change? 😘

**Pull request merged**
