### PR TITLE
docs: Type names changed from Wrapper to Primitive #14023

### PR DESCRIPTION
**Pull request by infinity052**
Reference issue - #14023 
### Description of Change
Changed all the types from wrappers to primitive types in all the files of the docs.
For example: 
(before) type : "String"
(after) type : "string"

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@infinity052 Hey, thanks for this.  Looks like the CI is failing because you've missed a few.  You have to update every single one of these for this to work 😄

**Comment by infinity052** [comment]
hey @MarshallOfSound, I did find a couple more types that got missed, my bad. But I've changed them all now and have double-checked. Still don't have any idea why the ci is failing, can you please let me know?

**Comment by MarshallOfSound** [comment]
Your changes have resulted in typescript errors.  My guess is you've changed types incorrectly.

image

**Comment by infinity052** [comment]
Screenshot (11)
The typescript error seems to be on master branch too. And also I haven't touched the typescript files mentioned in the error, just the .md files in the docs. Have no idea why this error is occuring.

**Comment by MarshallOfSound** [comment]
@infinity052 Our TS definitions file is auto-generated from our markdown documentation.  By changing the markdown docs you will also be changing the TS definition file.

**Comment by codebytere** [comment]
@infinity052 do you still wish to work on this?

**Comment by nornagon** [comment]
Closing this for now as it's stale, but I like this idea and would support reopening it if someone wants to pick it up again!

**Comment by miniak** [comment]
Taking over

**Pull request closed without merging**
