### PR TITLE
Add `webContents.startDrag(item)` API

### LINKED ISSUE #4622: OS native File Drag from Electron to *
The best way to start a File-Drag for now, is the downloadURL as i know.

Like here in Nylas N1:
https://github.com/nylas/N1/blob/master/internal_packages/attachments/lib/attachment-component.cjsx#L67

But only Images and PDFs are able to Drop direct on an Application (MAC). Other file formats just can be copied to Folders.
I think I'm not the only one who is looking for a full native file drop and I think chromium offers that already.

On chrome://downloads/ its possible to Drag any File on an Application (Mac).

Is there maybe a way to access this Drag Function in electron or can it become a part of?
Multi File Drag would be very nice too! :)

[chrome://downloads/ > js dragstart > chrome.send('drag', id)](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/resources/md_downloads/crisper.js&q=crisper.js&sq=package:chromium&type=cs&l=15751)

I have no knowledge, about cc++ but it found that... :D
[drag_download_item_views.cc](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/download/drag_download_item_views.cc&q=DragDownloadItem&sq=package:chromium&dr=CSs&l=31)
[md_downloads_dom_handler.cc](https://chromium.googlesource.com/chromium/src.git/+/master/chrome/browser/ui/webui/md_downloads/md_downloads_dom_handler.cc)

### PR DESCRIPTION
**Pull request by zcbenz**
Close #4622.

## Dragging files out of the window

For certain kinds of apps that manipulate on files, it is important to be able
to drag files from Electron to other apps. To implement this feature in your
app, you need to call `webContents.startDrag(item)` API on `ondragstart` event.

In web page:

```html
<a href="#" id="drag">item</a>
<script type="text/javascript" charset="utf-8">
  document.getElementById('drag').ondragstart = (event) => {
    event.preventDefault()
    ipcRenderer.send('ondragstart', '/path/to/item')
  }
</script>
```

In the main process:

```javascript
ipcMain.on('ondragstart', (event, filePath) => {
  event.sender.startDrag({
    file: filePath,
    icon: '/path/to/icon.png'
  })
})
```

### CODE REVIEW

**Comment by bpasero** [comment]
Nice! Some questions:
* I assume this solution does not prevent the normal HTML DND with dataTransfer to support DND inside the window?
* when I use this mechanism and drop to another Electron window, will I be able to read the dragged files in the same way I can do it today (e.g. when someone drags a file from the desktop onto the window)?
* how would this support DND of multiple files?

**Comment by zcbenz** [comment]
> I assume this solution does not prevent the normal HTML DND with dataTransfer to support DND inside the window?

No, this API just adds the file to current drag data, it doesn't remove existing data. So usually you need to call `event.preventDefault()` to prevent the default DND of DOM.

> when I use this mechanism and drop to another Electron window, will I be able to read the dragged files in the same way I can do it today (e.g. when someone drags a file from the desktop onto the window)?

It should be exactly the same.

> how would this support DND of multiple files?

I actually added the support, but somehow it doesn't work on Windows. The code path was never ran in Chromium, so I guess this is a bug of Chromium's dragging code.

You can try with `startDrag({files: ['file1', 'file2']})`.

**Comment by mattetti** [comment]
Thanks @zcbenz that's exactly what I needed. I'll build Electron using your PR and run a few tests.The API is very straightforward and the doc very clear. Based on the fact that Chrome's downloads DnD to apps work, I don't see why this wouldn't.

Super exciting!

**Comment by mattetti** [comment]
Confirmed working well on macOS. Thanks @zcbenz

**Comment by quicksnap** [comment]
@zcbenz Thank you _so much_ for taking the time to implement this feature! We really appreciate it. Our organization created the chromium hack that this feature mostly obviates.

What kind of effort is involved in fixing drag-out for multiple files? Unfortunately, I believe I'll personally have a hard time tracking down, filing and/or fixing the bug in Chromium myself. But it still remains a requirement for our needs.

I'd love to get off our fork--your code is much nicer =) Can I help in any way at least to file a Chromium bug?

**Comment by quicksnap** [comment]
Also, we have code that works in windows for multiple files, but it does so directly with Windows API and file paths. Not ideal to introduce to Electron, I imagine.

**Comment by zcbenz** [comment]
@quicksnap Under the hood the API is calling into `OSExchangeDataProviderWin::SetFilenames`:
https://cs.chromium.org/chromium/src/ui/base/dragdrop/os_exchange_data_provider_win.cc?sq=package:chromium&dr=Ss

Chromium itself only uses `SetFilename`, so we are calling an untested code path.

**Comment by docmars** [comment]
This is fantastic! Thanks for implementing this.

Is there any chance in supporting DOM nodes for use in place of the drag icon image? The Drag & Drop API in browsers support passing a node in the `img` parameter with `event.dataTransfer.setDragImage(img, xOffset, yOffset)`, which is really handy for building custom ghost images.

For instance, say you're making a presentation app and you want to drag a slide out into Finder/Explorer or another app. Using the node for the slide to represent the drag image would make the most sense. Let's say I'm dragging multiple slides. I would want to add a number counter to my drag image. This could all be done with just a few styled elements.

If there's already a way to do this that I'm missing, I'd be very interested!

**Comment by hems** [comment]
@docmars 's suggestion is pretty cool! i would also be curious how to make it work with a list of files instead of a single file, is it possible somehow?

**Comment by GeekDenCode** [comment]
Hello. Any news about multiple files?

**Comment by bennol** [comment]
@GeekDenCode 

Have a look at the `webContents.startDrag()` documentation: https://electronjs.org/docs/api/web-contents#contentsstartdragitem

Your item must have an `icon` property:
```
const nativeImage = require('electron').nativeImage

var myDragIcon =  nativeImage.createFromPath('...') // Insert path of the image you want do display as drag icon
webContents.startDrag({
    files: ['...'], // Insert paths of files you want to drag
    icon: myDragIcon
})

```

**Comment by eschirtz** [comment]
I know it's been a while, but any updates on @docmars request? I noticed that figma (app built with electron) is doing something similar, but unsure of how they implemented it.

**Comment by hems** [comment]
I'm curious to know if audio files can be dropped directly into audio software, like Ableton Live or Pro Tools.

I remember having issues with dragging files out of the window, so i had to drag to the desktop before dragging to the target app.

Is that OK on the current implementation ?

**Comment by eschirtz** [comment]
@hems this does work with the current implementation. Im currently developing an app that relies on this exact functionality.

**Comment by hems** [comment]
> I'm curious to know if audio files can be dropped directly into audio software, like Ableton Live or Pro Tools.

I just tried this and it worked!

Since it's my first time using Electron the pathing was a bit tricky.

I had to put the "Icon" and the "file" to be dragged into the "public" folder, run a build so the file ended up in the `app` directory and from there i was able to do the drag.

I'll read more about path / resources / etcs on Electron and try to understand it a bit better.

**Pull request merged**
