### PR TITLE
refactor: use std::make_unique<T> / std::make_shared<T>

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
It's more readable, safer and we don't need to repeat the type twice.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by dsanders11** [comment]
I think the title should be use `std::make_unique<T>/std::make_shared<T>`?

I have similar changes on a branch, but covered a few more cases, and did `base::MakeRefCounted<T>` as well. I hadn't gotten around to submitting it. It also includes replacing `.reset(..)` and usages in member variable initialization. @miniak, you're welcome to cherry-pick any of the changes to add to this PR if you'd like: a21a505240de111f6364500edee63e6da487d299

**Comment by miniak** [comment]
@dsanders11 I am ok with abandoning this PR if favor of yours if you publish it

**Comment by dsanders11** [comment]
@miniak, ok, that works, thanks. I've opened #29510.

**Comment by miniak** [comment]
Closing in favor of #29510

**Pull request closed without merging**
