### PR TITLE
refactor: merge duplicate _windowOpenHandler exception handling

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Follow-up to #34523

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: none

### CODE REVIEW

**Review by nornagon — APPROVED** [review]

**Comment by miniak** [comment]
@codebytere I am wondering why you moved the exception handling to the `_callWindowOpenHandler` call-site instead of doing it inside of `_callWindowOpenHandler`

**Comment by miniak** [comment]
@codebytere, @nornagon I would like to refactor it a bit more in #34591

**Comment by codebytere** [comment]
@miniak : https://github.com/electron/electron/pull/34523#discussion_r895473687

**Review by codebytere — CHANGES_REQUESTED** [review]
This change was intentional: see https://github.com/electron/electron/pull/34523#discussion_r895473687 cc @MarshallOfSound

**Comment by miniak** [comment]
@codebytere I see that, but I don't understand why we need to do it like that. Isn't this variant of the code doing the same thing?

**Pull request closed without merging**
