### PR TITLE
chore(extensions): remove unused features json

### PR DESCRIPTION
**Pull request by samuelmaddock**
#### Description of Change
A few of the extension features we include were copied from Chrome's feature json files. As such, they included support for contexts unsupported by Electron such as platform apps, hosted apps, and login screens (ChromeOS).

ref #19447

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by nornagon — APPROVED** [review]

**Review by ckerr — APPROVED** [review]
Nice catch.

Was this a random find, or did you do something that led you to this? I'm wondering now if we include other unused pieces...

**Comment by samuelmaddock** [comment]
> Was this a random find, or did you do something that led you to this? I'm wondering now if we include other unused pieces...

I had been looking into how script contexts are classified by the extensions system. Different classifications cause different APIs to be injected/supported.

In this case, I was comparing which extension permissions are supported in Electron vs Chrome. Fwiw, I checked the other `shell/common/extensions/api/_*_features.json` files and this was the only one with unused features.

**Comment by codebytere** [comment]
This looks like a legit crash caused by this PR:
```
[529:0929/154713.804183:FATAL:complex_feature.cc(10)] Check failed: features->size() > 1UL (1 vs. 1)
#0 0x00005c6e93df base::debug::CollectStackTrace()
#1 0x00005c62af82 base::debug::StackTrace::StackTrace()
#2 0x00005c641fa7 logging::LogMessage::~LogMessage()
#3 0x00005c6429df logging::LogMessage::~LogMessage()
#4 0x00005c626f32 logging::CheckError::~CheckError()
#5 0x000060e094de extensions::ComplexFeature::ComplexFeature()
#6 0x00005c538517 extensions::AddElectronPermissionFeatures()
#7 0x000058cf1e8c electron::ElectronExtensionsAPIProvider::AddPermissionFeatures()
#8 0x000060e09189 extensions::ExtensionsClient::CreateFeatureProvider()
#9 0x000060e0a48c extensions::FeatureProvider::GetByName()
```

**Comment by samuelmaddock** [comment]
@ckerr to elaborate further on unused APIs, the extensions system includes its own core collection of them which we use via https://github.com/electron/electron/blob/b43859f0984fbdd2954f1e8f97b7c4cadc0f48d4/shell/common/extensions/electron_extensions_client.cc#L69

This comes with a lot of API features via [_api_features.json](https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/api/_api_features.json) which we're not making full use of yet. My hope is to one day change that by possibly allowing a [script context type](https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/features/feature.h;l=32-43;drc=90ec3ea8494439da8fe0b924a24aea3cb9c1d2dd) to be configurable in Electron.

**Comment by samuelmaddock** [comment]
@codebytere thanks, it should be good now. the mac build may need a restart

**Review by codebytere — APPROVED** [review]

**Pull request merged**
