### PR TITLE
fix: update shell.openExternal to correctly focus on external window

### PR DESCRIPTION
**Pull request by alicelovescake**
#### Description of Change
This PR fixes bug [identified in Slack](https://electronhq.slack.com/archives/CB6CG54DB/p1729185377925139) where Electron 33 doesn't focus the browser window when opening links when using shell.openExternal.

**Current behavior:**
- If the URL was successfully opened and the options.activate flag is set to true, the method calls [[NSApp activateIgnoringOtherApps:YES].](https://developer.apple.com/documentation/appkit/nsapplication/1428468-activateignoringotherapps) This call forces the Electron app to become the active application, bringing it to the foreground and giving it focus, regardless of whether another application is currently active.

**Updated behavior:**
- The URL is opened with [`openURL:configuration:completionHandler`](https://developer.apple.com/documentation/appkit/nsworkspace/3172701-openurl) with configuration [`activates`](https://developer.apple.com/documentation/appkit/nsworkspaceopenconfiguration/3172704-activates) which ensures that the external application is activated (brought to the foreground) when the URL is opened.

### Before
https://github.com/user-attachments/assets/1162bada-3128-49db-b211-ea26c124c26b 

### After
https://github.com/user-attachments/assets/706da9af-9f6b-436a-a84a-4714a879fa49 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fix external window focus when using shell.openExternal

### CODE REVIEW

**Review by VerteDinde — APPROVED** [review]
Nice, thanks for fixing this!

**Review by codebytere — COMMENTED** [review]
Nice 🥳  I'd like to see a regression test added here - we can just call `shell.openExternal` and then ensure the window is focused afterward!

**Comment by alicelovescake** [comment]
> Nice 🥳 I'd like to see a regression test added here - we can just call `shell.openExternal` and then ensure the window is focused afterward!

Great idea! Added a new test that checks the focus of the window before and after. Confirms that it currently fails on the 33-x-y branch and passes on the feature branch.

Quick question: I added [`BindPostTaskToCurrentDefault`](https://source.chromium.org/chromium/chromium/src/+/main:base/task/bind_post_task.h;l=98?q=BindPostTaskToCurrentDefault&ss=chromium) but the chromium source comments mention to use it as a last resort. Do you recommend another task runner I should use for the callback?
I tried `content::GetUIThreadTaskRunner` but that caused a crash when we try to open the link from the renderer.

**Review by felixrieseberg — APPROVED** [review]
Solid change (and neat!). I don't know if that's at all helpful but I also had to test whether another app is active and focused in this PR (https://github.com/electron/electron/pull/40307/files#diff-16e70053ee400a01ab268e031a0ac295a011ed7f49d22be1a698663ee062e6aeR1229). Maybe you can steal some code!

**Review by jkleinsc — CHANGES_REQUESTED** [review]
LGTM pending the addition of a test.

**Review by samuelmaddock — APPROVED** [review]
PR description is concise and easy to follow. lgtm!

**Pull request merged**
