### PR TITLE
refactor: WebContents.send -> mainFrame.send

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Simplify webContents.send using the WebFrameMain API.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes

Notes: none

### CODE REVIEW

**Review by miniak — APPROVED** [review]

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
@nornagon can you rebase this?

**Comment by codebytere** [comment]
@nornagon can you rebase this?

**Comment by samuelmaddock** [comment]
Empty diff. Changes may have accidentally been included in #27475

**Comment by nornagon** [comment]
cool :) never seen a "0 files changed" pr before.

**Pull request closed without merging**
