### PR TITLE
build: fix missing deps when pdf support is disabled

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
cc @deermichel 

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: none

### CODE REVIEW

**Comment by codebytere** [comment]
@miniak needs rebase

**Review by deepak1556 — CHANGES_REQUESTED** [review]
`pepper_flash_font_file_host.cc` which depended on `pdf::GetFontTable` https://chromium-review.googlesource.com/c/chromium/src/+/2967218 is no longer present in `main` with removal of pepper flash support

**Comment by deepak1556** [comment]
`//pdf:font_table_linux` is still needed when pepper pdf is enabled but in that case it should be included behind `enable_pdf` condition.

**Comment by deermichel** [comment]
Yeah, I need to revisit that patch for e18 - once I find a free spot in my schedule 😄  ...

**Pull request closed without merging**
