### PR TITLE
[WIP] fix debug build on linux

### PR DESCRIPTION
**Pull request by codebytere**
Closes https://github.com/electron/electron/projects/7#card-6272321.

Working to fix the debug build for C63 on linux

/cc @alexeykuzmin

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
Hm... I remember it correctly we already did `NODE_BUILTIN_MODULE_CONTEXT_AWARE -> NODE_MODULE_CONTEXT_AWARE_BUILTIN` replacement somewhere.

**Comment by codebytere** [comment]
@alexeykuzmin i thought that too...i think this is a result of the node version mismatch that i mentioned to you a while ago, i'll undo it once i update the node version in C63 and conrirm

**Comment by alexeykuzmin** [comment]
@codebytere Let me rebase the Ch63 branch onto the latest master first. There is a chance the errors will go away after it.

**Comment by codebytere** [comment]
i'm just gonna branch off again

**Pull request closed without merging**
