### PR TITLE
Set Google API keys with environment variables

### LINKED ISSUE #6648: Provide a way to dynamically set GOOGLEAPIS_API_KEY
* Electron version: 1.3.1
* Operating system: OS X 10.11.6

Follow the instructions for running the electron-quickstart.  Modify the index.html by adding this script to the bottom:

```
<script>
	window.addEventListener('load', function() {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function(result) {
				console.log(result);
			}, function(error) {
				console.log(error);
			});
		}
	});
</script>
```

You will now see a Position Error in your console when running.  Error Code 2, 403 returned from google.  Adding a permission request handler to your session and always calling the callback with true does not eliminate this error.

### PR DESCRIPTION
**Pull request by zeke**
I cherry-picked these commits from the [brave fork](https://github.com/brave/electron), per @bbondy's suggestion.

Fixes #6648

### CODE REVIEW

**Comment by deepak1556** [comment]
* Does `GOOGLE_API_ENDPOINT` take effect for other services than geolocation ? As far as i know the speech recognition endpoint is hardcoded [here](https://cs.chromium.org/chromium/src/content/browser/speech/speech_recognition_engine.cc?s&l=35).

* If the endpoint was just for geolocation then we could have an api on app instead to set the geolocation service, the hack of having to combine endpoint and api key separately for geolocation is not needed when its a service other than the default.

**Comment by kevinsawicki** [comment]
Would be great to get some docs for these two so people know what they need to set, what the errors look like, and what it affects.

**Comment by bbondy** [comment]
Thanks, you probably want this before it is merged too:
https://github.com/brave/electron/commit/dcfd986ad53487b84c269ec2a195f763ccedcc90

It allows the key to be baked into the binary instead of needing the app to have an environment at runtime.

**Comment by zcbenz** [comment]
We also need to document how to get the keys, which is described in https://www.chromium.org/developers/how-tos/api-keys.

**Pull request closed without merging**
