### PR TITLE
chore: remove unused sendToAll + related APIs

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
No longer needed after the native Chrome extensions support has landed.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Review by nornagon — APPROVED** [review]
🎉

**Review by codebytere — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Review by samuelmaddock — APPROVED** [review]
Nice! Do we know which API relied on this with the JS chrome extensions implementation?

**Comment by miniak** [comment]
@samuelmaddock https://github.com/electron/electron/blob/24a1234e28cab6314271211ba8f1b4b40bfd3002/lib/renderer/chrome-api.ts#L50-L59

**Pull request merged**
