### PR TITLE
build: missing include in windows release builds 

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

OK this has been a journey. This patch includes three parts:

1. Manual backport of #21045 (plus a handful of similar issues found in `8-x-y` not present in `master`). See that PR for full description. (CC @codebytere, @jkleinsc)

2. Add `breakpad` as a target for our patches, since we now need to patch that in a couple of places. Unfortunately one of those patched files has dos-style crlf line endings, which prompts the third part:

3. In `electron/scripts`' import/export patches, add support for patching dos-style files whose lines end with crlf. Previously we were stripping line endings and appending `\n` to the end of each line, which caused `git am` to fail when patching dos files. It might be worthwhile to apply this portion to `master` as well even if we're not currently patching any crlf files there. (CC @nornagon, who patched a [similar problem](https://github.com/electron/electron/pull/15579) last year, for second opinion)

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by codebytere** [comment]
@ckerr since this is direct to 8, we should ensure that the patch formatting changes make it back to `master`

**Comment by jkleinsc** [comment]
Passing win-x64 release here: https://ci.appveyor.com/project/electron-bot/electron-x64-release/builds/28940243

**Comment by jkleinsc** [comment]
Passing woa release build here: https://ci.appveyor.com/project/electron-bot/electron-woa-release/builds/28940248

**Comment by jkleinsc** [comment]
Merging as Windows release builds are successful.

**Pull request merged**
