### PR TITLE
fix: deny instead of canceling when certificate-error passes false

### LINKED ISSUE #21867: certificate-error will not fire did-fail-load on callback(false)
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
5.0.0 to 8.0.0 beta7
* **Operating System:**
Windows 10

### Expected Behavior
The did-fail-load event should be fired.

### Actual Behavior
The did-fail-load event is not fired.

### To Reproduce
Add an event handler to the did-fail-load event.
Add an event handler to the certificate-error event and cancel the default handling. Then call the callback with false.
The did-fail-load event will not be fired.

```
mainWindow.webContents.on("certificate-error", (event, url, error, certificate, callback) => {
      event.preventDefault();
      callback(false)
});

mainWindow.webContents.on("did-fail-load", (event, url, error, certificate, callback) => {
      console.log("did-fail-load");
});
```

Electron fiddle gist:
https://gist.github.com/c1427e38bf0af9a5e78088fcea6e3c66

### Additional Information
loadURL returns a Promise, in the certificate error case this Promise will be rejected. The gist will show this too.

```
mainWindow.loadURL('https://expired.badssl.com')
  .then(() => console.log("success"))
  .catch(e => console.log("fail"))
```

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
When the certificate-error callback is invoked with `false`, deny the request
instead of cancelling it. This has a few effects:

1. The 'did-fail-loading' event will be properly emitted on WebContents (see
   #21867).
2. The error that is passed along will be the certificate error that was
   encountered, instead of net::ERR\_ABORTED.

Fixes #21867.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed the 'did-fail-load' event not being emitted when the 'certificate-error' handler allowed an error through.

### CODE REVIEW

**Comment by codebytere** [comment]
@nornagon is this testable? not sure how easy it is to test cert-related things 🤔

**Comment by nornagon** [comment]
@codebytere yep it's for sure testable, I'll add a test.

**Review by deepak1556 — APPROVED** [review]
👍

**Comment by nornagon** [comment]
linux build failing due to broken ci; merging.

**Pull request merged**
