### PR TITLE
Continue the work of Chrome 50 upgrade

### PR DESCRIPTION
**Pull request by zcbenz**
* [x] Mac App Store build not building
* [x] ia32 target of Linux not building
* [x] Switch to Visual Studio 2015 for building
* [x] Upgrade to Node v6.1.0
* [x] Crash in renderer process: `node::Buffer::CallbackInfo::CallbackInfo`
* [x] Crash in renderer process: `v8::internal::Isolate::FireBeforeCallEnteredCallback`
* [x] Crash in renderer process: `v8::internal::GlobalHandles::Node::Release()`
* [x] Crash in renderer process: `content::BlinkPlatformImpl::SetCompositorThread`
* [ ] crashReporter not working on x64 Windows
* [x] Linking error when building Release version on Windows

### CODE REVIEW

**Comment by bbondy** [comment]
Nice to see 6.1 and VS2015 👍 
Could you also merge in brightray's branch? Thanks!

**Comment by zcbenz** [comment]
Sure thing.

**Comment by paulcbetts** [comment]
We should make sure to call out the node 6.x breaking change of `path.join(undefined, "foo")` throwing now, I suspect it will break people

**Comment by rgbkrk** [comment]
That throws in `v5.10.1` as well:

```
$ node
> process.version
'v5.10.1'
> path.join(undefined,'sdaf')
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
```

**Pull request merged**
