### PR TITLE
fix: crash in sandbox on linux when getting execPath

### PR DESCRIPTION
**Pull request by nornagon**
calling `base::PathService::Get(base::FILE_EXE, &path)` on linux crashes with `--enable-sandbox`:

```
#0  0x00007faabaa2ae97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007faabaa2c801 in __GI_abort () at abort.c:79
#2  0x000056153ea42085 in  () at ./../../base/debug/debugger_posix.cc:258
#3  0x000056153e97e5be in ~LogMessage() () at ./../../base/logging.cc:858
#4  0x000056153ea55ac4 in PathProviderPosix() () at ./../../base/base_paths_posix.cc:43
#5  0x000056153e9b11ed in Get() () at ./../../base/path_service.cc:207
#6  0x000056153e90857c in GetExecPath () at ../../electron/atom/renderer/atom_sandboxed_renderer_client.cc:85
#7  0x000056153e90857c in InitializeBindings() () at ../../electron/atom/renderer/atom_sandboxed_renderer_client.cc:160
#8  0x000056153e9093f5 in DidCreateScriptContext() () at ../../electron/atom/renderer/atom_sandboxed_renderer_client.cc:219
#9  0x000056153e906607 in DidCreateScriptContext() () at ../../electron/atom/renderer/atom_render_frame_observer.cc:96
#10 0x0000561542469ae5 in DidCreateScriptContext() () at ./../../content/renderer/render_frame_impl.cc:5150
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes:
* fix a crash on Linux when starting a sandboxed renderer
* the `resourcesPath` property is no longer available on `process` in sandboxed renderers

### CODE REVIEW

**Comment by miniak** [comment]
@nornagon, I don’t remember exactly, I should probably just have used `process.helperExecPath` in the first place

**Comment by nornagon** [comment]
I'm also still uncertain about removing `resourcesPath`. Can anyone say for sure whether that will/won't break something important?

**Comment by miniak** [comment]
@nornagon `resourcesPath` was added just for consistency. We don’t use it. But somebody else might.

**Comment by nornagon** [comment]
Merging this without review from @electron/docs because the change to docs is trivial.

I'm removing `resourcesPath` because I'm not sure that a sandboxed renderer could actually do anything useful with that path, what with being sandboxed and all. Happy to restore it if someone comes up with a use case though!

**Pull request merged**
