### PR TITLE
chore: Remove unnecessary zlib patch

### PR DESCRIPTION
**Pull request by kromain**
#### Description of Change
zlib is now built statically like all other Chromium components,
there are no symbols to export anymore. This patch can be removed.

#### Checklist

- [X] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by kromain** [comment]
CC @codebytere 

I *think* this patch isn't needed anymore, at least I can build fine on Windows without it. However I'm not sure I completely understood the reason for adding it in the first place, so I might have missed something.
The only reason I looked into it was that it was interfering with component builds, causing zlib symbols to be exported multiple times. So I first disabled it for component builds, which helped, but then I wondered why it was there for non-component builds, since there are no DLLs at all there.

**Review by codebytere — COMMENTED** [review]
@kromain for context i added that [here](https://github.com/electron/electron/pull/23789/commits/105852e48513dd207e822320104edb2da7a3b63d) to address [this change](https://github.com/nodejs/node/commit/9e33f97c4ea4ba74375e3ecab1cf0fede069d016) in Node.js - Do you have a link to the Chromium Cl which changed zlib to be statically build and therefore not require the change made in my original commit? Once i can verify that we can approve and merge this :)

**Comment by kromain** [comment]
@codebytere thanks for the additional context and the links. I went back to those and now I better understand the purpose of the patch: this isn't about zlib being built as a dll or statically (it has always been built statically in non-component builds), but it's about having the zlib symbols in the static lib exported by electron.exe, which is needed for native Node modules (https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook).

Removing this patch makes the symbols not exported by electron.exe anymore. It doesn't affect the Electron build itself, but it will affect building native modules that need these zlib symbols. So I don't think this patch should be removed after all.

ps: as it stands the patch still breaks component builds, because it conflicts with how zlib already exports its symbols from its own dll. (same issue as in #15138). Would it be acceptable to you if we updated the patch this way:

```patch
-+  if (is_win) {
++  if (is_win && !is_component_build) {
 +    defines += [ "ZLIB_DLL" ]
 +  }
 +
``` 

I understand that Electron doesn't officially support component builds anymore, but I'm wondering if you'd still accept patches that fix issues with component builds without affecting regular builds. I have actually managed to get a successful component build, which requires the patch above and a few others tweaks (mainly adding a few dependencies to electron_lib). 

I guess I can open a separate PR with my other changes so we can discuss what you'd be willing to bring in. At least it'll be available for reference to others that want to attempt component builds on their own.

**Comment by nornagon** [comment]
Yep, this patch shouldn't be removed as it is needed for native node modules.

We don't support the component build officially, but we might consider minor changes on a case-by-case basis if they are low-maintenance.

**Pull request closed without merging**
