### PR TITLE
Build with dchecks disabled on subset of targets

### PR DESCRIPTION
**Pull request by deepak1556**
This pulls and tests https://github.com/electron/libchromiumcontent/pull/403

Refs https://github.com/electron/libchromiumcontent/issues/359

/cc @alexeykuzmin @alespergl @zcbenz @ckerr

### CODE REVIEW

**Comment by alespergl** [comment]
I quickly checked the failure
`[6975:1127/210918.696407:FATAL:url_util.cc(490)] Check failed: !scheme_registries_locked. Trying to add a scheme after the lists have been locked.`

I will disable DCHECK for the relevant GN target, but the problem is in how [`protocol.registerStandardSchemes`](https://electronjs.org/docs/api/protocol#protocolregisterstandardschemesschemes-options) is implemented. It will need to be refactored or removed to fix this properly. Schemes need to be added in [`AtomContentClient::AddAdditionalSchemes`](https://github.com/electron/electron/blob/124667c29b249b5f79c57c8abbf2912157370cc7/atom/app/atom_content_client.cc#L201) and nowhere else.

**Comment by alespergl** [comment]
@alexeykuzmin 
Not sure why this test is now timing out on Linux, but the build was green before the libcc branch was merged. Is it normal for this test to time out?
```
crashReporter module with sandbox should send minidump when renderer crashes - should send minidump when renderer crashes
```

**Comment by alexeykuzmin** [comment]
@alespergl that crash reporter test seems to be flaky. It fails quite often on linux, but not always.
https://circleci.com/gh/electron/electron
I think we can merge this PR and fix the test later.

**Comment by alespergl** [comment]
I seem to have lost merge rights here. Can someone else merge it? Please preserve the commits by creating a merge commit. Thanks

**Pull request merged**
