### PR TITLE
Allow custom window level when sending window to top

### PR DESCRIPTION
**Pull request by adammeyer**
This allows for a custom window level to be set when sending a window to the top.

```
win.setAlwaysOnTop(true, 102);
```

This can be used when the NSFloatingWindowLevel isn't high enough.  I have used this to put a window above the top menu bar.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Pretty cool, mind updating the docs as well for this?

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag

**Comment by kevinsawicki** [comment]
Might be useful to include the possible values as well of these https://developer.apple.com/reference/appkit/nswindow/1664726-window_levels#symbols in the docs

**Comment by adammeyer** [comment]
@kevinsawicki Thanks!  I added the details to the docs.  Currently the parameter is an integer, not a mac window level constant.  I like that idea, but I'm not sure how to take a constant in as a string and then convert it to the constant value in the native window controller.

**Comment by kevinsawicki** [comment]
> I like that idea, but I'm not sure how to take a constant in as a string and then convert it to the constant value in the native window controller.

I can help you update it, what do you think about these string value names for the different integer values:

* `NSNormalWindowLevel` -> `'normal'`
* `NSFloatingWindowLevel` -> `'floating'`
* `NSTornOffMenuWindowLevel` -> `'torn-off-menu'`
* `NSModalPanelWindowLevel` -> `'modal-panel'`
* `NSMainMenuWindowLevel` -> `'main-menu'`
* `NSStatusWindowLevel` -> `'status'`
* `NSPopUpMenuWindowLevel` -> `'pop-up-menu'`
* `NSScreenSaverWindowLevel` -> `'screen-saver'`
* `NSDockWindowLevel` -> `'dock'`

**Comment by adammeyer** [comment]
Looks great!  I committed my best attempt.  I'm getting some errors with the string declarations.

**Comment by kevinsawicki** [comment]
@adammeyer I pushed a change that gets things compiling.

When testing this though it is kind of hard to tell the differences between these levels, they seem to all be very similar.

Can you expand on how you plan to use it a bit?

**Comment by adammeyer** [comment]
I would like to open a window that fills the screen and is above the menu bar, without the animations that come with making a window "fullscreen".  Kind of like showing a PowerPoint presentation.  

I could also see it being used if you wanted multiple windows to always be on top, but one to be the top most of those.

**Comment by kevinsawicki** [comment]
> I would like to open a window that fills the screen and is above the menu bar

Which level allows this? Curious to test it locally.

**Comment by adammeyer** [comment]
I believe `screen-saver`.

**Comment by adammeyer** [comment]
Yes, just confirmed it is `screen-saver`

**Comment by adammeyer** [comment]
@kevinsawicki Anything left to add?

**Comment by zcbenz** [comment]
:+1:

**Comment by matheuss** [comment]
@adammeyer I just wanted to tell you that you're my hero – this will be *very useful* on [wulkano/kap](https://github.com/wulkano/kap) 😄

**Pull request merged**
