### PR TITLE
fix: input accept not work in mac  

### PR DESCRIPTION
**Pull request by dengyaolong**
see https://github.com/electron/electron/pull/11573

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@dengyaolong can you please rebase your branch onto the latest Electron's master?

**Comment by dengyaolong** [comment]
@alexeykuzmin Is this done?

**Comment by alexeykuzmin** [comment]
>> @dengyaolong can you please rebase your branch onto the latest Electron's master?
> @alexeykuzmin Is this done?

You have merged master into your branch, that's not exactly what I asked. But anyway.
I just restarted Linux build to check if it passes.

**Comment by dengyaolong** [comment]
so, what can I do in this pull request? Or there is any other way to fix this problem, cause I am suffer from this problem a long time...

**Comment by zcbenz** [comment]
I'm closing this in favor of #11959, which fixed the problem without breaking "All files" on macOS. But still thanks for your work on this!

**Pull request closed without merging**
