### PR TITLE
feat: expose sessionId in debugger module

### PR DESCRIPTION
**Pull request by deepak1556**
#### Description of Change

Fixes https://github.com/electron/electron/issues/24168

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: expose sessionId associated with a target from debugger module

### CODE REVIEW

**Comment by jkleinsc** [comment]
@electron/wg-api reviewed and approved this at our June 29, 2020 meeting

**Comment by codebytere** [comment]
(removing label as that label goes on the backports themselves ☝🏻)

**Comment by deepak1556** [comment]
Approval ping :)

**Comment by nornagon** [comment]
This is semver/minor, yes?

**Comment by deepak1556** [comment]
yup thats right, will mark the backports. Thanks!

**Pull request merged**
