### PR TITLE
Add mouse-enter and mouse-exit events for tray

### LINKED ISSUE #7616: Add Tray hover event
- Electron version:1.3.3
- Operating system:win10/mac

the Tray instance events shold provide the tray hover event. 
`tray.setToolTip` has limitations when do more operation.

### PR DESCRIPTION
**Pull request by shubham2892**
Fixes #7616 
Add API for listening to mouse-enter and mouse-exit events for Tray.

### CODE REVIEW

**Comment by zeke** [comment]
Related to https://github.com/electron/electron/issues/8689

cc @pronebird

**Comment by pronebird** [comment]
@zeke this PR introduces mouse hover support. That's different from when user clicks on other item in menubar...

**Comment by kevinsawicki** [comment]
Thanks for this @shubham2892 👍 

Pushed a few minor changes:

- Renamed `mouse-exit` to `mouse-leave` to be consistent with the `drag-leave` event name on Tray. Can revisit in the 2.0 API if we want to switch from `-leave` to `-exit`.
- Added the location and keyboard modifiers from the `NSEvent` to the emitted JavaScript event, similar to the `right-click` event.

**Comment by zeke** [comment]
✨ 🐭 ✨

**Comment by gclsoft** [comment]
https://electronjs.org/docs/api/tray#event-mouse-enter-macos
event-mouse-enter is works only on mac, not on Windows, right??

**Pull request merged**
