### PR TITLE
chore: enable check raw ptr fields

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change

- #37834 included a change to [Enable check_raw_ptr_fields for Linux](https://chromium-review.googlesource.com/c/chromium/src/+/4402277), but we disabled it to get the roll done.  This PR turns that check back on and updates the Electron codebase to use [raw_ptr](https://source.chromium.org/chromium/chromium/src/+/main:base/memory/raw_ptr.md) where possible.
- [RAW_PTR_EXCLUSION](https://chromium-review.googlesource.com/c/chromium/src/+/3298731) can be used on a field by field basis to skip the raw ptr field check.
#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by codebytere** [comment]
Looks like two issues left:

```
In file included from ../../base/functional/bind_internal.h:18:
../../base/allocator/partition_allocator/pointers/raw_ptr.h:539:17: error: static assertion failed due to requirement 'raw_ptr_traits::IsSupportedType<InAppTransactionObserver, void>::value': raw_ptr<T> doesn't work with this kind of pointee type T
  static_assert(raw_ptr_traits::IsSupportedType<T>::value,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../electron/shell/browser/mac/in_app_purchase_observer.h:78:37: note: in instantiation of template class 'base::raw_ptr<InAppTransactionObserver>' requested here
  raw_ptr<InAppTransactionObserver> observer_;
                                    ^
../../electron/shell/browser/mac/in_app_purchase_observer.h:78:37: error: private field 'observer_' is not used [-Werror,-Wunused-private-field]
  raw_ptr<InAppTransactionObserver> observer_;
                                    ^
2 errors generated.
```

**Comment by deepak1556** [comment]
Looks like the PR supersedes https://github.com/electron/electron/pull/35760, should we close that in favor of this PR ?

Additionally, can we address https://github.com/electron/electron/pull/35760#pullrequestreview-1116889885 as part of this PR ?

**Review by zcbenz — APPROVED** [review]

**Review by zcbenz — DISMISSED** [review]
It seems that the flag has actually caught a dangling pointer usage in the tests:

```
[524:0504/145614.453561:ERROR:partition_alloc_support.cc(630)] Detected dangling raw_ptr with id=0x00001b2400593af8:
[DanglingSignature]	std::Cr::__tree<>::destroy()	electron::api::WebContents::Destroy()	electron::api::WebContents::~WebContents()	electron::api::WebContents::Destroy()

The memory was freed at:
#0 0x5606501fe962 base::debug::CollectStackTrace()
#1 0x5606501e5463 base::debug::StackTrace::StackTrace()
#2 0x560650202a7f base::allocator::(anonymous namespace)::DanglingRawPtrDetected()
#3 0x5606501e2341 allocator_shim::internal::PartitionFree()
#4 0x56064b14365d std::Cr::__tree<>::destroy()
#5 0x56064b14363a std::Cr::__tree<>::destroy()
#6 0x56064b143646 std::Cr::__tree<>::destroy()
#7 0x56064b14363a std::Cr::__tree<>::destroy()
#8 0x56065013af36 base::SupportsUserData::~SupportsUserData()
#9 0x56064f4bd0b6 content::WebContentsImpl::~WebContentsImpl()
#10 0x56064f4bdbfe content::WebContentsImpl::~WebContentsImpl()
#11 0x56064b15fd6f electron::InspectableWebContents::~InspectableWebContents()
#12 0x56064b16003e electron::InspectableWebContents::~InspectableWebContents()
#13 0x56064b09b0a4 electron::api::WebContents::~WebContents()
#14 0x56064b09b5de electron::api::WebContents::~WebContents()
#15 0x56064b09b7a1 electron::api::WebContents::DeleteThisIfAlive()
#16 0x56064b017d89 base::internal::Invoker<>::Run()
#17 0x56065013ffd8 base::TaskAnnotator::RunTaskImpl()
#18 0x56065017367e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#19 0x560650172964 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#20 0x5606501743d5 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#21 0x560650217392 base::MessagePumpGlib::Run()
#22 0x5606501749f9 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#23 0x56065011b69d base::RunLoop::Run()
#24 0x56064ec207bf content::BrowserMainLoop::RunMainMessageLoop()
#25 0x56064ec22b05 content::BrowserMainRunnerImpl::Run()
#26 0x56064ec1cbaa content::BrowserMain()
#27 0x56064b394a64 content::RunBrowserProcessMain()
#28 0x56064b39740a content::ContentMainRunnerImpl::RunBrowser()
#29 0x56064b396c9e content::ContentMainRunnerImpl::Run()
#30 0x56064b39332b content::RunContentProcess()
#31 0x56064b393592 content::ContentMain()
#32 0x56064afd6b83 main
#33 0x7f5e193cd0b3 __libc_start_main
#34 0x56064afbf02a _start

Task trace:
#0 0x56064b09b88e electron::api::WebContents::Destroy()
#1 0x56064b1c14ac electron::NodeBindings::WakeupMainThread()

The dangling raw_ptr was released at:
#0 0x5606501fe962 base::debug::CollectStackTrace()
#1 0x5606501e5463 base::debug::StackTrace::StackTrace()
#2 0x560650202b36 base::allocator::(anonymous namespace)::DanglingRawPtrReleased<>()
#3 0x56064b27af30 base::internal::RawPtrBackupRefImpl<>::ReleaseInternal()
#4 0x56064b09b212 electron::api::WebContents::~WebContents()
#5 0x56064b09b5de electron::api::WebContents::~WebContents()
#6 0x56064b09b7a1 electron::api::WebContents::DeleteThisIfAlive()
```

**Comment by ckerr** [comment]
> Additionally, can we address [#35760 (review)](https://github.com/electron/electron/pull/35760#pullrequestreview-1116889885) as part of this PR ?

That comment:

> Can we enable dangling pointer detector as part of this PR to ensure the raw_ptr usages are correct. The feature is gated behind both build and runtime flag, and given macOS does not have partition allocator enabled, I suggest we add the gn arg to linux and windows CI testing config only for now rather than adding it in //electron/build/args/testing.gn https://source.chromium.org/chromium/chromium/src/+/main:docs/dangling_ptr.md

I think that should be done, but would be fine in a followup PR (or series of PRs). According to @jkleinsc we error out as soon as the first dangling pointer is discovered, so we don't actually know what the scope of that work will be until we go through it. So IMO it's fine to have this PR have a narrower scope and then work through any dangling pointers as a followup task

**Review by ckerr — APPROVED** [review]

**Pull request merged**
