### PR TITLE
Make use of sorted list to speed up searching

### PR DESCRIPTION
**Pull request by zcbenz**
Instead of iterating a 1300 items list, we can just sort the list in source code and do binary search at run time.

### CODE REVIEW

**Comment by alespergl** [comment]
@zcbenz @codebytere Is this optimization really worth the risk of false negatives in the search? 1300 strings should really be nothing. I'd vote for reverting this, but I'm willing to be convinced by some benchmarks.
@groundwater fyi

**Comment by ckerr** [comment]
A little off-topic to this PR, but I'd like to see the libcc branch with gtest/gmock enabled land so we can write Electron tests in C++. With that, it would be cheap to CI exhaustive tests on this type of change.

My second choice is to revert. No matter how much faster the binary search is, we're still only calling this a few of times per session. Even the fastest implementation will not make much difference. I'd rather _know_ that there are no edge cases, and that's clearer with the dumber, slower, brute-force approach.

**Comment by zcbenz** [comment]
@alespergl @ckerr Which false negative are you worried about? I have added extra checks in code to confirm: 1) the list is actually sorted and 2) we don't forget to add Electron/Node flags. And a `lower_bound` call does not look more complicated than a for loop.

**Comment by ckerr** [comment]
Yeah after looking at the DCHECKs I am going to backtrack on my comment about this being potentially unsafe. This is the kinds of checks that I would want to ensure the bsearch works.

One nitpick I should've made during the review, what would you think about simplifying this block a little:

```diff
- auto* iter = std::lower_bound(std::begin(kBlacklist), std::end(kBlacklist), switch_name);
- if (iter != std::end(kBlacklist) && switch_name == *iter) {
-   return true;
- }
+ return std::binary_search(std::begin(kBlacklist), std::end(kBlacklist), switch_name);
```

**Comment by zcbenz** [comment]
> One nitpick I should've made during the review, what would you think about simplifying by using std::binary search:

Didn't know there is `std::binary_search`, it looks better 👍 .

**Comment by alespergl** [comment]
I'm worried that the list won't be sorted for whatever reason. Someone can mess up, some locale ordering rules can come into play. Those DCHECKs are runtime checks that you need to exercise in unit tests - that can be missed for whatever reason. The code is much more convoluted and there's no real performance gain to be had here. It's just not worth the trouble.

**Comment by zcbenz** [comment]
The DCHECKs are run every time when Electron is started, if some messed up with the list, Electron would crash on startup with a clear message. String comparisons in C++ [are not locale-sensitive](http://en.cppreference.com/w/cpp/string/basic_string/compare), so I can not think of a way to silently break things.

The code is just a single `std::binary_search` call, it is something we get for free from C++ without adding any debt.

**Comment by alespergl** [comment]
> The DCHECKs are run every time when Electron is started

That's my point, you have to run it to know that it's wrong.

> String comparisons in C++ are not locale-sensitive

Yes, but it's not C++ who sorts the list, right?

Ask yourself this question: Why is this change needed?
From my perspective it only adds complication and no benefit. Therefore I would not do it.

**Comment by groundwater** [comment]
I'm 👍 with whatever if the group comes to a consensus. 

If you are waiting on me to cast any tie-breaking votes, I would say the long-term fix is of higher priority, and we should turn our attention towards that instead of any more changes, optimizations, or refactors of the current solution.

**Comment by zcbenz** [comment]
> That's my point, you have to run it to know that it's wrong.

We only merge the changes that pass the tests, or at least does not crash on startup. DCHECK on startup should be a good-enough safety guarantee, the only check better is compile-time asserts.

> Ask yourself this question: Why is this change needed?

Because I think it solves the problem in a beautiful way, it is probably just my personal taste.

**Pull request merged**
