### PR TITLE
Add process.isElevated flag

### PR DESCRIPTION
**Pull request by arkon**
This would be useful for https://github.com/Microsoft/vscode/issues/19707

Note that this PR is a WIP -- I just wanted to open it to get feedback on whether or not I'm going about this the right way, since I'm new to the codebase.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
This definitely seems useful but looking at the implementation, it looks like something that could be done in a native node module since it isn't using any Electron or Chromium APIs.

Putting it in a native node module would allow it to be independently versioned, published, and tested, and also work in other contexts like standalone node and nw.js.

It also looks like there may already be a module for this, https://github.com/sindresorhus/is-elevated, not sure if it provides the exact same checks but worth looking into.

@arkon how does this sound to you?

**Comment by arkon** [comment]
I think that the the native node module would be a viable option as well, if it's preferred to keep this out of Electron.

**Comment by bpasero** [comment]
+1 for making this a native module, VS Code would use it. We do not necessarily expect this to be within Electron.

**Comment by arkon** [comment]
Closing this (again) in favour of moving it to a separate native module then. Thanks for the feedback!

**Comment by arkon** [comment]
In case somebody stumbles across this, I've published [native-is-elevated](https://github.com/arkon/native-is-elevated) to NPM.

**Comment by bpasero** [comment]
@arkon awesome work!

**Pull request closed without merging**
