### PR TITLE
Upgrade electron-typescript-definitions to latest

### PR DESCRIPTION
**Pull request by poiru**
Needed for electron/electron-typescript-definitions#80

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
The current version range will pull this version in (semver is good 😄)

The PR that required this new version has already passed and been merged so I assume we don't need this bump.

**Comment by poiru** [comment]
@MarshallOfSound It won't update the package if the semver is satisfied though, right? Linting still fails for me after running `bootstrap.py`.

**Comment by felixrieseberg** [comment]
>  I could of course npm update manually, but I think we should merge this.
Agreed, there's no downside in doing it.

**Comment by poiru** [comment]
@MarshallOfSound Could you merge this? 🤗

**Comment by zeke** [comment]
Thanks for this, @poiru 👍

**Pull request merged**
