### PR TITLE
fix: ensure chrome colors are initialized

### LINKED ISSUE #34406: [Bug]: red background on hover to PiP
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 19044.1706

### What arch are you using?

x64

### Last Known Working Electron version

18.1.0

### Expected Behavior

when hovering over pip, there is no red background and controls are visible

### Actual Behavior

when hovering over pip, there is a red background and no controls are visible

### Testcase Gist URL

_No response_

### Additional Information

image

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #34406

After https://chromium-review.googlesource.com/c/chromium/src/+/3526815 we need to initialize chromes colors if we want to support pip.

Notes: Picture-In-Picture mode no longer becomes a red rectangle on hover

### CODE REVIEW

**Review by zcbenz — COMMENTED** [review]
There is linking error on Windows

```
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /OUT:./electron.exe /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\15.0.0\lib\windows "-libpath:../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/ATLMFC/lib/x64" "-libpath:../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/lib/x64" "-libpath:../../../../Program Files (x86)/Windows Kits/NETFXSDK/4.8/lib/um/x64" "-libpath:../../../../Program Files (x86)/Windows Kits/10/lib/10.0.20348.0/ucrt/x64" "-libpath:../../../../Program Files (x86)/Windows Kits/10/lib/10.0.20348.0/um/x64" /MACHINE:X64  /PDB:./electron.exe.pdb @./electron.exe.rsp
lld-link: error: undefined symbol: bool __cdecl ShouldCustomDrawSystemTitlebar(void)
```

**Comment by leonardxfce-dialpad** [comment]
The missing definition looks being defined here:
https://github.com/electron/electron/blob/main/shell/browser/ui/views/win_frame_view.cc
https://github.com/electron/electron/blob/main/shell/browser/ui/views/win_frame_view.h

**Comment by ShukantPal** [comment]
Thanks @MarshallOfSound!

**Comment by h615861768** [comment]
Thank you @MarshallOfSound!

**Comment by codebytere** [comment]
I think we need to add `chrome/browser/ui/color/win/native_chrome_color_mixer_win.cc` to `chromium_src/BUILD.gn`

**Comment by leonardxfce-dialpad** [comment]
@MarshallOfSound, sorry for the ping, could you apply the suggestions we wrote, if you have your hands full of work I can try to do a similar PR trying to address this problem (I know nothing C++ code but I can follow your code and use the suggestions here) just let me know.

**Review by VerteDinde — APPROVED** [review]

**Review by codebytere — APPROVED** [review]

**Comment by PikachuEXE** [comment]
@arnaudbud I have tested 18.x it there is no such issue

**Pull request merged**
