### PR TITLE
fix: send ELECTRON_BROWSER_CONTEXT_RELEASE asynchronously

### LINKED ISSUE #20086: Closing child window hangs main window
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I have enabled nativeWindowOpen and nodeIntegrationInSubFrames for main window, and I have a preload script which required a remote from electron. Which this configuration I open a child window and then I close it. The main window render process hangs for ever so I have to restart whole app. Here is and example app https://github.com/zarubond/electron-quick-start/tree/child_hang

* **Electron Version:**
6.0.7, 7.0.0-beta3
* **Operating System:**
Windows, Linux, MacOS
* **Last Known Working Electron version:**
5.0.10

### Expected Behavior
Closing child window should not hang main window for ever

### Actual Behavior
Main window hangs after closing child window. 

### To Reproduce
Open child window and then close it

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Fixes parts of #20086 by sending `ELECTRON_BROWSER_CONTEXT_RELEASE` asynchronously.
The synchronous send was added in #9389, which was necessary back then as we didn't have a unique identifier for each JS context.

Fixing `ipcRenderer.sendSync()` to not hang when the mojo connection is lost is also important, but more complicated.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed hang when closing a scriptable popup window using the `remote` module.

### CODE REVIEW

**Comment by nornagon** [comment]
cc @loc

**Comment by MarshallOfSound** [comment]
Also this doesn't fix the root cause of #20086 it just hides the underlying issue

**Comment by zcbenz** [comment]
### To add some background here:

The `ELECTRON_BROWSER_CONTEXT_RELEASE` message used to be required to be sent synchronously, so the remote references for current WebContents can be cleared before loading the new page, otherwise race conditions would happen.

However later there was some changes in Chromium that, the new page is pre-loaded before the old page gets destroyed, so race condition would happen even though the message was sent synchronously.

The race condition was then fixed by passing the ID of current context with the `ELECTRON_BROWSER_CONTEXT_RELEASE` message (https://github.com/electron/electron/pull/13603), so the remote references are cleared per-context instead of per-WebContents, and the sequence of messages does not matter anymore since then.

 So technically the `ELECTRON_BROWSER_CONTEXT_RELEASE` message no longer has to be sent synchronously. However we have to ensure that the message has actually been sent when navigation happens, and I think we should add a test for it.

### Also some note on how remote references are cleared:

Currently we have 2 ways of clearing remote references: one is listening to `render-view-deleted` event, and the other is sending the `ELECTRON_BROWSER_CONTEXT_RELEASE` message.

Both ways are required because `render-view-deleted` does not work for certain page navigations (depending on which Chromium version), and the `ELECTRON_BROWSER_CONTEXT_RELEASE` message can not be sent successfully when page is destroyed directly.

**Comment by zcbenz** [comment]
For the original issue #20086, before IPC was migrated to mojo, the `sendSync` would simply fail when the page is being destroyed; but with mojo the `sendSync` is waiting for signal manually and Chromium would not unlock it for us automatically.

**Comment by zcbenz** [comment]
I have added tests to ensure the remote references can be cleared for all cases (on navigation and on `destroy()`).

There is still problem that `sendSync` would hang when used in `exit` event while page is being destroyed directly, but I think it should be a separate problem.

**Comment by lkonstantinov** [comment]
I have to agree with @MarshallOfSound - this is just fixing piecemeal and sweeping under the carpet the underlying issue. After we've patched this particular sendSync (about a month or so ago - see #20350) we've been hitting slew of IPC deadlock issues in other situations.

**Comment by miniak** [comment]
@lkonstantinov This PR is not pretending to be fixing the root cause, it's fixing #20086. The change to use an async IPC could have been made sooner as a refactoring as it does not have to be sync anymore as @zcbenz explained.

**Comment by zcbenz** [comment]
@MarshallOfSound Can you take another look of this?

**Comment by zcbenz** [comment]
I'm merging this and keeping the original issue open.

**Pull request merged**
