### PR TITLE
fix: avoid Electron.dsym files in the main app bundle

### PR DESCRIPTION
**Pull request by deepak1556**
#### Description of Change

Screenshot (51)

This regressed since v7

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: remove Electron.dsym from macOS application zip

### CODE REVIEW

**Comment by deepak1556** [comment]
Only enabled the dist checks, haven't fixed the issue yet.

**Comment by deepak1556** [comment]
The regression came from https://chromium-review.googlesource.com/c/chromium/src/+/1671667, the following would do the trick

```
diff --git a/build/config/mac/rules.gni b/build/config/mac/rules.gni
index 3c816242375c..9b8bee7b4855 100644
--- a/build/config/mac/rules.gni
+++ b/build/config/mac/rules.gni
@@ -351,7 +351,7 @@ template("mac_framework_bundle") {
       ":$_shared_library_bundle_data",
     ]
 
-    if (enable_dsyms) {
+    if (enable_dsyms && !is_electron_build) {
       data = [
         "$root_out_dir/$_output_name.dSYM/Contents/Info.plist",
         "$root_out_dir/$_output_name.dSYM/Contents/Resources/DWARF/$_output_name",
@@ -559,7 +559,7 @@ template("mac_app_bundle") {
       deps += [ ":$_pkg_info_bundle_data" ]
     }
 
-    if (enable_dsyms) {
+    if (enable_dsyms && !is_electron_build) {
       data = [
         "$root_out_dir/$_output_name.dSYM/Contents/Info.plist",
         "$root_out_dir/$_output_name.dSYM/Contents/Resources/DWARF/$_output_name",
@@ -632,7 +632,7 @@ template("mac_plugin_bundle") {
     }
     deps += [ ":$_loadable_module_bundle_data" ]
 
-    if (enable_dsyms) {
+    if (enable_dsyms && !is_electron_build) {
       data = [
         "$root_out_dir/$_output_name.so.dSYM/Contents/Info.plist",
         "$root_out_dir/$_output_name.so.dSYM/Contents/Resources/DWARF/$_output_name.so",
```

since I don't want to mess the `runtime_deps` by manipulating `data`, `data_deps` without patch. But open to other solutions.

**Comment by nornagon** [comment]
Probably better to just exclude them in our zip code: https://github.com/electron/electron/blob/master/build/zip.py#L14-L23

**Comment by deepak1556** [comment]
@nornagon updated, can we trigger release builds for this PR before merging ?

**Comment by nornagon** [comment]
i can't trigger release builds but @jkleinsc can! i've pinged him.

**Comment by jkleinsc** [comment]
Mac release builds have been triggered.

**Comment by deepak1556** [comment]
Build artifacts looks good, ready for review.

**Comment by jkleinsc** [comment]
Merging as CI failures are unrelated to PR change.

**Pull request merged**
