### PR TITLE
fix: input accept not work in mac

### PR DESCRIPTION
**Pull request by dengyaolong**
about: https://github.com/electron/electron/issues/11456

### CODE REVIEW

**Comment by dengyaolong** [comment]
@marswong The commit add "All Files" filter by @yuya-oc , and solve this problem 
 https://github.com/mattermost/desktop/issues/497#issuecomment-355463151 . And It only trouble in windows not mac.

And you say `check other feature relay on this`, em... looks difficult because I don't know what is `other feature`?

**Comment by codebytere** [comment]
Can you try to rebase this on master to see if that resolves the jenkins failure?

**Comment by alexeykuzmin** [comment]
@codebytere The PR is to the `1-7-x` branch.

**Comment by dengyaolong** [comment]
image
Can I resolve this problem ? Or trigger jenkins again?

**Comment by dengyaolong** [comment]
@zcbenz @marswong  It's 25 days ago since I pull request...So what can I do?

**Comment by codebytere** [comment]
There's very little description on this pull request, and so it's unclear what exactly is being addressed. In addition, you specify that it is a MacOS-based issue, and so wrap the block with a check for `OS_WIN`. How are Linux users going to be affected by this?

**Comment by dengyaolong** [comment]
@yuya-oc So your commit will effect Linux or not?

**Comment by yuya-oc** [comment]
@dengyaolong I have tested 1.7.11 on Ubuntu 16.04 (Unity).

I got correct filtering and additional `All Files` filter. So my commit works as expected on Ubuntu at least.

```html
<input type="file" accept=".jpg,.png"/>
```

accept_on_linux

**Comment by ckerr** [comment]
I dropped the ball on this PR, I was going to try this out last week but got distracted with other tasks.

@dengyaolong it would be helpful if you could describe how this patch fixes the problem? There is a lot I don't understand about this patch :smile: 

* Why does removing the "All files" option from macOS fix the problem?
* Why does "All files" still show up on Linux even though the #ifdef is for Windows?
* Do Mac users no longer have an "All files" option after this patch? That seems counterproductive
* This patch is aimed at an older branch of Electron -- does the problem persist in 1.8x and master?

**Comment by yuya-oc** [comment]
@ckerr 

> Why does "All files" still show up on Linux even though the #ifdef is for Windows?

I tested released version of 1.7.11. This PR is not included, so "All files" should appears.

**Comment by dengyaolong** [comment]
@ckerr  Sorry for the late reply.

> Why does removing the "All files" option from macOS fix the problem?

because "All files" will cause `<input accept>` not work. and add "all files" only for fix windows before. So it's a bugfix cause bugfix

> Why does "All files" still show up on Linux even though the #ifdef is for Windows?

It's my lose, and I commit again to fixed, also added in Linux

> Do Mac users no longer have an "All files" option after this patch? That seems counterproductive

So @yuya-oc can you reply this problem?

> This patch is aimed at an older branch of Electron -- does the problem persist in 1.8x and master?
Seems only not work in 

yes...1.8.2 not work either.

**Comment by yuya-oc** [comment]
> Do Mac users no longer have an "All files" option after this patch? That seems counterproductive

Unfortunately it will be not available. However current behavior doesn't respect `accept` attribute any time. "All Files" should be an option.
I think that a solution is to provide "All Files" by another way such as accessoryView of NSSavePanel.

**Comment by alexeykuzmin** [comment]
@dengyaolong
If the master if affected too, the bug should be fixed there first.

**Comment by yuya-oc** [comment]
>> Do Mac users no longer have an "All files" option after this patch? That seems counterproductive

> Unfortunately it will be not available. However current behavior doesn't respect accept attribute any time. "All Files" should be an option.
> I think that a solution is to provide "All Files" by another way such as accessoryView of NSSavePanel.

Hi, I added a PR #11959 to solve this. Would you take a look?

**Comment by zcbenz** [comment]
I'm closing this in favor of #11959, which fixed the problem without breaking "All files" on macOS. But still thanks for your work on this!

**Pull request closed without merging**
