### PR TITLE
Add the new sandbox feature to the checklist

### PR DESCRIPTION
**Pull request by ColinEberhardt**
The new `sandbox` option is a very useful feature, but quite hidden. I think it should be added to the list!

### CODE REVIEW

**Comment by paulcbetts** [comment]
Enabling the Chromium sandbox comes with a whole bunch of caveats, and I don't think it's a requirement for "You should at least"-level of security. I think sandbox needs its own section with its own discussion on tradeoffs

**Comment by ColinEberhardt** [comment]
Thanks for the feedback @paulcbetts 

Regarding "it's own bunch of caveats", are you referring to the fact that by enabling the sandbox you lose access to all the node APIs? Should the documentation describe accessing node APIs by re-introducing `ipcRenderer` in the pre-load scripts?

Or are there some more fundamental, security-related caveats that I am unaware of?

I do agree that this feature needs more detailed documentation that described the pros / cons. I'd happy to contribute.

**Comment by zcbenz** [comment]
> Regarding "it's own bunch of caveats", are you referring to the fact that by enabling the sandbox you lose access to all the node APIs? Should the documentation describe accessing node APIs by re-introducing ipcRenderer in the pre-load scripts?

I'm 👍  on documenting the tradeoffs of using sandbox.

**Comment by kevinsawicki** [comment]
> I'm 👍 on documenting the tradeoffs of using sandbox.

These were added in #8983 so I think this can be closed out here.

**Pull request closed without merging**
