### PR TITLE
Document static methods on webContents

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull requests documents two new public API:

- `webContents.getAllWebContents()` (similar to `BrowserWindow.getAllWindows()`)
- `webContents.getFocusedWebContents()` (similar to `BrowserWindow.getFocusedWindow()`

Also adds an initial spec for `webContents` static APIs.

### CODE REVIEW

**Comment by zcbenz** [comment]
The `webContents` is actually a module not a class, and `WebContents` is the class. So the docs should look like:

```markdown
# webContents

## Methods

### `webContents.fromId(id)`

## Class: WebContents

### Instance Methods

#### `contents.loadURL(url)`
```

The architecture is the same with `session` module. We didn't make this clear because the `webContents` behaved more like a property of `BrowserWindow` instead of an independent module. And we can not use `webContents`  for the instance of `WebContents` class anymore since it is now the module's name.

**Comment by kevinsawicki** [comment]
> The webContents is actually a module not a class, and WebContents is the class. So the docs should look like

Yeah, I did it this way initially to keep it consistent with the current layout of `BrowserWindow`'s docs.

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#static-methods

I'm up for refactoring them to a  new format, but I thought we would probably do them all at once conforming to the new styleguide.

**Comment by zcbenz** [comment]
The `electron.BrowserWindow` returns the class, while `electron.webContents` and `electron.session` return the modules. So `BrowserWindow` has static methods, while `webContents` and `session` have module methods.

The essential difference between `BrowserWindow` module and `webContents`/`session` modules is, the `BrowserWindow` has to be created through its constructor, while `WebContents` and `Session` are usually created implicitly or can be created through module methods like `session.create()` or `webContents.create()`.

**Comment by kevinsawicki** [comment]
> The essential difference between BrowserWindow module and webContents/session modules is, the BrowserWindow has to be created through its constructor, while WebContents and Session are usually created implicitly or can be created through module methods like session.create() or webContents.create().

Yup, thanks for clarifying 👍 I've updated all the sections to follow the styleguide.

**Comment by zcbenz** [comment]
👍

**Pull request merged**
