### PR TITLE
fix: use generic capturer to list both screens and windows when possible

### LINKED ISSUE #39043: [Feature Request]: Use combined PipeWire Picker for desktopCapturer when windows and screens are requested
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When calling `desktopCapturer.getSources({ types: ['window', 'screen'] })` it opens two PipeWire pickers, one for a window and one for a screen. It can't get the sources if one of them is canceled (e.g. the user only wants to share a window or screen and cancels the other one).

image

### Proposed Solution

Use a combined picker if a window and screen capture is requested. 
My Pseudo Idea how this could be implemented:
Add a check in [electron_api_desktop_capturer.cc](https://github.com/aiddya/electron/blob/72f357ad773056483518964820700672465a048f/shell/browser/api/electron_api_desktop_capturer.cc#L240) if capture_window and capture_screen are true and a delegated Sourcelist is used.
Then somehow pass `ScreenCastPortal::CaptureSourceType::kAnyScreenContent` as a CaptureType in [screencast_portal.cc](https://webrtc.googlesource.com/src/+/8fcc6df79daf1810cd4ecdb8d2ef1d361abfdc9c/modules/desktop_capture/linux/wayland/screencast_portal.cc#95)

### Alternatives Considered

Ignore if one of the pickers gets canceled.

### Additional Information

Fixing behavior that was out of scope of #38833

### PR DESCRIPTION
**Pull request by aiddya**
#### Description of Change

Screensharing with PipeWire via XDG Desktop Portal requires explicit user permission via permission dialogs. Chromium has separate tabs for screens and windows and thus its portal implementation requests permissions separately for each. However, the screencast portal has no such limitation and supports both screens and windows in a single request.

WebRTC now supports this type of capture in a new method called `CreateGenericCapturer`. The `desktopCapturer` implementation has been modified to use it. Additionally, Chromium has been patched to use same generic capturer to ensure that the source IDs remain valid for `getUserMedia`.

Fixes #39043

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed a redundant permission popup while fetching screens and windows using `desktopCapturer.getSources()` on Wayland.

### CODE REVIEW

**Review by VerteDinde — COMMENTED** [review]
The code looks good to me, but I think we need to resolve a patch - would you mind rebasing with main and resolving that patch conflict, and I'll review?

Also, if it's not too much trouble, you mention in the PR description backporting a fix from WebRTC. Would you mind linking to the CL of that upstream backport in the patch description or the PR description? That will just help us remove the patch when it eventually lands in main, without accidentally removing some needed code 🙂 Thanks again for this fix!

**Comment by aiddya** [comment]
@VerteDinde I've rebased and resolved the patch conflict. One of the Chromium updates pushed after I created this PR has brought in the backported WebRTC patch. It was the cause of the conflict and I've removed it.

On the other hand, this means that I'll have to backport the PR manually to 26.x.y 😞. I'll add the CL details in the backport PR.

**Review by VerteDinde — APPROVED** [review]

**Comment by VerteDinde** [comment]
@aiddya Our automation opened a backport automatically - if you want, happy to manually backport the CL to it myself if you wouldn't mind linking me the relevant CL. Otherwise, I'll close the automated backport and let you open a manual backport 🙇‍♀️

**Comment by aiddya** [comment]
@VerteDinde That would be great, thanks! Here's the CL: https://webrtc-review.googlesource.com/c/src/+/311549

**Comment by aiddya** [comment]
@VerteDinde Is this backportable to stable branches?

I've noticed that the double permission dialogs sometimes cause focus bugs, where one dialog is perfectly superimposed on the other, but the bottom one has focus. The top dialog is not clickable, which leaves the impression that the application has frozen.

I want to backport this to 25-x-y and perhaps 24-x-y too. The double permission dialogs were introduced by #38833, so the backport can be seen as a fixup.

**Pull request merged**
