### PR TITLE
fix: properly pass openExternal activate option

### PR DESCRIPTION
**Pull request by jeremyspiegel**
#### Description of Change
A reference to an `OpenExternalOptions` structure was being captured by an Objective-C block that outlived the object that was being referenced (added in https://github.com/electron/electron/pull/15065). This caused the default browser window to not be activated when passing a URL on macOS when the default browser is Safari or Firefox. Fixes https://github.com/electron/electron/issues/18293.

cc @miniak @nornagon @alexeykuzmin @codebytere 

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed issue where `shell.openExternal` would not activate opened window on macOS

### CODE REVIEW

**Comment by jeremyspiegel** [comment]
Looks like I can't rely on a window onblur event in a test on CI (it worked when I ran it via `npm run test`). Not sure how else to test this, so maybe it'd be best to just revert the test change I made.

**Comment by jeremyspiegel** [comment]
Hmm, I see now that with https://github.com/electron/electron/issues/17649, osx-testing-test doesn't pass on PRs from forks. I don't have permission to push a branch to this repo though.

**Comment by MarshallOfSound** [comment]
@jeremyspiegel That's OK, as that's the only failure this PR is effectively green.  Just needs a review 👍

**Comment by codebytere** [comment]
The failing macOS spec is expected for forks; merging.

**Comment by codebytere** [comment]
@jeremyspiegel could you please open manual backports for the targeted release lines?

**Comment by jeremyspiegel** [comment]
@codebytere sure, but the bug is not in 4.2.x, it is new in 5.0.x.

**Comment by codebytere** [comment]
@jeremyspiegel oops, corrected!

**Pull request merged**
