### PR TITLE
fix: enable webview in sandbox renderer (#13435)

### PR DESCRIPTION
**Pull request by juturu**
Notes: Enable webview in sandbox renderer
Security: Inherit embedder prefs onto webview

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
```
spec/api-browser-window-spec.js:1591:9: 'expect' is not defined.
```

**Comment by juturu** [comment]
@alexeykuzmin thanks. Fixed the expect issue.

**Comment by MarshallOfSound** [comment]
@juturu It looks like this is hanging the tests, not sure how 🤔

**Comment by codebytere** [comment]
@juturu are you still interested in landing this?

**Comment by zcbenz** [comment]
The tests is hanging because `events-helpers` is not available in 2-0-x's source code, I have fixed the tests.

**Pull request merged**
