### PR TITLE
build: use script/lint.js for docs/fiddles + fix errors

### PR DESCRIPTION
**Pull request by miniak**
The goal is to be able to use additional rules such `unicorn/prefer-node-protocol` as a follow-up
Related to #38025

Notes: none

### CODE REVIEW

**Comment by miniak** [comment]
@dsanders11 are you ok with this? what was the reason for not just using script/lint.js for linting docs/fiddles?

**Comment by dsanders11** [comment]
@miniak, will take a deeper look later, but the short answer is we lint example code (code blocks in docs, example fiddles in Fiddle, etc) with `standard`, which we don't use for internal code. They follow different styles.

**Comment by miniak** [comment]
@dsanders11 ok, in that case let's just drop this

**Comment by miniak** [comment]
@dsanders11 does it make sense to use `require('node:xyz')` instead of `require('xyz')` there however? I wanted to enforce that by including `docs/fiddles` in `script/lint.js`

**Comment by dsanders11** [comment]
@miniak I think it makes sense, I'll think on the easiest way to add that to the existing linting.

**Comment by miniak** [comment]
@dsanders11 I will create a separate PR for that and we can figure it out there

**Pull request closed without merging**
