### PR TITLE
Add app.relaunch API

### LINKED ISSUE #539: app.restart()
Currently there is no app.restart function. I think a simple method that restarts the app is quite useful.

In my application, I do database updates after downloading a new version of an app.
After those database updates, it's best to just restart the app to prevent database problems.

The app.restart method can also be reused in the `auto-updater`.

### PR DESCRIPTION
**Pull request by zcbenz**
```markdown
### `app.relaunch([options])`

* `options` Object (optional)
  * `args` Array (optional)
  * `execPath` String (optional)

Relaunches the app when current instance exits.

By default the new instance will use the same working directory and command line
arguments with current instance. When `args` is specified, the `args` will be
passed as command line arguments instead. When `execPath` is specified, the
`execPath` will be executed for relaunch instead of current app.

Note that this method does not quit the app when executed, you have to call
`app.quit` or `app.exit` after calling `app.relaunch` to make the app restart.

When `app.relaunch` is called for multiple times, multiple instances will be
started after current instance exited.
```

Close #539.

### CODE REVIEW

**Comment by callodacity** [comment]
I believe this API doesn't work on `mas` builds (due to my own testing) but it doesn't say that in the docs. @zcbenz can you confirm that it doesn't work in `mas` builds? If so I'm happy to make a PR tp update the docs 😄

**Comment by zcbenz** [comment]
@callodacity Hmm it seems to work on my side.

Steps:

1. Download mas build
2. Open it and run `require('electron').remote.app.relaunch()` in devtools
3. Close window
4. Electron restarts

**Comment by callodacity** [comment]
@zcbenz Yes that works - but I should have given some more information. If you sign the build then it won't relaunch.

Steps:

1. Download mas build
2. Sign electron (with `development` certificate
3. Open it and run `require('electron').remote.app.relaunch()` in devtools
4. Quit application
5. Electron quits and doesn't reopen

**Comment by TheMaverickProgrammer** [comment]
This isn't working for me. Electron starts after quitting my application telling me to drag my program into it. This isn't what I expected.

**Comment by MarshallOfSound** [comment]
@TheMaverickProgrammer This is because you launched your application using the electron binary and a path to your app (`electron .`).  When you use this API in a packaged app it will work fine, when launching from the electron binary you need to ensure you provide the path to your app as an argument

**Comment by TheMaverickProgrammer** [comment]
I resolved the issue by passing in the same process arguments as the initial window.

**Pull request merged**
