### PR TITLE
feat: Windows implementation of powerMonitor "shutdown" event

### PR DESCRIPTION
**Pull request by tarruda**
#### Description of Change
The powerMonitor "shutdown" event is only handled on Linux/Mac, this PR adds the Windows implementation.

Handling shutdown correctly on Windows is more complex than Linux/Mac, since any process can be killed during shutdown. That means renderer processes can be killed first (and usually are) , which could result in loss of data even if the event is handled in the browser process.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: Add Windows implementation of powerMonitor "shutdown" event

### CODE REVIEW

**Comment by felixrieseberg** [comment]
This is an excellent effort, thank you! We should add that apps only get five seconds to the docs (right?). I'd also 😍 love to see some specs!

**Comment by tarruda** [comment]
@felixrieseberg I'm not sure how this could be tested considering it is mostly system interaction code. With the Linux version I was able to do some limited testing through the dbus-mock interface, but I'm not aware of anything similar to Windows.

In any case it seems this change is causing problems on some of the specs (even though our users have been using this code without issues for a few months now) so I still need to do some work.

**Comment by bpasero** [comment]
VSCode would be very interested in a way to do a proper shutdown during OS restart, so 👍

**Comment by miniak** [comment]
@tarruda can you rebase on latest master?

**Comment by codebytere** [comment]
@tarruda please address latest comments or this PR will be closed in 10 days due to inactivity.

**Comment by tarruda** [comment]
> @tarruda please address latest comments or this PR will be closed in 10 days due to inactivity.

@codebytere In a few days I might have some work time allocated on this, and would like to keep this PR open. Is rebasing on latest master enough for now?

**Comment by codebytere** [comment]
@tarruda yes, thanks!

**Comment by tarruda** [comment]
@codebytere I no longer have write access to electron repository, so I can't push to this PR. Should I open another PR with the rebased branch in my electron copy (https://github.com/tarruda/electron/tree/windows-powermonitor-shutdown-event), or is there a way to edit this PR to use my fork?

**Comment by zcbenz** [comment]
@tarruda Yeah the only way seems to be opening a new PR, and please do.

**Comment by codebytere** [comment]
@tarruda would you be opposed to me trying to pick this up? i'll ensure you have author credit in git!

**Comment by tarruda** [comment]
@codebytere I don't mind at all, please go ahead :smile:

**Pull request closed without merging**
