### PR TITLE
add new event to auto-updater

### PR DESCRIPTION
**Pull request by codebytere**
Resolves https://github.com/electron/electron/issues/8293. 

Adds a `before-quit-for-update` that's emitted when `quitAndInstall` is called in AutoUpdater.

/cc @MarshallOfSound

### CODE REVIEW

**Comment by zeke** [comment]
This is handy.

Is there any guarantee that the event handler will be able to finish before the app quits?

**Comment by ckerr** [comment]
This seems to be a workaround for a `before-quit` edge case of it being emitted too late when autoupdating, is that correct?

What's the rationale for adding a new wart into the public API, rather than fixing the emission order of `before-quit`? Is fixing the emission order that tricky?

**Comment by MarshallOfSound** [comment]
Changing the emit order may be possible but it would be a breaking change, and not one I'd be super comfortable doing even with semver.  Changing order of events would cause very weird issues in some apps that would make it super hard for devs to figure out IMO.

**Comment by codebytere** [comment]
@ckerr yeah, i briefly toyed with changing the emit order but given breaking change concerns outlined above this seemed like the easiest way to address the issue opener's request :)

**Comment by ckerr** [comment]
Yeah, that's fair that it would be a breaking change at this point.

**Comment by codebytere** [comment]
should we add more people to `updater` codeowners? right now it's just @zcbenz and @groundwater which is a bit of a bottleneck 🤔

**Comment by zeke** [comment]
👌

**Pull request merged**
