### PR TITLE
Add support for titleBarStyle: 'hidden-inset' on OS X 10.9

### PR DESCRIPTION
**Pull request by miniak**
Follow up to: https://github.com/electron/electron/pull/6848

### CODE REVIEW

**Comment by miniak** [comment]
screen shot 2016-09-03 at 1 29 44 am

**Comment by miniak** [comment]
@sindresorhus why thumbs down?

**Comment by sindresorhus** [comment]
I just don't think it's worth the complexity cost for something so non-essential. Most don't even support 10.9 anymore.

**Comment by miniak** [comment]
@sindresorhus Actually, this approach is IMHO better than using a fake toolbar to add padding as we do it on OS X 10.10 and higher. Also, 10.9 is still supported and it's not that complicated to make this work consistently on all versions, so why not do it?

**Comment by miniak** [comment]
If moving the buttons works everywhere, then it would be a also possible to make the left and top offset fully configurable, not only have 2 options (hidden and hidden-inset)

**Comment by miniak** [comment]
@sindresorhus That's your opinion. The code is not that complex. I think it's worth it, it makes the behavior consistent between all versions of macOS. In the future when support for OS X 10.9 gets dropped, all that code can be removed.

**Comment by zcbenz** [comment]
I don't care about OS X 10.9, but I agree the code does not add much compatibility and I think it is not a bad thing to have. 👍

**Pull request merged**
