### PR TITLE
fix: deprecate setLayoutZoomLevelLimits

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This hasn't worked [since Chromium removed it](https://chromium-review.googlesource.com/c/chromium/src/+/1809500) and I believe it's beyond our capacity to continue to support it. The function doesn't work, but instead of throwing an error it seems nicer to warn about it in 8.x and wait till 9.x to delete it completely.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: `setLayoutZoomLevelLimits` no longer works in Electron 8, so emit a warning message when using it. The function will be removed in Electron 9.

### CODE REVIEW

**Comment by deepak1556** [comment]
This was added in https://github.com/electron/electron/pull/8041 ,  the issue it mentioned was fixed in another way https://github.com/electron/electron/pull/8537, can you please verify if there is a regression before merging this.

**Comment by nornagon** [comment]
@deepak1556 do you mean this issue? https://github.com/electron/electron/issues/6958

**Comment by deepak1556** [comment]
Yup that one, users seem to have been using this api as a workaround to persist the zoom level across navigations but we later fixed it on electron core, just want to make sure its still fixed, so that we can remove this api safely.

**Comment by nornagon** [comment]
https://gist.github.com/8ace446c40111aca67391104c2a9cc76 I tested this in a Fiddle and it seems to work OK. However, I'm not totally sure what the original failing behavior was so I can't say for certain that I didn't accidentally dodge it somehow. Wish there had been a test written :(

**Pull request merged**
