### PR TITLE
fix: update and enable osr

### PR DESCRIPTION
**Pull request by brenca**
##### Description of Change

Pretty much what it says in the title.

##### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes:  none

### CODE REVIEW

**Comment by codebytere** [comment]
Compilation is 💯 on Mac, the specs are failing owing to the `NOTIMPLEMENTED()` in `NativeWindowMac::SetBackgroundColor`, i'm waiting on a response from an upstream refactor so i'd like to pend this PR on fixing that issue here.

**Comment by MarshallOfSound** [comment]
This PR needs to be rebased and retargetted at master

**Comment by codebytere** [comment]
I tried to muster the energy to rebase the sheer number of conflicts in this thing but i'm gonna cherry pick into a new PR, up imminently

**Comment by codebytere** [comment]
Closed in favor of https://github.com/electron/electron/pull/15046

**Pull request closed without merging**
