### PR TITLE
Added semi-colons

### PR DESCRIPTION
**Pull request by anshdhinhgra47**
#15148 ## Description of Change
As a beginner, I had just optimized the code and added semi-colons( ; ) just to enhance the readability of the code.

#### Release Notes

Notes:

### CODE REVIEW

**Review by zcbenz — CHANGES_REQUESTED** [review]
Can you add semi-colons for all necessary lines in these files? We can't have 2 lines with semi-colons while all other lines without.

**Comment by anshdhinhgra47** [comment]
Sure

**Comment by MarshallOfSound** [comment]
Can you add `npm` to the list of folders that our JS linter checks.

https://github.com/electron/electron/blob/master/script/lint.js#L93

Then this will be enforced in the future by the linter

**Comment by zcbenz** [comment]
I'm closing this PR since there has been no activity for a long time, please let me know if you still plan to work on this and I'll reopen it.

**Pull request closed without merging**
