### PR TITLE
feat: add screen reader support to Win32 toast notifications

### PR DESCRIPTION
**Pull request by miniak**
##### Description of Change
Implement missing accessibility support via UIAutomation

##### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes
Notes: Implemented missing accessibility support via UIAutomation for Windows 7 toasts.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@miniak Can you please fix linking errors?

**Comment by chandrakanthi07** [comment]
Hi
I wanted to know whether this feature is anyway related to desktopcapturing when screen is locked in win 32 machine.
Because right not we are not getting screenshots when screen is locked.

**Comment by miniak** [comment]
@chandrakanthi07 what makes you think it's related? This is an accessibility issues.

**Comment by miniak** [comment]
@alexeykuzmin the problem is that those headers must be included in a certain order (because Windows). @alespergl can you help here?

**Comment by alexeykuzmin** [comment]
@miniak 
```
brightray/browser/win/win32_desktop_notifications/toast.cc(328,9):  error: [chromium-style] auto variable type must not deduce to a raw pointer type.
        auto inst = Get(hwnd);
        ^~~~
        auto*
```

**Comment by miniak** [comment]
@alexeykuzmin all build issues should be fixed

**Comment by miniak** [comment]
@ckerr, @codebytere can you please merge?

**Pull request merged**
