### PR TITLE
WIP: reimplement PDF viewer

### LINKED ISSUE #12337: Enable PDF Viewer
It was disabled during the Chromium 63 upgrade in #11459.
Please turn `enable_pdf_viewer` flag in the **features.gypi** on, fix compilation and tests.

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change
The PDF viewer stopped working in 3-0-x due to changes in Chromium.  This PR will reimplement the PDF viewer functionality trying to stay as close as possible to the Chromium implementation.

Resolves #12337 

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:

### CODE REVIEW

**Comment by MiXT4PE** [comment]
Is there an update or any eta for this fix?

**Comment by godza** [comment]
What happened with this pull request? I really hoped this will be reimplemented.

**Comment by nornagon** [comment]
We're still intending to one day restore the PDF viewer, but it relies on us first migrating to use Chrome's extensions library instead of our own shim, as the PDF viewer in Chromium is implemented as an extension.

**Comment by maestrocoder** [comment]
+1  This is killing me, the flicker issues on electron 2.x make it almost unusable usages but iframe for pdf is critical to my app UX so we are stuck on electron 2.x.  

Not getting pdf iframe support continues to keep getting the kick the can down the road...  

Is the PR submission here not usable?  I don't know the Electron internals (yet).

Pardon my late comment, but I have been following this for 16 months.  Without knowing yet the code required to do this, I get it's easy to sit on the sideline and wish for a solution.  

- What is the estimated level of effort to first migrate to Chrome extension library?  
- Is that migration required for other requirements? If so, what branch(es)?
- Is the migration to Chrome extension library already schedule? Estimated completion date?
- Can we get a downstream branch off any partial work on the Chrome extension library? Is there already a Chrome extension library branch in progress?

Thx, in advance.
-m3

**Comment by namotco** [comment]
Is this something the community could find sponsors for?  I understand if the change required a more in-depth architectural change that does not lend itself to something like this, but I think many are stuck with an incomplete solution at present.

**Comment by Sryther** [comment]
@namotco There is already a BountySource for this feature: https://www.bountysource.com/issues/56240517-enable-pdf-viewer (source: https://github.com/electron/electron/issues/12337#issuecomment-526876989)

**Comment by aimergenge** [comment]
why was the branch deleted?
give up?

**Comment by samuelmaddock** [comment]
@aimergenge The PR was closed as it's blocked by #19447

**Pull request closed without merging**
