### PR TITLE
Bump external binaries to 1.2.2

### PR DESCRIPTION
**Pull request by joshaber**
This is to pick up the fix to https://github.com/Squirrel/Squirrel.Mac/issues/212.

### CODE REVIEW

**Comment by joshaber** [comment]
I'll be out for a couple weeks, but it'd be great to get this in once CI is functional again.

**Comment by lukeapage** [comment]
@zcbenz any chance we can merge this before cutting 1.8.0 ?

**Comment by zcbenz** [comment]
:+1:

**Comment by poiru** [comment]
@zcbenz Any chance we could include this for the next 1.7.x release?

**Comment by zcbenz** [comment]
@jkleinsc This seems to worth backporting to 1.7.x.

**Comment by devtobo** [comment]
It's available in Electron 1.7.9 but it doesn't work (still not asking for admin password to update the application).

**Comment by 50Wliu** [comment]
@zcbenz is there still a plan to backport this?  It doesn't look like 1.7 line contains this fix.

**Comment by jkleinsc** [comment]
@50Wliu this was backported to 1.7 via #10628 and is available in the 1.7.9 release

**Comment by 50Wliu** [comment]
@jkleinsc Ah, perfect!  Was looking at the tags for this PR and didn't notice there was a separate backport PR..

**Comment by devtobo** [comment]
I can also confirm that it works (asking for admin password when updating an app).

**Pull request merged**
