### PR TITLE
fix: `DCHECK` on Windows when calling `base::Time::ActivateHighResolutionTimer(false)`

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change

https://chromium-review.googlesource.com/c/chromium/src/+/4585093 added code to activate the  high-res timer in DesktopCaptureDevice on Windows, but the timer can be deactivated elsewhere and when that happens the call to
base::Time::ActivateHighResolutionTimer(false) in the ScopedHighResolutionTimer destructor DCHECKS because the timer has already been deactivated.  We are seeing this as a random flake on our Windows CI and there is an upstream issue filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=1457052.  https://chromium-review.googlesource.com/c/chromium/src/+/4632824 is a potential fix for this issue and is included in #38891, but if we want to resolve this issue before that is merged, this PR applies that fix.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by jkleinsc** [comment]
Looks like the CL [4585093: Ensures high-res timer in DesktopCaptureDevice on Windows](https://chromium-review.googlesource.com/c/chromium/src/+/4585093) caused this issue.

**Comment by jkleinsc** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1457052 upstream tracking issue

**Review by zcbenz — APPROVED** [review]

**Comment by codebytere** [comment]
@jkleinsc looks like this was removed upstream?

**Comment by jkleinsc** [comment]
@codebytere yes.  I'll close the PR.

**Pull request closed without merging**
