### PR TITLE
ci: rearrange builds on CircleCI

### PR DESCRIPTION
**Pull request by alexeykuzmin**
##### Description of Change

 - do not build ffmpeg for every PR on CircleCI
 - build and run unittests in a separate workflow on CircleCI
 - build chromedriver in a separate job

An updated workflow for all PRs: https://circleci.com/workflow-run/e00a158c-95b6-493d-b8ba-4211a34d5d73
An updated nightly run: https://circleci.com/workflow-run/13cca510-8c66-4f8d-a9bc-646f76101d05

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: no notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@jkleinsc Makes sense, thanks.

> The only "extra" step electron_mksnapshot_zip ends up doing is creating a zip file

Would it make sense to remove it from PRs and nightly checks then?

**Comment by jkleinsc** [comment]
>Would it make sense to remove it from PRs and nightly checks then?

@alexeykuzmin yes probably.  When mksnapshot gets built as part of v8 it actually runs a test to verify it, so just building electron should be good enough.  Native_mksnapshot is a different story though as it doesn't get automatically built.

**Comment by alexeykuzmin** [comment]
@jkleinsc All done.

The only thing left to do is to remove the "fixme: run release checks" commit.

**Comment by jkleinsc** [comment]
Merging as electron-osx-testing failure has nothing to do with this circleCI change.

**Pull request merged**
