### PR TITLE
[wip] refactor: migrate WebRequest to //gin

### PR DESCRIPTION
**Pull request by DeerMichel**
#### Description of Change
An adventurous start into #16443 with the _simple_ goal of removing `native_mate` in favor of Chromium's `gin`. This PR covers a pilot migration of `WebRequest` with all involved converters and classes around it. Because I don't want to cram the whole migration into one PR, there are some duplicated files suffixed with `_gin` which will eventually (after dropping native_mate) replace their unsuffixed friends.

For now, I patched missing functionality into gin. Later, we should eliminate these patches by either upstreaming the patches or rewrite some of our usages.

cc @deepak1556 @codebytere @zcbenz

#### Todos
- check all my `TODO(deermichel)` marks for correctness (and clarify mistakes to me 🦊)
- when closing Electron, it prints a decent crash log
- when calling any method of WebRequest, it throws following exception:
```
Uncaught Exception:
TypeError: Illegal invocation: Function must be called on an object of type TODO:PROBLEM:FLAG
    at App.<anonymous> (/private/var/folders/tg/v1p6mpc5389ddclnmpys6gw00000gp/T/tmp-28725mprt94ureVz3/main.js:15:37)
    at App.emit (events.js:199:15)
```

#### Patches
- Arguments: add `GetThis()`
- Dictionary: add `SetHidden()`, `GetHidden()`
- ObjectTemplateBuilder: add constructor with template parameter (prolly not working correctly)
- Wrappable: add `Init()`, `InitWith()`, `AfterInit()`, `GetConstructor()`

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: TODO

### CODE REVIEW

**Comment by zcbenz** [comment]
I wonder if we should add a custom class implementing `Wrappable` instead of patching the one in `gin`, I don't think Chromium would accept the `gin_wrappable_init_methods.patch`.

**Comment by DeerMichel** [comment]
Is there a way to access the private `wrapper_` property of `WrappableBase` in a subclass (e.g. for the `InitWith()` method)?

**Comment by zcbenz** [comment]
> Is there a way to access the private `wrapper_` property of `WrappableBase` in a subclass (e.g. for the `InitWith()` method)?

There is no way for that.

I think maintaining our own copies of `Wrappable` and `WrappableBase` (with different class names under `gin` namespace) would be easier for long-term maintenance, as `gin` still gets changes frequently and they may break our code, while the V8 API we use is stable.

**Comment by DeerMichel** [comment]
Closing this as it'll never get merged.

**Pull request closed without merging**
