### PR TITLE
Fix a bunch of chromium-style errors

### PR DESCRIPTION
**Pull request by nornagon**
We're not yet running any of the chromium-style checkers on our build, but as
part of exploring porting our build system to GN, I happened across a few
places where the chromium-style clang plugins threw warnings. This fixes them.

These patches are separated out by warning type, so I recommend reading each
commit separately, rather than using the "Files Changed" tab.

See [here](https://www.chromium.org/developers/coding-style/chromium-style-checker-errors) for more information about the chromium-style checker.

### CODE REVIEW

**Comment by deepak1556** [comment]
> We're not yet running any of the chromium-style checkers on our build

Have enabled the stye checker plugin from the downloaded clang prebuilt, the config is based on https://cs.chromium.org/chromium/src/build/config/clang/BUILD.gn


@nornagon WDYT about declaring the generated destructors created as a part of https://github.com/electron/electron/pull/12647/commits/82fd932867eee2ce306f67603b743f97c32ca3a7 inside headers rather than in the implementation file.

**Comment by deepak1556** [comment]
Seems like there is a style-error in the upstream source,

```
/Users/distiller/project/vendor/download/libchromiumcontent/src/content/public/browser/cookie_store_factory.h:32:1: error: [chromium-style] Complex class/struct needs an explicit out-of-line copy constructor.
struct CONTENT_EXPORT CookieStoreConfig {
^
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by alexeykuzmin** [comment]
> Seems like there is a style-error in the upstream source

Can we disable this particular check in the config?

**Comment by deepak1556** [comment]
> Can we disable this particular check in the config?

Its not possible.

> Also note that copying a complex class can be an expensive operation. The preferred solution is almost always is to avoid the copy if possible. Please consider changing the code and eliminating unnecessary copies instead of simply adding an out of line copy constructor to silence the error. Additionally, in a large number of cases, you can utilize move semantics to improve the efficiency of the code.

From the chromium documentation, the right fix here would be avoid generating a copy of that class. I am working on the fix.

**Comment by ckerr** [comment]
@deepak1556 could this be enabled for Linux as well with something like this?

```diff
+                'cflags_cc': [
+                  '-Xclang', '-load',
+                  '-Xclang', '<(source_root)/<(make_clang_dir)/lib/libFindBadConstructs.so',
+                  '-Xclang', '-add-plugin',
+                  '-Xclang', 'find-bad-constructs',
+                  '-Xclang', '-plugin-arg-find-bad-constructs',
+                  '-Xclang', 'check-auto-raw-pointer'
+                ],
```

To enable it on all platforms?

**Comment by deepak1556** [comment]
@ckerr yup that should work, I was planning to do it once the mac build got fixed, Feel free to add it. Thanks!

**Pull request merged**
