### PR TITLE
Add layout support for View API

### PR DESCRIPTION
**Pull request by zcbenz**
This PR adds some bindings for Chromium's LayoutManager system. The JavaScript APIs are directly mapped from the C++ APIs, and they are not very easy to use, the APIs are very likely to change in future. 

```js
const {app, webContents, BoxLayout, TopLevelWindow, View, WebContentsView} = require('electron')

let win = null
app.once('ready', () => {
  const web = webContents.create({})
  const webview = new WebContentsView(web)
  web.loadURL('http://github.com')

  const layout = new BoxLayout('vertical')

  const view = new View()
  view.setLayoutManager(layout)
  view.addChildView(webview)

  layout.setFlexForView(webview, 1)

  win = new TopLevelWindow({frame: false})
  win.setContentView(view)
})
```

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@zcbenz Should we put these things behind a build flag?

/cc @alexeykuzmin

**Comment by miniak** [comment]
@zcbenz webContents.create is not documented, is that deliberate?

**Comment by zcbenz** [comment]
> @zcbenz Should we put these things behind a build flag?

I'm not quite sure, most Chromium APIs I used here have not been changed for years. But if it is causing problems for Chromium upgrades, I can easily hide them under build flags.

> @zcbenz webContents.create is not documented, is that deliberate?

Yeah it is currently only used in internal code and not supposed to be used by users, using it requires cautious otherwise crashes can easily happen. I'll make it a stable interface once the View API is ready for public.

**Comment by zcbenz** [comment]
> Until the stable release of this view API I'd ❤️it if these were put behind a build flag

👍

**Pull request merged**
