### PR TITLE
test: spellchecker may take several minutes to load under ASan

### PR DESCRIPTION
**Pull request by zcbenz**
#### Description of Change

The spellchecker may take several minutes to load under ASan, give it 10 minutes to load.

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by nornagon** [comment]
several minutes :O

is there some way we can reduce the load time?

**Comment by zcbenz** [comment]
It only takes so long when running in CI, I don't know why but I think it is probably because the CI does not have much RAM left and the disk read is very slow, so I can't think of a way to make it faster.

The good news is the spellchecker is only slow for the first load, once it has been loaded for one time the following tests would run fast, so the whole spellchecker tests wouldn't take like half hour to run.

**Review by codebytere — APPROVED** [review]

**Comment by nornagon** [comment]
@zcbenz would it be possible we could load a smaller "testing" dictionary?

**Comment by zcbenz** [comment]
> would it be possible we could load a smaller "testing" dictionary?

Yeah it is possible with existing APIs and I think it would be a very good way to make the tests faster and more stable.

But it would take time to figure out how to generate a custom dictionary and rewrite the tests, so I prefer to increase timeout for now and fix other CI failures first, and I have added a note in the tests.

**Pull request merged**
