### PR TITLE
docs: changes object wrapper to primitive in API methods #14023

### PR DESCRIPTION
**Pull request by kartikpandey2**
##### Description of Change

Changes Javascript object wrapper to primitive values in API docs.
Example : String(String object wrapper)  to  string(Primitive value) 
Related to #14023.

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by codebytere** [comment]
@kartikpandey2 please fill out the `Description of Change` section.

**Comment by kartikpandey2** [comment]
added Description of Change. Is it fine .?
@codebytere

**Comment by codebytere** [comment]
@kartikpandey2 does this address all the instances of this change that would need to be made across our docs? We'd love if all of these changes could be made in a single PR. If so, I'll approve and we can get this merged!

**Comment by kartikpandey2** [comment]
@codebytere Yes, I believe 😃

**Pull request closed without merging**
