### PR TITLE
fix: make navigator.userAgentData non-empty

### LINKED ISSUE #30201: [Bug]: Possibly broken user agent client hint
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

12.0.15

### Expected Behavior

Checking `navigator.userAgentData` in Chrome 91 returns an array of brands appropriately. Electron 13/14 do not return anything.

This appears to then become a problem for my situation. I am posting a form with hidden variables to a third-party vendor I work with. This form post ultimately loads an iframe.

Expected: As it does in Chrome 91, load the iframe from this third-party vendor.

### Actual Behavior

A header of "sec-ch-ua" is included in the request to the third-party vendor and it is blank. They are rejecting the post because of an invalid header. I suspect this is because Chrome 13/14 does not make this hint data made available correctly.

I tried loading various sites in Chrome 91 that do load brand names in Electron 13/14 and they are empty if you review `navigator.userAgentData`.

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #30201.

Previously, Electron was always overriding the user-agent string, but not the
user-agent metadata. This resulted in `navigator.userAgentData` being empty,
and `Sec-CH-UA` headers not being sent.

With this change, the user-agent data is set correctly & should be sent with
`Sec-CH-UA` and should be visible in `navigator.userAgentData`. One notable
fact is that the `brands` field does not contain `Electron`, only `Chromium`.
I'm not sure if this is something we want to change.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed missing Sec-CH-UA headers and empty navigator.userAgentData.

### CODE REVIEW

**Review by jkleinsc — APPROVED** [review]

**Comment by PalmerAL** [comment]
> One notable fact is that the brands field does not contain Electron, only Chromium. I'm not sure if this is something we want to change.

This is possibly a preemptive comment, but for my use case, I want the UA header to be identical to Chromium's (and therefore not contain Electron). If you do change this, could you add a way to disable it (or more generally, an API like `session.setUserAgent` to set the userAgentData, which would be even better)?

**Comment by yellow1234** [comment]
I did test with new BrowserWindow/loadURL to:
https://www.bing.com/search?q=car

After this merge the low entropy headers
sec-ch-ua
sec-ch-ua-mobile
sec-ch-ua-platform

Are working, but only from the second request to origin (after response with "Accept-CH" header)
if you test in chrome incognito, you will see that its send those headers from the first request

Also, the high entropy headers aren't working at all
sec-ch-ua-arch
sec-ch-ua-full-version
sec-ch-ua-full-version-list
sec-ch-ua-platform-version
sec-ch-ua-bitness
sec-ch-ua-wow64

Electron never sending those, even after response with "Accept-CH" header
like this:
Accept-CH: Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA

**Comment by nornagon** [comment]
@yellow1234 please file a new bug with a test case, thanks!

**Pull request merged**
