### PR TITLE
fix: send `chrome.runtime/tabs.sendMessage` result to correct sender

### PR DESCRIPTION
**Pull request by stewartlord**
Fix for #16394 

#### Checklist
- [ ] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by stewartlord** [comment]
Thanks @MarshallOfSound

**Comment by jkleinsc** [comment]
Merging as failing mac test passed on ssh rerun here: https://circleci.com/gh/electron/electron/135807

**Comment by CVertex** [comment]
Excellent! Great fix! I'm encountering this issue right now. Which build/version of Electron has this fix?

**Comment by CVertex** [comment]
@jkleinsc Hey, we really need sendMessage to work for us with our use-case, do you know which electron build supports this?

Thanks

**Comment by CVertex** [comment]
How do we get this onto v4.0.x branch?

**Comment by CVertex** [comment]
Hey @MarshallOfSound — thanks for approving this PR, what’s the best way to get this into v4.0.x and v4.1.x branches? 
Thank you

**Pull request merged**
