### PR TITLE
fix: building node modules with Visual Studio 2017

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Build error occurs when `[[deprecated]]` is used in this context in Visual Studio 2017:
```cpp
  template <class S>
  V8_DEPRECATE_SOON("See class comment.")
  TracedGlobal(Isolate* isolate, Local<S> that) : BasicTracedReference<T>() {
    this->val_ =
        this->New(isolate, that.val_, &this->val_,
                  internal::GlobalHandleDestructionMode::kWithDestructor,
                  internal::GlobalHandleStoreMode::kInitializingStore);
    static_assert(std::is_base_of<T, S>::value, "type check");
  }
```
https://developercommunity2.visualstudio.com/t/Adding-deprecated-to-a-templated-con/1232182
https://stackoverflow.com/questions/38499462/how-to-tell-clang-to-stop-pretending-to-be-other-compilers

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed building node modules with Visual Studio 2017

### CODE REVIEW

**Review by nornagon — COMMENTED** [review]
can you upstream this whole patch please?

**Comment by nornagon** [comment]
also, building node modules with MSVC sounds like a recipe for disaster unless you're using N-API 😬

**Comment by miniak** [comment]
> can you upstream this whole patch please?
@nornagon I can do that, but I don't think we should block this PR on that considering that we already have this patch and I am just fixing it.

**Review by jkleinsc — CHANGES_REQUESTED** [review]
Patch fails to build

**Comment by miniak** [comment]
@jkleinsc fixed

**Pull request merged**
