### PR TITLE
chore: deprecate nativeWindowOpen in Electron 17

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Prepare for #29405

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes
Notes: none

### CODE REVIEW

**Review by nornagon — COMMENTED** [review]
Do we need to add warnings or something? Or are they already in place?

**Comment by miniak** [comment]
@nornagon good point, yes, we should add a warning

**Review by VerteDinde — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Review by codebytere — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]
API LGTM

**Comment by codebytere** [comment]
API LGTM

**Review by codebytere — APPROVED** [review]
API LGTM

**Pull request merged**
