### PR TITLE
fix: use generic capturer to list both screens and windows when possible

### PR DESCRIPTION
**Pull request by aiddya**
#### Description of Change

Backport of #39111

Backporting this because the double screen sharing dialogs introduced by #38833 sometimes cause focus bugs, where one dialog is perfectly superimposed on the other, but the bottom one has focus. The top dialog is not clickable, which leaves the impression that the application has frozen.

cc @VerteDinde 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed a redundant permission popup while fetching screens and windows using `desktopCapturer.getSources()` on Wayland.

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
Looks like the patch(es) need to be updated for 24-x-y.
You can update the patch(es) by running:
```
e sync --3
```
and then running
```
e patches all
```

**Comment by aiddya** [comment]
I've updated the patches. I didn't realize that they were out of date as `gclient` never complained. I don't know what `e` refers to (is it an alias?), but re-running `git-export-patches` seems to have created the same changeset as in the CI artifacts.

**Comment by jkleinsc** [comment]
@aiddya `e` refers to electron-build-tools: https://github.com/electron/build-tools. `e patches all` calls `git-export-patches`, so that is fine that you called it directly.

**Comment by aiddya** [comment]
Rebased

**Review by codebytere — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Pull request merged**
