### PR TITLE
Just to build Release version of "upgrade-to-chromium-59" branch

### PR DESCRIPTION
**Pull request by alexeykuzmin**
Rel to #9946.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
Both Mac builds failed on "Running upload.py" with `requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))` error.

**Comment by alexeykuzmin** [comment]
@zcbenz, tests are not ran for Release builds, is it intentional?

**Comment by alexeykuzmin** [comment]
Test failures on Windows:
```
> python script\test.py --rebuild_native_modules --ci -c R
not ok 134 BrowserWindow module "webPreferences" option "sandbox" option can print to PDF
  AssertionError: { Error: Failed to generate PDF message: 'Failed to generate PDF', name: 'Error' } == null
      at C:\Users\alkuzmin\Projects\electron\spec\api-browser-window-spec.js:1197:20
      at CallbacksRegistry.apply (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\common\api\callbacks-registry.js:48:25)
      at EventEmitter.<anonymous> (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\renderer\api\remote.js:299:21)
      at emitThree (events.js:116:13)
      at EventEmitter.emit (events.js:197:7)
not ok 143 BrowserWindow module "webPreferences" option nativeWindowOpen option blocks accessing cross-origin frames
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runnable.js:232:19
not ok 145 BrowserWindow module "webPreferences" option nativeWindowOpen option loads native addons correctly after reload
  AssertionError: 'Require runas failed: A dynamic link library (DLL) initialization routine failed.\r\n\\\\?\\C:\\Users\\alkuzmin\\Projects\\elec == 'function'
      at ipcMain.once (C:\Users\alkuzmin\Projects\electron\spec\api-browser-window-spec.js:1359:18)
      at CallbacksRegistry.apply (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\common\api\callbacks-registry.js:48:25)
      at EventEmitter.<anonymous> (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\renderer\api\remote.js:299:21)
      at emitThree (events.js:116:13)
      at EventEmitter.emit (events.js:197:7)
not ok 173 BrowserWindow module window states resizable state works for a frameless window
  AssertionError: true == false
      at Context.it (C:\Users\alkuzmin\Projects\electron\spec\api-browser-window-spec.js:1970:18)
      at callFn (C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runnable.js:348:21)
      at Test.Runnable.run (C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runnable.js:340:7)
      at Runner.runTest (C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runner.js:443:10)
      at C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runner.js:549:12
      at next (C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runner.js:361:14)
      at C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runner.js:371:7
      at next (C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runner.js:295:14)
      at Immediate.<anonymous> (C:\Users\alkuzmin\Projects\electron\spec\node_modules\mocha\lib\runner.js:339:5)
      at runCallback (timers.js:672:20)
not ok 718 modules support third-party module runas can be required in renderer
  Error: A dynamic link library (DLL) initialization routine failed.
  \\?\C:\Users\alkuzmin\Projects\electron\spec\node_modules\runas\build\Release\runas.node
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
      at Object.Module._extensions..node (module.js:598:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.require (module.js:498:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (C:\Users\alkuzmin\Projects\electron\spec\node_modules\runas\lib\runas.js:4:11)
      at Object.<anonymous> (C:\Users\alkuzmin\Projects\electron\spec\node_modules\runas\lib\runas.js:47:4)
not ok 719 modules support third-party module runas can be required in node binary
  AssertionError: 'A dynamic link library (DLL) initialization routine failed.\r\n\\\\?\\C:\\Users\\alkuzmin\\Projects\\electron\\spec\\node_modul == 'ok'
      at ChildProcess.<anonymous> (C:\Users\alkuzmin\Projects\electron\spec\modules-spec.js:25:18)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:194:7)
      at process.nextTick (internal/child_process.js:766:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
not ok 740 <webview> tag nodeintegration attribute loads native modules when navigation happens
  AssertionError: 'Uncaught Error: A dynamic link library (DLL) initialization routine failed.\r\n\\\\?\\C:\\Users\\alkuzmin\\Projects\\electron\\ == 'function'
      at HTMLElement.listener2 (C:\Users\alkuzmin\Projects\electron\spec\webview-spec.js:181:18)
      at WebViewImpl.dispatchEvent (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\renderer\web-view\web-view.js:175:22)
      at dispatchEvent (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\renderer\web-view\guest-view-internal.js:55:11)
      at EventEmitter.<anonymous> (C:\Users\alkuzmin\Projects\electron\out\R\resources\electron.asar\renderer\web-view\guest-view-internal.js:72:7)
      at emitMany (events.js:127:13)
      at EventEmitter.emit (events.js:204:7)
# tests 827
# pass 820
# fail 7
```

**Comment by alexeykuzmin** [comment]
On Mac:
```
$ ./script/test.py --rebuild_native_modules --ci -c R
<...>
# tests 837
# pass 837
# fail 0
```

**Comment by zcbenz** [comment]
> Both Mac builds failed on "Running upload.py" with requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe')) error.
> @zcbenz Is it ok?

It happens occasionally, usually because of provider's networking issues, it is fine to ignore it if we are just testing whether Release version builds.

> @zcbenz, tests are not ran for Release builds, is it intentional?

Yeah it is intentional, because tests of native modules would fail for an unreleased version.

**Comment by zeke** [comment]
Heads up @alexeykuzmin: we just deleted your 1.8 draft release to make way for a 1.6 release backport. Our release process currently does not allow for more than one draft release to exist.

**Comment by hokein** [comment]
Oops, sorry, I clicked the name on the reviewer panel by accident ;(. Feel free to ignore it.

**Comment by alexeykuzmin** [comment]
> we just deleted your 1.8 draft release to make way for a 1.6 release backport

@zeke it's perfectly fine, this PR is here only to make sure that there is no issues with Release build in CI environment.

**Pull request closed without merging**
