### PR TITLE
Docs: Start Italian translations

### PR DESCRIPTION
**Pull request by Gioggio**
This is a starting point for the Italian translation. I will try to update it as soon as I can.
Suggestion and questions, if any, are heartily appreciated.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Thanks for getting these started 👍  Are these ready to be merged in or are you still working on them?

**Comment by Gioggio** [comment]
I forgot to review faq.md. Now they're ready to be merged 👍

**Comment by kevinsawicki** [comment]
Thanks 👍 🇮🇹

**Comment by zeke** [comment]
Awesome work @Gioggio. Grazie mille!

**Pull request merged**
