### PR TITLE
fix: loading dedicated/shared worker scripts over custom protocol

### PR DESCRIPTION
**Pull request by deepak1556**
#### Description of Change

Closes https://github.com/electron/electron/issues/20557.
Closes https://github.com/electron/electron/issues/24715.

This is a two part fix,

**Part I: Fix crash when loading over data: protocol mentioned in the above issue**

This issue will appear only with nodeintegration enabled in the worker. Adds patch `worker_feat_add_hook_to_notify_script_ready.patch` that explains the root cause of this issue, I am gonna try upstreaming this, will see how it goes. The access to global properties from Node.js happens in `node::MaybeInitializeContext` which modifies the global object for primordials.

**Part II: Cannot load worker scripts over custom protocol**

After https://chromium-review.googlesource.com/c/chromium/src/+/1798250 we need to explicitly register custom URLLoaderFactories for dedicated/shared workers.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:
* fix loading shared worker scripts over custom protocol
* fix crash when loading worker scripts with nodeIntegration enabled

### CODE REVIEW

**Comment by deepak1556** [comment]
`WIP` to add some tests.

**Comment by Dan-Shields** [comment]
Wouldn't know where to begin with writing the tests, but would love to see this merged, especially as v6 is now not supported and was the last version where shared workers worked!

**Comment by krisdages** [comment]
I thought this had been ready to go for a while and just needed to be merged... I assumed there were tests in the last commit since it was approved...

**Comment by codebytere** [comment]
macOS failures are: https://github.com/electron/electron/pull/24748. Will merge when woa finishes.

**Pull request merged**
