### PR TITLE
Add webview attributes for more webPreferences

### PR DESCRIPTION
**Pull request by pfrazee**
Per https://github.com/electron/electron/issues/2749

Adds the following webview tags:

 - disableimages
 - disablejavascript
 - disablewebgl
 - disablewebaudio
 - displayinsecurecontent
 - runinsecurecontent

### CODE REVIEW

**Comment by pfrazee** [comment]
I started to write some tests for this, but ran into problems. I started with images, and found that no error is emitted when images are disabled (loading fails silently).

Let me know what we want to do about that.

**Comment by zcbenz** [comment]
Adding attribute for every property in webPreferences makes the code hard to maintain, I think we should probably add a generic attribute to set webPreferences like the `features` string of `window.open` instead, or add the events as described in https://github.com/electron/electron/issues/2749#issuecomment-232843021.

**Comment by pfrazee** [comment]
Ok. I'll submit a new PR with a webpreferences string

**Comment by pfrazee** [comment]
Closing. This PR is replace by https://github.com/electron/electron/pull/7631.

**Pull request closed without merging**
