### PR TITLE
fix: reduce clipboard flakiness on Windows on Arm

### PR DESCRIPTION
**Pull request by richard-townsend-arm**
#### Description of Change

We've noticed that the clipboard tests (which attempt to put stuff onto the system clipboard and retrieve it later) seem to fail on Windows on Arm more often than on x86. We suspect that this is due to system software increasing contention for the clipboard. This patch adds a chromium-based workaround that increases the retry count when acquiring the clipboard which seems to reduce the number of times the test spuriously fails. We don't expect any impact on other systems (where the clipboard has less contention) and we don't expect this to negatively impact user experience (i.e. when the device is not under test). 

This issue affects the master branch and 6-0-x. Arm will try to contribute the change (or one similar) upstream.

CC @jkleinsc 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by richard-townsend-arm** [comment]
win-x64-testing-pr failure seems spurious, has this in the log:
```
not ok 438 net module ClientRequest API should be able to pipe a readable stream into a net request
  AssertionError: Unexpected URL: /200
      at C:\projects\src\electron\spec-main\api-net-spec.ts:45:14
      at Server.<anonymous> (electron\spec-main\api-net-spec.ts:27:7)
      at parserOnIncoming (_http_server.js:713:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
Unhandled exception in main spec runner: [Error: net::ERR_CONNECTION_RESET]
```
build-mac: CI failed because it could not build [robotjs, autoupdate failure.](https://circleci.com/gh/electron/electron/270979?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link).
buil-linux: linux-arm-build failed [because of a corrupt sscache stream](https://circleci.com/gh/electron/electron/270924?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link).

**Comment by codebytere** [comment]
@jkleinsc is this ok to merge now?

**Comment by jkleinsc** [comment]
@codebytere I'm concerned about this line: https://cs.chromium.org/chromium/src/remoting/host/clipboard_win.cc?type=cs&q=kMaxAttemptsToOpenClipboard&sq=package:chromium&g=0&l=55

**Comment by richard-townsend-arm** [comment]
Hi folks (I’m away from my build machine for a few days), this was an attempted quick fix to try and get in for 6.0.0, but now the time pressure’s eased off a little, I’d like to spend a bit more time getting to the bottom of what’s really going on here. Hopefully have a bit more detail at the end of this week.

**Comment by zcbenz** [comment]
@richard-townsend-arm Do you still plan to work on this? I agree with deepak1556 that changing `//remoting` should not have any effect on Electron.

**Comment by codebytere** [comment]
Closing due to inactivity and no response, but please ping to re-open!

**Pull request closed without merging**
