### PR TITLE
fix: crash on printer dialog cancellation

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/32684.

This PR fixes a crash that occurred when a user attempted to print a document either with `window.print()`, the print button in the PDF viewer, or with `BrowserWindow.webContents()` and clicked cancel in the resulting print dialog. This was introduced in https://github.com/electron/electron/pull/32030/commits/e693ad9f50ff9228fa3b5c228851fb01b3f5ff5a as a result of an attempt to handle upstream changed in CL:3305095. This added a new function `OnUserInitCancelled` to the `PrintJob` `Observer` with the intent that when a job was cancelled it would broadcast to an observed function `OnUserInitCancelled()` in `PrintViewManagerBase`. However, there is one critical problem with that - that `print_job_` does not exist that that point and is intialized afterwards [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/printing/print_job.cc;l=125?q=setprintjob&ss=chromium). As such, `print_job->OnUserInitCancelled()` was a null pointer crash. We fix this by moving the cancellation check to [`ScriptedPrintReplyOnIO`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/printing/print_view_manager_base.cc;l=267?q=ScriptedPrintReplyOnIO&ss=chromium).

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed a crash that occurred when a user attempted to print a document either with `window.print()`, the print button in the PDF viewer, or with `BrowserWindow.webContents()` and clicked cancel in the resulting print dialog

### CODE REVIEW

**Review by VerteDinde — APPROVED** [review]
Thank you! 🙇‍♀️

**Review by zcbenz — APPROVED** [review]

**Comment by deepak1556** [comment]
`ScriptedPrintReplyOnIO` will yield back to UI thread via [ScriptedPrintReply](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/printing/print_view_manager_base.cc;l=708) , the user cancellation check can be performed there and end up calling `UserInitCancelled` directly. This will reduce the patch to not pass around the manager class weak ptr to the different sequences and also avoid the necessity to create a separate UI task `NotifyUserCancelled`

Another question, the scripted print sequences will be triggered for renderer initiated print calls like the pdf viewer print and `window.print` but will this also handle the case for `webContents.print` as mentioned in the PR description ?

**Comment by codebytere** [comment]
@deepak1556 updated and tested with https://gist.github.com/0f0e776b138452d6815ef4efc16aa0d1 to confirm that this fix covers relevant scenarios.

**Review by deepak1556 — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

**Comment by pushkin-** [comment]
When can we expect a backport of this (to 17)?

**Pull request merged**
