### PR TITLE
Don't wait for xdg-open to exit when OpenExternal is called (Linux)

### PR DESCRIPTION
**Pull request by sneakypete81**
Some browsers (eg. Firefox) may not return until the browser window is closed. This causes the Electron application to lock up while the browser window is open.

Fixes https://github.com/atom/atom/issues/6320

I'm struggling to properly test this fix, as I can't work out how to use a custom build of Electron when building Atom. Any help with this would be appreciated.

### CODE REVIEW

**Comment by sneakypete81** [comment]
wait_for_exit should be const, of course.

**Comment by paulcbetts** [comment]
This has been trolling us too, :+1:

**Comment by paulcbetts** [comment]
@sneakypete81 I'd just test it via the console in the Electron default app - if you've got a repro it should be pretty easy

**Comment by zcbenz** [comment]
This would leak processes, I think we can follow Chromium's behavior, by launching a background killer for the process:

```c++
  base::Process process = base::LaunchProcess(argv, options);
  if (process.IsValid())
    base::EnsureProcessGetsReaped(process.Pid());
```

https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/platform_util_linux.cc&q=XDGUtil&sq=package:chromium&type=cs&l=46

**Comment by sneakypete81** [comment]
Thanks @zcbenz, good catch.

@paulcbetts I've verified the fix like this:

**Steps to reproduce:**
* Make Firefox your default browser
* Ensure all Firefox windows are closed
* Start electron without no app
* Click the "docs" link to launch Firefox
* Go back to the electron window and attempt to select some text

**Before PR**
Electron window is frozen, text cannot be selected.
Closing the Firefox window unfreezes the Electron window.

**After PR**
Electron window is not frozen, text can be selected, links clicked, etc.

**Comment by zcbenz** [comment]
👍

**Comment by sneakypete81** [comment]
Great, thanks for the feedback and the quick merge.

**Pull request merged**
