### PR TITLE
build: update symbol script to match chromium script

### LINKED ISSUE #16161: Linux symbols size has decreased significantly in Electron 3
* Output of `node_modules/.bin/electron --version`: 3.0.10
* Operating System (Platform and Version): Linux
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.16

It seems like Linux symbols' size has dropped significantly comparing to Electron 2, e.g. for Electron 2.0.16 [1] size of “electron-v2.0.16-linux-x64-symbols.zip” is *51.3* Mb, but for Electron 3.0.13 “electron-v3.0.13-linux-x64-symbols.zip” it’s only *9.84* Mb.
Native stacktraces are barely useful because of this.

[1] https://github.com/electron/electron/releases/tag/v2.0.16
[2] https://github.com/electron/electron/releases/tag/v3.0.13

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change
Fixes #16161
This PR updates `generate_breakpad_symbols.py` (which is used to generate symbols for Linux and MacOS) to match what Chromium ships with for Chromium 66.0.3359.181:
https://chromium.googlesource.com/chromium/src/+/66.0.3359.181/components/crash/content/tools/generate_breakpad_symbols.py

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] PR release notes describe the change in a way relevant to app-developers

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
Does any of regular CI jobs run this script? Can we compare results to the old version?

**Comment by jkleinsc** [comment]
@alexeykuzmin I can run release builds which can be compared to our last 3-0-x release.

**Comment by jkleinsc** [comment]
@alexeykuzmin release builds running here:
ircleCI release build request for electron-linux-x64 successful.  Check https://circleci.com/gh/electron/electron/110174 for status.
CircleCI release build request for electron-linux-ia32 successful.  Check https://circleci.com/gh/electron/electron/110173 for status.
CircleCI release build request for electron-linux-arm64 successful.  Check https://circleci.com/gh/electron/electron/110175 for status.
VSTS release build request for electron-release-osx-x64 successful. Check https://github.visualstudio.com/545fc86b-2771-473d-94fe-05d8cdc9219a/_build/results?buildId=26572 for status.
AppVeyor release build request for electron-x64 successful.  Check build status at https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.8641
AppVeyor release build request for electron-ia32 successful.  Check build status at https://windows-ci.electronjs.org/project/AppVeyor/electron-39ng6/build/1.0.2207
VSTS release build request for electron-release-mas-x64 successful. Check https://github.visualstudio.com/545fc86b-2771-473d-94fe-05d8cdc9219a/_build/results?buildId=26573 for status.
CircleCI release build request for electron-linux-arm successful.  Check https://circleci.com/gh/electron/electron/110176 for status.

**Comment by blaatunga** [comment]
I've quickly checked the new symbols package from the CI build and compared it with the published Github Electron 3.0.13 symbols and there is certainly change in the size of Linux symbols for Electron (101MB vs. 64MB), however it lacks all the other symbols for all the libraries and I'm not sure that is expected.

Github 3.0.13 Linux x64 symbols example:
image

Pull request Linux x64 symbols example:
image

**Comment by ckerr** [comment]
@alexeykuzmin bump

**Comment by alexeykuzmin** [comment]
@jkleinsc @ckerr 
We will try to do it today.

**Comment by alexeykuzmin** [comment]
@jkleinsc @ckerr 
We created a build with this change, generated a crash, but it didn't get symbolicated.
Unfortunately we aren't able to understand why exactly it doesn't work or how it can be fixed.
Can anyone from GitHub help with that?

**Comment by miniak** [comment]
@jkleinsc, @alexeykuzmin are you still going to pursue this considering Electron 3 is only receiving security fixes now?

**Comment by jkleinsc** [comment]
Closing as it seems like we don't have a good way of verifying this PR.

**Pull request closed without merging**
