### PR TITLE
docs: remove v5 and v6 modernization docs

### PR DESCRIPTION
**Pull request by erickzhao**
#### Description of Change

Removes documentation for API modernization that happened 2 years ago. Added relevant details into the Breaking Changes document.

cc @codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Review by ckerr — APPROVED** [review]
CC @codebytere for fe

**Review by codebytere — APPROVED** [review]

**Review by miniak — APPROVED** [review]

**Comment by miniak** [comment]
@codebytere shouldn't docs changes be `semver/none`?

**Comment by ckerr** [comment]
@erickzhao looks like this needs a change to make CI happy

https://app.circleci.com/pipelines/github/electron/electron/35246/workflows/23f06e0d-6d9a-4e6c-80bd-27f8d8fa1585/jobs/777147

```
#!/bin/bash -eo pipefail
cd src
ninja -C out/Default electron:default_app_js -j $NUMBER_OF_NINJA_PROCESSES
ninja -C out/Default electron:electron_js2c -j $NUMBER_OF_NINJA_PROCESSES
ninja: Entering directory `out/Default'
ninja: error: '../../electron/docs/api/modernization', needed by 'gen/electron/tsc/typings/electron.d.ts', missing and no known rule to make it

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by erickzhao** [comment]
It seems I had to run `ts-node script/gen-filenames.ts`, but `lint-staged` is supposed to re-run it whenever a `docs/api/**/*.md` file is changed. Does it not catch deleted files?

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
