### PR TITLE
feat: activate Happy Eyeballs in NodeJS

### PR DESCRIPTION
**Pull request by treysis**
Implements https://github.com/electron/electron/issues/37044
Fixes https://github.com/electron/electron/issues/31515
Updates https://github.com/electron/electron/commit/75d2caf451c925a826229ae27264c9b54de9b6db, https://github.com/electron/electron/pull/35999

#### Description of Change

Activates usage of the Happy Eyeballs algorithm according to RFC 8305 introduced in NodeJS v18.13. Solves connections problems in IPv4- and IPv6-only networks by creating alternating connection attempts to IPv4 and IPv6 addresses as returned by the DNS resolver.

#### Checklist

- [x] PR description included
- [X] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: activates usage of the Happy Eyeballs algorithm according to RFC 8305 introduced in NodeJS v18.13.

### CODE REVIEW

**Comment by treysis** [comment]
Something with the pipeline jobs seems flaky.

**Comment by treysis** [comment]
Why are the builds failing at `Gclient sync`?

**Review by codebytere — CHANGES_REQUESTED** [review]
hey - could you explain what's going on a bit more here? This change is being made in a test file, which means that it doesn't currently and won't affect end users.

**Comment by treysis** [comment]
> This change is being made in a test file, which means that it won't affect end users.

Ah, oh, I was under the impression that this would change the global settings.

However, I think it would be good to enable Happy Eyeballs globally when switching to Node v18(.13). I'll do some tests and adjust.

**Comment by treysis** [comment]
So I was under the impression you could submit runtime arguments to Node from Electron. This is gonna be interesting when Node v18 lands in Electron v23.

**Comment by jkleinsc** [comment]
Closing as apps can activate this via `net.setDefaultAutoSelectFamily(true)`

**Comment by treysis** [comment]
> Closing as apps can activate this via `net.setDefaultAutoSelectFamily(true)`

They cannot. Happy Eyeballs was introduced with Node v18.13, Electron still uses v18.12. Furthermore, the global setting hasn't been backported. Until now, every `net`-call needs to have the option set individually.

**Pull request closed without merging**
