### PR TITLE
build: rebuild the `dist_zip`s when the deps get modified

### PR DESCRIPTION
**Pull request by RaisinTen**
#### Description of Change

The `dist.zip` generated by the `electron_dist_zip` action was not getting
updated when changes were being made to the dependencies, like the
source files. It turns out, we were using `data_deps` for the dependencies
instead of `deps`. Here is the difference:

`data_deps`: things needed to ultimately run the thing built by a target
`deps`: things needed to build the target

So the difference in treatment of both sets of dependencies is actually
intentional.

Signed-off-by: Darshan Sen <raisinten@gmail.com>

cc @nornagon @dsanders11 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Review by nornagon — APPROVED** [review]
seems plausible

**Review by nornagon — CHANGES_REQUESTED** [review]
whoops nevermind actually this doesn't seem to work: https://app.circleci.com/pipelines/github/electron/electron/49068/workflows/a7ef6297-ab55-4b89-9304-9ff5024adad2/jobs/1116811

**Comment by RaisinTen** [comment]
I updated the patch and the current test failures are unrelated to this change.

**Comment by RaisinTen** [comment]
@codebytere can we please backport this to 15-x-y also?

**Review by nornagon — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Pull request merged**
