### PR TITLE
chore: enable v2 sandbox on mac

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This re-enables the v2 sandbox on mac (disabled by https://github.com/electron/electron/commit/878c5b663df543c684395b672b191fcfbc9f8629). That commit asserts that the v2 sandbox would prevent the `mixed-sandbox` mode from working, but in my testing with this change, it seems to work fine.

```sh
$ ps aux | grep Electron | grep type=renderer
# (abridged)
33083 .../Electron Helper --type=renderer [...] --no-sandbox
33082 .../Electron Helper --type=renderer [...] --enable-sandbox --seatbelt-client=53
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes:
* switch to [V2 sandbox](https://chromium.googlesource.com/chromium/src/+/69.0.3497.106/sandbox/mac/seatbelt_sandbox_design.md) on mac

### CODE REVIEW

**Comment by codebytere** [comment]
ah dangit i didn't intend to approve this yet, ignore the above 🤦‍♀️

**Comment by nornagon** [comment]
Rebased on top of #15894

**Comment by deepak1556** [comment]
Upstream is trying to remove the `kMacV2Sandbox` feature flag soon, they tried it in 71 but due to some failures its fortunately delayed https://github.com/electron/electron/pull/15966/commits/5406108649cac9b850fb28465358cbe4eeb6a528

**Comment by nornagon** [comment]
Pretty sure I can update & land this before 72. Thanks for the info.

**Comment by nornagon** [comment]
I believe the mac and arm failures are flakes, see https://github.com/electron/electron/pull/16027

**Pull request merged**
