### PR TITLE
fix: restore original draggable regions behavior pre-35603

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Reverts three PRs so that we can restore the old draggable regions behaviour.

* #35603
* #36230
* #37016

Notes: no-notes

### CODE REVIEW

**Comment by nornagon** [comment]
reverting not necessary; discovered that new impl is correct.

tldr: previously, `-webkit-app-region: no-drag` would "shine through" `-webkit-app-region: drag`. it no longer does. hacks that apps used to work around that bug may now be presenting as bugs, but these should be fixed on the app side.

**Comment by codebytere** [comment]
@nornagon can you please comment on the open bugs then? there are several:
- https://github.com/electron/electron/issues/37137
- https://github.com/electron/electron/issues/37210
- https://github.com/electron/electron/issues/37301

**Comment by nornagon** [comment]
@codebytere done. #37137 is a duplicate of an older bug (https://github.com/electron/electron/issues/32341), that one is gnarly and can't be fixed without some serious hacking in Blink. It's a Chrome bug, not (just) our bug.

#37210 is WAI, the old behavior was buggy.

#37301 is a real bug, I opened https://github.com/electron/electron/pull/37386 to fix it.

**Comment by codebytere** [comment]
ty! is https://github.com/electron/electron/issues/32341 open as a crbug anywhere? i'd prefer to kick it up there where possible 😅

**Pull request closed without merging**
