### PR TITLE
feat: support `systemPreferences.isDarkMode()` on Windows

### LINKED ISSUE #15316: Windows support for `systemPreferences.isDarkMode()` API
**Is your feature request related to a problem? Please describe.**
Electron has an API which works on macOS for detecting when the system is in Dark Mode.
[Windows 10 also has a dark mode setting](https://www.digitaltrends.com/computing/how-to-enable-dark-mode-in-windows-10/). It would be useful if the same Electron API also worked on Windows.

**Describe the solution you'd like**
1. The `systemPreferences.isDarkMode()` method should work on Windows.
2. Ideally a way of subscribing to change events, equivalent to `systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', callback)`. Or perhaps the `color-changed` event (or another event) would be fired by `systemPreferences`.

**Additional context**
On Windows the state of the dark mode setting [is stored in the](https://stackoverflow.com/a/51336913/365069) `HKCU(HKLM)\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme` registry key.

### LINKED ISSUE #18696: Add method for getting Windows 10 Shell Color
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I need a way of checking if the user is in https://i.imgur.com/yvZYfsG.png
Windows Dark mode or light mode

### Proposed Solution
systemPreferences.getShellColorType()

### Alternatives Considered
n/a

### Additional Information
Because my app icon is white, I want it to invert if using the Windows 10 light mode.
https://i.imgur.com/dzsLQTs.png
You can barely see it in light mode.

### PR DESCRIPTION
**Pull request by DeerMichel**
#### Description of Change
Closes #18696. Closes #15316. Adds support for the `systemPreferences.isDarkMode()` API on Windows using Chromium's `NativeTheme` API. 

#### Outdated (not-actually-used) approach
Whether the system uses dark or light theme is derived from following registry key: 
```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme 
  | value 0  == dark
  | value 1+ == light
```

cc @MarshallOfSound @erickzhao @codebytere 

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added support for `systemPreferences.isDarkMode()` API on Windows.

### CODE REVIEW

**Comment by deepak1556** [comment]
I want to reiterate on this again https://github.com/electron/electron/pull/18666#issuecomment-502882748, why aren't we reusing the api from `ui::NativeTheme` ?

/cc @codebytere @MarshallOfSound

**Comment by DeerMichel** [comment]
Huh... probs bc that would've been too easy 😄. I'll take a closer look at it tmw - looks promising... and even offers an event emitter for theme changes.

Maybe we can get Linux support as well and upstream it to Chromium?

**Comment by codebytere** [comment]
@DeerMichel @deepak1556 we can’t use `ui::NativeTheme` without modifying Chromium; they only support Mojave and higher for isDarkMode(). They only check `effectiveAppearance` whereas we support legacy user prefs back to `10.12`

**Comment by MarshallOfSound** [comment]
Yeah macOS is the issue there.  We could use that api just for Windows support though?

**Comment by deepak1556** [comment]
@codebytere I don't see the reason to patch even if thats the case we could return `ui::NativeTheme` result for `if (@available(macOS 10.14, *)) {` else return result from our implementation..

**Comment by codebytere** [comment]
oops my comment somehow deleted but in response to the above, yeah it might just be fine to gate it on mac and use for windows in totality

**Comment by DeerMichel** [comment]
**Before** merging, should I also add a `dark-mode-changed` (or sth like that) event or better an additional PR? (And i might migrate the other methods to `NativeTheme` as well)

**Comment by MarshallOfSound** [comment]
@DeerMichel If we do do a first-party `dark-mode-changed` event we should probs do it for macOS as well and that requires some consideration as we support < 10.14.  Let's land `isDarkMode` for windows and think about the event separately

**Comment by DeerMichel** [comment]
You're right, I totally forgot about macOS. Then this PR is ready to get merged 👍

**Comment by caesar** [comment]
Will this make it into Electron 6.0.0?

**Pull request merged**
