### PR TITLE
Fix maximized frameless window overflow.

### LINKED ISSUE #5267: Strange overflowing window when maximizing a frameless window
- Electron version: `0.37.4`
- Operating system: Windows

When I maximize my [frameless](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md) electron window a small part of the window in an unmaximized state is visible on a secondary monitor.

**Screenshot**
electronbug

You can visibly see the "line between the monitors" and you can see some really strange overhanging content that is over that line.

**Steps to reproduce**  
1. Open an electron app
2. Maximize the app on your secondary display
3. Look closely for the overflow onto your primary display

This might take a few times to trigger, it appears to do it about 70% of the time :confused:

### PR DESCRIPTION
**Pull request by thesbros**
Fixes #5267, #8728.

### CODE REVIEW

**Comment by groundwater** [comment]
cc/ @tonyganch

**Comment by bsclifton** [comment]
@thesbros one thing you can try is basically turning non-client sizing and painting into a noop ([which I had tried in a previous commit](https://github.com/electron/electron/pull/8404/commits/cf6e215a66687dc983cd81755275f95a78a25a10#diff-c82e463d6bbeb41164c49696ba0d8733)):

```diff
/** Return zero (no-op) for non-client area events when window is frameless.
 +     *  \see WM_NCPAINT - https://msdn.microsoft.com/en-us/library/windows/desktop/dd145212(v=vs.85).aspx
 +     *  \see WM_NCCALCSIZE - https://msdn.microsoft.com/en-us/library/windows/desktop/ms632634(v=vs.85).aspx
 +     */
 +    case WM_NCPAINT:
 +    case WM_NCCALCSIZE: {
 +      if (!has_frame()) {
 +        *result = 0;
 +        return true;
 +      }
 +      return false;
 +    }
```

Unfortunately, this caused rounded edges at 200% DPI ☹️

**Comment by thesbros** [comment]
@bsclifton I tried that and it caused rounded edges even on 100% DPI for me. I'll try doing some testing with higher DPI to fix the borders.

Another thing I noticed while fixing this (that I did not fix) was with a normal, unmaximized frameless window on >100% DPI - the edges are cut off. This only happens in v1.5.x and higher, not on v1.4.x.

**Comment by bsclifton** [comment]
@thesbros doh, then it definitely isn't a good fix (if it caused rounded edges) 

Something I did notice in `WM_NCCALCSIZE` was that you only set the Y. I'd suggest also setting the X like this too

**Comment by thesbros** [comment]
@bsclifton I may have come up with a fix for the rounded edges - however it requires including Uxtheme.h. Where would I add `uxtheme.lib` to be linked in `native_window_views_win.cc`?

**Comment by tonyganch** [comment]
cc @HitomiTenshi

**Comment by thesbros** [comment]
I got everything working, but it requires handling `WM_NCPAINT`  - which in turn causes rounded edges. Does anyone know how to fix this? I tried calling `SetWindowTheme` with empty strings as suggested elsewhere, but that causes the window to disappear.

**Comment by tonyganch** [comment]
> I got everything working

@thesbros, do you have that part when everything except round edges is okay somewhere? I checked out your branch but seems like you haven't updated it.

**Comment by bsclifton** [comment]
Sounds like great progress; great job @thesbros! 😄 

I'm also curious about that branch.  I can help research / try a few things if you are able to make it available 😄

**Comment by thesbros** [comment]
I've pushed the commit. I'd appreciate if someone can test it on higher DPIs (particularly 200%, 250%, 300%) - my display only goes up to 175%.

**Comment by mst128256** [comment]
I've tested a1e012e for 150%, 175%, 200% and 225%. Works well.

**Comment by thesbros** [comment]
@mst128256 That's good to hear. Any thoughts @bsclifton?

**Comment by tonyganch** [comment]
Any news on that PR?

**Comment by adi518** [comment]
@thesbros hey, did you manage to fix the round corners?

**Comment by bsclifton** [comment]
Hi folks- apologies I hadn't responded (I was out most of last week)

I'll try your patch @thesbros and see if I have any ideas

**Comment by juturu** [comment]
@thesbros - Is there any other issue blocking this PR?

**Comment by thesbros** [comment]
@juturu None other than the PR itself. The fix works but has a side effect of causing rounded edges on the left/right top of the frame. My efforts to workaround this have been futile, so I may have to find a different method of disabling non-client paints.

**Comment by poiru** [comment]
@thesbros @bsclifton @juturu Could you try the [frameless-overflow](https://github.com/electron/electron/tree/frameless-overflow) branch?

**Comment by poiru** [comment]
Fixed by #9167.

**Pull request closed without merging**
