### PR TITLE
docs: add connection monitor guide

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
#### Description of Change

This PR supersedes https://github.com/electron/electron/pull/30043 

For semanticness I've renamed the branch and dropped the MSAL example entirely. It was too much set up and felt out of place on the site. I've instead rewrote the example so it starts without authentication and then has a trivial implementation added after the fact. 

Inspired by some internal work I did, this PR adds a guide to the documentation for how users can implement a connection monitoring service. This pattern is useful for any application that needs to support more complex offline capabilities than whats possible with the chromium based online/offline detection. The customer project this was based on used a VPN connection for everything and thus while an internal network may exist, and access to the (regular?) internet could too, if their VPN wasn't on, the app needed to operate in "offline" mode.

If there is still interest in an azure msal-node example I have that code still and can add a follow up article/guide or something later. 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added

#### Release Notes

notes: no-notes

CC @bnb @erickzhao @molant

### CODE REVIEW

**Review by nornagon — CHANGES_REQUESTED** [review]
This seems too complicated to be an example. Have you thought about packaging this as an npm module instead?

**Comment by Ethan-Arrowood** [comment]
> This seems too complicated to be an example. 

I know this is much longer than any existing example but with the new docs site I was hoping we could find an appropriate home for this kind of guide (even if thats a new section in the site). I built this specifically so that a user could one-click run it using electron-fiddle too

> Have you thought about packaging this as an npm module instead?

I don't have the capacity to maintain this as an npm module. I believe the pattern is general enough to be valuable to certain users.

**Comment by nornagon** [comment]
@Ethan-Arrowood I don't see why this example would require less maintenance than an npm module. If it's code that you expect to go out of date quickly, then it's potentially harmful as an example, especially as an unmaintained example.

**Comment by Ethan-Arrowood** [comment]
I don't think it will need much maintenance, but it is not in the format of being something someone would install, import, and run with. I believe it is much more like a starting point/reference folks could adapt to fit their project's specific needs.

**Comment by nornagon** [comment]
Sorry, I still don't think the Electron documentation is the right place for this.

**Comment by molant** [comment]
@nornagon one of the top feedback we've revived in the latest electron surveys is improving three documentation and having more complex scenarios.

I do believe we should provide an space for that type of content in the site and had been discussed lightly in the past in some of the ecosystem meetings.

I'm currently on PTO but maybe we can reopen this PR and discuss this in a future meeting of the WG?
I'll be back in September but @erickzhao should have a similar context as the one I have of you don't want to wait.

**Comment by nornagon** [comment]
I still think this is overly complex. It's more of an example of a state-machine library than an example of any Electron API (though the context bridge and IPC stuff is not bad). I'm happy to have more detailed examples in the docs, but I think 1k LOC is excessive.

A version of this that replaced the state machine logic with something simpler, along with a link to a blog post or example repo with a more fleshed-out core might make sense. It seems like `setInterval` could get you 80% of the way there.

**Comment by Ethan-Arrowood** [comment]
> I still think this is overly complex. It's more of an example of a state-machine library than an example of any Electron API (though the context bridge and IPC stuff is not bad). I'm happy to have more detailed examples in the docs, but I think 1k LOC is excessive.

I hate to be pedantic but the example is much smaller than it appears (and is no where close to 1k LOC). Majority of the lines are comments. And there are essentially two examples here `base` and `with-auth` that share a large percentage of their code. The `with-auth` example adds to the code in `base`.

> A version of this that replaced the state machine logic with something simpler, along with a link to a blog post or example repo with a more fleshed-out core might make sense. It seems like setInterval could get you 80% of the way there.

I'm open to alternative implementations; however, the state machine logic was an intentional decision. The state machine pattern demonstrates resilient development patterns and helps reduce the potential for unknown edge cases. In the project this is based on, it was first built without a state machine and had a plethora of issues cases that were difficult to solve. In fact, the code was significantly longer without the state machine.

I would appreciate if we kept this open while we discuss what to do with my work. I spent a lot of time working on this to benefit the Electron developer community.

**Pull request closed without merging**
