### PR TITLE
Certificate Viewer for macOS

### PR DESCRIPTION
**Pull request by qazbnm456**
Try to implement the certificate viewer for viewing detail of certificate through webContents's API and the button in DevTools. Now with this commit, only `macOS` is supported.

Screenshot:

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
If this feature were under a build flag (and disabled by default) we could probably merge it without waiting for it being done on the other platforms.

**Comment by qazbnm456** [comment]
Thank you for your opinions, @cifratila and @alexeykuzmin . I've put this new feature under a build flag, and therefore I think it could be merged without waiting for it being done on the other platforms.

However, it seems to me that this feature should be enabled by default eventually. Viewing certificates to ensure everything is okay is sometimes needed and useful when we must to load the remote content from a secure website over SSL/TLS connection. Hence, after completing the implementations on the other platforms, I'll re-enable it.

What do you think? Is it more acceptable for you?

**Comment by joshaber** [comment]
This looks very similar to the existing [`dialog.showCertificateTrustDialog`](https://electron.atom.io/docs/api/dialog/#dialogshowcertificatetrustdialogbrowserwindow-options-callback-macos-windows). Is there a difference?

**Comment by qazbnm456** [comment]
@joshaber I don't think the objective is the same. This PR aims for providing a traditional way for users to view a certificate a website owns. It works just like normal browsers will do.

For example, viewing a certificate through the DevTools:

**Comment by vanessayuenn** [comment]
Thank you for your contribution! However, since `dialog.showCertificateTrustDialog` provides a similar functionality, the Electron maintainers group has decided the added value of this PR will not justify the cost of additional maintenance in the project. Closing this PR out as a result.

**Comment by steverandy** [comment]
@vanessayuenn I understand you can use `dialog.showCertificateTrustDialog`, but how do you actually get the `certificate` object from a webview? I couldn't find it in the docs.

**Comment by qazbnm456** [comment]
@steverandy I eventually use [`ses.setCertificateVerifyProc(proc)`](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetcertificateverifyprocproc) to store each certificate object of each website. Though we will store lots of useless certificate objects, it's still a good solution.

I'm pretty sad about this PR didn't get accepted, otherwise, it would be the best solution.

**Pull request closed without merging**
