### PR TITLE
chore: fix chrome_process_finder.patch description

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Follow up to https://github.com/electron/electron/pull/15424.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by deepak1556** [comment]
> and it looks to me like the whole patch could be removed. What would break if we deleted this patch?

Agreed, wanted to hear @zcbenz opinion since he implemented it, only reason I could think of was https://github.com/electron/electron/pull/15424#discussion_r230602052

**Comment by miniak** [comment]
@codebytere can you please merge?

**Comment by zcbenz** [comment]
When using the `app.makeSingleInstance` API, the command line arguments of the new instance will be passed to existing instance. Without this patch, Chromium would append some new flags (`kOriginalProcessStartTime` and `kFastStart`).

The patch description should say `Windows` instead of `POSIX system`.

**Comment by nornagon** [comment]
Why are those extra command line arguments a problem?

What would break if we removed this patch?

**Comment by zcbenz** [comment]
Some apps might have some unit tests failing as there are new command line arguments appended.

I'm good removing this patch and documenting the extra cmd arguments as breaking change.

**Comment by zcbenz** [comment]
> Also, it looks like we have a copy of this file in `chromium_src` anyway—does this patch even have any effect?

We have `process_singleton_win.cc` in `chromium_src` but not `chrome_process_finder.cc`, the former calls `chrome::AttemptToNotifyRunningChrome` which is defined in the latter.

**Comment by nornagon** [comment]
d'oh, my bad, i had an older version checked out. right you are.

**Comment by nornagon** [comment]
In that case, I agree with @zcbenz, let's remove the patch and document the extra flag.

**Pull request merged**
