### PR TITLE
refactor: replace base::StringPrintf() calls with absl::StrFormat()

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

`base::StringPrintf()` is slated for removal and is currently just a pass-through to `absl::StrFormat()`.

Xref: https://issues.chromium.org/issues/40241565
Xref: https://chromium-review.googlesource.com/c/chromium/src/+/4907781

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none.

### CODE REVIEW

**Comment by alicelovescake** [comment]
Is there a reason we want to do this refactor now? Given that the chromium authors are deciding whether `fmt` is more performant and might change the underlying implementation from `absl::StrFormat()` to `{fmt}`, do you think it makes sense to wait until they decide on the implementation before doing the refactor again?
image

**Comment by ckerr** [comment]
Good question!

Until / unless upstream moves to {fmt}, it makes sense for us to call `absl::StrFormat()` directly because of https://chromium-review.googlesource.com/c/chromium/src/+/4907781. `base::StringPrintf()` is now just a wrapper around it, so it's cheaper to remove the intermediate step.

As an aside, if `{fmt}` doesn't cause Chromium any major issues, I would _love_ for upstream to adopt it.  I've been using it in other projects and it's like going from runtime C `printf()` calls to python f-strings / JS template literals that are (mostly) compile-time. Just in terms of Electron, the migration PR would be about the same size as this PR.

https://github.com/fmtlib/fmt

**Comment by ckerr** [comment]
Kind of off-topic for this PR, but just another quick comment in praise of `{fmt}`: here's one before-and-after example from when I migrated code in another project from printf() to {fmt}.

```diff
-            gstr += gtr_sprintf(
-                /* %1$s is the torrent's total size,
-                   %2$s is how much we've uploaded,
-                   %3$s is our upload-to-download ratio,
-                   %4$s is the ratio we want to reach before we stop uploading */
-                _("%1$s, uploaded %2$s (Ratio: %3$s Goal: %4$s)"),
-                tr_strlsize(total_size),
-                tr_strlsize(st->uploadedEver),
-                tr_strlratio(st->ratio),
-                tr_strlratio(seedRatio));
+        gstr += fmt::format(
+            _("{complete_size}, uploaded {uploaded_size} (Ratio: {ratio}, Goal: {seed_ratio})"),
+            fmt::arg("complete_size", tr_strlsize(total_size)),
+            fmt::arg("uploaded_size", tr_strlsize(st->uploadedEver)),
+            fmt::arg("ratio", tr_strlratio(st->ratio)),
+            fmt::arg("seed_ratio", tr_strlratio(seedRatio)));
```

So yes, imagine you're a translator looking at strings to translate.  Would you rather see

> _("%1$s, uploaded %2$s (Ratio: %3$s Goal: %4$s)")

or 

>  _("{complete_size}, uploaded {uploaded_size} (Ratio: {ratio}, Goal: {seed_ratio})"),

:smile:

**Comment by alicelovescake** [comment]
> Good question!
> 
> Until / unless upstream moves to {fmt}, it makes sense for us to call `absl::StrFormat()` directly because of https://chromium-review.googlesource.com/c/chromium/src/+/4907781. `base::StringPrintf()` is now just a wrapper around it, so it's cheaper to remove the intermediate step.
> 
> As an aside, if `{fmt}` doesn't cause Chromium any major issues, I would _love_ for upstream to adopt it. I've been using it in other projects and it's like going from runtime C `printf()` calls to python f-strings / JS template literals that are (mostly) compile-time. More efficient, more type-safe, it's just a great choice.
> 
> wrt Electron, migrating to {fmt} would be about the same size & effort as this PR was.
> 
> https://github.com/fmtlib/fmt

Makes sense! Thanks for highlighting the performance gains from removing the intermediary step and doing the work to make sure our code is always up to date!

**Review by alicelovescake — APPROVED** [review]
🚀

**Pull request merged**
