### PR TITLE
chore: roll libcc (1-7-x)

### PR DESCRIPTION
**Pull request by nornagon**
Pulls in electron/libchromiumcontent#639

### CODE REVIEW

**Comment by ckerr** [comment]
These CI failures look like they're all failing on an artifact download, e.g.

> subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/builduser/project/vendor/libchromiumcontent/script/download', '-f', '-c', 'cf618a1dc03084d5cd4c397ec7989bc912ac7e32', '--target_arch', 'ia32', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', '/home/builduser/project/vendor/download/libchromiumcontent']' returned non-zero exit status 1
Exited with code 1

**Comment by nornagon** [comment]
I was under the assumption that the artifact download issue was a real problem, i.e. that release builds wouldn't work unless those artifacts were available. Am I wrong?

**Comment by ckerr** [comment]
@jkleinsc ^

**Comment by jkleinsc** [comment]
yeah @ckerr this pr shouldn't have been merged yet

**Comment by jkleinsc** [comment]
It looks like the Mac builds for 1-7-x are borked:
https://circleci.com/gh/electron/electron/tree/1-7-x

**Pull request merged**
