### PR TITLE
browser: flags to control iwa enabled server whitelist

### PR DESCRIPTION
**Pull request by deepak1556**
Since v0.37 there is no `URLSecurityManager` directly configured by brightray, instead we need to set the whitelist with `HttpAuthPreferences`. This makes `app.allowNTLMCredentialsForAllDomains` obsolete, have introduced flags which mimic chromes' behavior. This will be a breaking change. Also should `DisableAuthNegotiateCnameLookup` and `EnableAuthNegotiatePort` be added ? 

Ref https://www.chromium.org/developers/design-documents/http-authentication

Fixes https://github.com/electron/electron/issues/4825

Depends on https://github.com/electron/brightray/pull/223

/cc @paulcbetts

### CODE REVIEW

**Comment by deepak1556** [comment]
Actually could bring back `app.AllowNTLMCredentialsForAllDomains` by setting `auth-server-whitelist=*` internally, that way it wouldnt be breaking change. Thoughts ?

**Comment by paulcbetts** [comment]
@deepak1556 This sounds good, we could just make the `allowNTLMCredentialsForAllDomains` just add command-line flags and require that you have to move it before `ready`

**Comment by deepak1556** [comment]
Fixed, thanks!

**Comment by deepak1556** [comment]
Have deprecated `app.allowNTLMCredentialsForAllDomains` and replaced with generic `session.allowNTLMCredentialsForDomains`. Not sure if this the right way to deprecate.

**Comment by zcbenz** [comment]
:+1:

**Pull request merged**
