### PR TITLE
[WIP] Added tray kind detection through dbus

### PR DESCRIPTION
**Pull request by cromefire**
`dbus-native` is still missing and I'm not sure whether electron hasn't an own dbus library.

**At this point not yet able to merge!**

### CODE REVIEW

**Comment by Cromefire** [comment]
Build errors shouldn't have anything to do with my changes as their errors are handled

**Comment by Cromefire** [comment]
Is there an code, which uses that, I'm not much developing neither nodejs nor electron itself and I need at least an example.

**Comment by ckerr** [comment]
An example of using dbus in Electron? Yep, check out the power observer code in `atom/browser/lib/power_observer_linux.{cc,h}`

**Comment by Cromefire** [comment]
So is there any way to call into gio from JavaScript?

**Comment by ckerr** [comment]
Closing stale PR.

No judgement intended. If this PR was closed in error, please ask a maintainer to reopen it.

**Pull request closed without merging**
