### PR TITLE
update  document 

### PR DESCRIPTION
**Pull request by runinspring**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Thanks for these 👍 

Looks like several of these new files aren't translated yet though. Were you planning on updating them in this pull request?

**Comment by runinspring** [comment]
These are missing documents,  I will translate them in next time。

**Comment by kevinsawicki** [comment]
> These are missing documents, I will translate them in next time。

Could we only add them to the folder once they are translated?

That way people don't need to update the API examples in them unless they are already fully translated

**Comment by zeke** [comment]
Hey @runinspring thanks for your contribution. We can definitely merge this PR, but I wanted to let you know that we're working on a new system for translating Electron's docs.

See the readme at https://github.com/electron/electron-i18n#readme for info on how to get started.

If you're able to give it a try, your feedback would be much appreciated!

**Comment by zeke** [comment]
I'm going to close this due to inactivity. @runinspring feel free to comment here if you'd like me to re-open it.

**Pull request closed without merging**
