### PR TITLE
fix: fix an original-fs regression introduced in 4.0 betas

### LINKED ISSUE #15543: `createWriteStream` in `original-fs` is broken
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.6
* Operating System (Platform and Version): Windows 10 x64 Build 17134
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.7

**Expected Behavior**
`require('original-fs').createWriteStream('some/asar/file.asar')` should not error.

**Actual behavior**
The write stream fails with error: `Error: Invalid package some/asar/file.asar`

**To Reproduce**
I've forked `electron-quick-start` with the most trivial repro: https://github.com/adill/electron-quick-start/tree/demo-create-write-stream

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

Fixes a 4.0.0-beta.X regression in `original-fs`. Node's `fs` and `internal/fs/streams` have a lazy-loaded circular dependency, so to expose the unmodified Node `fs` functionality, we have to copy both `fs` *and* `internal/fs/streams` and modify the copies to depend on each other instead of on our asarified 'fs' code.

Fixes #15543.

Discussion: an earlier draft of this code added a new `original_fs` module into atom/common/node-bindings so that multiple Node code that calls `process.binding('fs')` could also be swapped out with a `process.binding('fs_original')`. This more completely separates the asarified and original versions of `fs`, but it also requires more cloning and inter-dependencies, and is not required for #15543. This PR tries to KISS by replacing only what's clearly needed.

CC @codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: Fix 4-0-x regression that broke original-fs

### CODE REVIEW

**Comment by ckerr** [comment]
Hmm, adding on a CC to @MarshallOfSound since he appears to be online sometimes despite it being his holiday. :smile: 

This PR works, and I believe avoids the [previous PR's](https://github.com/electron/node/pull/79) incorrect dependency chain, but I'd like a second opinion on whether or not this is enough or if we should pull `process.binding('fs')` replacements into this patch as well?

**Comment by ckerr** [comment]
Sounds good. Glad to have a sanity check on the priority on the `process.binding()` usage. Thanks :D

**Comment by ckerr** [comment]
The linter bot seems to be hiccuping here, but the change was already validate by our precommit hook, so merging despite the hiccup.

**Comment by jkleinsc** [comment]
Lint passed: https://github.visualstudio.com/electron/_build/results?buildId=25393

**Pull request merged**
