### PR TITLE
A few style updates 2 docs

### PR DESCRIPTION
**Pull request by jlord**
This PR adds a line break before a list on `desktop-capturer.md` so that it renders correctly on the Electron website ✨ It also fixes the header levels on the `session.md` doc as well as go back to using `session` over `ses` for the method examples. 

_Edit_ I just saw @zcbenz that you changed it to `ses`. Whatever you think is best 👍 I thought it was just it was a little unclear but can I change it back if you like it the best as `ses`.

### CODE REVIEW

**Comment by zeke** [comment]
I prefer `session`

**Comment by zcbenz** [comment]
The docs of `session` module is a bit complex case:

* the module name is `session`, and there are a few methods of it;
* there is a class named `Session`;
* the instance of `Session` class is named as `see`.

The layout is of the docs is:

```markdown
# session

## Methods

### session.xxx

## Properties

### session.xxx

## Class: Session

### Instance Events

#### Event: xxx

### Instance Methods

#### ses.xxxx
```

The logic is:

* `Methods`, `Properties` and `Class: Session` belong to the `session` module, so they have `##` level;
* the `session` module's methods and properties use `session.xxx` as title;
* `Instance Events` and `Instance Methods` belong to the `Class: Session` instead of `session` module, so they have `###` level;
* the `Session` class's methods use `ses.xxx` as title, since `ses` is the name of `Session` class's instance;
* the instance of `Session` is named `ses` because `session` is already used as module's name, if we mix the name then it would be hard to distinguish between module methods and `Session`'s instance methods.

Pros:

* Names from docs can be copied to code without modification;
* It is possible to put multiple classes inside one page (think of Node's `http` module);
* It is possible to mix classes and module's methods inside one page.

Cons:

* The level of titles can be too deep;
* The class instance's name can be very ugly.

The whole idea follows Node's documentation style, though I don't any page documents the rules.

**Comment by jlord** [comment]
Thanks for that clarification @zcbenz ✨ I think we can go with what you said and I can make an update to the CSS so that the `#### ses.xxxx` level gets styled similarly to the `###` level methods (this style difference is what first signaled to me something seemed off).

**Comment by jlord** [comment]
Whoops, closed and forgot I also had the space added in this PR and definitely still want that. So I reverted the commit with changes to `session` and will open a PR for style changes in the website repo 👍

**Pull request merged**
