### PR TITLE
chore: remove blink_local_frame.patch

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
As best I can understand from the description, this patch was intended to fix a crash that happened when using `process.on('exit')` to execute code during shutdown. From my testing, there is no such crash now when this patch is removed.

Test code:

```js
// main process
process.on('exit', () => console.log("hi"))
setTimeout(() => process.exit(0), 1000)
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by deepak1556** [comment]
The test code should be executed in render process, also the exit event is emitted when the script context is released which was reliable than the unload event handler but downside was the script execution being forbidden in that hook, which this patch tried to solve. 

At the moment, removing this patch identified a bug in affinity mode, if there are no other crashes then I believe its safe to remove it.

**Comment by nornagon** [comment]
I'm having a hard time verifying that `process.on('exit')` works at all in the renderer process because `console.log`, `alert`, and `process.stdout.write` all don't work during the shutdown process (possibly the child is shut down too quickly/shortly after the `log` that it gets lost somewhere?)

That said, it's not crashing.

Do you have any suggestions for a reliable test?

**Comment by MarshallOfSound** [comment]
@nornagon I'm pretty sure we have a spec for it, but try using syncronous fs

**Comment by nornagon** [comment]
huh... there's `process-exit.html` in the fixtures but it looks like nothing actually loads it?

**Comment by codebytere** [comment]
closing after chat with @nornagon

**Pull request closed without merging**
