### PR TITLE
docs: improve Windows build variable documentation

### PR DESCRIPTION
**Pull request by bnb**
Documents an additional and possibly unclear variable, `DRIVE:`, in the example global variables for building with Windows

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by bnb** [comment]
I see that this is actually violating the `No nesting lists more than 2 levels (due to the markdown renderer).` element in the style guide (thanks to the welcome bot!).

Any suggestions on how similar content has been approached in other cases like this?

**Comment by bnb** [comment]
Perhaps:

```
    * `vs2019_install = DRIVE:\path\to\Microsoft Visual Studio\2019\Community`, replacing `2019` and `Community` with your installed versions and replacing `DRIVE:` with the drive that Visual Studio is on. Often, this will be `C:`.
```

and:

```
    * `WINDOWSSDKDIR = DRIVE:\path\to\Windows Kits\10`, replacing `DRIVE:` with the drive that Windows Kits is on. Often, this will be `C:`.
```

**Comment by zcbenz** [comment]
I'm good putting them in one line.

**Comment by zcbenz** [comment]
I'm closing this since there have been no update for 2 months since last review, please let me know if you plan to continue working on this PR and I'll reopen this.

**Comment by bnb** [comment]
@zcbenz updated! Sorry for dropping out on this one <3

**Pull request merged**
