### PR TITLE
clang-format atom files

### PR DESCRIPTION
**Pull request by codebytere**
what it says on the tin.

/cc @nornagon @ckerr @MarshallOfSound @alexeykuzmin

### CODE REVIEW

**Comment by zcbenz** [comment]
Does this cover the changes in #12647?

**Comment by ckerr** [comment]
That doesn't answer the question though -- why are we excluding those files in our cpplint runner? It's not an accident, multiple files were added to the exclusion over several commits. Were there issues that we're not thinking of here, or is it just historical and can be changed without issue?

@zcbenz did some of those commits, so he might know.

If this is a nonissue, I'm :+1: on bulk-formatting Obj-C along with C++

**Comment by zeke** [comment]
Would now be a good time to also rename `/atom` to `/electron`?

**Comment by codebytere** [comment]
i would be in support of that @zeke

**Comment by zcbenz** [comment]
> That doesn't answer the question though -- why are we excluding those files in our cpplint runner? It's not an accident, multiple files were added to the exclusion over several commits. Were there issues that we're not thinking of here, or is it just historical and can be changed without issue?

cpplint did not work with Objective-C files, we can surely format them with clang-format if it is supported.

**Comment by deepak1556** [comment]
@zcbenz do we want to fix the build failures separately https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.4150/job/0qtjcsjqipndrgfr ?

**Comment by zcbenz** [comment]
@deepak1556 I'm working on a fix for it.

**Pull request merged**
