### PR TITLE
Don't access unique pointer after it was moved from

### PR DESCRIPTION
**Pull request by alespergl**
Fixing crash introduced by https://github.com/electron/electron/commit/2c063f93ff97cd3478f2020ab343b6249fe12546

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@alespergl is it possible to write a test for this?
Maybe not exactly for those headers stuff, but something that would trigger a crash?

**Comment by alespergl** [comment]
It crashed every time, so it's not something that would need a specific test case. It would be good to have a test that would cover this code path, but I don't know what that test would look like.

**Comment by alexeykuzmin** [comment]
Ok, it seems like the problem was quite low level and implementation specific, and it doesn't make much sense to try to avoid a regression writing tests.
Thanks for the fix btw! )

**Comment by ckerr** [comment]
Does this fix #11157?

Asking because the versions match up and because [this comment](https://github.com/electron/electron/issues/11157#issuecomment-347506086) says 11157's crash is triggered inside DevTools, which matches how @cifratila described the bug being fixed in this PR

**Comment by alexeykuzmin** [comment]
@ckerr no, it's different
this crash is was introduced by changes made during the Chromium 61 upgrade,
1.8.x is not affected.

**Comment by ckerr** [comment]
d'oh of course. Thanks Alexey.

**Pull request merged**
