### PR TITLE
Remove judgmental docs terms

### PR DESCRIPTION
**Pull request by codebytere**
Prompted by [this tweet](https://twitter.com/jesstelford/status/992756386160234497).

This PR removes some judgmental words from docs including 'easy', 'just', 'simply', and similar words which might be unfriendly to developers just entering the source and looking at docs.

### CODE REVIEW

**Comment by zeke** [comment]
Good stuff. Did you use a tool to find these?

**Comment by codebytere** [comment]
@zeke i just global searched for combinations and variations of words :)

**Comment by ckerr** [comment]
@zeke grep? :rofl:

**Comment by zeke** [comment]
Finally found the thing I was trying to remember: http://alexjs.com

**Comment by nornagon** [comment]
Ah, the ol' "developed on a macbook" giveaway alex_-_catch_insensitive__inconsiderate_writing

**Comment by zeke** [comment]
@nornagon maybe file an issue? https://github.com/wooorm/alex/issues/new

**Comment by nornagon** [comment]
Good idea! Done: https://github.com/wooorm/alex/issues/187

**Pull request merged**
