### PR TITLE
chore: drop xib files

### PR DESCRIPTION
**Pull request by robertgzr**
Considering the substantial dependency that xcode introduces (16G) build
using just 'Command Line Tools for Xcode' (2G).
Remove the only hard dependency on Xcode by dropping MainMenu.xib. It appears
that the main menu is correctly created without it.

I have an open CL with chromium that removes the dependency there as
well: https://chromium-review.googlesource.com/c/chromium/src/+/3820054

---

I'm opening as draft for now to get some comments and to check I'm not just missing something here :) as in the commit description included above, it would be a big win for the developer experience on mac and CI.

cc @jviotti @RaisinTen 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

### CODE REVIEW

**Review by codebytere — CHANGES_REQUESTED** [review]
This cannot be removed - it's required for `recentDocuments` to work correctly. See https://github.com/electron/electron/pull/20615

**Comment by robertgzr** [comment]
@codebytere ahh this is exactly the kind of input what I was looking for when opening this. I knew there must've been a good reason to keep it in. should've done a search through the PRs here too!

**Comment by codebytere** [comment]
Fwiw if we can figure out a way to solve the `recentDocuments` problem without using the xib files, i'm all for it!

**Comment by jviotti** [comment]
For context: we are trying avoid requiring the full blown Xcode installation + additional components to build Electron on CI and on local environments. From what we can tell, this XIB is the only reason why the Xcode command line tools are not enough. Chromium itself discourages XIBs too (https://www.chromium.org/developers/design-documents/mac-xib-files/).

**Comment by MarshallOfSound** [comment]
FWIW @jviotti the Xcode you need to build Electron is only ~8.6GB and could be made smaller if you didn't care about it being universal.

image

Agreed with @codebytere though, if someone can figure out the magic to make `recentDocuments` work without a xib then I'm 100% down to remove this dependency

**Comment by zcbenz** [comment]
Removing the xib file is possible, but requires using a private API:
https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MMAppController.m#L356-L380

**Comment by robertgzr** [comment]
@codebytere I did some digging around and playing with the code, you might know better about the macOS specifics.

I'm not sure if I fully understand the purpose of the "swap" code here:
https://github.com/electron/electron/blob/e85450b21aea2bb1fd536313fbeca890ab083576/shell/browser/ui/cocoa/electron_menu_controller.mm#L271-L295

I assume it has something to do with recovering the menu as it is auto-populated when the xib is used and then merging that into the menu we create from the model we get from `Menu.buildFromTemplate` and friends

without the xib, it seems the recent document tracking still happens correctly, and we can still access them via [`[[NSDocumentController sharedDocumentController] recentDocumentURLs]`](https://developer.apple.com/documentation/appkit/nsdocumentcontroller/1514976-recentdocumenturls).

Wouldn't it be possible to manually populate the `recentDocuments` submenu with this?

**Comment by codebytere** [comment]
@robertgzr can this be closed for now? Happy to pick it back up if a path forward emerges but as it stands there's not one here now.

**Comment by codebytere** [comment]
Closing as there's not a path forward here now, but happy to pick back up if that changes!

**Pull request closed without merging**
