### PR TITLE
refactor: enable weak ptr unwrap sequence dcheck

### PR DESCRIPTION
**Pull request by deepak1556**
##### Description of Change

- [x] Depends on https://github.com/electron/electron/pull/11357
- [x] Depends on https://github.com/electron/electron/pull/14835

we are depending on weak ptrs quite a bit and ignoring this dcheck will cause problems moving forward.

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
👍 
@deepak1556 can you please rebase it onto the latest master and remove the `[wip]` prefix if you are not going to make any more changes?

**Comment by deepak1556** [comment]
This PR is actually branched against https://github.com/electron/electron/pull/11357 , have rebased them on latest master. There are no more changes to this PR, but need to merge the following before this can be merged.

* https://github.com/electron/electron/pull/11357
* https://github.com/electron/electron/pull/14835

**Comment by deepak1556** [comment]
> Can you also remove all blacklisted WeakPtrDeathTest.* tests from the unittests.yml config?

👍, will do it when I target this PR against master.

**Comment by deepak1556** [comment]
This PR ready for review, thanks!

**Comment by ckerr** [comment]
> need to merge the following before this can be merged.
>
> #11357
> #14835

14835 has been merged, so now we only need #11357.

**Comment by deepak1556** [comment]
@ckerr yup thats correct, will target this PR against master once thats merged.

**Comment by jkleinsc** [comment]
@deepak1556 I just merged in #11357 into master.  Please rebase this when you get the chance.  Thanks!

**Comment by deepak1556** [comment]
@jkleinsc have rebased it against master, thanks!

**Comment by alexeykuzmin** [comment]
@deepak1556 Can you please rebase again? )

**Pull request merged**
