### PR TITLE
fix: backport patch for leaking HTML5 video elements

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Backports https://chromium-review.googlesource.com/c/chromium/src/+/1677053 to `4-2-x` to fix a rather noticeable memory leak when removing HTML5 video elements from the DOM

Notes: Fixed memory leak when removing HTML5 video elements from the DOM with Javascript

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@codebytere Those changes are due to the different versions of `git` folks have on their machines (namely me and @nornagon have different git versions) we fixed this in the patch scripts in more recent branches (I think `6-0-x` and above).  The changes are ok 👍

**Comment by MarshallOfSound** [comment]
I just ran git-export-patches.  I'd rather avoid manually editing patch files by hand or picking and choosing.

**Comment by jkleinsc** [comment]
@MarshallOfSound I get that but couldn't you be selective on what files you commit?

**Comment by MarshallOfSound** [comment]
@jkleinsc those hunks generate the sha that my newly added patch is based off of.  It might work, but it might not.  Id rather just take the output of git-export-patches.

**Comment by MarshallOfSound** [comment]
test failures look video related, I'll take a look

**Comment by MarshallOfSound** [comment]
@jkleinsc @codebytere Tests are fixed, should be All Clear now.  Needed to handle a `nullptr` case that the original CL did not as Chromium has removed legacy media inputs in C75, we still have them in C69 👍

**Comment by codebytere** [comment]
Approving given added context above!

**Comment by deepak1556** [comment]
> Needed to handle a nullptr case that the original CL did not as Chromium has removed legacy media inputs in C75, we still have them in C69

Can you share the CL that changed this ? I am concerned that `volume_slider_` is expected to be non-null and while it doesn't. There are other locations in the code where they null protect against `volume_slider_`. 

Did you try running with `--enable-features=UseModernMediaControls` to check if its the legacy controls thats causing this difference ?

**Comment by peteringram0** [comment]
@MarshallOfSound Does this also fix the following bug: https://github.com/electron/electron/issues/18019 ? Thanks

**Pull request merged**
