### PR TITLE
test: fix and undisable parallel/node-crypto

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Undisable many node crypto tests.

Broadly, we should be able to run almost all of Node's crypto tests. In most
cases, the only change needed is to use ciphers or hashes that are available in
both BoringSSL and OpenSSL. For tests that depend on OpenSSL-specific behavior,
or which specifically test ciphers that BoringSSL doesn't support, we will need
to find a way to enable them only when building against OpenSSL.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by ckerr** [comment]
The `build-linux` failure looks like it might not be a flake:

```
            duration_ms: 0.43
            severity: fail
            exitcode: 1
            stack: internal/crypto/hash.js:46
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:115:10)
    at Object.<anonymous> (/home/builduser/project/src/third_party/electron_node/test/parallel/test-crypto-hash.js:188:29)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Function.Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by nornagon** [comment]
@ckerr i'm confused how those weren't failing in master, given they weren't in the ignore list...

**Comment by nornagon** [comment]
Includes #27674

**Comment by ckerr** [comment]
https://app.circleci.com/pipelines/github/electron/electron/35826/workflows/eea7b9d0-c056-4cef-abbe-2d441e37d8b8/jobs/785757 appears to not be a flake

```
#446 parallel/test-crypto-dh-stateless - Default

          ---
            duration_ms: 0.333
            severity: fail
            exitcode: 1
            stack: internal/crypto/keys.js:351
  handle.init(kKeyTypePrivate, data, format, type, passphrase);
         ^

Error: error:06000080:public key routines:OPENSSL_internal:UNSUPPORTED_ALGORITHM
    at Object.createPrivateKey (internal/crypto/keys.js:351:10)
    at Object.<anonymous> (/home/builduser/project/src/third_party/electron_node/test/parallel/test-crypto-dh-stateless.js:32:32)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Function.Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  opensslErrorStack: [
    'error:0900000c:PEM routines:OPENSSL_internal:ASN.1 encoding routines',
    'error:13000068:PKCS8 routines:OPENSSL_internal:DECODE_ERROR'
  ],
  library: 'public key routines',
  function: 'OPENSSL_internal',
  reason: 'UNSUPPORTED_ALGORITHM',
  code: 'ERR_OSSL_EVP_UNSUPPORTED_ALGORITHM'
}
```

**Comment by nornagon** [comment]
hm... i wonder if the disabled tests are somehow acting as patterns rather than specific exclusions? it seems like having `parallel/test-crypto-dh` in the disabled list was also causing `parallel/test-crypto-dh-stateless` to be disabled.

**Comment by nornagon** [comment]
> acting as patterns rather than specific exclusions

indeed: https://github.com/nodejs/node/blob/6ea9af9906cd74ed07ca05cf6aa44382025a6044/tools/test.py#L1689

**Comment by nornagon** [comment]
@ckerr tests are green now

**Review by codebytere — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Comment by nornagon** [comment]
Test failures unrelated, merging.

**Pull request merged**
