### PR TITLE
change heading level for MenuItem instance properties

### PR DESCRIPTION
**Pull request by zeke**
@zcbenz I think these headings were too deep. Is that correct?

### CODE REVIEW

**Comment by zcbenz** [comment]
The `Instance Properties` section is part of `Class: MenuItem` section, so it is one leveler deeper than `## Class: MenuItem`:

```markdown
## Class MenuItem

### Instance Properties
```

**Comment by zeke** [comment]
The `## Instance Properties` headings in `browser-window.md` and `menu.md` also occur after a `## Class: ...` heading. Should they be `### ` then as well?

**Comment by zcbenz** [comment]
Yeah they should be updated to follow the style guide, many files are still using the old style.

**Comment by zeke** [comment]
> many files are still using the old style.

I'll track those down and open a new PR.

**Pull request closed without merging**
