### PR TITLE
refactor: use [Sync,NoDeadlockPrevention] in for MessageSync

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This removes a bunch of hacks we have to pretend that the `ElectronBrowser.Message` mojo function is asynchronous, by adding a new `[NoDeadlockPrevention]` flag to Mojo.

Some background: Mojo already has the functionality to be able to send synchronous messages; i.e. messages on which the sender will block until a response is received. In order to prevent a situation in which two processes are waiting for each other (or other deadlock situations), if process (A) sends a synchronous message to (B) and is waiting on the result, and then process (A) receives a synchronous request from process (C), it will process it immediately (even though it's still waiting for the response to its first message). This can result in synchronous messages being received out-of-order with respect to asynchronous messages.

There are some IPC messages in Electron which rely on strict ordering between synchronous and asynchronous messages. Most of the time, the main process doesn't send any synchronous IPC messages and `[Sync]` would work just fine (because the reordering only kicks in if a process receives a synchronous message while it's waiting for a response to a synchronous message that it sent). However, there are a few cases in window shutdown where the main process _does_ send a synchronous message, resulting in out-of-order message delivery.

This new `[NoDeadlockPrevention]` flag disables the deadlock-breaking feature for the method, meaning that correct ordering will be guaranteed w.r.t. other asynchronous messages sent on the same channel. The sending side still sees the message as synchronous, but the receiving side won't reorder the message on receipt if it's in the middle of making a synchronous request itself.

The main reason to do this is that our existing approach with `ThreadSafeElectronBrowserPtr` cannot listen for channel errors, since the `ThreadSafeInterfacePtr` class doesn't have that functionality, resulting in a possible issue where the process issues a request and then blocks waiting for a response which it will never receive, because the remote end has hung up. This PR doesn't fix that issue, but it does make it _possible_ to fix.

Upstream CL: https://chromium-review.googlesource.com/c/chromium/src/+/1872981

Ref #20086 #20547 #20632

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by deepak1556** [comment]
This is cool!

> The main reason to do this is that our existing approach with ThreadSafeElectronBrowserPtr cannot listen for channel errors

Can you also please give some background on why the current approach was taken instead of fixing this ?

**Comment by nornagon** [comment]
`ThreadSafeElectronBrowserPtr` doesn't have the `set_connection_error_handler` method that `ElectronBrowserPtr` has, so it's not possible to listen for connection errors through that class.

**Comment by deepak1556** [comment]
`ThreadSafeInterfacePtr` operates on the `InterfacePtr` and has access to the ptr state , so we could add a method to set the connection handler right https://cs.chromium.org/chromium/src/mojo/public/cpp/bindings/thread_safe_interface_ptr.h?l=169-176 ?

**Comment by deepak1556** [comment]
Having said that, I don't have the best expertise to judge which approach is better here, if upstream accepts the deadlock flag, we should very well use it as its much more straight forward and makes our implementation simpler.

**Comment by nornagon** [comment]
update: chances of upstream accepting my patch are looking gloomy.

**Pull request closed without merging**
