### PR TITLE
Add mode prop to segmented touch bar control

### LINKED ISSUE #9298: removing space between TouchBar buttons
How can I make TouchBar buttons smaller and or remove the space between buttons?

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #9298

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@kevinsawicki Woops, looks like I closed my laptop lid before the last push finished 😆 Will push up the missing docs in the morning 👍

**Comment by kinglime** [comment]
is there a way I could test this out on my local machine?

**Comment by kevinsawicki** [comment]
> is there a way I could test this out on my local machine?

You can check out this branch and build Electron locally and then run `npm start` to launch the newly built version, https://electron.atom.io/docs/development/build-instructions-osx/

**Comment by kevinsawicki** [comment]
> Woops, looks like I closed my laptop lid before the last push finished 😆 Will push up the missing docs in the morning

@MarshallOfSound got a chance to push up these docs? 📝

**Comment by MarshallOfSound** [comment]
> @MarshallOfSound got a chance to push up these docs? 📝

I always see these just as I'm heading to sleep 😆 I swear I'll push it up tomorrow morning 😉

**Comment by MarshallOfSound** [comment]
Not gonna lie, totally wasn't "in the morning", but they're up there now 😆 @kevinsawicki

**Comment by kevinsawicki** [comment]
Thanks for this @MarshallOfSound 👍

**Pull request merged**
