### PR TITLE
chore: pull ProxyingURLLoaderFactory closer to upstream class it mirrors

### PR DESCRIPTION
**Pull request by dsanders11**
#### Description of Change

This PR pulls `electron::ProxyingURLLoaderFactory` closer to upstream `extensions::WebRequestProxyingURLLoaderFactory` so that diffs between the two are cleaner, and it's easier to see how they differ, and land changes from upstream. Creating this PR highlighted a few future PRs in this class (will make those PRs after this is merged to avoid conflicts) and some changes for upstream (will make those).

There should be no functional changes in this PR, the closest to a functional change is adding `const` to one of the member variables to match upstream. Otherwise this PR:

* Adds/removes headers to more closely match upstream
* Changes a couple of comments to match upstream
* Changes order of methods and a member variable to match upstream 

This results in a more clear diff when comparing to `extensions::WebRequestProxyingURLLoaderFactory`.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes

Notes: none

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
How different is this to upstream? Is the potential / risk of drift quite high? Maybe it's worth maintaining a patch-set instead of copy-pasting the source in this case.  I don't fully understand the risk / drift here maybe @nornagon has thoughts

**Review by nornagon — APPROVED** [review]
Seems fine to me. It's worth thinking about what a patch might look like, but iirc we decided that copy/pasting was the way to go here.

**Comment by dsanders11** [comment]
> How different is this to upstream?

Not radically different, but different. `electron::ProxyingURLLoaderFactory` drops a few large chunks from `extensions::WebRequestProxyingURLLoaderFactory` about authorization and 'is redirect safe', as well as a few other logic changes. It also adds some logic for '--ignore-connections-limit' and intercepting requests.

> Is the potential / risk of drift quite high?

`extensions::WebRequestProxyingURLLoaderFactory` seems pretty stable overall, the only changes it really gets are bug fixes, a few other changes, and they added code for UMA graphs. In 2020 there were 25 changes (many of which made it into `electron::ProxyingURLLoaderFactory), in 2021 so far there's been 7, at least one of which was grabbed during a Chromium bump.

> Maybe it's worth maintaining a patch-set instead of copy-pasting the source in this case.

Definitely something that crossed my mind. The changes are enough, and include Electron feature logic, to the point where it might obscure the code too much if it ended up in a patch-set. Future changes to how intercepting requests is done might move where that logic is, which might make this a better candidate for a patch-set.

> I don't fully understand the risk / drift

I think the main risk is just not picking up fixes from upstream, which could be helpful to users.

**Comment by dsanders11** [comment]
Added another commit (change to a comment) which I'd submitted to upstream and they just merged.

**Review by zcbenz — APPROVED** [review]
Can you fix the merge conflict?

**Comment by dsanders11** [comment]
@zcbenz, rebased.

**Pull request merged**
