### PR TITLE
Bump node version number

### PR DESCRIPTION
**Pull request by Alex-D**

### CODE REVIEW

**Comment by thomasjo** [comment]
What's the justification for choosing v8.2.0? The latest release is v8.4.0. If there is some specific, valid reason for sticking to the 8.2.x releases, this should at the very least be using v8.2.1.

**Comment by Alex-D** [comment]
I'm just updating the version in this file, as you can see on the release note, we are on v8.2.1 (I will update the PR).

**Comment by zeke** [comment]
@zcbenz what are we using this file for?

**Comment by zcbenz** [comment]
@zeke As far as I know it is used by `nvm` to switch node versions when running node script in this repo, I'm not sure whether it has other uses.

**Pull request merged**
