### PR TITLE
feat: add preloadSrc web preference

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This allows specifying the source of a preload script as a string, rather than by a file path.

This is marked [WIP] for two reasons:

1. This API should be considered within the broader scope of what we're thinking about for the future of preload scripts, including but not limited to:
  - defining multiple different kinds of preload scripts depending on the context type (e.g. an extensions preload script)
  - precompiling preload scripts
  - bundling precompiled preload scripts with the app
  - automatically precompiling/caching preload scripts in the main process, rather than reading them off disk every time
2. The way this system works in renderers with node integration enabled is odd, in that preload scripts are loaded with `Module._load`, which requires a file path to function. How this should interact with `preloadSrc` is unclear to me.

However, I'm putting this PR up in its WIP state to gather feedback and design critique to hopefully move this feature forward & make preload scripts faster and better.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: Added the `preloadSrc` web preference, which allows preload scripts to be specified by their source code instead of by file name.

### CODE REVIEW

**Comment by miniak** [comment]
@nornagon we should later use `ELECTRON_BROWSER_LOAD` to pass more webPreferences to the renderer instead of using the commandline, which is causing issues when multiple webContents live in the same renderer process, such as #18466

**Comment by MarshallOfSound** [comment]
@miniak the act of moving webprefs to be IPC based instead of cmd line based is being worked on but I don't think that's directly related to this PR.

**Comment by miniak** [comment]
@MarshallOfSound I have an old PR where I was experimenting with that, but using a native mojo call (#19043). Are you working on it?

**Comment by MarshallOfSound** [comment]
I'm not, @loc is though

**Comment by deepak1556** [comment]
Precompiling and loading cached data for preload scripts is a good one to have. https://nodejs.org/docs/latest-v12.x/api/vm.html#vm_script_createcacheddata should serve for spitting out v8 code cache

For the preload strings, do we generate them on every run of the app ?. And for preload scripts, even if we generate cache data we would still have to write them to disk, then we would be comparing the performance of loading via `Module._load` vs loading cached data from disk.

Do you have other ideas for caching ?

Certainly benchmarks on these would be helpful for general design of the api.

**Comment by nornagon** [comment]
> Do you have other ideas for caching ?

My plan was to expose the necessary functionality and leave the strategy to developers / 3rd party libraries. There are real tradeoffs between convenience, flexibility and performance and I'm not sure we can choose the right way for every use case.

e.g.

- it's convenient to re-read from disk every time during development, because then you can edit / cmd+r and not have to restart the whole app. so we shouldn't cache forever.
- compiling on first run might ultimately make launch slower.
- holding onto the preload script's source code in the main process could be an undesirable memory cost

the api we decide on should allow apps to make the right trade-off for their use case.

**Comment by deepak1556** [comment]
That sums up pretty well, thanks!

Just to add, incase the app decides the necessity for a cached preload src then we are responsible for generating it. And if we are looking to promote different kinds of preload then maybe [session.setPreloads](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetpreloadspreloads) can serve as the main source of serving preloads instead of the webPreference container.

```
session.setPreloads([
  {
     source: <Buffer> | <Path> | <DataView>,
     kind: 'extension' | 'BrowserWindow' | 'webView',
     produceCachedData: <Boolean>,
     origin: <url::Origin>
  }
])
```

**Comment by nornagon** [comment]
. o O ( I wonder if we should support something like [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)s as preload sources...? )

**Comment by deepak1556** [comment]
That would be a cool exploration for storing and transferring large preload sources.

**Comment by nornagon** [comment]
I still think this idea is worth pursuing, but this PR is pretty stale by now and I haven't had time to work on it.

**Pull request closed without merging**
