### PR TITLE
build: use python3 to download external binaries

### PR DESCRIPTION
**Pull request by MarshallOfSound**
On master, on macOS the version of `vpython` chrome ships in depot tools does not have a new enough version of openssl to download things from github.  This updates our script to work in both python 2 and python 3 and updates our DEPS file to use python 3 to download the external binaries.

This fixes the issue with nightlies not releasing.

Notes: no-notes

### CODE REVIEW

**Comment by codebytere** [comment]
Do we need to backport this to 8?

**Comment by jkleinsc** [comment]
Merging as CI failures unrelated to PR change

**Comment by nornagon** [comment]
FWIW this broke my build on Windows as I don't have python3 installed there.

**Pull request merged**
