### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by ToPeas**
#### Description of Change

`!DOCTYPE` can’t display properly on the website [here](https://www.electronjs.org/docs/tutorial/quick-start).

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: 

just update docs

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
https://www.electronjs.org/docs/tutorial/quick-start appears correctly for me as is:
Screen Shot 2020-11-24 at 9 57 22 AM.  Are you seeing something different?  If so, what browser are you using?

**Review by erickzhao — COMMENTED** [review]
It renders correctly for me on FF, Chrome, and Safari on macOS.

**Comment by ToPeas** [comment]
> https://www.electronjs.org/docs/tutorial/quick-start appears correctly for me as is:
> Screen Shot 2020-11-24 at 9 57 22 AM. Are you seeing something different? If so, what browser are you using?

> It renders correctly for me on FF, Chrome, and Safari on macOS.


It’s amazing, now my browser can display correctly. 
yesterday, my browser only show `<OCTYPE>`, i copy these code in vscode and then reports error, so i find it. 
i close this PR. thanks for your reply

**Comment by erickzhao** [comment]
Thanks for the update. :)

**Pull request closed without merging**
