### PR TITLE
chore: add a script to check if patches changed post-checkout

### PR DESCRIPTION
**Pull request by brenca**
#### Description of Change

Sometimes I find myself forgetting to run `gclient sync` when patches change, which can lead to things not building (properly). This PR adds a script to check the patches against the applied patchsets to indicate if you should run `gclient sync` after you checked out the code.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by malept** [comment]
Hm, shouldn't this be the Releases WG and not the Docs & Tools WG?

**Comment by brenca** [comment]
@malept For me, this is more in the territory of docs & tools than releases - this doesn't have much to do with releases, it's closer to `lint` in my eyes (alerts you to do st. you should), and that sounded like st. that fits the description of a `tool`. I'm ready to change my mind 'tho, I'll cc @ckerr and @codebytere to maybe get some additional insight.

**Comment by malept** [comment]
I guess maybe either the Releases WG, or more likely the Upgrades WG, as Upgrades handles the patches.

Per the [Docs & Tools WG README](https://github.com/electron/governance/tree/master/wg-docs-tools#readme), we handle external tools (e.g., Electron Packager), not internal tooling like linting.

**Comment by nornagon** [comment]
Patch management falls under the purview of the Upgrades WG :)

**Comment by zcbenz** [comment]
I'm closing this PR since the author is not going to work on this. Please start a new PR if anyone else would like to pick up the work.

**Pull request closed without merging**
