### PR TITLE
fix: removed unused import

### PR DESCRIPTION
**Pull request by Biki-das**
#### Description of Change

Removed imported objects which were being unused.

#### Checklist

- [x] `npm test` passes

#### Release Notes: 

Notes: none

### CODE REVIEW

**Comment by dsanders11** [comment]
@Biki-das, thanks for the PR! I'll review this shortly, but in the mean time can you fix this PR up to follow our processes?

- Your initial comment [needs to follow the PR template](https://github.com/electron/electron/blob/main/.github/PULL_REQUEST_TEMPLATE.md), so please edit it to match
- Your commit should use a [semantic commit message](https://github.com/electron/electron/blob/main/docs/development/pull-requests.md#commit-message-guidelines)

**Comment by dsanders11** [comment]
The Python changes LGTM, just needs the changes I mentioned in the previous comment.

**Review by VerteDinde — CHANGES_REQUESTED** [review]
Hey @Biki-das, thanks for submitting a PR! As @dsanders11 said, we just need you to update a few items in this PR to follow our style guide, so I'm marking this as "Changes Requested" until those are added.

We have a PR template that you should see when submitting a PR - following that template is recommended. 🙂  If you have any other questions, you're welcome to ask them here or reference [our Contributing guide.](https://www.electronjs.org/docs/latest/development/pull-requests#step-9-opening-the-pull-request) Thanks!

**Comment by Biki-das** [comment]
@VerteDinde is it fine now 😅, and i am sorry for not following the pr template and commit guidelines, will surely follow it for next PR's.

**Review by VerteDinde — APPROVED** [review]
Looks good, and CI is passing - thanks for the PR!

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
