### PR TITLE
fix: NativeImage serialization of <webview>.capturePage() result

### LINKED ISSUE #8151: Remote issues with clipboard and NativeImage
* Electron version: 1.4.10
* Operating system: MacOS

### Expected behavior

Captured image from webview is copied into clipboard

### Actual behavior

Crashes with error message 

```
Uncaught TypeError: Error processing argument at index 0, conversion failure from [object Object]
```

### How to reproduce

I am capturing a region of a webview object and then saving as an image (works pretty ok, although sometimes the image is empty), then I am trying to copy the NativeImage into clipboard, but it crashes

```js
webview.capturePage(rect, image => {
              const quality = 90
              const filename = 'image.jpg'
              const fullPath = path.join(__dirname, filename)
              fs.writeFile(fullPath, image.toJPEG(quality), (err) => {                
                 // TODO: retry save if the image is 0 size
                clipboard.writeImage(image)
              })
})
```

I can see the image on the disk, but the clipboard has never received it, always crashing

### LINKED ISSUE #16241: Electron 4.0.0 - webview.capturePage returns empty object.
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.13

**Expected Behavior**
[`webview.capturePage(callback)`](https://electronjs.org/docs/api/webview-tag#webviewcapturepagerect-callback) should invoke the callback with a NativeImage.

**Actual behavior**
`webview.capturePage(callback)` invokes the callback with an empty/plain object.

**To Reproduce**
See [this gist](https://gist.github.com/wjhir/c8cb4497c9c2ce2ec4d0262b285584eb#file-renderer-js).

**Additional Information**
`webview.getWebContents().capturePage(callback)` still works as expected.

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Fixes #8151
Fixes #16241

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed `<webview>.capturePage()` resolving with an empty object instead of `NativeImage` instance.

### CODE REVIEW

**Comment by miniak** [comment]
@nornagon, @MarshallOfSound can you please review?

**Comment by miniak** [comment]
@nornagon done, I've created a separate IPC for `capturePage`, which does the serialization.

**Comment by nornagon** [comment]
@alexeykuzmin i agree, but it was there before, so 🤷‍♂ i guess?

**Comment by alexeykuzmin** [comment]
@nornagon yeah, I was going to write a comment about it but then checked contents of the removed file =) The PR looks good otherwise.

**Comment by alexeykuzmin** [comment]
The **win-x64-testing** failure is not related to the change. Merging.

**Pull request merged**
