### PR TITLE
fix: invoke the window open handler for _blank links

### LINKED ISSUE #27967: The handler of "setWindowOpenHandler" not fires on Electron 12.0.0
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * Windows 10 20H2

### Expected Behavior
Handler fires and no new window opens 

### Actual Behavior
Handler fails and a new window opens

### To Reproduce
1. Write this code:

```javascript
window.webContents.setWindowOpenHandler(() => ({ action: "deny" }));
```

2. Debug or run the application.
3. Press Alt + LMB (or Scroll) on any <a> link in app.

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #27967.

The window open handler was not invoked in situations where `-new-window` was
called without calling `-will-add-new-contents` / `-add-new-contents`, in
particular, when `target=_blank` or when holding a modifier key when clicking
on a link.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed the handler set with `setWindowOpenHandler` not being invoked when a link was middle-clicked or shift-clicked.

### CODE REVIEW

**Comment by nornagon** [comment]
cc @clavin @VerteDinde

**Review by VerteDinde — APPROVED** [review]
Looks good! Tested with nativeWindowOpen set to true and set to false; `action: deny` blocks the window from opening, and `action: allow` opens it.

**Review by clavin — APPROVED** [review]

**Comment by nornagon** [comment]
hmmm i should probably write a test though.

**Review by clavin — APPROVED** [review]
Good call on adding some testing 👍 I was curious to see how this could be tested

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
Asan test failure:

> chrome extensions devtools extensions loads a devtools extension - loads a devtools extension

is not relevant.

**Pull request merged**
