### PR TITLE
docs: use Emoji in documentation

### PR DESCRIPTION
**Pull request by HashimotoYT**
See https://github.com/electron/electronjs.org/issues/1265
This pull request change string emoji to Emoji.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Hey @HashimotoYT 

Can you explain the reasoning behind changing these, GitHub auto corrects the textual form when rendering markdown so visually they are the same but the previous form made it clear to editors when the emoji was

**Comment by HashimotoYT** [comment]
@MarshallOfSound This question written to not end?:
> the previous form made it clear to editors when the emoji was

## The Problem

Yes, GitHub compile textual form of Emoji, but [electronjs.org](https://github.com/electron/electronjs.org) don't able to compile textual form Emoji and it's see on screenshot:

v1

This is small fix give to render the Emoji on website.

## Readability

If someone wants view emoji code he able to hover the Emoji and view it:

v2

**Comment by MarshallOfSound** [comment]
cc @zeke Is that a bug in the markdown parser used on the website?

**Comment by zeke** [comment]
Opened https://github.com/electron/hubdown/issues/5 -- I'll look into it.

**Comment by ckerr** [comment]
I agree with @zeke on where to fix the issue. Thanks very much @HashimotoYT for spotting this and reporting it!

**Pull request closed without merging**
