### PR TITLE
fix: revive offscreen rendering support

### PR DESCRIPTION
**Pull request by adill**
#### Description of Change

This PR reintroduces offscreen rendering on Windows, macOS, and Linux. It should be relatively backport friendly for `8-x-y` and `9-x-y`.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Enable offscreen rendering

### CODE REVIEW

**Comment by jkleinsc** [comment]
@adill can you rebase against master?

**Comment by adill** [comment]
> @adill can you rebase against master?

I'm back from vacation today so I'll rebase and send a ping!

**Comment by adill** [comment]
@jkleinsc Finished the rebase on `master`

**Comment by jkleinsc** [comment]
@adill can you rebase one more time to resolve the conflict?  I'd like to merge this in today if we can.

**Comment by adill** [comment]
@jkleinsc Ye olde `chromium/.patches` 💯 conflict resolved.

**Comment by jkleinsc** [comment]
CI is green and I validated this locally as well.  Thanks for your work on this @adill!

**Pull request merged**
