### PR TITLE
add a prerelease check

### PR DESCRIPTION
**Pull request by zeke**
This adds a check to ensure that a draft release has the right version, is a prerelease, has release notes, and includes all the expected assets.

The `prerelease` npm script will be run automatically when `npm run release` is run.

🍐 @vanessayuenn

### CODE REVIEW

**Comment by zeke** [comment]
```
❯ npm run prerelease

> electron@1.7.5 prerelease /Users/z/git/electron/electron
> node ./script/prerelease

✓ one draft exists
✗ draft release version matches local package.json (v1.7.5)
✓ draft is a prerelease
✓ draft has release notes
✓ draft has expected number of assets
✓ electron-api.json
✓ electron-v1.7.6-darwin-x64-dsym.zip
✓ electron-v1.7.6-darwin-x64-symbols.zip
✓ electron-v1.7.6-darwin-x64.zip
✓ electron-v1.7.6-linux-arm-symbols.zip
✓ electron-v1.7.6-linux-arm.zip
✓ electron-v1.7.6-linux-armv7l-symbols.zip
✓ electron-v1.7.6-linux-armv7l.zip
✓ electron-v1.7.6-linux-ia32-symbols.zip
✓ electron-v1.7.6-linux-ia32.zip
✓ electron-v1.7.6-linux-x64-symbols.zip
✓ electron-v1.7.6-linux-x64.zip
✓ electron-v1.7.6-mas-x64-dsym.zip
✓ electron-v1.7.6-mas-x64-symbols.zip
✓ electron-v1.7.6-mas-x64.zip
✓ electron-v1.7.6-win32-ia32-pdb.zip
✓ electron-v1.7.6-win32-ia32-symbols.zip
✓ electron-v1.7.6-win32-ia32.zip
✓ electron-v1.7.6-win32-x64-pdb.zip
✓ electron-v1.7.6-win32-x64-symbols.zip
✓ electron-v1.7.6-win32-x64.zip
✓ electron.d.ts
✓ ffmpeg-v1.7.6-darwin-x64.zip
✓ ffmpeg-v1.7.6-linux-arm.zip
✓ ffmpeg-v1.7.6-linux-armv7l.zip
✓ ffmpeg-v1.7.6-linux-ia32.zip
✓ ffmpeg-v1.7.6-linux-x64.zip
✓ ffmpeg-v1.7.6-mas-x64.zip
✓ ffmpeg-v1.7.6-win32-ia32.zip
✓ ffmpeg-v1.7.6-win32-x64.zip
```

**Comment by zeke** [comment]
This now checks for assets on s3 and is ready for review. To test it locally, comment line 20 and uncomment line 21.

screen shot 2017-08-09 at 1 38 08 pm

**Comment by zeke** [comment]
@zcbenz we also want to verify that the debug symbols are uploaded to S3, but are not sure how to correlate the Electron version to the generated filenames on S3, e.g. `atom-shell/symbols/electron.exe.pdb/693f86a3f93041e38f908152294c93391/electron.exe.pdb`. Can you recommend a good way to verify that the symbols have been uploaded?

**Comment by zcbenz** [comment]
> Can you recommend a good way to verify that the symbols have been uploaded?

The only way I can think of is to download `-pdb.zip` from releases and then get the correct path from it, but it unfortunately has to download the huge symbols archive.

**Pull request merged**
