### PR TITLE
session: webRequest.OnHeadersReceived should accept status line.

### LINKED ISSUE #5023: webRequest.onHeadersReceived doesn't obey "Location" redirects
* Electron version: v0.37.4
* Operating system: OSX 10.10.5

When _listening_ on [`onHeadersReceived`](https://github.com/electron/electron/blob/master/docs/api/session.md#seswebrequestonheadersreceivedfilter-listener), "Location" headers are no longer obeyed, and redirects are not followed, even when passing the original `responseHeaders` untouched. I'm not sure if this behaviour is intentional or a bug, it feels like the latter.

**Follows redirect:**

```js
// Assuming the following
var win = new BrowserWindow({});
var sess = win.webContents.session;
// The page is loaded as expected
win.loadURL("http://bbc.co.uk");
```

**Does not follow redirect (ends early):**

```js
// Same as above
var win = new BrowserWindow({});
var sess = win.webContents.session;
// But, this time, let's listen to `onHeadersReceived`
sess.webRequest.onHeadersReceived(function (details, callback) {
  console.log(details.responseHeaders);
  callback({cancel: false, responseHeaders: details.responseHeaders});
});
// The page is not loaded / the redirect is not obeyed...
win.loadURL("http://bbc.co.uk");
```

And below is the output of the `console.log`:

```
{ Connection: [ 'Keep-Alive' ],
  'Content-Length': [ '0' ],
  'Content-Type': [ 'text/html' ],
  Date: [ 'Mon, 04 Apr 2016 21:32:18 GMT' ],
  Location: [ 'http://www.bbc.co.uk/' ] }
```

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #5023

### CODE REVIEW

**Comment by zcbenz** [comment]
This looks good to me, and out of curiosity, does Chrome's webRequest API behave the same?

**Comment by deepak1556** [comment]
Yup, users are required to provide a redirectURL when overriding response headers to redirect, they override the status line [here](https://code.google.com/p/chromium/codesearch#chromium/src/extensions/browser/api/web_request/web_request_api_helpers.cc&sq=package:chromium&l=1176&rcl=1459999039).

**Comment by zcbenz** [comment]
I tested with Chrome extension and it seems that `chrome.webRequest` doesn't have this issue. I wrote following extension code and then load `http://bbc.co.uk`, the website redirected successfully and I can see the logging too:

```js
  chrome.webRequest.onHeadersReceived.addListener(
    function(response) {
      console.log(response)
      return {responseHeaders: response.responseHeaders}
    },
    {
      urls: [
        "http://bbc.co.uk/*"
      ],
    },
    ["blocking", "responseHeaders"]);
```

**Comment by deepak1556** [comment]
You are right I was too soon on deciding the behavior, they construct new response headers from original replacing only the changed or added attributes, preserving the status line while we construct a completely new one, I will change this PR to match chrome webrequest api behavior.

**Comment by deepak1556** [comment]
Have made the changes, not sure if this best fix. Replacing the status line when a location header is present or should we ask users to provide status line ?

**Comment by deepak1556** [comment]
Will use original response headers' status line by default, users can override this by providing `statusLine` option in callback.

**Comment by zcbenz** [comment]
👍

**Pull request merged**
