### PR TITLE
build: remove dead symlink from MAS build

### LINKED ISSUE #23828: Electron 9.0.0: Mac App Store rejection - ITMS-90332: Invalid Symbolic Link
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0
* **Operating System:** MacOS
* **Last Known Working Electron version:** Electron 8

Release to Mac App Store failed with below error:

ITMS-90332: Invalid Symbolic Link - The symbolic link 'com.my.app.pkg/Payload/MyApp.app/Contents/Frameworks/Electron Framework.framework/Helpers' resolves to an invalid location. Make sure that the symbolic link does not resolve to itself, and that the location exists and is contained within the app bundle.

I've checked `electron-v9.0.0-mas-x64.zip` file from `~/Library/Caches/electron`, open the package content of `Electron.app` and I found it contains an invalid alias at `Electron.app/Contents/Frameworks/Electron Framework.framework/Helpers`. I am not sure if this file is added on purpose - it is not in electron 8 release.

### Expected Behavior

App should be able to release to App Store

### Actual Behavior
Apple rejected the build

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #23828

This fixes the stray symbolic link and adds a script to ensure it doesn't happen again

Notes: Fixed mac app store rejection notice for invalid symbolic link in bundle.

### CODE REVIEW

**Comment by nornagon** [comment]
This is a reland of #23831?

**Comment by MarshallOfSound** [comment]
@nornagon Yes but with a more correct fix for the gn check failures, the MAS build now truly doesn't depend on any parts of the crash component

**Comment by deepak1556** [comment]
Some crash symbols still leak through because of this path

```
//electron:electron_lib --[private]-->
//electron/chromium_src:chrome --[public]-->
//chrome/common:common --[private]-->
//components/crash/core/app:app
```

if symbols should be completely removed in MAS build then this path should be addressed.

**Comment by nornagon** [comment]
I don't _think_ symbols are the issue here, I think it's API calls?

**Comment by deepak1556** [comment]
I am not sure too, @MarshallOfSound can you please clarify the end goal of conditionally including those deps. If symbols are not an issue, I would like to add `//components/crash/core/app` back and remove the `nogncheck`

**Comment by MarshallOfSound** [comment]
@deepak1556 It's a combination.  The original goal was to _completely remove_ the crash component as a dependency to guarantee that MAS build can't call anything in there that straight up won't work.  If there's a dependency chain I missed I can follow up to remove that.

The actual _problem_ this PR solves is twofold.

(1) The `Helpers` folder needs to not exist on MAS builds, this requires changing some GN config
(2) The MAS build needs to not end up binding to, or calling, any crash methods (so this introduces some new noop / stub methods)

I think the dependency chain you posted can be removed by [patching out the dependency for mas builds](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/BUILD.gn;l=261?q=%22%2F%2Fcomponents%2Fcrash%2Fcore%2Fapp%22&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F)

**Comment by deepak1556** [comment]
Thanks for the context!

Removing the dependency chain from `//chrome` is a patch that we have to maintain always. With the electron crash api sources, `Helpers` framework and `crashpad_handler_syms` excluded, can we just build the deps unconditionally ?

**Comment by MarshallOfSound** [comment]
> With the electron crash api sources, Helpers framework and crashpad_handler_syms excluded, can we just build the deps unconditionally ?

The Helpers and syms are completely excluded but the `electron_api_crash_reporter` files and a few others are left in and we rely on `MAS_BUILD` `defined` checks to ensure we aren't doing The Wrong Thing in a mas build.  It would be way safer to ensure it's impossible link those symbols into the MAS build accidentally.  I don't know how big of a patch that would end up looking like though.

**Comment by deepak1556** [comment]
Hmm, this is a unique case where it is not completely necessary to remove the symbols but at the same time want to ensure headers are behind `#if defined`. I am fine with ignoring the symbols coming from `//chrome`, I don't think a patch is worth it.

**Comment by davidwinter** [comment]
Will this be backported to v9?

**Pull request merged**
