### PR TITLE
fix: ensure v8 pointer compression + sandbox is enabled on 64bit native modules

### PR DESCRIPTION
**Pull request by MarshallOfSound**
We screwed up in https://github.com/electron/electron/pull/34157 and created logic that said "turn off pointer compression, unless we are on a 32 bit host, in which case also turn off pointer compression" 😭 

This also takes the opportunity to align other new flags in E20 (specifically sandbox related flags) with their state in our v8 build.  Without this alignment everything just _falls apart randomly_.

Notes: Fixed spontaneous crashing in native modules that depended on `nan`

### CODE REVIEW

**Review by VerteDinde — APPROVED** [review]

**Review by deepak1556 — COMMENTED** [review]
@MarshallOfSound the patch was removed in favor of the pointer compression being generated as part of `config.gypi` https://github.com/electron/electron/blob/e83c3ec74442f0533e2d66c53fa84a075ebc20ae/script/generate-config-gypi.py#L17-L19

**Comment by deepak1556** [comment]
I can confirm pointer compression is enabled with `config.gypi` headers from main https://output.circle-artifacts.com/output/job/c9303ce5-21b4-4005-a222-4c0c502b93fc/artifacts/0/node_headers.tar.gz

**Comment by VerteDinde** [comment]
@deepak1556 I don't think the pointer compression is working quite right unfortunately. If you try to compile a native module that uses nan using any Electron 20 alpha or beta build, the module crashes (you can see an example of that happening here - sorry, it's Windows-only): https://gist.github.com/VerteDinde/90c7f4555c0f7ba5fd374fed3f20cbb0

The crash that's occurring is a similar one to what was reported here, in Electron 9: https://github.com/electron/electron/issues/31509#issuecomment-949011671 Adding the includes Milan mentioned in that comment fixes the native module crashing issue, and running Electron locally with the fix here also seems to fix the issue.

**Comment by MarshallOfSound** [comment]
@deepak1556 Ah I think I now understand the issue.  We only upload a single `node_headers` bundle for each platform.  But the value of `enable_pointer_compression` varies between architectures 🤔

**Comment by MarshallOfSound** [comment]
We discussed this on Slack and concluded that if a slight adjustment (c556ce9) was made that this change was GTG

**Pull request merged**
