### PR TITLE
docs: update tray documentation with notes about linux crashes

### PR DESCRIPTION
**Pull request by nicks**
#### Description of Change
Update tray documentation with notes about linux crashes

Fixes https://github.com/electron/electron/issues/36274

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added

#### Release Notes
notes: no-notes

### CODE REVIEW

**Comment by nicks** [comment]
i agree in theory, but i think it's a fairly big lift in practice (it's been a problem for years, and fixing it involves moving to a different system library). Did you read the attached issue report and the links there?

**Comment by codebytere** [comment]
@MarshallOfSound @zcbenz opened https://github.com/electron/electron/issues/36283 - i agree with you on principle but it'll probably be a bit before that happens so it's probably not a bad idea to note it in the short-term 🤔

**Comment by MarshallOfSound** [comment]
@codebytere https://github.com/electron/electron/issues/36283 is a long term "remove all this code" issue, the actual crash can definitely be fixed / worked around without such a drastic refactor

**Comment by nicks** [comment]
sounds good, thanks all!

**Pull request closed without merging**
