### PR TITLE
fix: web request support proxying websocket (#21308)

### PR DESCRIPTION
**Pull request by zimengle**
#### Description of Change
web request of electron api can support proxying websocket 

Fixes [21308](https://github.com/electron/electron/issues/21308)

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

### CODE REVIEW

**Comment by zcbenz** [comment]
@zimengle The code looks mostly fine to me, but for releasing a fix to 7.x, we have to first merge it to master branch and then backport it to `7-1-x` branch. 

Do you mind recreating a PR that targets the master branch instead of the `7-1-x` branch?

**Comment by killpowa** [comment]
Do you guys think it's possible to have this released as a pre-release soon?

**Comment by zcbenz** [comment]
@killpowa This PR has to be merged in master branch first, and then backported to release branches. Currently this PR targets for `7-1-x` branch and can not be merged directly.

I can do the work if the original op @zimengle does not have time for this.

**Comment by killpowa** [comment]
Ok, let me know if I can donate to make this process any faster, I really need this pr merged and released as soon as possible, thanks

**Comment by zcbenz** [comment]
I have started porting this to master branch, but it will take a while.

**Comment by zcbenz** [comment]
Closed in favor of https://github.com/electron/electron/pull/22040.

**Pull request closed without merging**
