### PR TITLE
test: disable failing node tests

### PR DESCRIPTION
**Pull request by nornagon**
These started failing recently for unknown reasons.

Notes: none

### CODE REVIEW

**Review by zcbenz — APPROVED** [review]

**Comment by zcbenz** [comment]
@deepak1556 It seems that the "multiple windows inherit correct fullscreen state" test is still flaky, the test is failing in this PR: https://app.circleci.com/pipelines/github/electron/electron/42218/workflows/0bc6db0e-30de-4226-ac28-31e2e0341edf/jobs/940703.

**Comment by deepak1556** [comment]
Not sure what the difference is in ci, as long as the window is able to use a separate workspace then it should transition into the fullscreen state.

Thoughts on removing this test given it has proven to be flaky in ci ?

**Comment by zcbenz** [comment]
> Thoughts on removing this test given it has proven to be flaky in ci ?

Yeah we should probably disable it for now.

**Pull request merged**
