### PR TITLE
fix: use legacy base::Value serializers for ipc (7-1-x)

### LINKED ISSUE #20334: Renderer subprocess crash on method invocation.
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 5.0.10

### Expected Behavior
Invoking a method (defined in and provided by the main process) from the renderer process (attached to the global object in the preload script), should work and not crash the renderer process. 

### Actual Behavior
Invoking such method with simple arguments like a string or a simple object works, but invoking it with a complex nested object (**no** circular dependency and **low** in size) causes the renderer process to crash.

### To Reproduce
Git Repo URL: https://github.com/flashd2n/electron-submit

```sh
$ git clone https://github.com/flashd2n/electron-submit.git
$ npm install
$ npm start
```

### Additional Information
Starting the app will open a single window and it's devtools console. The main process will pass to the renderer an object (**reproduce**) with a property (**invoke**) - a method which returns a success message. In the renderer's preload script this object is assigned to the global window object. The spawned window has three buttons:
* Simple - invokes window.reproduce.invoke with a simple string and prints the result
* Medium - invokes window.reproduce.invoke with a medium in complexity object and prints the result
* Complex - invokes window.reproduce.invoke with a high in complex object and prints the result

Simple or Medium will print the success message the the window console, but Complex will crash subprocess and close the window - a crash message is displayed in the main process's console.

This was tried in Electron:
* 5.0.10 - all invocations work. 
* 6.0.10 - the complex invocation crashes the subprocess. 
* 7.0.0-beta.4 - the complex invocation crashes the subprocess.

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
This switches the serialization algorithm for base::ListValue values sent over IPC (through `ipcRenderer` / `ipcMain`) to use the legacy serialization algorithm, rather than the new Mojo algorithm. The messages themselves are still sent over Mojo.

Fixes #20334.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an issue where sending complex objects over IPC could in some cases cause the renderer process to be terminated.

### CODE REVIEW

**Comment by nornagon** [comment]
This is marked [wip] because I'm yet to convert the return values of those messages to use the legacy serializers.

**Comment by zcbenz** [comment]
This PR requires approval from @electron/wg-upgrades.

**Comment by nornagon** [comment]
arm is flake, woa is queued forever apparently. I think this is good to go 🚀

**Pull request merged**
