### PR TITLE
Update README.md URLs to HTTPS

### PR DESCRIPTION
**Pull request by him2him2**
Updating HTTP protocol to HTTPS on applicable URLS

### CODE REVIEW

**Comment by ckerr** [comment]
This CI failure seems to clearly be unrelated to the, the issue is lint failures in `upgrading-chrome.md` and this PR's changes are in `README.md`.

This PR looks fine to me but before we merge let's see if we can resolve the test failures separately. I'm also curious how we got `master` into this state in the first place.

**Comment by him2him2** [comment]
@ckerr Yes, I noticed the build error when I created this PR. 

Looks like https://github.com/electron/electron/pull/11191 (which was merged about 10 hrs ago) introduced the code that was not passing CI on master. However, PR shows no build error. Not sure why.

Once #11218 is merged, I will re-push my commits for this PR and they should pass.

**Comment by ckerr** [comment]
Sounds good.

I've merged #11218 if you want to re-push

**Comment by him2him2** [comment]
Tests passed. 
As a note, there are transient timeout errors in the CI scripts. Sometimes it fails and sometimes it doesn't.

**Pull request merged**
