### PR TITLE
chore: sort filenames

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
List of sources should be kept sorted.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Review by alexeykuzmin — APPROVED** [review]

**Review by codebytere — APPROVED** [review]
We may want to automate or enforce this somehow - also needs rebase :)

**Comment by miniak** [comment]
@codebytere rebased. I will consider that for a follow-up.

**Comment by nornagon** [comment]
this should be enforced by `gn format`...

**Comment by codebytere** [comment]
@nornagon hmm - running `npm run lint:gn` exits cleanly in master rn 🤔

**Pull request merged**
