### PR TITLE
feat: enable macOS apps to receive push notifications from APNs

### PR DESCRIPTION
**Pull request by kevinhu88**
#### Description of Change
I'm picking up where @frantic left off in https://github.com/electron/electron/pull/13777 :)

This exposes some API for registering for [Apple Push Notification service](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns?language=objc) to let macOS apps receive push notifications even when the app is not running. Here is an [example of electron-quick-start](https://github.com/kevinhu88/electron-quick-start) that uses the stuff in this PR to register for APNS, receive a remote notification, launch the app from a user action, and displays the notification contents:
Screen Shot 2019-05-13 at 11 33 09 AM
Screen Shot 2019-05-13 at 11 33 23 AM
Screen Shot 2019-05-13 at 11 33 37 AM

This PR uses the [UserNotifications Framework](https://developer.apple.com/documentation/usernotifications?language=objc), which allows us to launch apps from custom user actions in the push notification, optionally with text input, on macOS mojave. **This requires building Electron with the macOS SDK 10.14+.** Launching the app from a notification on mojave results in a `UNNotificationResponse` mapped to `[notify userInfo][NSApplicationLaunchUserNotificationKey]` in `applicationDidFinishLaunching`, instead of `NSUserNotification`. This PR accounts for this and adds a function `UNNotificationResponseToNSDictionary` to convert the `UNNotificationResponse` to send as the `launch_info` dictionary with the `did-finish-launching` event so the Electron app can handle the notification payload.

As with any other macOS app, enabling push notifications requires setting up a provisioning profile with the APS Environment (macOS) Entitlement enabled in your Apple developer account. See [this doc](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns?language=objc) for more info about setup. Because of this requirement, I'm not sure what other test cases I could add besides testing failed registration.

I'm looking forward to feedback on this and really hope we can get this feature into the official Electron release!

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added support for push notifications from APNs for macOS apps.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
> This requires building Electron with the macOS SDK 10.14+

This is going to be the main problem here, we can't build against that SDK.  You're going to need to forward declare any of the APIs that are required for this to work against the 10.12 SDK similar to how we forward declared the touchbar APIs.

**Comment by kevinhu88** [comment]
> > This requires building Electron with the macOS SDK 10.14+
> 
> This is going to be the main problem here, we can't build against that SDK. You're going to need to forward declare any of the APIs that are required for this to work against the 10.12 SDK similar to how we forward declared the touchbar APIs.

Got it, will do 👍

**Comment by nkt** [comment]
@kevinhu88 hi, any update on this? I'm ready to help finish this PR in case you don't have enough time

**Comment by kevinhu88** [comment]
> @kevinhu88 hi, any update on this? I'm ready to help finish this PR in case you don't have enough time

Hey, sorry for the late response. I haven't prioritized this lately, I figured it'd be more worthwhile after Electron bumps the sdk used for official releases to 10.14. By all means feel free to take over if you'd like, otherwise I will finish this up eventually 👌

**Comment by RenzHoly** [comment]
awesome!

**Comment by Sachanski** [comment]
Hello everyone,

first of all thank you @frantic and @kevinhu88 for moving this functionality forward. I would like to heIp get this merged, so I have made a [fork](https://github.com/Sachanski/electron/tree/push-notifications) of the electron repository based on the v8.2.1.

@MarshallOfSound I saw your comment about the target SDK, but I also saw some runtime checks in @kevinhu88's PR for the availability of MacOS API 10.14. What is the remaining work that needs to be done? In my fork I am conditionally importing `<UserNotifications/UserNotifications.h>`, but I am not sure this is correct (a bit of stabbing in the dark; unfortunatelly the time it takes to compile the entire thing even with sccache is quite long). If you want I can make a fork and/or PR based on the current master branch, if that will speed things up?

Cheers and thank you all again for the amazing framework.

**Comment by zcbenz** [comment]
It has been a year and we are now using 10.15 SDK, so I think this PR should be ready to go. I'll do a rebase and add this to wg-api's list.

**Comment by Sachanski** [comment]
@zcbenz Thank you very much for this. Do you know which Electron version this will be avaialble in? I will be checking the Release Notes anyways, I am just curious if it known at this time.

Thanks again.

**Comment by zcbenz** [comment]
It will be included in version 11, see also https://www.electronjs.org/docs/tutorial/electron-versioning#semver.

**Comment by jkleinsc** [comment]
The @electron/wg-api reviewed this at the August 24, 2020 meeting.

**Review by Rada8732 — APPROVED** [review]

**Comment by radex** [comment]
@nornagon Hey, what's stopping this PR from being merged?

**Comment by nornagon** [comment]
@radex currently, there are merge conflicts :)

**Comment by miniak** [comment]
@nornagon should we abandon this PR in favor of #33574?

**Pull request closed without merging**
