### PR TITLE
test: migrate remaining webview specs to main

### LINKED ISSUE #32705: <webview>.capturePage() test very unreliable
the `<webview>.capturePage() returns a Promise with a NativeImage` test was disabled in https://github.com/electron/electron/pull/32419 due to severe flakiness. Follow up & fix.

### PR DESCRIPTION
**Pull request by nornagon**
Also fixes #32705.

Notes: none

### CODE REVIEW

**Comment by codebytere** [comment]
> <webview> tag methods <webview>.capturePage() returns a Promise with a NativeImage

looks like a real failure

**Comment by nornagon** [comment]
Frustrating, that passes every time for me locally. I'll disable it for now on mac; it was disabled everywhere previously so even running it only on some platforms would be an improvement!

**Comment by nornagon** [comment]
@codebytere PTAL, should be fixed now

**Review by zcbenz — COMMENTED** [review]
The `<webview> tag methods <webview>.goForward() should work after a replaced history entry` test is failing.

**Review by zcbenz — APPROVED** [review]

**Pull request merged**
