### PR TITLE
feat: `systemPreferences.getColor` should return RGBA instead of RGB

### PR DESCRIPTION
**Pull request by ILikeTeaALot**
#### Description of Change

Fully completes #26628

This fix implements the change requested in #26628, as stated there due to low usage of the API and the fact that returning a hex colour with alpha appended to the end should not cause any breaking changes, this is not marked as breaking.

(I don't have a recent-enough Mac to compile the code, so I would be immensely greatful for someone to take the time to do the necessary tests.)

The same change has **not** been made to the Windows version as no Windows system colour use alpha, however it could easily be changed as well for consistency.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

No test changes are necessary, but as noted above I've been unable to run them myself.

#### Release Notes

Notes: Changed `systemPreferences.getColor(name)` to return an RGBA hex value (`#RRGGBBAA`) instead of a plain RGB (`#RRGGBB`) value.

### CODE REVIEW

**Review by zcbenz — CHANGES_REQUESTED** [review]
It was not settled that this kind of change should be a `fix` in https://github.com/electron/electron/issues/26628. The PR https://github.com/electron/electron/pull/30055 that changed `getSystemColor` to return RGBA was a `fix` because the document stated the API returned RGBA but the code did not.

Having said that I do think it is fine to mark this change as `fix` though, but it should be @electron/wg-api to decide.

Also the return value should also be changed on Windows/Linux too, even if those platforms do not use transparent colors we should still fill the value with a `FF` alpha value.

**Review by erickzhao — APPROVED** [review]
API LGTM

I agree with @zcbenz that the alpha channel `FF` should be added for consistency.

**Comment by itsananderson** [comment]
API LGTM

+1 for including `FF` on Win/Linux for consistency

**Comment by jkleinsc** [comment]
@ILikeTeaALot can you address @zcbenz's concerns?

**Comment by ILikeTeaALot** [comment]
@jkleinsc Happy to! Apologies I didn't see the activity on this PR.

The Windows version should work exactly the same now.

**Review by zcbenz — APPROVED** [review]

**Review by codebytere — APPROVED** [review]
API LGTM

**Review by jkleinsc — APPROVED** [review]
API LGTM

**Pull request merged**
