### PR TITLE
feat: add WCO height option

### LINKED ISSUE #30857: [Feature Request]: Set Windows control overlay height
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When using the [new API](https://www.electronjs.org/docs/api/frameless-window#windows-control-overlay) to enable the Windows control overlay, I would like to be able to set the height of the controls to match the height of the remaining of the custom window titlebar. 

Something similar to what Teams is already doing on their UI:

image

### Proposed Solution

My guess is that adding a height property to the titleBarOverlay object would be the best solution.

### Alternatives Considered

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mlaurencin**
#### Description of Change

Closes #30857

This PR adds a `height` option to the Windows and macOS implementations of the Window Controls Overlay. See [this other PR](https://github.com/electron/electron/pull/29600) for the initial implementations. The height specified is in pixels.

*Current Issues:*
- Adding docs
- Fixing macOS button placement

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes:  Added `height` option for Windows Control Overlay

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
> Would a macOS compatible height option also be something of interest?

Yes 👍 😆

**Review by zcbenz — APPROVED** [review]
API LGTM

**Review by jkleinsc — CHANGES_REQUESTED** [review]
Mac traffic light position is not correct (this was tested with height of 50):
Screen Shot 2021-11-15 at 11 35 31 AM

**Comment by mlaurencin** [comment]
> Mac traffic light position is not correct (this was tested with height of 50): Screen Shot 2021-11-15 at 11 35 31 AM

The traffic lights should have the proper y-axis positioning in the most recent commit.

**Review by jkleinsc — COMMENTED** [review]
It looks like the new logic centers the macOS traffic lights in the titlebar vs placing them near the top of the titlebar eg in this example the titlebar height is set to 100:
Screen Shot 2021-11-29 at 10 51 03 AM

Also, it appears that both the 
`titleBarStyle: 'hiddenInset',` 
`trafficLightPosition: { x: 10, y: 0 },` settings are not working correctly.  In both cases, the traffic lights end up on the bottom of the title bar instead of near the top:
Screen Shot 2021-11-29 at 11 01 27 AM

I think what should happen here is that if trafficLightPosition is specified, that should override any automatic calculation of margin; otherwise if a custom titlebar height is used, the `hiddenInset` margin (` [buttons_proxy_ setMargin:gfx::Point(12, 11)];`) should be used

**Comment by clavin** [comment]
> otherwise if a custom titlebar height is used \[with no `trafficLightPosition` set\], the hiddenInset margin ... should be used

I think the window controls should be centered vertically in this case. Often, the height given to this property will be the same height as some container behind it (usually like an "integrated title bar and toolbar" in macOS HIG parlance). In other macOS applications with integrated title bar and toolbars (Safari, Finder, System Preferences, Activity Monitor, etc.) the standard is to center the window controls in the height of the toolbar (at least from a design perspective). I think this property should also do the same.

**Review by jkleinsc — APPROVED** [review]
LGTM

**Comment by theolivenbaum** [comment]
Quick question, is this feature already pushed to the latest release?

**Pull request merged**
