### PR TITLE
Fixes electron/electron#12147

### PR DESCRIPTION
**Pull request by nous-**
When calling `clearHistory()` from an external caller, it does not correctly check and rebuild the navigation stack with the active URL, as it does during construction.

This clearHistory issue would also cause bugs in similar functions: getURL, canGoToIndex, canGoBack.

Afaict, there are no existing automated tests for the navigation-controller. I verified this change by performing the steps described in the issue and verifying the expected outcome. I did not verify any other case that did not call `clearHistory`, as the object is logically identical.

### CODE REVIEW

**Comment by nous-** [comment]
Can someone kick ci/circleci: electron-linux-ia32?  Looks like a shaky test

**Comment by alexeykuzmin** [comment]
> Can someone kick ci/circleci: electron-linux-ia32? Looks like a shaky test

Done.

**Comment by nous-** [comment]
What's going on with the tests?

**Comment by codebytere** [comment]
hey @nous-! this failure is happening because you forked before we made the change to support arm64, so it's trying to run the x64 clang binary on arm64. Just rebase this on master and we'll be good to go and can get this merged 😁

**Comment by nous-** [comment]
@MarshallOfSound What happened with the revert?

**Comment by MarshallOfSound** [comment]
@nous- See https://github.com/electron/electron/pull/12293#issuecomment-373264621

**Comment by nous-** [comment]
Thanks- look forward to seeing the change @deepak1556 👍

**Pull request merged**
