### PR TITLE
Replace "Mac OS" and "OS X" with "macOS"

### PR DESCRIPTION
**Pull request by leo**
OS X has been renamed to "macOS". More details [here](http://www.macworld.co.uk/news/mac-software/mac-os-sierra-x-10-12-fuji-features-uk-release-date-macos-touch-id-siri-apfs-wwdc-2016-3630374/).

### CODE REVIEW

**Comment by enlight** [comment]
Have you seen #6112?

**Comment by leo** [comment]
@enlight Whoops, no! 😄 But it looks like mine changes a few more instances of these words (changed 157 files compared to 28).

**Comment by paulcbetts** [comment]
Two _separate_ PRs to change #branding? Are y'all on the dime from Apple's marketing dept? ;)

**Comment by zcbenz** [comment]
👍

**Pull request merged**
