### PR TITLE
remove function invocation from crash test

### PR DESCRIPTION
**Pull request by codebytere**
It appears the timeout issues was only apparent in my other branch; i removed it here and all tests are well and green again in that module :)

/cc @alexeykuzmin @ckerr

### CODE REVIEW

**Comment by codebytere** [comment]
Weird, so it was previously failing locally but now passes, and now is failing on `electron-osx-x64` with the same timeout error. Does anyone have thoughts on this? 
👇 
http://208.52.191.140:8080/job/electron-osx-x64/5613/console

**Comment by SunXuezeng** [comment]
请不要给我发邮件了，谢谢



sunxuezeng2008@163.com
 
From: Shelley Vohr
Date: 2017-11-02 21:01
To: electron/electron
CC: Subscribed
Subject: Re: [electron/electron] remove function invocation from crash test (#10992)
Weird, so it was previously failing locally but now passes, and now is failing on electron-osx-x64 with the same timeout error. Does anyone have thoughts on this?
????
http://208.52.191.140:8080/job/electron-osx-x64/5613/console

**Comment by amor520** [comment]
@SunXuezeng 请取消watch,谢谢
image

**Comment by alexeykuzmin** [comment]
> Weird, so it was previously failing locally but now passes, and now is failing on electron-osx-x64 with the same timeout error. Does anyone have thoughts on this?
>
> 👇
> http://208.52.191.140:8080/job/electron-osx-x64/5613/console

@codebytere 
*electron-osx-x64* started to fail in all PRs after this one was merged =/
http://208.52.191.140:8080/job/electron-osx-x64/

**Comment by codebytere** [comment]
wat haha this is how it's been for years! i'm definitely down to invoke the function again, but i think it's worth investigating why it started failing in the first place after being this way for the lifetime of the file

**Comment by alexeykuzmin** [comment]
> wat haha this is how it's been for years!

The test itself is ok, but the deprecation warning breaks something and it makes the tests to time out =/

**Comment by codebytere** [comment]
Gotcha, finally all caught up on related PRs haha 

i'll work on it today 😁

**Pull request merged**
