### PR TITLE
fix: failing build with `enable_electron_extensions=false`

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/39987.

Fixes build when `enable_electron_extensions=false`. The new dependencies added to `chromium_src/BUILD.gn` are required for functionality in the `webRequest` module.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixes failing build when `enable_electron_extensions=false`.

### CODE REVIEW

**Review by deepak1556 — APPROVED** [review]

**Comment by brjsp** [comment]
Non-LTO builds are still failing with this patch:
```
[ 9463s] /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: obj/electron/chromium_src/chrome/extension_navigation_ui_data.o: warning: relocation against `_ZN10extensions12WebViewGuest4TypeE' in read-only section `.text'
[ 9463s] /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: obj/electron/chromium_src/chrome/extension_navigation_ui_data.o: in function `guest_view::GuestView<extensions::WebViewGuest>::AsDerivedGuest(guest_view::GuestViewBase*)':
[ 9463s] /home/abuild/rpmbuild/BUILD/src/out/Release/../../components/guest_view/browser/guest_view.h:67:(.text+0xdd): undefined reference to `extensions::WebViewGuest::Type'
```

**Comment by codebytere** [comment]
@brjsp ah - that should probably be sent as an upstream CL to Chromium then. I can patch it in here though as well.

**Comment by brjsp** [comment]
@codebytere not sure? There seems to be no configuration of Chromium upstream that has problem with this code — it's entirely due to Electron frankensteining half of `//extensions` as detached source files.

**Comment by codebytere** [comment]
@brjsp I can potentially follow up with that but I'm merging this as-is because your current build configuration isn't supported formally by Electron nor by Chromium.

**Pull request merged**
