### PR TITLE
refactor: fix chromium-style in url_request_asar_job

### PR DESCRIPTION
**Pull request by nornagon**
Chromium-style was failing on this file. Now it isn't.

### CODE REVIEW

**Comment by jkleinsc** [comment]
@nornagon can you add a short description to this PR? Thanks!

**Comment by nornagon** [comment]
@jkleinsc done, though I'm not sure I know what your confusion was. Is there anything you'd like clarification on?

**Comment by jkleinsc** [comment]
@nornagon it makes it easier to put together the release notes when there is a description provided.  Does Chromium-style checking happen automatically with the GN builds?

**Comment by nornagon** [comment]
@jkleinsc i feel like the description i added did nothing to expand on the commit title; is there a tool you're using that's particular about empty descriptions?

**Pull request merged**
