### PR TITLE
fix: disable partition alloc on mac

### LINKED ISSUE #32718: [Bug]: Segmentation fault in uv_spawn with Electron 17.0.0
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

No segmentation fault

Crash Report Screenshot

[Text version of crash report](https://github.com/electron/electron/files/7987634/crash.report.txt)

### Actual Behavior

Sometimes, after working for a while, the app crashes giving the Apple Problem Report attached.

### Testcase Gist URL

_No response_

### Additional Information

We're hoping to move to Electron 17 ASAP to pick up some Chromium bug fixes.  I built an alpha of our application with the new 17.0.0 release yesterday.

The crash behavior isn't predictably reproducible that I know of, although it has happened a few times to this user who is one of the employees of our company.  I haven't see in at all in my arm64 version or for the 15 minutes I used our x64 version on my old laptop.

### PR DESCRIPTION
**Pull request by VerteDinde**
#### Description of Change

Closes #32718

After re-enabling partition alloc in Electron 17, we began seeing crashes when spawning child processes on Mac. This PR disables partition alloc for Mac builds to address the crash.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an occasional crash on Mac when spawning a child process.

### CODE REVIEW

**Comment by VerteDinde** [comment]
It looks like the AppVeyor crashes are also happening on other PRs, so I don't think related to this change.

**Review by clavin — APPROVED** [review]
Looks the same as last time we disabled this 👍

**Review by MarshallOfSound — APPROVED** [review]

**Comment by deepak1556** [comment]
Do we have additional context on why the partition allocator started crashing fork calls from uv_spawn ?

**Comment by nornagon** [comment]
What's the plan for re-enabling this?

**Comment by pr0t4zy** [comment]
This can be reverted now, with [#33114](https://github.com/electron/electron/pull/33114) integrated.

**Comment by erickzhao** [comment]
See https://github.com/electron/electron/pull/33981 for WIP

**Pull request merged**
