### PR TITLE
Remove command line argument black-list

### PR DESCRIPTION
**Pull request by alespergl**
Per our agreement we will instead block all arguments following a URL.

Users of apps that accept multiple URLs, or other arguments following a URL, will need to use a `--` argument as a prefix.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@alespergl Has it been / should it be backported to the `2.0` branch?
cc @ckerr

**Comment by DandroidDeveloper** [comment]
Do any of you know the state of --ignore-gpu-blacklist? That flag just seems to be ignored in any version past electron 2.0.0. 

https://github.com/electron/electron/issues/15339

**Comment by MarshallOfSound** [comment]
@DandroidDeveloper This PR isn't related to the GPU blacklist

**Comment by gannons** [comment]
@alespergl is this documented?

Hit an issue on Windows 10 where the arguments

> --url https://my-service-url.com/api/v1 --location ~/Downloads/args/

caused the app to die before hitting any code in app.js. But when the args were refiddled to

> --location ~/Downloads/args/ --url https://my-service-url.com/api/v1

or 

> -- --url https://my-service-url.com/api/v1 --location ~/Downloads/args/

it works. Does not seem to be a problem on Mac but will catch people out on Windows. It's also a bit unintuitive.

**Pull request merged**
