### PR TITLE
Exit gracefully on linux

### LINKED ISSUE #12050: not ok 11 app module app.exit(exitCode) exits gracefully on macos
This causes intermittent CI failures, showing up several times a week but is not reliably reproducible.

[Example](https://mac-ci.electronjs.org/blue/organizations/jenkins/Electron%20org%2Felectron/detail/PR-12037/3/pipeline)

```text
not ok 11 app module app.exit(exitCode) exits gracefully on macos
  AssertionError [ERR_ASSERTION]: false == true
      at ChildProcess.exec (/Users/electron/workspace/ctron_org_electron_PR-12037-TWW4HVB7PMGXB75WUNR2QMXJH33XQBHCRTABBUJLBSRYSKBW4FWA/spec/api-app-spec.js:172:11)
      at ChildProcess.exithandler (child_process.js:294:5)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

### PR DESCRIPTION
**Pull request by ckerr**
1. Fixes #12050 which was caused by a timing issue. The singleton fixture was reporting its readiness before app had emitted a 'ready' signal. At times, this could cause the parent test harness to run its tests before the child Electron process had finished starting its event loop.

2. Rewrites the `exit_gracefully_on_macos()` test to run on other platforms too.

This code is ready for review but is a WIP in the sense that I need confirmation from CI about the portability of the rewritten test.

### CODE REVIEW

**Comment by codebytere** [comment]
It appears it's successful on mac and linux but that it's failing on windows

**Comment by ckerr** [comment]
@codebytere, thank you for doing the win32 research on this!

I agree we'll need a different approach for win32. Simulating SIGTERM is a good Node feature, but forcing an unconditional exit doesn't give us a meaningful test when we're looking for a graceful shutdown. So let's limit this implementation of the test to macOS and Linux.

**Comment by codebytere** [comment]
in that case, i'll merge when CI goes ✅✨

**Comment by alexeykuzmin** [comment]
I would vote for backporting the change to `2-0-x`. Flaky tests is pain.

@ckerr, @codebytere

**Comment by codebytere** [comment]
done, pr up

**Pull request merged**
