### PR TITLE
chore: Move webFrame scheme privilege methods to main process

### PR DESCRIPTION
**Pull request by nitsakh**
#### Description of Change
This PR updates the custom scheme registration APIs and moves them to the browser process.
#15767 was a precursor to the current PR.
Custom schemes have to be registered from the main process and before app ready.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Moved `webFrame` custom scheme APIs to browser process under `protocol`

### CODE REVIEW

**Comment by zcbenz** [comment]
Can you also document this in `docs/api/breaking-changes.md`?

And do we have deprecation warnings in 4.x?

**Comment by codebytere** [comment]
@nitsakh once the conflict is fixed and the change added to the api contract i think this is good to go 👍

**Comment by miniak** [comment]
@nitsakh, @zcbenz this PR broke the `electron.d.ts` generation
```
Error: Ruh roh, "Options" is already declared
    at Object.keys.sort.forEach (/Users/miburda/Development/github/electron-gn/src/electron/node_modules/electron-typescript-definitions/lib/dynamic-param-interfaces.js:83:17)
    at Array.forEach (<anonymous>)
    at Object.flushParamInterfaces (/Users/miburda/Development/github/electron-gn/src/electron/node_modules/electron-typescript-definitions/lib/dynamic-param-interfaces.js:70:142)
    at module.exports (/Users/miburda/Development/github/electron-gn/src/electron/node_modules/electron-typescript-definitions/index.js:69:19)
    at apiPromise.then.then.API (/Users/miburda/Development/github/electron-gn/src/electron/node_modules/electron-typescript-definitions/cli.js:56:18)
    at process._tickCallback (internal/process/next_tick.js:43:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
```

**Comment by nitsakh** [comment]
Thanks @miniak . Let me look at it now and I'll send a PR with the fix.

**Comment by miniak** [comment]
There are even more issues
```
test/main.ts(830,12): error TS2339: Property 'registerStandardSchemes' does not exist on type 'Protocol'.

test/main.ts(831,12): error TS2339: Property 'registerServiceWorkerSchemes' does not exist on type 'Protocol'.
test/renderer.ts(73,10): error TS2339: Property 'registerURLSchemeAsBypassingCSP' does not exist on type 'WebFrame'.
test/renderer.ts(74,10): error TS2339: Property 'registerURLSchemeAsPrivileged' does not exist on type 'WebFrame'.
test/renderer.ts(75,10): error TS2339: Property 'registerURLSchemeAsPrivileged' does not exist on type 'WebFrame'.
```

**Comment by miniak** [comment]
@nitsakh, @zcbenz personally, I would recommend reverting this PR until the issues are resolved and applying it again when fixed.

**Pull request merged**
