### PR TITLE
fix: build with Visual Studio 2019

### PR DESCRIPTION
**Pull request by jaimecbernardo**
#### Description of Change

Applies the patches necessary for Electron to build with Visual Studio 2019.

Each commit in this PR patches a dependency with a commit that has already been merged upstream into a master branch to fix building that dependency with the Visual Studio 2019 build tools:
- [angle](https://chromium.googlesource.com/angle/angle/+/755417dd79071d6149c81418e1404b0c61d19672)
- [v8](https://chromium.googlesource.com/v8/v8/+/53e62affd33ad036a169eff7d6c1d50b0adcd21a)
- [perfetto](https://android.googlesource.com/platform/external/perfetto/+/f10b2053be67439539968c9f391f63664de779d4)
- [quiche](https://quiche.googlesource.com/quiche/+/c1e9121f16559b084bb80afc6922f0316d082160)

After applying these fixes, electron builds using the Visual Studio 2019 C++ build tools.

Fixes: https://github.com/electron/electron/issues/20346

cc @codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
Update: The new "Native specs" test also passes if `ninja -C out/Release shell_browser_ui_unittests` is run before starting the tests.
Edited the PR text to remove the note that this test didn't pass.

**Comment by deepak1556** [comment]
> Are these new #includes needed because of patches in Electron, or does it make sense for you to upstream to V8 as well?

@ckerr all the patches in this PR are already upstreamed :) the PR decription and the patches also have the links to commits.

**Comment by MarshallOfSound** [comment]
If these are all upstreamed already, won't we get them in the next roll? Is it worth patching for the fee days in the middle?

**Comment by jaimecbernardo** [comment]
Hi @MarshallOfSound,
I am not aware of the timings.
Either way, this PR might need to be backported to build previous versions of electron on Visual Studio 2019.

**Comment by nornagon** [comment]
@MarshallOfSound I don't see the harm in merging, & like @jaimecbernardo says this'll be handy for backporting if we need it.

**Pull request merged**
