### PR TITLE
Update gyp: Add Visual Studio 2017 support

### PR DESCRIPTION
**Pull request by zcbenz**
Refs https://github.com/electron/gyp/pull/1.

### CODE REVIEW

**Comment by zcbenz** [comment]
The failing test is not related to this PR, I'm merging anyway.

**Comment by PhoebeHui** [comment]
Thanks for doing this change to support VS2017!

I encounter an issue 'could not locate Visual Studio installation' when execute ''python script\bootstrap.py -v --target_arch=ia32"

The script/update.py looks also need update. the GYP_MSVS_VERSION should be 2017, after I made this change, everything works well.
https://github.com/electron/electron/blob/master/script/update.py#L61

The failures like
Traceback (most recent call last):
  File "vendor\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "vendor\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "vendor\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "vendor\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "vendor\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\generator\ninja.py", line 1695, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 1097, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 948, in GetVSVersion
    allow_fallback=False)
  File "vendor\gyp\pylib\gyp\MSVSVersion.py", line 485, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.

Thanks,
Phoebe

**Comment by zcbenz** [comment]
It seems that we should add a flag to specify Visual Studio version, or try to automatically find out it.

**Comment by alexeykuzmin** [comment]
@PhoebeHui 

> The script/update.py looks also need update. the GYP_MSVS_VERSION should be 2017, after I made this change, everything works well.

VS 2017 is only required by the Chromium 63, so we don't need to change the `GYP_MSVS_VERSION` in the master which uses libcc based on the Chromium 61.

**Pull request merged**
