### PR TITLE
Update icon loading API implementation

### PR DESCRIPTION
**Pull request by YurySolovyov**
See: https://github.com/electron/electron/pull/8631#issuecomment-278461065

As per [commit](https://chromium.googlesource.com/chromium/src/+/f0a7b5b81faa4d2abf594b6e3ac135ed60dad504%5E%21/): 
> There are lifetime issues due to IconLoader being refcounted for no good reason, so stop doing that.

And from [Chromium Issue 674743](https://bugs.chromium.org/p/chromium/issues/detail?id=674743):

> In reviewing this code it seems like IconManager is racy. In particular
IconManager is not ref counted, but IconLoader is. IconLoader references
IconManager through it's a delegate. This means it's possible for IconLoader to
outlive it's delegate. Seems this function should null out the delegates (and
you should keep the null check in IconLoader::NotifyDelegate).

### CODE REVIEW

**Comment by deepak1556** [comment]
@YurySolovyov I pushed some changes to the `IconManager` class lifetime management.

**Comment by YurySolovyov** [comment]
@deepak1556 cool, thanks, any explanation about why it it better this way?

**Comment by deepak1556** [comment]
> any explanation about why it it better this way?

Needed to make sure the icon resources created on the file thread are destroyed before the `IconManager` class destroys itself, since it doesn't have the ownership of `IconLoader`.

**Comment by kevinsawicki** [comment]
Thanks for this @YurySolovyov and @deepak1556 👍 🖼

**Pull request merged**
