### PR TITLE
chore: remove obsolete native node module patch

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

We can now remove this patch as it's been released in [`node-gyp v5.1.1`](https://github.com/nodejs/node-gyp/releases/tag/v5.1.1). 

Release proposal PR here: https://github.com/nodejs/node-gyp/pull/2125

cc @zcbenz @deepak1556 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by deepak1556** [comment]
Thanks for following up on this.

Question:

I believe this change gets picked up for users who have node-gyp installed separately and who can update the version. For users who use a node version manager, node-gyp usually comes from npm dependency, so this change will not be picked up until a corresponding npm version is out. Is this correct ?

In which case I would suggest to float this patch in electron until v12 hits maintenance mode, that way the change is available to all users independent of their local node toolchain installation.

**Comment by codebytere** [comment]
@deepak1556 that's correct - the only caveat is that the version bundled and distributed within Node.js is not made directly available for developers to use and is intended only to support the ability to use `npm install` to compile and install addons. 

`npm` does get updated in LTS versions though (last update was `v12.16.2`) so i think there's potential for it to pick up this patch version and remove the potential issue before maintenance mode.

**Comment by deepak1556** [comment]
> I don't see a particular urgency to remove this patch really so i'm happy to hinge this patch's removal on the next roll of npm into Node.js in v12 if that feels like the better option!

That would be great, since we have control on the gyp file used for compilation, its good to have this change around until the toolchains are updated. Lets make this PR a draft until then.

**Comment by codebytere** [comment]
@deepak1556 Node.js v12 is now in maintenance mode - I think we can land this now.

**Review by deepak1556 — APPROVED** [review]
Great!

**Pull request merged**
