### PR TITLE
Re-enabled debug mode

### PR DESCRIPTION
**Pull request by alespergl**
See https://github.com/electron/libchromiumcontent/pull/345

### CODE REVIEW

**Comment by zcbenz** [comment]
It seems that tests are passing on Linux CI! I'm 👍 on merging this.

(Our CI servers are having some problems, will merge after fixing that).

**Comment by zcbenz** [comment]
@jkleinsc I just realized I have overwritten some of your commits, do you mind pushing them again?

**Comment by jkleinsc** [comment]
@zcbenz changes have been pushed.  These are the changes needed to run Docker with the new docker setup on libchromiumcontent.

**Comment by zcbenz** [comment]
I'm seeing 2 flaky failings tests on Windows, they also happens on master branch so it was not introduce by this branch. But using debug mode does make them happen more frequently.

```
not ok 107 BrowserWindow module "webPreferences" option "sandbox" option should open windows in same domain with cross-scripting enabled
  AssertionError [ERR_ASSERTION]: 18 == 60
      at w.webContents.once (C:\e\workspace\electron-win-x64\spec\api-browser-window-spec.js:1020:18)
      at CallbacksRegistry.apply (C:\e\workspace\electron-win-x64\out\D\resources\electron.asar\common\api\callbacks-registry.js:48:25)
      at EventEmitter.<anonymous> (C:\e\workspace\electron-win-x64\out\D\resources\electron.asar\renderer\api\remote.js:299:21)
      at emitThree (events.js:135:13)
      at EventEmitter.emit (events.js:216:7)
not ok 108 BrowserWindow module "webPreferences" option "sandbox" option should open windows in another domain with cross-scripting disabled
  AssertionError [ERR_ASSERTION]: 13 == 65
      at w.webContents.once (C:\e\workspace\electron-win-x64\spec\api-browser-window-spec.js:1047:18)
      at CallbacksRegistry.apply (C:\e\workspace\electron-win-x64\out\D\resources\electron.asar\common\api\callbacks-registry.js:48:25)
      at EventEmitter.<anonymous> (C:\e\workspace\electron-win-x64\out\D\resources\electron.asar\renderer\api\remote.js:299:21)
      at emitThree (events.js:135:13)
      at EventEmitter.emit (events.js:216:7)
```

**Comment by zcbenz** [comment]
Electron is also crashing when switching between menus in menubar, which seems to require a refactor of our menubar code to fix.

**Pull request merged**
