### PR TITLE
docs: update code of conduct

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change

This PR updates our code of conduct to Contributor Covenant v2.0 in accordance with Electron joining the OpenJS foundation.
#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by jkleinsc** [comment]
Needed for electron/governance#267

**Review by lee-dohm — APPROVED** [review]
Looks like a good change to me 👍

**Review by bnb — APPROVED** [review]
This LGTM.

The only additional thing that may eventually be needed is the escalation path to the OpenJS Foundation CoC handling team, which is currently relatively undefined by them (this does not replace the project's handling, but instead is an escape hatch available for the project if it's wanted and).

**Review by codebytere — APPROVED** [review]

**Review by felixrieseberg — APPROVED** [review]
Looks sensible :+1:

**Comment by jkleinsc** [comment]
Merging as CI failures unrelated to PR change.

**Comment by chaiphetbuathong4776-svg** [comment]
> **No Release Notes**

- 
- 
- 
- 
- 
-

**Pull request merged**
