### PR TITLE
chore: update to latest TypeScript 3.5.2

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Update to latest TypeScript 3.5.2 + `yarn upgrade` transitive dependencies to latest versions.
Required by #18820

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by miniak** [comment]
I was getting this error after updating just TypeScript
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0

YOUR TYPESCRIPT VERSION: 3.5.2

Please only submit bug reports when using the officially supported version.

=============
```

**Comment by MarshallOfSound** [comment]
Please do not merge with the above warnings 👍 Upgrading the eslint ts plugins and such should remove that warning

**Comment by miniak** [comment]
@MarshallOfSound upgrading transitive dependencies via `yarn upgrade` fixed the warning.

**Comment by miniak** [comment]
Also this PR #18340 removed all the checksums, should we enforce a minimum version of yarn to make sure it does not happen again?

**Comment by zcbenz** [comment]
Looks good to me as the warning is resolved,

**Pull request merged**
