### PR TITLE
feat: enable dark mode on GTK UIs

### PR DESCRIPTION
**Pull request by robertgzr**
#### Description of Change

This is needed after https://bugs.chromium.org/p/chromium/issues/detail?id=998903
and replaces the previous workaround to detect dark mode on GTK.
Detect system dark theme preference via xdg settings portal:
https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings

Closes: https://github.com/electron/electron/issues/38961
Closes https://github.com/electron/electron/issues/28838

cc @codebytere @ckerr

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [ ] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Detect system dark theme preference via xdg settings portal on Linux

### CODE REVIEW

**Comment by robertgzr** [comment]
this also fixes https://github.com/electron/electron/issues/28838, tested using https://github.com/electron/electron/tree/main/docs/fiddles/features/dark-mode

**Comment by robertgzr** [comment]
Since Electron/Chromium use GTK3, the system needs to have `org.gnome.desktop.interface gtk-theme` set to the correct variant for native UI elements to actually be styled.

So when using Gnome, `Adwaita` (for light mode) and `Adwaita-dark` (for dark mode)

**Comment by codebytere** [comment]
I don't feel strongly either way but we can likely call this a fix and mark it `semver/patch` cc @electron/wg-api

**Comment by dsanders11** [comment]
> https://github.com/electron/electron/issues/28887 (maybe, haven't tested on Ubuntu 20)

A quick test on Ubuntu 22 determines that issue is not resolved by these changes.

> this also fixes https://github.com/electron/electron/issues/28838

That one doesn't repro for me on Ubuntu 22 (haven't tested on Ubuntu 20).

I haven't reviewed the changes in this PR, just chiming in after testing it on Ubuntu 22.

**Review by dsanders11 — COMMENTED** [review]
`#include "ui/gfx/color_utils.h"` becomes unused with these changes and should be removed in `shell/browser/electron_browser_main_parts.cc`.

**Comment by robertgzr** [comment]
tested for gnome 42.9 on ubuntu 22.01:

https://github.com/electron/electron/assets/3930615/99c8ce37-f6cc-4a14-9886-9f0c44cc574f

behavior is the same on fedora 38 with KDE, menubar style follows system UI elements

**Comment by robertgzr** [comment]
i tested this out on ubuntu 20 (gnome 3.36.8) and it seems that there is some inconsistency when switching, even with native apps:


https://github.com/electron/electron/assets/3930615/881d3fdf-3adf-479e-b368-75dee24809db

**Comment by robertgzr** [comment]
that test failure looks like a flake? https://app.circleci.com/pipelines/github/electron/electron/72486/workflows/a9b3d28b-bbf6-42fc-9f50-ee789af823c7/jobs/1567694/tests

**Comment by q234rty** [comment]
Gentle ping on this :)

**Comment by Danik1601** [comment]
> I have automatically backported this PR to "24-x-y", please check out #40008

AFAIK the [upstream fix](https://chromium.googlesource.com/chromium/src/+/1acb960204281157ac3a583a07ce07e2754ea42b) has [landed in Chromium 114](https://chromium.googlesource.com/chromium/src/+/dbc93d8d591454458ad53d66465a8cf71d9515e9) (Electron 25), so PR for Electron 24 should be rejected. Other PRs, however, should be good to go.

**Pull request merged**
