### PR TITLE
infra: Allow notifications debugging

### PR DESCRIPTION
**Pull request by felixrieseberg**
We at Slack were about to switch to Electron's very own notifications for macOS, but we're seeing some trouble with notifications just silently not showing up. Debugging this is currently very difficult - we don't actually know where exactly things are going wrong – and without attaching a debugger on our customer's machines, it might continue to be difficult.

This PR adds logging statements to Electron's native notifications for macOS and Windows 10. It doesn't change any logic and _only_ starts logging if the environment variable `ELECTRON_DEBUG_NOTIFICATIONS` is set, together with the already existing `--enable-logging` parameter.

Output looks roughly like this:

```
[24035:1213/163133.070393:VERBOSE1:CONSOLE(8192)] "Main._createAppUI: 70.869873046875ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[24035:1213/163133.372009:VERBOSE1:CONSOLE(8192)] "Main._showAppUI: 83.883056640625ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[24035:1213/163133.380724:VERBOSE1:CONSOLE(8192)] "Main._initializeTarget: 13.277099609375ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[24035:1213/163136.552704:INFO:cocoa_notification.mm(41)] Notification created (ElectronNotification1)
[24035:1213/163136.659964:INFO:cocoa_notification.mm(114)] Notification displayed (ElectronNotification1)
[24035:1213/163149.003999:INFO:cocoa_notification.mm(41)] Notification created (ElectronNotification2)
[24035:1213/163149.107720:INFO:cocoa_notification.mm(114)] Notification displayed (ElectronNotification2)
[24035:1213/163152.011869:INFO:notification_center_delegate.mm(33)] Notification activated (ElectronNotification2)
[24035:1213/163152.012128:INFO:cocoa_notification.mm(114)] Notification replied to (ElectronNotification2)
```

### CODE REVIEW

**Comment by felixrieseberg** [comment]
I believe that the Windows x64 build is CI fluke, since the log is empty and the ia32 build worked just fine.

**Comment by codebytere** [comment]
strangely, in appveyor right now the logs are empty in the x64 build so it fails 🤔

**Comment by codebytere** [comment]
@felixrieseberg we're good now!

**Comment by MarshallOfSound** [comment]
> if the existing vlog feature might be more flexible than a new environment variable here?

This sounds like a good thing to use 👍

**Pull request merged**
