### PR TITLE
Upgrade to 50.0.2661.94

### PR DESCRIPTION
**Pull request by bbondy**
Debug build compiles on:

- [x] OS X
- [x] Linux
- [x] Windows

Release build compiles on:

- [x] OS X
- [x] Linux
- [x] Windows

Tests passing on:

- [x] OS X
- [x] Linux
- [x] Windows

See also:
https://github.com/electron/brightray/pull/216
https://github.com/electron/libchromiumcontent/pull/200

### CODE REVIEW

**Comment by marionleborgne** [comment]
Hi @bbondy do you know what the status of this PR is?

In our electron app, the charts disappear (dygraph) if the app stays in the background for too long. This seems to be related to a chromium bug (https://bugs.chromium.org/p/chromium/issues/detail?id=588434) and using chomium v50 would appear to fix it. So your PR is going to unblock us. Thanks 😄

**Comment by bbondy** [comment]
Oops hit close by accident...
Yes we finished with this upgrade to v50 and we just released it (live within the hour) for Brave.

Some of the commits on the pull request need updating here, I had to parallel the upstream because our fork has extensions in it so needed sme extra things.

I'll sync up the commits here after that release and get builds off of electron for tests etc.

As I understand, the github guys need to update their build machines to have the win10 sdk though because of new dependencies on it in Chromium.

**Comment by marionleborgne** [comment]
@bbondy thanks for the quick reply. What do you mean by "we just released it (live within the hour) for Brave."? I haven't been able to find a release of Electron that has chromium v50.

Thanks

**Comment by bbondy** [comment]
The Brave browser maintains their own electron fork.  You should wait until Electron does a release.
We released our new version based on v50 chromium today and our electron fork w/ chromium v50 is here: https://github.com/brave/electron/releases/tag/v0.37.7

**Comment by marionleborgne** [comment]
Thanks @bbondy

**Comment by bbondy** [comment]
This is complete now, and ready for review.
It builds in release and debug on all platforms and tests pass on all platforms.

Note that the pull requests do NOT include extensions or other Brave specific forked items. I did the work of pulling it into the main `electron/electron` repo cleanly and made sure it builds cleanly on all platforms and tests pass on all platfrorks outside of our brave fork.

If you just want to try it out you can grab the electron builds here (they are built off of master tip though not from the 0.37.8 release tag)
https://github.com/bbondy/electron/releases

**Comment by bbondy** [comment]
Take note of these 2 commits which need to be rebased out or modified though:

https://github.com/electron/brightray/pull/216/commits/ed10a4edf6af528055e917b1763e1aedec63f4a7
https://github.com/electron/electron/pull/5322/commits/dbce3bfaf28cafdfda909dd5e9a20ed0588b2de5

**Comment by paulcbetts** [comment]
@bbondy This is awesome, thank you so much!

**Comment by zcbenz** [comment]
Thanks! This PR has been merged into the [chrome50 branch](https://github.com/electron/electron/tree/chrome50).

**Comment by jprichardson** [comment]
Thanks @bbondy! @zcbenz will the release w/ libchromiumcontent v50 include Node v6 to keep v8 versions (v5.0) consistent?

**Comment by zcbenz** [comment]
@jprichardson Yeah it will include Node v6.1.0.

**Pull request closed without merging**
