### PR TITLE
Throw error when session module is used before app is ready

### LINKED ISSUE #5778: Application Crashing while quiting
* Electron version: 1.0.0
* Operating system: OSX 10.5

With Love and respect To Electron Team

I want to terminate the application 
1. when all windows are closed  
2. The main window is closed
3. User click the sign out button

in order to achieve the above task I am using `app.quit();` but the time it is called the application crashes and show crash report.

Note: There can n number of windows opened at the time of terminating the applicaiton.

```
function signOut()
{
    app.quit();
}

```
```

    mainWindow.on('closed', function () {
        mainWindow = null;
        app.quit();

    });
```
```

app.on('window-all-closed', function () {
    // if (process.platform !== 'darwin') {
    //     app.quit();
    // }

    app.quit();
});
````

**Debug Log Printed in Console**
```

> 
> [901:0531/114426:FATAL:resource_dispatcher_host_impl.cc(658)] Check failed: ContainsKey(active_resource_contexts_, context). 
> 0   Electron Framework                  0x000000010bfa3903 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 389891
> 1   Electron Framework                  0x000000010bfb9ec9 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 481481
> 2   Electron Framework                  0x000000010c83b765 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 9400677
> 3   Electron Framework                  0x000000010c8ff0cc _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 10201804
> 4   Electron Framework                  0x000000010bf15009 _ZN9brightray14BrowserContext15ResourceContextD2Ev + 9
> 5   Electron Framework                  0x000000010bf14f79 _ZN9brightray14BrowserContext15ResourceContextD1Ev + 9
> 6   Electron Framework                  0x000000010bf14f8e _ZN9brightray14BrowserContext15ResourceContextD1Ev + 30
> 7   Electron Framework                  0x000000010bf158cf _ZN4base12DeleteHelperIN9brightray14BrowserContext15ResourceContextEE8DoDeleteEPKv + 15
> 8   Electron Framework                  0x000000010bfa3e0b _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 391179
> 9   Electron Framework                  0x000000010bfc2973 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 516979
> 10  Electron Framework                  0x000000010bfc2c4c _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 517708
> 11  Electron Framework                  0x000000010bfc2e3b _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 518203
> 12  Electron Framework                  0x000000010bf98a31 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 345137
> 13  Electron Framework                  0x000000010bfd57e3 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 594403
> 14  Electron Framework                  0x000000010bfc216d _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 514925
> 15  Electron Framework                  0x000000010c6e7b38 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 8009016
> 16  Electron Framework                  0x000000010c6e7d0e _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 8009486
> 17  Electron Framework                  0x000000010bff4758 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 721240
> 18  Electron Framework                  0x000000010bff0937 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 705335
> 19  libsystem_pthread.dylib             0x00007fff8780405a _pthread_body + 131
> 20  libsystem_pthread.dylib             0x00007fff87803fd7 _pthread_body + 0
> 21  libsystem_pthread.dylib             0x00007fff878013ed thread_start + 13

```
screen shot 2016-05-31 at 11 24 16 am

### PR DESCRIPTION
**Pull request by zcbenz**
Close #5778.

### CODE REVIEW

**Comment by deepak1556** [comment]
The reason for moving the `sessionWrapper` to `webContents` was to avoid crash when creating `webContents` without initializing `session` module. Currently there is `session` initialization in `app` module because of a deprecated [api](https://github.com/electron/electron/blob/master/lib/browser/api/app.js#L3) , once that is removed this will crash.

**Comment by zcbenz** [comment]
@deepak1556 We can probably explicitly initialize `session` module in `webContents` module.

**Comment by deepak1556** [comment]
Or just moving the wrapper would do ? Either way sounds good :+1:

**Comment by zcbenz** [comment]
I think it makes the code more clear by keeping session's wrapper in session.js.

**Pull request merged**
