### PR TITLE
Fix avoid the same method used many times

### PR DESCRIPTION
**Pull request by lzxb**
```javascript
const callback = () => { }

const event = new Event()

event.addListener(callback)
event.addListener(callback)
event.removeListener(callback)

// Before
// event.listeners = [callback]

// Now
// event.listeners = []
```

### CODE REVIEW

**Comment by ckerr** [comment]
I don't see what issue this is fixing?

**Comment by lzxb** [comment]
I'm sorry, now I've added an example

**Comment by ckerr** [comment]
OK I see the issue now and agree with your point.

I think @alexeykuzmin is right, this would be better fixed by implementing listeners as a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). @lzxb, would you be willing to do that?

**Comment by MarshallOfSound** [comment]
Changing the implementation to use a `Set` would be inconsistent with the chromium implementation, adding the same function as a listener multiple times should call that function multiple times.  Just like adding handlers to an `EventEmitter` would.  I think this change is 👌

**Comment by alexeykuzmin** [comment]
> Changing the implementation to use a Set would be inconsistent with the chromium implementation, adding the same function as a listener multiple times should call that function multiple times.

@MarshallOfSound 
You mean implementation of DOM event listeners?

**Comment by MarshallOfSound** [comment]
> You mean implementation of DOM event listeners?

No, this class is used to implement Chromium extension API's such as https://developer.chrome.com/apps/runtime#event-onConnect  We should be consistent with the functionality in that API

**Comment by ckerr** [comment]
I'm not sure what you mean by 'the chromium implementation'?

Looks like `bindings/event_emitter.h` takes a unique_ptr to an `APIEventListeners`, and in `atom/browser/api/event_emitter.cc`, the FilteredEventListeners' and UnfilteredEventListeners' implementations of AddListener() both return false if the argument object already has the listener passed in.

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 
Actually the current implementation already matches the Chromium's one =(
If you add the same listener twice if will be invoked twice, and even to remove it you would have to remove it twice. Doesn't make any sense to me to be honest.

**Comment by lzxb** [comment]
Well, long knowledge, agree with @alexeykuzmin

**Pull request closed without merging**
