### PR TITLE
fix: handle shortcuts by default if no WebPreference object exists

### LINKED ISSUE #14685: Paste shortcut doesn't work in DevTools in 3.0.0
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): macOS High Sierra 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.0

**Expected Behavior**
Hitting `Cmd+V` should paste the contents of the clipboard in the DevTools Console tab. 

**Actual behavior**
Nothing happens as if I haven't pressed anything.

**To Reproduce**
You can run any Electron app running 3.0.0 and the issue will be reproduced. I tried it with our own project and also a boilerplate project that contained nothing but the setup code to run the app.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
DevTools webContents do not have webPreferences

_reccomend viewing the diff with `?w=1`_

Fixes #14685

Notes: fix basic shortcuts (copy, paste, etc.) not working in devtools

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@deepak1556 I did look into making a spec but we currently have no way to trigger keyboard inputs that map into the `HandleKeyboardEvent` method (we skip them and go straight to `ForwardKeyboardEvent`.

**Comment by deepak1556** [comment]
Maybe create an internal that gets emitted from `HandleKeyboardEvent` and check if it receives right shortcuts for devtools with something like the following.
```
await emitOnce('devtools-focused', mainWindow.webContents)
mainWindow.devToolsWebContents.sendInputEvent({
    type: 'keyDown',
    modifiers: ['command'],
    keyCode: 'V'
})
```

**Comment by MarshallOfSound** [comment]
@deepak1556 I thought `sendInputEvent` skipped this stuff, will give it a shot 👍

**Comment by MarshallOfSound** [comment]
@deepak1556 Test added 👍

**Comment by MarshallOfSound** [comment]
@deepak1556 The test was failing on CI and it was super flaky locally, ended up using the `robotjs` npm module to fake a paste keypress at the OS level and see if the app responds correctly.  IMO it's a better test anyway 👍

**Comment by deepak1556** [comment]
Why is it required to test the specific shortcut execution in the devtools ? Wouldn't it be enough to just see if the shortcut gets passed to the desired window in `HandleKeyboardEvent` ? The specs could be simpler in that case.

**Comment by MarshallOfSound** [comment]
@deepak1556 I don't want to emit an event purely for the case of testing, people will start using it when they shouldn't and making this spec isn't too hard and is guaruntee'ed end-to-end working 👍

**Comment by deepak1556** [comment]
> I don't want to emit an event purely for the case of testing, people will start using it when they shouldn't

We already have a couple of internal events, methods purely for testing. Agreed this could be easier if we have native tests. Incase we want to go with the non event route then a shortcut thats deterministic like devtools reload, I am just worried about the polling for checking the clipboard response, it can get flaky on ci.

I am good with the original fix for the issue and the spec looks good too, was just hoping it could be better.

**Comment by MarshallOfSound** [comment]
> I am just worried about the polling for checking the clipboard response, it can get flaky on ci.

To be honest, I added that even though it was working synchronously consistently.  I added it with the specific intent of avoiding future race condition flakes.  I think this is in a relatively good state.

**Comment by MarshallOfSound** [comment]
I've disabled these tests on CI on macOS, assuming the VM's don't work with robotjs or something.  The tests pass locally on macOS on both my macOS machines and someone else's.

**Comment by MarshallOfSound** [comment]
Failed windows ia32 CI was a flake

**Comment by MarshallOfSound** [comment]
@mhuggins no

**Pull request merged**
