### PR TITLE
docs: update china npmmirror

### PR DESCRIPTION
**Pull request by onion7878**
Source: https://zhuanlan.zhihu.com/p/465424728

Notes: none

### CODE REVIEW

**Comment by zcbenz** [comment]
It was updated in https://github.com/electron/electron/pull/32076 but somehow got reverted when merging another PR.

**Review by zcbenz — APPROVED** [review]

**Comment by jkleinsc** [comment]
- Requesting @erickzhao to review since he intentionally changed it in #32964

**Review by erickzhao — APPROVED** [review]
Sorry, I think that was a mistake on my end. My apologies!

**Review by jkleinsc — APPROVED** [review]

**Comment by jkleinsc** [comment]
Merging as CI failure unrelated to PR change.

**Pull request merged**
