### PR TITLE
feat: add CustomMediaStream API

### PR DESCRIPTION
**Pull request by DyckGerman**
#### Description of Change
This PR includes the draft implementation of 'Custom media tracks API' mentioned here

https://github.com/electron/electron/issues/17690

#### Checklist
I have read the contributors guide but since it is a draft pr, some work still should be done

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added the 'CustomMediaStream' API which allows to convert any bitmap sequence inside the native module to a MediaStreamTrack for the render process

### CODE REVIEW

**Comment by miniak** [comment]
please target the master branch

**Comment by codebytere** [comment]
@DyckGerman a dependency is missing for `content/renderer/media/stream/media_stream_video_capturer_source.h`, which is what's causing the compilation errors

**Comment by DyckGerman** [comment]
build-linux
build-mac
build is successfull, but testing tasks fail. It does not look like something related to changes

**Comment by nornagon** [comment]
I agree that the linux/mac failures aren't related to this build. You'll need to rebase this on top of master to get windows CI runs.

The lint check is important, as is the release-notes check, please do fix those!

**Comment by DyckGerman** [comment]
rebase fixed some build issues
lint fixes e.g. changing the order of includes leads to compilation errors. work on them now

**Comment by veemex** [comment]
Hi ! Any news on this ?

**Comment by jphw** [comment]
> Hi ! Any news on this ?

Hi. We are making final steps in terms of documentation and tests.

**Comment by duanwenjian** [comment]
Hi ! Any news on this ?

**Comment by gamerz1990** [comment]
Any news on this

**Comment by Nic01as** [comment]
UP ? We can help ?

**Review by lastthyme — APPROVED** [review]

**Comment by nornagon** [comment]
There has been no activity on this PR for over a year, so I'm closing it. Feel free to open a new PR to continue work.

**Pull request closed without merging**
