### PR TITLE
fix: implement 'login' event for net.ClientRequest

### PR DESCRIPTION
**Pull request by nornagon**
Backport of #21096. See that PR for details.

Notes: Fixed the 'login' event not being emitted when HTTP Basic auth was requested during a `net.request`.

### CODE REVIEW

**Comment by nornagon** [comment]
NB: this includes https://github.com/electron/electron/pull/21098 to avoid having to resolve conflicts twice. Will rebase once that lands.

**Comment by true-zero** [comment]
This issue was never resolved.

**Comment by true-zero** [comment]
https://github.com/electron/electron/issues/21323

**Comment by nornagon** [comment]
@true-zero do you mean you're still encountering problems with the 'login' event? Or do you mean that #21323 should now be closed?

**Pull request merged**
