### PR TITLE
fix: bind fake mojo service for badging

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/25141.

Bind a fake mojo service for the [Badging API](https://web.dev/badging-api/). When users add e.g. `navigator.setAppBadge(42)` to the renderer, they will now see

```
The Chromium Badging API is not available in Electron
```

logged as a warning.

cc @nornagon @MarshallOfSound @deepak1556 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed a crash in the renderer process when invoking the Badging API.

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
Quick test? 😄

**Review by jkleinsc — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

**Review by nornagon — COMMENTED** [review]
Is it possible we could actually support the badging service? We do expose the relevant APIs...

**Comment by codebytere** [comment]
@nornagon not as it stands without massive patching, given that the Chromium impl is per-Profile.

For now, i think in the short term we should mitigate this crash, although I _do_ think there are some paths forward here. At minimum, we should look towards adding badging support for Windows. Once that's done, I think we can look to bind this to our own badging APIs 🤔  I can open a follow-up issue about adding Windows support if that seems like something we feel would be the next best step.

**Comment by nornagon** [comment]
Can we expose the events to the main process and let the app figure it out?

**Comment by codebytere** [comment]
Potentially? Wiring up the events would almost certainly require a fair bit of patching as well, and at that point it seems more prudent to actually support badging on Windows and wire it up more properly 🤔

**Comment by nornagon** [comment]
I think it still makes sense to give the app control over what's allowed to badge, for instance.

**Review by zcbenz — APPROVED** [review]

**Comment by zcbenz** [comment]
I assume it is OK to merge this PR? Providing some APIs to implement `navigator.setAppBadge` would be great, but this PR is only about fixing a crash and does not conflict with that purpose.

**Pull request merged**
