### PR TITLE
test: skip flaky <webview>.capturePage() test on Windows

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Fixes CI issue introduced by #20825

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes
Notes: no-notes

### CODE REVIEW

**Comment by miniak** [comment]
@nornagon what about just skipping it for now? I don't have a Windows build available currently for investigating why it's failing.

**Comment by nornagon** [comment]
Is it only flaky on Windows?

What about continually calling `capturePage` until you get something non-empty?

I don't like the idea of skipping this test, it's the sort of thing that seems like it'll just stay disabled forever.

**Comment by jkleinsc** [comment]
Merging as CI failure unrelated to PR change.

**Pull request merged**
