### PR TITLE
:apple: Add roles for macOS native tab menu items

### LINKED ISSUE #9086: Introduce menu roles for macOS Sierra tabs
After https://github.com/electron/electron/pull/9052 landed and you can enable native macOS sierra tabs in Electron apps it would be nice if as an application I could control where this menu item goes to:

image

My understanding is that a menu item role could help here? That way I would add a menu item to the desired location with that role and not have it show up as first entry without much control from the application itself.

/cc @tonyganch

### PR DESCRIPTION
**Pull request by kaylanm**
Fixes #9086, #10064.

image

### CODE REVIEW

**Comment by zeke** [comment]
Side note: Anyone know why the roles names have to be all lowercase?

**Comment by bpasero** [comment]
@kaylanm awesome, can't wait to have these in VSCode!

**Comment by kaylanm** [comment]
@bpasero neither can I. https://github.com/kaylanm/vscode/commit/ce1e5721c0dd9851c76391abb0472677aa173bb9

Time permitting I'll also try to expose these through the JS API so the command palette etc. can trigger them.

**Comment by tonyganch** [comment]
> Side note: Anyone know why the role names have to be all lowercase?

@zeke, as i understand, this is not a requirement, just a design decision made some time ago, as we seem to control user-facing role names.

**Comment by bpasero** [comment]
@kaylanm 

> Time permitting I'll also try to expose these through the JS API so the command palette etc. can trigger them.

My understanding is that this can be done already from the [`Menu.sendActionToFirstResponder()`](https://github.com/electron/electron/blob/master/docs/api/menu.md#menusendactiontofirstresponderaction-macos) method?

**Comment by kaylanm** [comment]
Ah, I didn't know that existed. You're right, it should work. It might still be nice to have first-class functions on the window object - the PR for that is here: https://github.com/electron/electron/pull/10321

**Pull request merged**
