### PR TITLE
Fix printing with the sandbox enabled

### LINKED ISSUE #7984: Printing to PDF doesn't work with sandbox enabled
* Electron version: 1.4.6
* Operating system: Linux Mint 18

### Expected behavior

Printing to PDF works even when using a renderer sandbox

### Actual behavior

The callback passed to printToPDF never gets called, so my app hangs. The sample code logs "Printing" on the console, but never "Success." Changing the sandbox flag to false fixes the issue.

### How to reproduce

```
const {BrowserWindow, app} = require('electron')

app.on('ready', function() {
  var webPreferences = {
    sandbox: true
  }

  var mainWindow = new BrowserWindow({
    webPreferences: webPreferences
  })

  mainWindow.webContents.on('did-finish-load', function() {
    console.log('Printing')
    mainWindow.webContents.printToPDF({}, function(error, data) {
      if (error) {
        console.error('Failed to print')
      } else {
        console.log('Success')
      }
    })
  })

  mainWindow.loadURL('https://www.google.com')
})
```

### PR DESCRIPTION
**Pull request by geoff-addepar**
Closes #7984

### CODE REVIEW

**Comment by tarruda** [comment]
While I'm not familiar with the printing API, the usage seems to be the same as in `AtomRendererClient`, so LGTM.

**Comment by hokein** [comment]
LGTM on printing API part.

**Comment by kevinsawicki** [comment]
Thanks @geoff-addepar for this :+1: :ship:

Thanks @hokein and @tarruda for reviewing 👍 :eyes:

**Pull request merged**
