### PR TITLE
Added BrowserWindow.setAppDetails to set user model id, icon and relaunch command

### PR DESCRIPTION
**Pull request by the-ress**
Calls [ui::win::SetAppDetailsForWindow](https://github.com/nwjs/chromium.src/blob/151b8e5d39b7edcf9eed78ebedf3b4eae9f93d28/ui/base/win/shell.cc#L117) in Chromium.

For Microsoft/vscode#13905

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Thanks for this, would you mind adding a simple spec to `spec/api-browser-window-spec.js` for this that just verifies it does not crash or throw unexpected errors?

Something like but with valid values for all the supported keys:

```js
it('supports setting the app details', function () {
  assert.doesNotThrow(function () {
    window.setAppDetails({appId: 'my.app.id', relaunchCommand: 'electron'})
    window.setAppDetails({})
  })
})
```

Also, can you update the docs in `docs/browser-window.md` with the usage details?

**Comment by the-ress** [comment]
Thanks for the suggestions. I've updated those files.

**Comment by kevinsawicki** [comment]
Thanks for adding this, apologies for the delay getting it merged 🚢 👍

**Comment by the-ress** [comment]
Thanks!

**Comment by dbradleyfl** [comment]
Heads up: this doesn't seem to do anything anymore #16087 @the-ress

**Pull request merged**
