### PR TITLE
printToPDF: `landscape` ignored if `@page` is used

### PR DESCRIPTION
**Pull request by destan**
This is very frustrating to find out via debugging, I think it should be in docs.

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the PR, @destan. Can your provide a little more context as to why this is?

**Comment by destan** [comment]
well, I am happy to provide more info however I don't know what more I could say about this.

* supply an HTML page which has a stylesheet with [@page](https://developer.mozilla.org/en/docs/Web/CSS/@page) rule
* use [printToPdf](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprinttopdfoptions-callback) api
*  when there is `@page` rule chrome/chromium silently ignores `landscape` option's value. It defaults to `portrait`
* to make it print in `landscape` you need to provide it in `@page` rule's value like 

```css
@page {size: landscape;}
/* OR */
@page {size: A4 landscape;}
```

----

Also note that when there is `@page` rule chrome/chromium hides `Layout` choice in UI (using in desktop)

image

**Comment by zeke** [comment]
@destan do you have the same result in Chrome?

**Comment by destan** [comment]
yes 

> Also note that when there is @page rule chrome/chromium hides Layout choice in UI (using in desktop)

in above part I tried to explain this :). It hides layout option in desktop's chrome because it ignores it anyway.

**Comment by destan** [comment]
can't upload an `html` file but you can save following as html and see for yourself:

when printing (save as pdf) it's w/o layput and page size options: (you can even see the hiding animation of layout and page size options when the print preview popup first show up)

image

when you remove `@page` rule the layout and page size options won't be hidden:

image

```html
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.0/build/pure-min.css">

  <style>
  body {
      width: 100%;
      height: 100%;
      margin: 0;
      padding: 0;
      background-color: #FAFAFA;
      font: 9px "Arial";
  }
  * {
      box-sizing: border-box;
  }
  .page {
      width: 210mm;
      min-height: 297mm;
      padding: 20mm;
      margin: 10mm auto;
      border: 1px #D3D3D3 solid;
      border-radius: 5px;
      background: white;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
  }

  .content {
      border: 1px #DDD solid;
      height: 257mm;
  }

  @page {
      size: A4;
      margin: 20mm;
  }
  @media print {
      html, body {
          width: 100%;
          height: 100%;
          margin: 0;
          padding: 0;
          background: white;
      }
      .page {
          padding: 0;
          margin: 0;
          border: initial;
          border-radius: initial;
          width: initial;
          min-height: initial;
          box-shadow: initial;
          background: transparent;
          page-break-after: always;
      }
  }

  table {
    width: 100%;
  }
  </style>

</head>
<body>
  <div class="book">

    <div class="page">
        <div class="subpage">

          <div class="ui grid container">
            <div class="center aligned row pure-g">
              <div class="eight wide column pure-u-1-2">
                <div id="chart1" style="min-width: 100%; height: 100%;"></div>
              </div>
              <div class="eight wide column pure-u-1-2">
                <div id="chart2" style="min-width: 100%; height: 100%;"></div>
              </div>
            </div>
            <div class="row">
              <table class="ui striped compact table pure-table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Date Joined</th>
                    <th>E-mail</th>
                    <th>Called</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td id="example_data">{example_data}</td>
                    <td id="example_data2">{example_data2}</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Line 1</td>
                    <td>Entry Line 2</td>
                    <td>Entry Line 3</td>
                    <td>Entry Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>Jamie Harington</td>
                    <td>January 11, 2014</td>
                    <td>jamieharingonton@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>Jill Lewis</td>
                    <td>May 11, 2014</td>
                    <td>jilsewris22@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>Jamie Harington</td>
                    <td>January 11, 2014</td>
                    <td>jamieharingonton@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>Jill Lewis</td>
                    <td>May 11, 2014</td>
                    <td>jilsewris22@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Line 1</td>
                    <td>Entry Line 2</td>
                    <td>Entry Line 3</td>
                    <td>Entry Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Line 1</td>
                    <td>Entry Line 2</td>
                    <td>Entry Line 3</td>
                    <td>Entry Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Line 1</td>
                    <td>Entry Line 2</td>
                    <td>Entry Line 3</td>
                    <td>Entry Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>Jamie Harington</td>
                    <td>January 11, 2014</td>
                    <td>jamieharingonton@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>Jill Lewis</td>
                    <td>May 11, 2014</td>
                    <td>jilsewris22@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>Jamie Harington</td>
                    <td>January 11, 2014</td>
                    <td>jamieharingonton@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>Jill Lewis</td>
                    <td>May 11, 2014</td>
                    <td>jilsewris22@yahoo.com</td>
                    <td>Yes</td>
                  </tr>
                  <tr>
                    <td>John Lilki</td>
                    <td>September 14, 2013</td>
                    <td>jhlilk22@yahoo.com</td>
                    <td>No</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Line 1</td>
                    <td>Entry Line 2</td>
                    <td>Entry Line 3</td>
                    <td>Entry Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry First Line 1</td>
                    <td>Entry First Line 2</td>
                    <td>Entry First Line 3</td>
                    <td>Entry First Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Line 1</td>
                    <td>Entry Line 2</td>
                    <td>Entry Line 3</td>
                    <td>Entry Line 4</td>
                  </tr>
                  <tr>
                    <td>Entry Last Line 1</td>
                    <td>Entry Last Line 2</td>
                    <td>Entry Last Line 3</td>
                    <td>Entry Last Line 4</td>
                  </tr>
                  <tr>
                    <td>THE LAST 1</td>
                    <td>THE LAST 2</td>
                    <td>THE LAST 3</td>
                    <td>THE LAST 4</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>


        </div>
    </div>
  </div>

  <div class="page">
      <div class="subpage">Page 1/2</div>
  </div>
</body>
</html>

```

**Comment by zeke** [comment]
Because this appears to be a Chromium bug, I would prefer not to add it to our documentation. I would recommend trying to find the bug on Chromium's tracker and filing a new bug if you can't find an existing one. https://bugs.chromium.org/p/chromium/issues/list?q=landscape

**Comment by destan** [comment]
No, I don't think that's a bug. This is a real chrome feature. I take "hide animations of page size and layout options on print preview when having `@page` rule on html" as an evidence for it being a feature not a bug. And there is no accepted bug report about it.

Furthermore, even it was a bug, I strongly think that Electron should document this well observable behavior in its docs.

**Comment by zeke** [comment]
Thanks!

**Pull request merged**
