### PR TITLE
fix: set Wayland application ID

### LINKED ISSUE #33578: [Bug]: app_id not set when running Electron with native Wayland
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0

### Expected Behavior

The `app_id` window property should be set to the same value as `class` under X11.

### Actual Behavior

`app_id` is an empty string when running Electron under Wayland.

### Testcase Gist URL

_No response_

### Additional Information

While most apps would crash prior to #33355, the default page if you run `electron --ozone-platform=wayland` would still run and properly set `app_id`.

### PR DESCRIPTION
**Pull request by vially**
#### Description of Change

Electron versions prior to 18.0.0 (`<18.0.0`) were setting the [Wayland application ID](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) to the same value as the X11 `WM_CLASS` property. But in recent versions of Electron the Wayland's application ID property is empty (#33578).

Most likely this was caused by [this upstream Chromium change](https://chromium-review.googlesource.com/c/chromium/src/+/3347575) which introduced the [`wayland_app_id`](https://source.chromium.org/chromium/chromium/src/+/main:ui/platform_window/platform_window_init_properties.h;l=132-134;drc=f28f4f8f90c4494c9bc9f34a28f5dcc215caa077) property.

This pull-request makes use of the `wayland_app_id` property by setting its value to the *basename of the application's `.desktop` file*.

Fixes #33578
Closes https://github.com/electron/electron/issues/34852

##### Related issues

- #34852 (it *may* be related, but it needs more investigation)

#### Checklist

- [x] PR description included and stakeholders cc'd (@zcbenz @ckerr @deepak1556)
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix empty app_id when running under wayland

### CODE REVIEW

**Review by RaisinTen — COMMENTED** [review]
Could you add `Fixes: https://github.com/electron/electron/issues/33578` to the PR description, so that the issue gets closed automatically when your change gets merged? Might also want to add a release note because it fixes an issue that's relevant to app developers.

Could you also add a test? Maybe something like parsing the output of the logs mentioned in https://github.com/electron/electron/issues/33578#issuecomment-1093345814 if there's no neater way?

**Review by deepak1556 — APPROVED** [review]
Thanks for addressing this issue! Also reminded me that `wm_class_class` should also be fixed for wayland https://github.com/microsoft/vscode/issues/129953#issuecomment-925780316

**Review by MarshallOfSound — APPROVED** [review]

**Comment by vially** [comment]
> Could you also add a test? Maybe something like parsing the output of the logs mentioned in https://github.com/electron/electron/issues/33578#issuecomment-1093345814 if there's no neater way?

@RaisinTen  I was considering adding some basic Wayland tests but I encountered some issues and I have the feeling there are some things that would need to be taken care of before being able to do that.

Part of the challenge here is that, as far as I'm aware, the CI is currently configured to run all Linux tests under X11 only. On top of that, some of the *existing tests are currently failing* when run under Wayland.

So, before getting started with writing some Wayland specific tests, these are a couple of things that would need to be fixed first:
- make a Wayland environment available for running the tests in CI
- identify and either fix or disable the tests that are currently failing under Wayland
- decide on a strategy for running the Linux tests (e.g.: should all Linux tests be run twice: once under X11 and once under Wayland?)

I could try to help with some of these issues, but I would need some pointers from someone who is 1) familiar with these systems and 2) is able to provide guidance and feedback along the way.

> Also reminded me that wm_class_class should also be fixed for wayland

@deepak1556 My impression was that `wm_class_class` should not be used at all when Electron is running as a *native* Wayland client (e.g.: `--ozone-platform=wayland`). Or do you mean that it should be fixed when running Electron under XWayland? If that's what you mean, what should it be changed into?

### X11 WM_CLASS vs Wayland app_id

I've only looked briefly into it, but according to [GNOME's recommendation](https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased#The_WM_CLASS_X_Window_property), the app should "[...] set the WM_CLASS X window property to be the same as your application's `.desktop` file name, without the `.desktop` extension". In other words, it should be the same as Wayland's `app_id`.

But, as you've mentioned (https://github.com/microsoft/vscode/issues/129953#issuecomment-925780316), that's not currently the case.

So, if backwards compatibility was not a concern, my suggestion would be to make both X11's `WM_CLASS` and Wayland's `app_id` to be the same (e.g.: the app's `.desktop` file name without the extension). It might also be worth making the [`setDesktopName()`](https://github.com/electron/electron/blob/afd08c9450f5ad9b067b5f6dbf9b9243307d00b2/typings/internal-electron.d.ts#L17) API public (Linux only), or improve the documentation to make it slightly easier to [find a way to set it](https://www.electronjs.org/docs/latest/api/browser-window#winsetprogressbarprogress-options):

https://github.com/electron/electron/blob/afd08c9450f5ad9b067b5f6dbf9b9243307d00b2/lib/browser/init.ts#L119-L124

**Comment by RaisinTen** [comment]
> So, before getting started with writing some Wayland specific tests, these are a couple of things that would need to be fixed first:
> 
> * make a Wayland environment available for running the tests in CI
> * identify and either fix or disable the tests that are currently failing under Wayland
> * decide on a strategy for running the Linux tests (e.g.: should all Linux tests be run twice: once under X11 and once under Wayland?)
> 
> I could try to help with some of these issues, but I would need some pointers from someone who is 1) familiar with these systems and 2) is able to provide guidance and feedback along the way.

To my understanding, making the Wayland environment should be done in https://github.com/electron/build-images. I'm not sure who the right person is for answering your questions, maybe @MarshallOfSound and @jkleinsc because y'all have the highest number of commits on that repo?

**Comment by ReillyBrogan** [comment]
I think there's an issue in this in the case where an application has multiple .desktop files. For instance consider the following two desktop files:

code-oss.desktop
```
[Desktop Entry]
Name=Visual Studio Code
Comment=Visual Studio Code
GenericName=Text Editor
Exec=/usr/bin/code-oss --ozone-platform-hint=auto --disable-crash-reporter %U
Icon=com.visualstudio.code.oss
Type=Application
StartupNotify=false
StartupWMClass=code-oss
Categories=TextEditor;Development;IDE;
MimeType=text/plain;application/x-code-oss-workspace;
Terminal=false
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/bin/code-oss --ozone-platform-hint=auto --disable-crash-reporter --new-window %F
Icon=com.visualstudio.code.oss
```

code-oss-url-handler.desktop
```
[Desktop Entry]
Name=Visual Studio Code URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/bin/code-oss --ozone-platform-hint=auto --disable-crash-reporter --open-url %U
Icon=com.visualstudio.code.oss
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/code-oss;
Keywords=vscode;
```
(this is a real example where a separate desktop file exists in order to register a URL handler, tested by switching vscode 1.69.2 to Electron 19.0.10)

In this case Electron when launched via the `code-oss.desktop` desktop fill will apparently set the `app_id` to `code-oss-url-handler` which obviously does not match what it should be in the `code-oss.desktop` file, thus triggering the WM to believe that it's a separate application and show the generic icon instead.

I'm not sure what the correct logic should be, but perhaps desktop files with `NoDisplay=true` should be ignored during the check?

**Comment by zcbenz** [comment]
@ReillyBrogan Apps should have specified its desktop filename with `app.setDesktopName`, so I think multiple desktop files should be fine?

**Comment by ReillyBrogan** [comment]
> @ReillyBrogan Apps should have specified its desktop filename with `app.setDesktopName`, so I think multiple desktop files should be fine?

I'm unsure of what you mean (I'm not generally familiar with the Electron codebase, just trying to report this issue after testing the new version of Electron with a few apps) . Are you saying that that's how they should do it when the electron app is installed at the user-level? What about the case where an Electron app is packaged as a system package? The user running the app would typically not run it as a root-level process and it would not be able to modify its desktop

**Comment by ReillyBrogan** [comment]
In the system package case the packager usually decides the name of the desktop file, though they may decide to use the default names provided by the application.

**Comment by zcbenz** [comment]
Electron has an API (`app.setDesktopName`) to set which desktop file to use, and the `wayland_app_id` set in this PR uses the result of the API. So if apps have multiple desktop files, they can use the API to specify the name of desktop instead of letting the desktop manager to guess one for them.

**Comment by vially** [comment]
> [...] when launched via the `code-oss.desktop` desktop fill will apparently set the `app_id` to `code-oss-url-handler`

For what it's worth, VSCode [explicitly sets the `desktopName` to the URL handler desktop file](https://github.com/microsoft/vscode/blob/0ea1cfd5d252245aef711b552966eb567f4a5653/build/gulpfile.vscode.js#L202). Without looking into it, this does seem a bit strange, but I suppose there must be a good reason for it.

But even so, my interpretation of the specs[^1] is that as long as the deskop file (`code-oss-url-handler.desktop` in this case) contains an `Icon` field, I think the window manager/compositor should be able to pick it up.

[^1]:
    1. [Applications in GNOME 3](https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased)
    2. [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)

**Pull request merged**
