### PR TITLE
fix: backport 3b21b6d from v8 to fix profiler crash

### PR DESCRIPTION
**Pull request by indutny**
#### Description of Change

Fix: #28472

#### Release Notes

Notes: Fix crash when using profiler in devtools.

### CODE REVIEW

**Comment by ckerr** [comment]
@indutny, looks like this patch needs another look

```
Applying: Allow empty source URL for asm modules
Using index info to reconstruct a base tree...
M	src/profiler/profiler-listener.cc
Falling back to patching base and 3-way merge...
Auto-merging src/profiler/profiler-listener.cc
CONFLICT (content): Merge conflict in src/profiler/profiler-listener.cc
error: Failed to merge in the changes.
Patch failed at 0010 Allow empty source URL for asm modules
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Traceback (most recent call last):
  File "src/electron/script/apply_all_patches.py", line 34, in <module>
    main()
  File "src/electron/script/apply_all_patches.py", line 30, in main
    apply_patches(json.load(config_json))
  File "src/electron/script/apply_all_patches.py", line 16, in apply_patches
    committer_name="Electron Scripts", committer_email="scripts@electron")
  File "/home/builduser/project/src/electron/script/lib/git.py", line 107, in import_patches
    am(repo=repo, **kwargs)
  File "/home/builduser/project/src/electron/script/lib/git.py", line 77, in am
    proc.returncode))
RuntimeError: Command ['git', '-C', 'src/v8', '-c', 'user.name=Electron Scripts', '-c', 'user.email=scripts@electron', '-c', 'commit.gpgsign=false', 'am', '--3way', '--keep-cr'] returned 128
Error: Command 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json' returned non-zero exit status 1 in /home/builduser/project
Hook 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 52.25 secs


Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by indutny** [comment]
@ckerr ah, this is because the master branch uses V8 9.1.127 that is already fixed. I'll re-target this PR to 12-x-y. Sorry for the noise!

**Comment by indutny** [comment]
@ckerr should be better now. PTAL

**Review by codebytere — APPROVED** [review]

**Comment by codebytere** [comment]
@indutny this patch needs to be fixed up - the commit to push to fix it is [here](https://829589-9384267-gh.circle-artifacts.com/0/patches/update-patches.patch)

**Comment by indutny** [comment]
Thank you @codebytere . Force pushed again.

**Comment by indutny** [comment]
Sorry for a ping, but it'd be great if it could get into 12-x-y before the release (which apparently wasn't cut out just yet!)

**Review by zcbenz — APPROVED** [review]

**Comment by indutny** [comment]
Awesome. Thanks!

**Pull request merged**
