### PR TITLE
Upgrade to Chrome 52

### PR DESCRIPTION
**Pull request by zcbenz**

### CODE REVIEW

**Comment by paulcbetts** [comment]
@zcbenz Is this waiting on M52 to hit stable?

**Comment by zcbenz** [comment]
@paulcbetts yep.

**Comment by paulcbetts** [comment]
@zcbenz :+1: ✨ :dancer:

**Comment by YurySolovyov** [comment]
[Looks like it happened](http://googlechromereleases.blogspot.com.by/2016/07/stable-channel-update.html)

**Pull request merged**
