### PR TITLE
Official build for 1.8

### PR DESCRIPTION
**Pull request by alespergl**
Verified that release builds on:
- [x] Linux ia32
- [x] Linux x64
- [x] Linux arm
- [x] Linux arm64
- [x] Linux mips64el
- [x] macOS x64
- [x] Windows ia32
- [x] Windows x64

Requires https://github.com/electron/libchromiumcontent/pull/454

### CODE REVIEW

**Comment by alespergl** [comment]
@jkleinsc Can we run test suite on the release build for this PR?

**Comment by jkleinsc** [comment]
@alespergl release builds here:
Jenkins build request successful.  Check build status at https://mac-ci.electronjs.org/job/electron-osx-x64-release/40/.
Jenkins build request successful.  Check build status at https://mac-ci.electronjs.org/job/electron-mas-x64-release/45/.
Check https://circleci.com/gh/electron/electron/10679 for status. (electron-linux-arm64)
Check https://circleci.com/gh/electron/electron/10681 for status. (electron-linux-ia32)
Check https://circleci.com/gh/electron/electron/10680 for status. (electron-linux-arm)
Check https://circleci.com/gh/electron/electron/10678 for status. (electron-linux-mips64el)
Check https://circleci.com/gh/electron/electron/10682 for status. (electron-linux-x64)
AppVeyor release build request successful.  Check build status at https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.2810

**Comment by alespergl** [comment]
**Linux x64** release build timed out. Seems the build is killed after 10 minutes, but linking of the official build can take longer. Maybe we need to increase the timeout value? @jkleinsc 

**Linux mips64el** linker is failing with the following error. I haven't heard of this problem on master. Can the mips toolchain be upgraded? @zcbenz 
```
[1206/1206] LINK electron
FAILED: ../../vendor/cross-gcc-4.9.3-n64-loongson-rc5.4/usr/bin/mips64el-loongson-linux-g++ -Wl,--whole-archive /home/builduser/project/vendor/download/libchromiumcontent/static_library/libmedia.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libbase.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libskia.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libwebkit.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libwebkitcore.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libnet.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libangle.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libservices.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libcomponents.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libcc.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libppapi.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libpdfium.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libwebkitbindings.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libwebrtc.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libwebkitmodules.a /home/builduser/project/vendor/download/libchromiumcontent/static_library/libchromiumcontent.a -Wl,--no-whole-archive -Wl,-z,noexecstack -Wl,-rpath=\$ORIGIN -rdynamic -L/home/builduser/project/vendor/debian_jessie_mips64-sysroot/usr/lib64 -L/home/builduser/project/vendor/debian_jessie_mips64-sysroot/lib64 -L/home/builduser/project/vendor/debian_jessie_mips64-sysroot/usr/lib64 -Wl,--export-dynamic -pthread --sysroot=/home/builduser/project/vendor/debian_jessie_mips64-sysroot  -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -Wl,-rpath=\$ORIGIN/lib/ -Wl,-rpath-link=lib/ -o electron -Wl,--start-group obj/atom/app/electron.atom_main.o obj/libelectron_lib.a obj/brightray/libbrightray.a obj/vendor/breakpad/libbreakpad_client.a -Wl,--end-group lib/libnode.so -lpthread -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lfontconfig -lfreetype -ldbus-1 -lX11-xcb -lxcb -lXi -lXcursor -lXdamage -lXrandr -lXcomposite -lXext -lXfixes -lXrender -lX11 -lXtst -lXss -lgconf-2 -lgmodule-2.0 -lglib-2.0 -lpulse /home/builduser/project/vendor/download/libchromiumcontent/static_library/libffmpeg.so -lasound -lcap -lcups -lrt -ldl -lresolv -lexpat
/home/builduser/project/vendor/cross-gcc-4.9.3-n64-loongson-rc5.4/usr/bin/../lib/gcc/mips64el-loongson-linux/4.9.3/../../../../mips64el-loongson-linux/bin/ld: BFD version 2.24 assertion fail ../../bfd/elf-strtab.c:200
```

**Comment by zcbenz** [comment]
> Linux mips64el linker is failing with the following error. I haven't heard of this problem on master. Can the mips toolchain be upgraded? @zcbenz

I'll ask the mips64el developers, if not I'll try to work around this error.

**Comment by alespergl** [comment]
I found that the mips issue can be mitigated by removing `--as-needed` from the linker command line. @jkleinsc could you re-run the release tests to validate? Thanks.

**Comment by jkleinsc** [comment]
@alespergl release builds have been retriggered:
Jenkins build request successful.  Check build status at https://mac-ci.electronjs.org/job/electron-osx-x64-release/41/.
Jenkins build request successful.  Check build status at https://mac-ci.electronjs.org/job/electron-mas-x64-release/46/.
Check https://circleci.com/gh/electron/electron/10835 for status. (electron-linux-ia32)
Check https://circleci.com/gh/electron/electron/10837 for status. (electron-linux-mips64el)
Check https://circleci.com/gh/electron/electron/10839 for status. (electron-linux-x64)
Check https://circleci.com/gh/electron/electron/10836 for status. (electron-linux-arm)
Check https://circleci.com/gh/electron/electron/10838 for status. (electron-linux-arm64)
AppVeyor release build request successful.  Check build status at https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.2842

**Comment by jkleinsc** [comment]
A couple of the builds failed.  I bumped up the timeout for the linux x64 build and fixed the issue with the mas build (the libcc static file was incorrectly named).

Jenkins build request successful.  Check build status at https://mac-ci.electronjs.org/job/electron-mas-x64-release/lastBuild/.
Jenkins build request successful.  Check build status at https://mac-ci.electronjs.org/job/electron-osx-x64-release/lastBuild/.
Check https://circleci.com/gh/electron/electron/10845 for status. (electron-linux-ia32)
Check https://circleci.com/gh/electron/electron/10846 for status. (electron-linux-x64)
Check https://circleci.com/gh/electron/electron/10847 for status. (electron-linux-arm64)
Check https://circleci.com/gh/electron/electron/10844 for status. (electron-linux-mips64el)
Check https://circleci.com/gh/electron/electron/10848 for status. (electron-linux-arm)
AppVeyor release build request successful.  Check build status at https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.2843

**Comment by alespergl** [comment]
@jkleinsc I think the Linux agent is short on memory. We had the same problem internally. Is there a swap file/partition on that system? Adding it should fix the current failure.

**Comment by jkleinsc** [comment]
@alespergl we can use larger machines on CircleCI.  I updated the CircleCI config to use the same machines we are using on master.

**Comment by alespergl** [comment]
This is ready for merging now.

**Comment by ckerr** [comment]
Fixes https://github.com/electron/electron/issues/11628

**Pull request merged**
