### PR TITLE
Make MenuItem roles camelCase-compatible

### LINKED ISSUE #10372: Use camelCase for MenuItem roles
A followup to #10271 

Lowercase roles like `movetabtonewwindow` are hard to read. If there's not a technical reason that they have to be lowercase, we should use mixed case to make them more legible, e.g. `moveTabToNewWindow`. To avoid making this a breaking change, we could quietly continue to support the old lowercase style.

https://electron.atom.io/docs/api/menu-item/#roles

### PR DESCRIPTION
**Pull request by sethlu**
Migrating MenuItem roles to be in camelCase while keeping backward lowercase compatibility.

Closes #10372
CC: @zeke

### CODE REVIEW

**Comment by codebytere** [comment]
hey seth, you'll need to fix linting errors here before we can begin to review this. thanks!

**Comment by sethlu** [comment]
@codebytere cool! I’ll do that a little later today 👍

**Comment by codebytere** [comment]
hey @sethlu, it looks like you're failing `342 Menu module MenuItem editMenu includes a default submenu layout when submenu is empty`; what's happening locally?

**Comment by sethlu** [comment]
@codebytere I forgot to run the test cases again... 😢 Should work now.

**Comment by zeke** [comment]
Nice! Thanks @sethlu.

**Pull request merged**
