### PR TITLE
Debug mode (take 2)

### PR DESCRIPTION
**Pull request by alespergl**
Another attempt at enabling debug mode (the first was #9934). I disabled an assert in libcc which caused some Electron tests to fail. This PR is identical to #9934, it only references an updated libcc.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Looks like the tests are still aborting:

```
ok 197 BrowserWindow module offscreen rendering creates offscreen window with correct size
abort() has been calledTraceback (most recent call last):
```

**Comment by alespergl** [comment]
So the aborts are gone. Some tests timed out on Windows 64bit and OSX, but at least Windows 32bit and MAS builds passed. Good enough, @kevinsawicki ? If so, I will merge https://github.com/electron/libchromiumcontent/pull/322 and then this.

**Comment by alexeykuzmin** [comment]
> Some tests timed out on Windows 64bit and OSX

They all are green now.

**Comment by alexeykuzmin** [comment]
It seems like tests
```
not ok 221 crashReporter module without sandbox should not send minidump if uploadToServer is false
  Error: Uploaded crash report
...
not ok 225 crashReporter module without sandbox should not send minidump if uploadToServer is false
  Error: done() called multiple times
```
fail in all PRs and it's safe to merge this one.

**Pull request merged**
