### PR TITLE
feat: add popover api to BrowserView for macos

### PR DESCRIPTION
**Pull request by gerhardberger**
#### Description of Change

This PR adds the ability to open Electron BrowserViews in an [NSPopover](https://developer.apple.com/documentation/appkit/nspopover?language=objc) on macOS. There can be a various use-cases to open temporary modals in an app an let the OS handle the animation and the positioning.

Usage:

``` js
// Create parent window.
const win = new BrowserWindow({ width: 400, height: 400 });

// Create the popover view.
const popover = new BrowserView({
  width: 300,
  height: 300,
  // This is a custom flag introduced by this PR that makes it possible to use
  // transparent backgrounds in a popover's content.
  webPreferences: { disableAllowsVibrancy: true },
});

win.loadFile('index.html');
popover.webContents.loadFile('popover.html');

// Listen for the event when the popover is closed either programatically,
// or by user gesture.
popover.webContents.on('popover-closed', () => {
  console.log('Popover closed.');
});

// Open the popover, the parameters follow the official method: https://developer.apple.com/documentation/appkit/nspopover/1532113-showrelativetorect?language=objc
// Note, that the positioning_rect coordinates are calculated from the bottom
// left corner of the parent window 'win'.
popover.showPopoverWindow({
  positioningWindow: win,
  positioningRect: { x: 100, y: 100, width: 50, height: 50 },
  size: { width: 300, height: 300 },
  behavior: 'transient',
  animate: true
});

// Close the popover.
popover.closePopoverWindow();

// Resize the popover once its opened. The x and y coords are not used since
// we always position it to fill the popover.
popover.setBounds({ x: 0, y: 0, width, height });
```

Default positioning relative to the BrowserWindow:

https://user-images.githubusercontent.com/1059699/221580002-fb89f548-dd7c-4379-bab5-b02fb9b596cd.mov

Sizing and positioning in a custom rectangle relative to the positioning window's bounds:

https://user-images.githubusercontent.com/1059699/221580777-78dd7513-56b1-46d3-aee8-72a17700869e.mov

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Added opening BrowserViews in native popovers on macOS.

### CODE REVIEW

**Review by nornagon — CHANGES_REQUESTED** [review]
I think this should probably wait for https://github.com/electron/electron/pull/35658 to land!

**Comment by JCBsystem** [comment]
i need this one. please approve it

**Comment by zcbenz** [comment]
https://github.com/electron/electron/pull/35658 has landed.

**Comment by JCBsystem** [comment]
bump. please add this

**Comment by gerhardberger** [comment]
Hey!
Replaced the functionality of the PR with this native module: [electron-mac-popover](https://github.com/gerhardberger/electron-mac-popover)
This does exactly the same thing without the necessity to be added into the Electron codebase, which also has the benefit of not needing to maintain an extra patch.

**Comment by jkleinsc** [comment]
Closing due to this PR no longer being needed as explained in this comment: https://github.com/electron/electron/pull/37423#issuecomment-2527425528

**Pull request closed without merging**
