### PR TITLE
Fix notification actions not working on High Sierra

### LINKED ISSUE #10655: Can't get callback(click or reply event) from Notification on MainProcess
* Electron version: 1.7.8
* Operating system: MacOS High Sierra(10.13)

### Expected behavior

Trigger callback when I click notification.

### Actual behavior

nothing happened.

### How to reproduce

```js
const { app, BrowserWindow, Notification, ipcMain, nativeImage } = require('electron')

ipcMain.on('notify', async (e, opts) => {
    const isSupported = Notification.isSupported()
    let icon;

    if (opts.url) {
      icon = await covertImage(opts.url)
    }

    console.log('isSupported', isSupported)

    if (!isSupported) return

    const data = {
      title: opts.title,
      body: opts.body,
      hasReply: opts.hasReply,
    };

    const notify = new Notification(icon ? Object.assign(data, { icon }) : data)

    notify.on('reply', (e, replyText) => {
      console.log('replayText', replyText)
    })

    notify.show()
  })
```

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #10655

### CODE REVIEW

**Comment by ckerr** [comment]
Should be good for the first two million notifications or so :smile: 

Did it make sense to merge this with the electron-mas-x64 build failing though? Is that a false negative?

**Comment by MarshallOfSound** [comment]
@ckerr Yeah, if you're showing more than 2 million notifications you're gonna have bigger problems than this int overflowing 😆 

The MAS build failed on webview tests which are unrelated to this code change so called out as a flake.

**Comment by ilyaLibin** [comment]
@MarshallOfSound Still doesn't work for me.  :/
Same code
"electron": "^1.7.10",
OS High Sierra 10.13.2

**Comment by MarshallOfSound** [comment]
@ilyaLibin This fix is not in the `1.7.x` series, only in the `1.8.x` series

**Pull request merged**
