### PR TITLE
feat: support exclude from capture on Windows

### PR DESCRIPTION
**Pull request by BenRussert**
#### Description of Change

This change will allow full window exclusion similar to Mac's current behavior for Windows 10 versions 2004 and later.
Older Windows versions will still show a black window as before, but `WDA_EXCLUDEFROMCAPTURE` simply falls back to `WDA_MONITOR`.

https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/64#issuecomment-697074762

Windows api docs here: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity

https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Windows 10 versions 2004 and later support `WDA_EXCLUDEFROMCAPTURE` and will now exclude a window entirely from screen capture when `setContentProtection`  is enabled. Older Windows versions will continue to show a black window as before.

### CODE REVIEW

**Review by zcbenz — APPROVED** [review]
Nice!

**Review by codebytere — APPROVED** [review]

**Comment by sapkra** [comment]
@codebytere @zcbenz Can any of you already predict in which electron version will it land? v12?

**Comment by infinite3219** [comment]
Any update on when this will be merged into a release?

**Comment by eric-gitta-moore** [comment]
Great feature. But I wonder if we can be a little more specific and hide the screen sharing indicator separately.

Something like this- 
image

#12973

**Pull request merged**
