### PR TITLE
build: remove legacy helpers (Electron Helper EH/NP)

### PR DESCRIPTION
**Pull request by miniak**
##### Description of Change
Electron Helper EH/NP is not used anymore. Chrome is also not shipping these separate helpers anymore (since NPAPI plugin support was removed)

https://bugs.chromium.org/p/chromium/issues/detail?id=520680
> Google Chrome Helper EH.app is the "executable helper" which is only used by NPAPI. This needs to be removed as it is no longer used.

##### Checklist
- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes
Notes: Removed legacy helpers (Electron Helper EH/NP).

### CODE REVIEW

**Comment by miniak** [comment]
@deepak1556 it would make sense to do this for 3.0 as well, but I guess it's technically a breaking change.

**Comment by alexeykuzmin** [comment]
@deepak1556 
You're absolutely right.
Moving to GN is a great opportunity for us to clean all obsolete tools and scripts.
But the PR in question intentionally doesn't try to remove _everything_ to be easier to be reviewed.

**Comment by deepak1556** [comment]
@miniak I would be onboard for backporting this to 3.x, technically this isn't a breaking change as its an unused binary, i don't see a reason for users to depend on it.

**Comment by MarshallOfSound** [comment]
@miniak You have to be on a list to run trop commands

**Comment by MarshallOfSound** [comment]
Actually wait, we probably shouldn't backport this

**Pull request merged**
