### PR TITLE
Frame subscriber improvements

### PR DESCRIPTION
**Pull request by gerhardberger**
This PR fixes the scale factor issue that was present when enabling frame subscription in `<webview>`s. #7158 

Also it simplifies the frame subscription API exposing a `NativeImage` instead of a `Buffer`.

### CODE REVIEW

**Comment by IsaiahJTurner** [comment]
Two questions:
- From what I know `NativeImage` is not backwards compatible with `Buffer` so this would be a breaking change? Would the change for upgrading legacy code be as simple as calling `getBitmap` on image?
- Are there any performance impacts from using `NativeImage`?

My current usage of `beginFrameSubscription` does all the image rendering in C on another thread. I do end up converting it to JPEG but this gives me fine control over optimizing that. I would likely end up calling `getBitmap` so I can continue this. However, I do see huge advantages to `NativeImage` since the work involved to even start using `beginFrameSubscription` is extremely difficult at the moment.

**Comment by gerhardberger** [comment]
@IsaiahJTurner using `NativeImage` has no performance impact, if you use `toBitmap()` of `NativeImage` you get the same `Buffer` as it passed previously.

if you use `getBitmap()` its even faster, because it doesn't copy the data to a new buffer, but this way you are not in control of it.

yes, I also think this is a more versatile and simple-to-use API for users.

**Comment by brenca** [comment]
@IsaiahJTurner can confirm, a change in `NativeImage` API does allow you to get the raw data without a performance impact.

**Comment by zcbenz** [comment]
Changing the callback type is a breaking API change, and since `beginFrameSubscription` is already a commonly used API, we have to postpone the API change to 2.0, which would take a very long time.

So can you keep the API unchanged, or add an option to make the behavior optional?

**Comment by gerhardberger** [comment]
@zcbenz thanks, I reverted the API to the old one, but I kept it on a branch in my fork for later, because it is a nicer and simpler API I think.

**Comment by zcbenz** [comment]
👍

**Pull request merged**
