### PR TITLE
fixed everything

### PR DESCRIPTION
**Pull request by binsenpai**
#### Checklist

- [X ] PR description included and stakeholders cc'd
- [ X] `npm test` passes
- [ X] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ X] relevant documentation is changed or added
- [ X] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

I benefited humanity, I saved everyone. I am the white knight of the technology world. Everyone from here on till forever will praise me for saving all your souls.
Notes:

### CODE REVIEW

**Comment by apap04** [comment]
C  L  A  P

**Comment by BenjaminUrquhart** [comment]
To be fair this will save the world if merged.

**Comment by kot83** [comment]
F to pay respects.

**Comment by Chewsterchew** [comment]
Beautiful

**Pull request closed without merging**
