### PR TITLE
test: move some BrowserWindow specs to the main runner

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Move a couple of BrowserWindow specs to the main runner and refactor the 'when invoked synchronously inside navigation observer' test. I'm not sure it was actually running before, because visiting `/404` did not trigger a `did-fail-load` event.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by nornagon** [comment]
not sure what's up with appveyor but i'm gonna merge this since the final commit was a very minor change, the prior commit passed on all platforms, and this is passing on linux/mac and arm.

**Comment by CapOM** [comment]
Hi, how to you run a specific test now it is moved ? Thx

I used to do: `./out/Debug/Electron.app/Contents/MacOS/Electron electron/spec -g 'moveTop' ` but does not work if I replace spec by spec-main

**Comment by nornagon** [comment]
`npm test` will run both main and renderer specs for you.

**Comment by CapOM** [comment]
Thx. I am looking for a solution where I specify the electron binary directly

**Comment by CapOM** [comment]
It was not trivial so maybe it can help someone else, here is what I did:

```
export ELECTRON_OUT_DIR=Release
sudo apt-get install python-dbusmock
npm run test -- -g moveTop
```

**Comment by nornagon** [comment]
This works for me:

```
$ ./out/Debug/Electron.app/Contents/MacOS/Electron electron/spec-main -g moveTop
1..1
ok 1 BrowserWindow module focus and visibility BrowserWindow.moveTop() should not steal focus
# tests 1
# pass 1
# fail 0
```

not sure what's different for you 🤷‍♂

**Comment by CapOM** [comment]
Yes it is working now, thx!

**Pull request merged**
