### PR TITLE
[WIP] Add Thai translation to Electron documents

### PR DESCRIPTION
**Pull request by ThePooE**
I'm working on Thai translation to the Electron documents. I'll let you guys know if I have finished every translation in docs folder.

**TODO**:

- [x] Translate docs/README.md
- [x] Translate docs/faq.md
- [x] Translate docs/glossary.md
- [x] Translate docs/styleguide.md
- [ ] Translate docs/api/*
- [ ] Translate docs/development/*
- [ ] [WIP] Translate docs/tutorial/*

### CODE REVIEW

**Comment by ThePooE** [comment]
Alright now we are moving to translating sub-directories

**Comment by kevinsawicki** [comment]
@ThePooE how is this going? Would it be better to merge what you have here now and you can open up further pull requests for further updates?

**Comment by ThePooE** [comment]
Hi @kevinsawicki,
It's been going well but slowly lately. I've had less free time to translate all documents for the past few weeks.

Per your suggestion I think it would be a good idea to do so, judging from the amount of files left to be done.

**Comment by kevinsawicki** [comment]
> It's been going well but slowly lately. I've had less free time to translate all documents for the past few weeks.

No worries, we appreciate the files you did translate, and please feel free to open new pull requests if you translate any remaining docs 👍 👍 👍 

I accidentally closed this pull request via trying to push up a change to your branch that rebased on top of master and removed the untranslated files, I've restored them in #8655.

**Pull request closed without merging**
