### PR TITLE
move each API doc into its own file

### LINKED ISSUE #6931: Separate each API into its own doc
@kevinsawicki and I are pairing on a docs parser. The `session.md` file is quite long, and might be easier to parse/maintain/read if each API was broken out into its own file:
- `session.md` (exists already)
- `web-request.md`
- `cookies.md`

@zcbenz what do you think of this?

### PR DESCRIPTION
**Pull request by zeke**
This PR separates every API into its own markdown document. This will allow the docs linter to dynamically construct a list of every API, so that changes to Electron's API surface area will not require changes in the linter.

Fixes #6931

### CODE REVIEW

**Comment by zeke** [comment]
There are currently a handful of files in /docs/api that are not APIs:

- [accelerator.md](https://github.com/electron/electron/tree/master/docs/api/accelerator.md)
- [chrome-command-line-switches.md](https://github.com/electron/electron/tree/master/docs/api/chrome-command-line-switches.md)
- [environment-variables.md](https://github.com/electron/electron/tree/master/docs/api/environment-variables.md)
- [file-object.md](https://github.com/electron/electron/tree/master/docs/api/file-object.md)
- [frameless-window.md](https://github.com/electron/electron/tree/master/docs/api/frameless-window.md)
- [locales.md](https://github.com/electron/electron/tree/master/docs/api/locales.md)
- [synopsis.md](https://github.com/electron/electron/tree/master/docs/api/synopsis.md)
- [web-view-tag.md](https://github.com/electron/electron/tree/master/docs/api/web-view-tag.md)
- [window-open.md](https://github.com/electron/electron/tree/master/docs/api/window-open.md)

Can we move these to their own directory? What would we call it? `reference`? Here's the current structure:

```
❯ tree -d docs
docs
├── api
│   └── structures
├── development
└── tutorial
```

cc @electron/maintainers

**Comment by MarshallOfSound** [comment]
I feel as though `synopsis`, `locales` and `frameless-window` can go in the tutorial folder.

Perhaps some of the others could go there as well.  The hard ones to place / name are WebView Tag and Accelerator.  They are both almost API's but they also aren't 😕

**Comment by zeke** [comment]
Testing this out on CI by pointing the `electron-docs-linter` dep at this unreleased branch: https://github.com/electron/electron-docs-linter/pull/77

**Comment by zeke** [comment]
@electron/maintainers this is ready for 👁 👁

**Pull request merged**
