### PR TITLE
[wip] feat: add hooks for profiling startup performance

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

This is a draft of some code that's been used by an internal app for awhile. Since it could be useful to other users too, this is a draft of an API that could be both generally usable and also extensible.

The documentation and tests are incomplete since this PR is still in the feedback-gathering phase...

Feedback welcomed @miniak @alexeykuzmin 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added startup profiling API.

### CODE REVIEW

**Comment by nornagon** [comment]
Hm, this seems like something that the [chromium tracing framework](https://www.electronjs.org/docs/api/content-tracing) should be able to provide.

Can you say more about the use case here?

**Comment by MarshallOfSound** [comment]
In agreement with the above, would love more context on this.  As an example of us using Chromium's tracing framework you can search for these kinds of `TRACE` calls.

https://github.com/electron/electron/blob/master/shell/browser/api/electron_api_web_contents.cc#L1190

**Comment by jkleinsc** [comment]
@electron/wg-api reviewed on [May-18-2020](https://github.com/electron/governance/blob/master/wg-api/meeting-notes/2020-05-18.md) and is waiting for this PR to be updated by @ckerr.

**Comment by ckerr** [comment]
Just a courtesy pong since this has gotten some attention, though it wasn't meant to have. As marked above, this is a WIP that got moved back in the queue because I got some higher priority issues on my TODO list. I didn't consider this ready for prime time, which is why I didn't request @electron/wg-api review.

The context is that Teams has a downstream patch similar to this to benchmark how long specific parts take to startup and makes that information available via a JS API for consumption. This seems like it might be generally useful & not Teams-specific, so my intent was to try to upstream a more flexible variant of it.

Agree with @nornagon and @MarshallOfSound that the Tracing API could be useful here too.

**Comment by nornagon** [comment]
@ckerr it's been a while since this PR was opened, do you still plan to work on this?

**Comment by ckerr** [comment]
TBH I didn't realize it was still open until your bot pinged it @nornagon :slightly_smiling_face: 

This draft is pretty stale and the suggestions that you and @MarshallOfSound provided would probably be a better starting point IMO. I'm going to close this PR and revisit as necessary.

**Pull request closed without merging**
