### PR TITLE
build: store the patches config in a json file

### PR DESCRIPTION
**Pull request by alexeykuzmin**
#### Description of Change

```
$ ./script/apply_all_patches.py patches/common/config.json
```

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: no notes

### CODE REVIEW

**Comment by nornagon** [comment]
Would calling `git-import-patches` twice work for this?

**Comment by alexeykuzmin** [comment]
> Would calling `git-import-patches` twice work for this?

You mean something like 
```
cd src
git import-patches .../my-patches/chromium
cd electron
git import-patches .../my-patches/electron
if [ "$CONDITION" != "" ]; then
  git import-patches .../my-other-patches/electron
fi
```

it would be one weird looking script.

**Comment by alexeykuzmin** [comment]
My goal is to use `apply_all_patches.py` in a DEPS file, just like Electron does that.

**Comment by nornagon** [comment]
> > Would calling `git-import-patches` twice work for this?
> 
> You mean something like this?
> 
> ```
> cd src
> git import-patches .../my-patches/chromium
> cd electron
> git import-patches .../my-patches/electron
> if [ "$CONDITION" != "" ]; then
>   git import-patches .../my-other-patches/electron
> fi
> ```
> it would be one weird looking script.

1. you can use `git -C src import-patches` if `electron/script` is in your PATH.
2. you'd need the `if` anyway even with this change

**Comment by alexeykuzmin** [comment]
> you can use git -C src import-patches if electron/script is in your PATH.

I don't run it from a command line, it is not supposed to be run by humans at all.
A script that would add some folder to the `PATH` and then running git commands, would look at least questionable.

**Comment by alexeykuzmin** [comment]
@nornagon Ok, another iteration.
Some shared logic moved to a new script, which can be both imported and used from a command-line.

**Comment by alexeykuzmin** [comment]
@nornagon 

> `apply_all_patches.py` was supposed to be a slightly glorified for loop, and could have been written in bash. i don't love adding a little syntax to it (with the `:`). 

`apply_all_patches.py` still does exactly the same, just the `for` loop has been moved to a new file.

> i'd rather simplify the scripts so that it's trivial for you to write your own for loop.

I basically can't import anything from the `script/lib/` if code I write is not in the `electron` repo.

**Comment by nornagon** [comment]
my concern isn't about changing the behaviour of apply_all_patches.py, it's with complicating the logic.

how about this:

```python
import os
from subprocess import check_call

patches = {
  'patches/foo': 'src/foo',
  'patches/bar': 'src/bar',
}

for dir,src in patches.iteritems():
  check_call(['git', '-C', src, 'import-patches', dir],
      env={'PATH': ['../electron/script'] + os.environ['PATH']})
```

Another reasonable approach would be to move the list of patch dirs to a `patches/config.json` or something, and pass the path to that file to `apply_all_patches.py` instead of hardcoding it. Then `apply_all_patches.py` could become simply:


```
#!/usr/bin/env python

import json
import sys

from lib import git
from lib.patches import patch_from_dir


def apply_patches(dirs):
  for patch_dir, repo in dirs.iteritems():
    git.am(repo=repo, patch_data=patch_from_dir(patch_dir),
      committer_name="Electron Scripts", committer_email="scripts@electron")


def main():
  with open(sys.argv[1]) as config_json:
    apply_patches(json.load(config_json))


if __name__ == '__main__':
  main()
```

**Comment by alexeykuzmin** [comment]
> Another reasonable approach would be to move the list of patch dirs to a `patches/config.json` or something

@nornagon 
Created a JSON config for the patches.

**Pull request merged**
