### PR TITLE
Ensure DirectX capturer is supported.

### PR DESCRIPTION
**Pull request by ajmacd**
Should resolve https://github.com/electron/electron/issues/13426

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
refs: https://cs.chromium.org/chromium/src/third_party/webrtc/modules/desktop_capture/screen_capturer_win.cc?q=allow_directx_capturer&dr=C&l=37

**Comment by ajmacd** [comment]
@MarshallOfSound I haven't succeeded in packaging a Windows build to test on my Win7 machine, but this works as before on Win10 and I suspect will resolve the Win7 crash. Want to merge?

**Comment by ajmacd** [comment]
I'd love to, but haven't been able to produce a distributable package on Windows to test on my Win7 machine. Is there any way to have CI produce one?

**Comment by alexeykuzmin** [comment]
> haven't been able to produce a distributable package on Windows to test on my Win7 machine. Is there any way to have CI produce one?

@jkleinsc ?

**Comment by MarshallOfSound** [comment]
@ajmacd I'll try building this on my local today and send you a build on Slack :+1:

**Comment by ckerr** [comment]
@MarshallOfSound any progress on this?

**Comment by ajmacd** [comment]
Sorry for the delay. Finally got a working build on a Win7 machine and verified this PR resolves the crash in https://github.com/electron/electron/issues/13426.

The display IDs don't match between the desktopCapturer and screen APIs, but that's not a regression. Let's merge this!

**Comment by ajmacd** [comment]
@alexeykuzmin Good to merge?

**Comment by ckerr** [comment]
Oop. My first guess is this failed because https://github.com/electron/electron/pull/13986 needed to be merged first.. let's try again.

**Comment by ckerr** [comment]
Bah.

**Pull request merged**
