### PR TITLE
Fix documentation tyop

### LINKED ISSUE #12420: typo in docs - additionALarguments, not additionArguments
The `BrowserWindow`'s `webPreferences` option `additionalArguments` is mistakenly named `additionArguments` in the [docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md).

### PR DESCRIPTION
**Pull request by ckerr**
Fixes #12420

### CODE REVIEW

**Comment by zeke** [comment]
tyop! Love it.

**Comment by miniak** [comment]
@ckerr, @codebytere this one should be back-ported to the release branches as well

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/2-0-x/atom/common/options_switches.cc#L142
https://github.com/electron/electron/blob/3-0-x/atom/common/options_switches.cc#L143

**Pull request merged**
