### PR TITLE
fix: disable private macOS APIs in MAS build except for CAContext/CALayerHost (7-1-x)

### PR DESCRIPTION
**Pull request by zcbenz**
#### Description of Change

Refs #20027.

This PR is split from https://github.com/electron/electron/pull/20967 to only include patches that are safe to merge.

#### Release Notes

Notes: no-notes

### CODE REVIEW

**Comment by ymmuse** [comment]
Hi @MarshallOfSound, The newest 7-1-x mas version still has some private APIs in use. 
There is missing a patch file look at this https://github.com/electron/electron/pull/20965/commits/4fcc2b03bb332bcf995ece96831acef5728e7fb7

**Comment by soundar78** [comment]
@zcbenz 
will CAContext & CALayerHost apis be removed or anything has been decided regarding these apis ?
just checking as apps using 7.x.x depend on this decision.

**Comment by zcbenz** [comment]
@soundar78 Removing those APIs would have significant affects on app's battery performance and we are still seeking from Apple to provide an alternative solution or unblock those APIs. So currently CAContext/CALayerHost are still being included in 7.x and use it for your app may result in getting rejected by Apple.

**Comment by jarek-foksa** [comment]
As of February 9th Apple is still rejecting Electron >= 7 apps because of the usage of CAContext and CALayerHost.

Wouldn't it make more sense to remove those APIs now (just like it was done in Electron 5.x and 6.x) and bring them back when a better solution is provided by Apple? It doesn't look like they are willing to do anything about it anytime soon. A version with poor battery performance is always better than a version that can't be used at all.

Besides, battery performance is not that important for desktop apps, so far none of my existing users have complained about it (I'm using a patched Electron 5.x MAS version, but I have received several complains about [the broken print dialog](https://github.com/electron/electron/issues/21439) that can fixed without updating to Electron 7.

**Pull request merged**
