### PR TITLE
Add Debugging Instructions for Windows

### PR DESCRIPTION
**Pull request by felixrieseberg**
Contributing to Electron would probably be a bit easier if we had debugging instructions. I started writing some for Windows (because that's an area where I'd love to see more people submit PRs 😸) but if people agree that this is useful, I could probably add some instructions for how to use the [OS X/Linux VSCode C++ Debugger](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/cc-extension-for-visual-studio-code/).

Ref #5140

### CODE REVIEW

**Comment by paulcbetts** [comment]
I'm into it, though tbh I always use WinDbg to debug Electron on Windows, because WinDbg can debug multiple processes at once which as one might imagine, super useful.

**Comment by felixrieseberg** [comment]
Makes sense, I'll add some blurb for those of us who're willing to do some driver level debugging ;-)

**Comment by zcbenz** [comment]
I'm merging this now, we can update it for more in other PRs.

**Comment by dhaavi** [comment]
Just in case anyone stumbles over this, @felixrieseberg has written a blog post on how to debug electron crashes here: https://felixrieseberg.com/debugging-electron-apps-on-windows/

**Pull request merged**
