### PR TITLE
test: drop now-empty remote runner

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
The `spec` folder is empty and the `remote` runner does nothing, so delete it.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added

#### Release Notes

Notes: none

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
https://github.com/electron/electron/blob/main/.github/workflows/electron_woa_testing.yml will also need to be changed.

**Comment by nornagon** [comment]
@jkleinsc done

**Review by jkleinsc — APPROVED** [review]

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏

**Pull request merged**
