### PR TITLE
chore: remove deprecated remote module

### PR DESCRIPTION
**Pull request by miniak**
#### Description of Change
Finalize  #21408

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: The deprecated `remote` module was removed from Electron.

### CODE REVIEW

**Review by nornagon — CHANGES_REQUESTED** [review]
just marking this is unmergeable until 14.x.

(also, way to steal my negative lines ;p)

**Comment by miniak** [comment]
@jkleinsc I am getting this failed test on all platforms, is it a known issue? Seems unrelated to my change
```
not ok 1418 webContents module crashed event does not crash main process when quiting in it
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\src\electron\spec-main\api-web-contents-spec.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by jkleinsc** [comment]
@miniak I have not seen that particular failure before, but I just checked master and it does seem to be failing there too: 
https://app.circleci.com/pipelines/github/electron/electron/36496/workflows/ee8f9014-fcb9-4de2-905d-25f0b27abffd/jobs/800877

**Comment by jkleinsc** [comment]
@miniak looks like that failure was introduced via #27815

**Comment by jkleinsc** [comment]
@miniak #27998 should resolve this test failure.

**Review by nornagon — APPROVED** [review]

**Pull request merged**
