### PR TITLE
fix: add Chromium patch to fix RTL window buttons

### LINKED ISSUE #21583: [RTL][Mac] Window buttons do not respect system default
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron 9.0.0-nightly.20191217
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * _Uncertain_

### Expected Behavior

On a Mac with primary language set to an RTL language (say, Arabic), the window buttons (the "traffic lights") _should_ appear on the right side of the window.

### Actual Behavior

It seems that Electron-based apps still show the window buttons on the left, just like in LTR languages like English.

See below for a screenshot indicating the issue.

### To Reproduce

1. Change the MacOS system language to Arabic. (https://support.apple.com/guide/mac-help/change-the-language-your-mac-uses-mh26684/mac)
2. Restart your computer. (Notice how native windows now have window buttons on the right side.)
3. Open an Electron app. The window buttons appear on the left side.

### Screenshots

Here is a screenshot of my Mac in Arabic (with a native window open for reference), along with a test build of the Electron app. Notice that the position of the window buttons is different.

image

### Additional Information

I was also able to reproduce this issue on various Electron-based apps including VS Code, Skype, WhatsApp, Slack.

### PR DESCRIPTION
**Pull request by seshrs**
### Description of Change

BREAKING CHANGE

This PR fixes the positioning of window buttons in MacOS when the primary OS language is set to an RTL language (such as Arabic or Hebrew). This fixes #21583.

‏لقطة الشاشة ٢٠٢٠-٠١-٣١ في ٧ ٢٩ ٥٨ م

Classes that inherit from `NSThemeFrame` seem to show window buttons in the
incorrect position when the primary MacOS language is set to an RTL
(right-to-left) language like Arabic or Hebrew. The fix in this commit mirrors
that of `tabbed_browser_window.mm`
(https://chromium-review.googlesource.com/c/chromium/src/+/562603/10/chrome/browser/ui/cocoa/tabbed_browser_window.mm#88).

This change should be upstreamed, and then this patch can be removed.

/CC @TonyWuu, @MarshallOfSound 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed the positioning of window buttons on MacOS when the OS locale is set to an RTL language (like Arabic or Hebrew). Frameless window apps may have to account for this change while styling their windows.

### CODE REVIEW

**Comment by codebytere** [comment]
@seshrs would you like to try your hand at upstreaming this or would it help for one of us to do it? i'm happy to help if that'd be easier.

**Comment by seshrs** [comment]
@codebytere thanks for your quick response! I haven't contributed to the Chromium repository before — I'd love to try, but please let me know if it would be more efficient for you to upstream the change yourself.

**Comment by codebytere** [comment]
@seshrs why don't you try (see [this doc](https://chromium.googlesource.com/chromium/src/+/master/docs/contributing.md) for info) and then ping me if you'd like me to handle it instead?

**Comment by seshrs** [comment]
@MarshallOfSound Ah, makes sense. I've updated the Release Notes in the PR description, suggestions and edits are welcome.

**Comment by jkleinsc** [comment]
Merging as CI failure unrelated to PR changes.

**Comment by seshrs** [comment]
For reference: I am attempting to patch this fix in Chromium at https://chromium-review.googlesource.com/c/chromium/src/+/2040377. (Associated issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1049796)

**Comment by seshrs** [comment]
Update: The upstream fix landed in Chromium `82.0.4069.0`. (See https://storage.googleapis.com/chromium-find-releases-static/f6a.html#f6a3d9c877f8c6369556ff835ce48af3957cd419 for the status.)

When Electron updates its Chromium dependency, the patch introduced by this PR can be removed.

**Pull request merged**
