### PR TITLE
Update to node v9.7.0

### PR DESCRIPTION
**Pull request by codebytere**
Updating to Node `v9.7.0`.

Todo:
- [x] update libcc ref with new v8 backports
- [x] update Node ref to new `electron-node-v9.7.0` branch
- [x] fix build error on windows

/cc @alexeykuzmin

### CODE REVIEW

**Comment by zcbenz** [comment]
I saw a crash when running tests on my local Windows:

```
[1740:0309/152127.929:FATAL:observer_list.h(276)] Check failed: false. Observers can only be added once!
Backtrace:
        base::debug::GlobalActivityAnalyzer::GetUserDataSnapshot [0x000000E202D858E5+675194]
        base::debug::GlobalActivityAnalyzer::GetUserDataSnapshot [0x000000E202D85408+673949]
        base::debug::GlobalActivityAnalyzer::GetUserDataSnapshot [0x000000E202DF74B0+1141061]
        content::WebContentsImpl::GetOuterDelegateFrameTreeNodeId [0x000000E20B0DA064+45185986]
        content::WebContentsImpl::GetOuterDelegateFrameTreeNodeId [0x000000E20B0DA116+45186164]
        atom::AtomBrowserClient::RenderProcessWillLaunch [0x00007FF73BB7B498+776] (c:\cygwin\home\zcbenz\codes\electron\atom\browser\atom_browser_client.cc:182)
```

It does not seem to be related to this PR though.

**Comment by deepak1556** [comment]
Oh thats weird, does that mean `AtomBrowserClient::RenderProcessWillLaunch` is being triggered twice for the same process ?

**Comment by zcbenz** [comment]
It seems so, but it should not happen.

**Comment by deepak1556** [comment]
When enabling dchecks I saw a similar crash but we were doing it twice in different places and removed one of them https://github.com/electron/electron/pull/11396/commits/69bd44edbb1e03e866b34ae5d87f578ba9d76ff8 . No idea of this crash though.

**Comment by deepak1556** [comment]
@zcbenz based on the ci report, i guess this is being triggered for the `affinity` flag feature. Might help narrow down the cause.

**Pull request merged**
