### PR TITLE
fix: Ensure electron delay loads the same modules as chromium

### PR DESCRIPTION
**Pull request by chrdavis**
This change adds the same module delay load list that chromium uses for electron.  Some modules were already getting delay loaded from other build files in chromium but not the main list via //build/config/win:delayloads.  We do not include the list of delay loads in delayloads_not_for_child_dll as those have issues being loaded in sandboxes processes.  This will reduce the overall reference set impact of the electron processes.
notes: Added missing module delay loads on windows to reduce per process reference set impact

### CODE REVIEW

**Comment by chrdavis** [comment]
Here is the list of delay loaded modules after the change:
image

**Review by nornagon — APPROVED** [review]

**Review by MarshallOfSound — APPROVED** [review]

**Review by deepak1556 — APPROVED** [review]

**Comment by chrdavis** [comment]
Not sure what the build-mac failures are.  I can't access logs.  Also, my changes shouldn't impact anything but Windows.

**Comment by nornagon** [comment]
mac failures seem to be flakes.

**Comment by MarshallOfSound** [comment]
@chrdavis For future reference you should be able to view the CI build log just by signing in, you have to auth with github but the logs aren't behind any kind of permission barrier.  If you can't view them after signing in to CircleCI let me know and I can look into it 😄

**Comment by chrdavis** [comment]
Do the mac tests have to be run again or is this ok to merge now?

**Comment by deepak1556** [comment]
It is fine to merge, the failures are unrelated. Thanks for the pr!

**Pull request merged**
