### PR TITLE
fix: proper l10n on Linux dialog buttons

### LINKED ISSUE #19663: Feature Request: support localization of button labels in Open and Save dialogs
### Problem Description
I use ubuntu linux. my system language is Chinese, but the dialog button labels is English by default. I found the buttonLabel option from the API to set the label of the save or open button, but the label of the cancel button is not supported.

### Proposed Solution
Support customizing cancel button label in Open and Save dialogs

### PR DESCRIPTION
**Pull request by erickzhao**
#### Description of Change
Closes #19663 in a roundabout way. Leverages Chromium's UI strings to apply proper labels to dialog buttons.

Previously, we were attempting to use GNU gettext, but it wasn't really working. I don't have too much context on that, but I think it's because we didn't have manual translations.

##### Screenshots:

Fiddle's Dialog show-me and my Linux system set to French.

Before:
Capture d'écran 2019-08-12 17:53:28

After:
Capture d'écran 2019-08-12 17:55:14
ccc

##### Limitations:
* Some strings borrowed from Chromium are not exactly used properly. They seemed to be OK for usage in English and French, but I'm not sure if they don't match up in other languages.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Localized dialog button text on Linux.

### CODE REVIEW

**Comment by codebytere** [comment]
@erickzhao do you have screenshots of before and after? that'd be helpful for context and reducing friction of reproducing locally to verify efficacy of this change!

**Comment by erickzhao** [comment]
@codebytere Sure! These are with Fiddle's Dialog show-me and my Linux system set to French.

Before:
Capture d'écran 2019-08-12 17:53:28

After:
Capture d'écran 2019-08-12 17:55:14
ccc

**Comment by codebytere** [comment]
@erickzhao where does this need to get sent back to? i don't see any `target/` labels 🤔

**Comment by erickzhao** [comment]
@codebytere added them! Forgot to do that since I initially marked this as a `feature` 😅

**Comment by codebytere** [comment]
@erickzhao this needs manual backports to 6/5 when you have a moment!

**Comment by ckerr** [comment]
See https://github.com/electron/electron/issues/19755

**Pull request merged**
