### PR TITLE
fix: Support running git-[im,ex]port-patches with Python3 too

### PR DESCRIPTION
**Pull request by kromain**
#### Description of Change

The scripts `git-import-patches` and `git-export-patches` work *almost* out of the box with Python3,
the only issue is that the `unicode` type was renamed to `str` there. For this reason, the interpreter version was hardcoded in #25335.

But the error with Python3 can easily be fixed by aliasing `unicode` to `str`. With that issue fixed, we can switch the shebang line back to the unversioned python command.

This saves one from having to install Python2 just for these scripts when Python3 is already installed on the system.

#### Checklist

- [X] PR description included and stakeholders cc'd

#### Release Notes

Notes: none

### CODE REVIEW

**Comment by kromain** [comment]
cc'ing @vially as the author of #25335 which added the explicit interpreter version, @zcbenz as the original approver, and @nornagon as the author and maintainer of these scripts. Sorry for the noise, for some reason I can't add Reviewers or Assignees to this PR.

**Review by codebytere — DISMISSED** [review]

**Review by codebytere — COMMENTED** [review]
@kromain this works but 

> W: 20, 4: Redefining built-in 'unicode' (redefined-builtin)

isn't allowed by our linter, so it'll need a little more tweaking before it's ready to go. Is there another way to fix this issue or conditionally decide which one to use?

**Comment by kromain** [comment]
@codebytere thanks for the review and pointing out the linter failure! Ok then a simple alternative is to conditionally call `unicode` or `str` instead based on the interpreter version, instead of directly aliasing `unicode`. Fortunately it's only called at one place in the file so it won't increase the size of the patch. I'll update it shortly.

**Comment by kromain** [comment]
Updated the patch to use a wrapper method instead of aliasing `unicode` directly. The linter is happy now, and as a bonus the wrapper method improves readability a little bit.

**Review by codebytere — APPROVED** [review]
Thanks! Looks good to me.

**Review by zcbenz — APPROVED** [review]

**Comment by kromain** [comment]
@nornagon can you merge if you're ok with it too? thanks

**Comment by codebytere** [comment]
Unrelated failure - merging.

**Review by jkleinsc — APPROVED** [review]

**Comment by jkleinsc** [comment]
merging as CI failure is unrelated to PR change.

**Pull request merged**
