### PR TITLE
Add v7l to ARM release assets

### LINKED ISSUE #2343: Release name 'linux-arm' is too vague e.g. (armv7 vs armv8)
the new arm release is called `electron-v0.30.1-linux-arm.zip`, but there are many different arm types:  armv6, armv7, armv8 and also armhf vs armel

iojs uses the format `armv7l` and `armv6l`: https://iojs.org/dist/v2.4.0/. would that make sense to use?

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull requests adds the `v7l` suffix to ARM build release assets so they can eventually be disambiguated from future `armv6l` and `arm64` assets that may be produced.

This mirrors the ARM build names that node uses: https://nodejs.org/dist/v4.5.0/

### Example

* Old name: `electron-v1.3.4-linux-arm.zip`
* New name: `electron-v1.3.4-linux-armv7l.zip`

This will be backported to all 1.0+ releases but no old assets will be deleted.

Closes #2343 
Refs #5706

### CODE REVIEW

**Comment by malept** [comment]
🙌 this is great! I eagerly await the backport so we can finally add ARM support to Electron Packager properly!

**Comment by malept** [comment]
Out of curiosity, what is the timeline for this PR? (Or perhaps, what is currently blocking it?) I only ask because I'd like to get this in the next major release (version 8) of Electron Packager and this is basically the last major feature. (I am OK with it slipping to version 9, but having an idea of when it's going to happen would be ideal.)

**Comment by zcbenz** [comment]
We will include it in the next release which will be published in this week.

**Comment by malept** [comment]
@zcbenz I see that Electron 1.3.5 has been released, thanks! Is there a timeframe for the backport mentioned in the PR summary?

**Comment by kevinsawicki** [comment]
>  Is there a timeframe for the backport mentioned in the PR summary?

Planning doing it today, will post back here with updates 📝

**Comment by malept** [comment]
This is probably in your checklist, but please make sure to update the SHASUMS256.txt files for Electron versions 1.3.2 through 1.3.4 as well.

**Comment by kevinsawicki** [comment]
> This is probably in your checklist, but please make sure to update the SHASUMS256.txt files for Electron versions 1.3.2 through 1.3.4 as well.

`electron-vX.X.X-linux-armv7l.zip` assets now exist for every release back to 1.0.0 and the existing `SHASUMS256.txt` asset files have been updated.

I did not backport the rename to the other assets such as `chromedriver`, `mksnapshot`,  or `ffmpeg` since they are downloaded significantly less than the main Electron release asset and tooling like `electron-packager` does not integrate with them directly.

**Comment by malept** [comment]
Excellent, thanks!

**Pull request merged**
