### PR TITLE
[WIP] fix: don't leak NotifyIcon objects on Windows

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

Don't leak NotifyIcon objects on Windows. Previously we held a vector of NotifyIcon*s allocated with new but never deleted them when removing from the vector.

This refactor also changes the implementation from holding icons in a container to holding them in a map keyed by icon ID, simplifying the icon lookup code.

#### Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [ ] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed notification icon memory leak on Windows.

### CODE REVIEW

**Comment by codebytere** [comment]
@ckerr do you still intend to work on this?

**Comment by ckerr** [comment]
Yikes; I'd forgotten this PR was still open. I'll add it to my medium-term TODO

**Comment by codebytere** [comment]
@ckerr can this be closed?

**Comment by codebytere** [comment]
@ckerr can this be closed?

**Pull request closed without merging**
