### PR TITLE
Add window.loadFile and webContents.loadFile helper methods

### LINKED ISSUE #11560: Add `browserWindow.loadFile()` convenience method
* Electron version: 1.7.10
* Operating system: macOS 10.13.2

### Description

The most common use-case for Electron is to load a local HTML file. The default way to do this is pretty verbose and ugly ```win.loadURL(`file://${__dirname}/index.html`)```.

I propose adding a convenience method to make the most common use-case simpler and nicer. A `win.loadFile()` method which loads a file relative to the root of the app:

```js
win.loadFile('index.html');
```

Which would be almost equivalent to:

```js
const loadFile = filePath => win.loadURL(`file://${path.resolve(electron.app.getAppPath(), filePath)}`);
```

We should also add `file` option to the `BrowserWindow` constructor, so all you needed to do to create a window with a local file (which is what most would do) is just:

```js
const win = new BrowserWindow({file: 'index.html'});
```

Ergonomics are important, and this is something that would benefit most Electron apps.

I would be happy to do a PR if this is accepted.

I've added support for it in my Electron utility module if you want it today: https://github.com/sindresorhus/electron-util#loadfilewindow-filepath

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Closes #11560

### CODE REVIEW

**Comment by sindresorhus** [comment]
What do you think about the idea of adding a `file` option to BrowserWindow as a convenience? Most users will want to load the local file right away, so would be nice to be able to specify it there instead.

`loadURL()` is not a `BrowserWindow` option as it has support for its own options, but `loadFile()` only accepts a string, so it could easily be an option in `BrowserWindow`.

**Comment by sindresorhus** [comment]
Maybe also update the docs here: https://github.com/electron/electron/blame/249bd41e11443feb8949f21367eb1802b19f9544/docs/api/browser-window.md#L23 and here: https://github.com/electron/electron/blame/249bd41e11443feb8949f21367eb1802b19f9544/docs/api/web-contents.md#L1199

**Comment by MarshallOfSound** [comment]
> What do you think about the idea of adding a file option to BrowserWindow as a convenience? 

Not a fan tbh, I much prefer the explicit "create then navigate" approach we currently use.  This method just makes it easier/safer for people to navigate to local files 👍

**Comment by MarshallOfSound** [comment]
> Maybe also update the docs here: 

Yeah once this goes through I'll follow up with a PR to update docs and usage in our own code.  I didn't realize we had so much string templating `loadURL` around the place 🤔

**Comment by felixrieseberg** [comment]
> Not a fan tbh, I much prefer the explicit "create then navigate" approach we currently use. This method just makes it easier/safer for people to navigate to local files 👍

I'm with you on that, especially because you can't attach listeners to something that hasn't been created yet - and therefore wouldn't be able to catch errors emitted via EventEmitter.

**Pull request merged**
