### PR TITLE
Offscreen rendering support for Electron

### PR DESCRIPTION
**Pull request by gerhardberger**
This PR adds support to render browser windows offscreen in Electron, through a `'paint'` event on `window.webContents`.

We (@brenca and me) implemented a similar approach, than what [CEF](https://bitbucket.org/chromiumembedded/cef) uses.

It supports two types of offscreen rendering: GPU-accelerated and software-based (which is quite faster), also the frame rate can be adjusted and painting can be controlled.

It depends on a custom *brightray* fork, which is also submitted as a [PR](https://github.com/electron/brightray/pull/243).

### CODE REVIEW

**Comment by miniak** [comment]
@gerhardberger I would suggest squashing the commits, 66 is way too many.

**Comment by paulcbetts** [comment]
Please fix the indentation in your files so that you're not rewriting whole files first as well

**Comment by gerhardberger** [comment]
@paulcbetts thanks, it was a line-endings issue, didn't notice it.

**Comment by paulcbetts** [comment]
@gerhardberger Sorry to lead off my response with a complaint, this is very cool!

**Pull request merged**
